Text0e5a:
	text "EHH?! I LOST?"
	linefw "...I'M SO HOPELESS..."
	done

Text0e5b:
	text "I'LL PRACTICE REALLY HARD"
	linefw "SO I DON'T LOSE NEXT TIME!"
	done

Text0e5c:
	text "I WON, I WON!"
	linefw "MY DECK IS SO STRONG!"
	done

Text0e5d:
	text "NIKKI HAS RETURNED AT LONG LAST!"
	linefw "EVERYONE'S SO RELIEVED."
	linefw "THANKS FOR ALL OF YOUR HELP,"
	linefw "<RAMNAME>", "."
	done

Text0e5e:
	text "THANK YOU SO MUCH!"
	linefw "I WAS FINALLY ABLE TO MAKE A DECK."
	linefw "I HAVEN'T CHALLENGED ANYONE WITH IT"
	linefw "YET, THOUGH. WANT TO BE THE FIRST?"
	done

Text0e5f:
	text "DO YOU LIKE OUR CLUB'S GARDEN?"
	linefw "WE WORK HARD TO KEEP IT PRISTINE."
	linefw "BEAUTIFUL GARDENS CALL FOR"
	linefw "BEAUTIFUL CARD BATTLES, RIGHT?"
	done

Text0e60:
	text "WOULD YOU LIKE TO DUEL KRISTIN?"
	done

Text0e61:
	text "THEN LET'S SET ASIDE"
	linefw "4 PRIZE CARDS."
	done

Text0e62:
	text "AWW, I WANTED TO BATTLE WITH YOU,"
	linefw "<RAMNAME>", ". OH WELL."
	linefw "IF YOU EVER FEEL LIKE HAVING A DUEL,"
	linefw "PLEASE COME BACK AND FIND ME."
	done

Text0e63:
	text "IT WAS MY LOSS."
	linefw "YOU REALLY ARE A STRONG KID!"
	done

Text0e64:
	text "PLEASE COME BACK IF YOU'D"
	linefw "LIKE TO PLAY AGAIN."
	done

Text0e65:
	text "I CAN'T BELIEVE IT!"
	linefw "I WON THE MATCH!"
	linefw "YOU DIDN'T EVEN THINK YOU COULD"
	linefw "LOSE AGAINST ME, DID YOU? "
	done

Text0e66:
	text "THANKS TO YOUR EFFORTS, EVERYONE"
	linefw "COULD RETURN TO THE PLAY HALL."
	linefw "NOW IF ONLY I COULD DUEL YOU,"
	linefw "EVERYTHING WOULD BE GREAT..."
	done

Text0e67:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "IT'S SO GOOD OF YOU TO VISIT!"
	linefw "I'M GLAD TO HEAR THAT YOU'VE BEEN"
	linefw "OVERCOMING TEAM GR'S CHALLENGES."
	linefw "IF YOU HAVE THE TIME FOR A DUEL,"
	linefw "WOULD YOU MIND PLAYING WITH ME?"
	done

Text0e68:
	text "IT'S QUITE PLEASANT WORKING"
	linefw "IN THIS BEAUTIFUL GARDEN."
	linefw "HOWEVER, CARD GAMES ARE FUN, TOO."
	linefw "WOULD YOU PLEASE DUEL WITH ME?"
	done

Text0e69:
	text "WOULD YOU LIKE TO DUEL HEATHER?"
	done

Text0e6a:
	text "ARE 4 PRIZE CARDS ALRIGHT"
	linefw "FOR OUR CARD BATTLE?"
	linefw "THEN LET'S BEGIN."
	linefw "OH, I'M SO EXCITED!"
	done

Text0e6b:
	text "OH, WELL IF NOT TODAY, PERHAPS NEXT"
	linefw "TIME. THANKS FOR CHATTING WITH ME!"
	done

Text0e6c:
	text "OH, DEAR ME! I LOST!"
	done

Text0e6d:
	text "PLEASE COME BACK AGAIN FOR ANOTHER"
	linefw "GAME. I WON'T LOSE NEXT TIME!"
	done

Text0e6e:
	text "WERE YOU SURPRISED AT MY PLAYSTYLE?"
	linefw "I BET YOU DIDN'T EXPECT MY TRICKS!"
	linefw "ANYWAY, THANKS FOR PLAYING."
	done

Text0e6f:
	text "HEY HEY HEEY!"
	linefw "I'M A MEMBER OF TEAM GR!"
	linefw "BUUUT...I CAN'T SEEM TO FIND THAT"
	linefw "BLASTED CLUB MASTER, NIKKI."
	linefw "HUNH??"
	linefw "YOU AAARE..."
	linefw "AHH! YOU'RE THE KID THAT'S FIGHTING"
	linefw "AGAINST TEAM GR, AREN'T YOU?"
	linefw "ANYONE WHO DEFIES TEAM GR"
	linefw "MUST BE PUNISHED!"
	done

Text0e70:
	text "WHAT DO YOUUU WANT?"
	linefw "YOU LOOKING TO PICK A FIGHT?"
	linefw "I'M A LITTLE BUSY AT THE MOMENT"
	linefw "TRYING TO TRACK DOWN NIKKI."
	linefw "BUUUT...SINCE YOU'RE SO PERSISTENT,"
	linefw "I'LL GLADLY TAKE YOU ON!"
	done

Text0e71:
	text "WOULD YOU LIKE TO DUEL GR No.2?"
	done

Text0e72:
	text "WE'LL BATTLE TO 6 PRIZE CARDS!"
	linefw "LET'S BEGIIIN!"
	done

Text0e73:
	text "WELL THEN, LET ME ALONE!"
	linefw "I'M BUSY TRYING TO FIND NIKKI."
	done

Text0e74:
	text "OH NOOO..."
	linefw "I LOST THE MATCH."
	done

Text0e75:
	text "ARE YOU QUITE SATISFIED?"
	linefw "I DIDN'T THINK SO."
	linefw "JUST A FAIR WARNING: NEXT TIME WE"
	linefw "MEET, I'LL BE EVEN STRONGER."
	done

Text0e76:
	text "OH, I ALMOST FORGOT!"
	linefw "YOU GET THIS GR COIN PIECE AS WELL."
	done

Text0e77:
	text "COLLECT ALL 4 PIECES OF THE GR COIN"
	linefw "TO EARN FREE AIRFARE AT THE AIRPORT."
	linefw "BY THE BY, WE HAVE THE SCIENCE"
	linefw "CLUB MASTER, RICK, IN OUR CUSTODY."
	linefw "IF YOU WANT HIM BACK, YOU'LL JUST"
	linefw "HAVE TO COME TO GR ISLAND."
	linefw "MAYBE I'LL SEE YOU ON OUR ISLAND!"
	linefw "I'M OUTTA HEEERE!"
	done

Text0e78:
	text "OH? SO YOU'VE COLLECTED ALL"
	linefw "4 PIECES OF THE GR COIN."
	linefw "GO ON OVER TO OUR AIRPORT. SHOW THEM"
	linefw "THAT COIN AND YOU CAN FLY FOR FREE!"
	linefw "BY THE BY, WE HAVE THE SCIENCE"
	linefw "CLUB MASTER, RICK, IN OUR CUSTODY."
	linefw "IF YOU WANT HIM BACK, YOU'LL JUST"
	linefw "HAVE TO COME TO GR ISLAND."
	linefw "MAYBE I'LL SEE YOU ON OUR ISLAND!"
	linefw "I'M OUTTA HEEERE!"
	done

Text0e79:
	text "HEY, THERE!"
	linefw "I'M BRITTANY OF THE GRASS CLUB!"
	linefw "SAY, YOU'RE ", "<RAMNAME>", ", THE KID"
	linefw "GOING AFTER GR No.2, RIGHT?"
	linefw "IF YOU WANNA BEAT HIM, YOU'LL NEED"
	linefw "TO SPEAK WITH NIKKI FIRST."
	linefw "BEAT ME, AND I'LL TELL WHERE SHE IS."
	linefw "LOSE, AND I WON'T TELL YOU ANYTHING."
	linefw "IF YOU'RE READY TO TEST YOUR"
	linefw "ABILITIES, LET'S DUEL!"
	done

Text0e7a:
	text "IF YOU'D LIKE TO DEFEAT GR No.2,"
	linefw "YOU'LL NEED TO SPEAK WITH NIKKI."
	linefw "BUT I WON'T TELL YOU WHERE SHE IS"
	linefw "UNLESS YOU BEAT ME IN A CARD DUEL."
	done

Text0e7b:
	text "I KNOW YOU LOST ALL OF YOUR CARDS,"
	linefw "BUT I WON'T RECONSIDER."
	linefw "YOU GOTTA DEFEAT ME FIRST BEFORE"
	linefw "I TELL YOU WHERE NIKKI IS HIDING."
	done

Text0e7c:
	text "IF YOU'RE NOT AT FULL POWER,"
	linefw "TEAM GR WILL WRECK YOU."
	linefw "BUT SINCE ALL OF YOUR CARDS ARE"
	linefw "GONE, HOW WILL YOU DEFEAT THEM?"
	done

Text0e7d:
	text "WOULD YOU LIKE TO DUEL BRITTANY?"
	done

Text0e7e:
	text "IN THAT CASE, 4 PRIZE CARDS!"
	done

Text0e7f:
	text "NO DUEL, EH? ALL I HAVE TO SAY"
	linefw "TO YOU, THEN, IS...GOODBYE!"
	done

Text0e80:
	text "YEP! JUST AS STRONG AS I THOUGHT!"
	linefw "HERE, TAKE THESE BOOSTER PACKS!!"
	done

Text0e81:
	text "YOU WANTED TO KNOW WHERE NIKKI"
	linefw "IS HIDING, CORRECT?"
	linefw "YOU CAN FIND HER AT ISHIHARA'S,"
	linefw "THE HOUSE NEAR THE NORTHWEST CAPE."
	linefw "HURRY TO ISHIHARA'S HOUSE AND"
	linefw "SPEAK WITH NIKKI!"
	done

Text0e82:
	text "I'LL ONLY TELL YOU WHERE TO FIND"
	linefw "NIKKI ONE MORE TIME."
	linefw "SHE'S HIDDEN AT MR. ISHIHARA'S HOUSE"
	linefw "ON THE NORTHEAST PART OF THE ISLAND."
	linefw "HURRY TO MR. ISHIHARA'S HOUSE"
	linefw "AND TELL NIKKI SHE CAN RETURN!"
	done

Text0e83:
	text "I GAVE YOU THOSE BOOSTER PACKS SO"
	linefw "YOU COULD OVERTHROW TEAM GR FASTER!"
	done

Text0e84:
	text "WOW, YOU'RE A REAL NOVICE PLAYER!"
	linefw "I DON'T THINK YOU CAN BEAT TEAM GR!"
	done

Text0e85:
	text "MY NAME IS KRISTIN. I'M A GRASS"
	linefw "CLUB MEMBER, OF COURSE."
	linefw "OUR CLUB MASTER, NIKKI,"
	linefw "HAS FLED FROM THE CLUB."
	linefw "I WAS TOLD TO GIVE YOU THIS IF"
	linefw "YOU STOPPED BY TO INVESTIGATE."
	done

Text0e86:
	text "PLEASE DO YOUR BEST TO HELP NIKKI."
	linefw "BRITTANY KNOWS WHERE SHE FLED TO."
	linefw "YOU CAN FIND BRITTANY SITTING AT"
	linefw "THE DUELLING TABLE OVER THERE."
	done

Text0e87:
	text "COULD YOU HURRY, PLEASE?"
	linefw "I'D LIKE TO PLAY CARDS SOON."
	linefw "GO ASK HOW YOU CAN MEET WITH NIKKI."
	linefw ""
	done

Text0e88:
	text "AS LONG AS GR No.2 IS AT LARGE,"
	linefw "NIKKI CAN'T RETURN TO THE CLUB."
	done

Text0e89:
	text "SINCE YOU CHASED OFF TEAM GR,"
	linefw "NIKKI CAN FINALLY RETURN."
	done

Text0e8a:
	text "I AM HEATHER,"
	linefw "A MEMBER OF THE GRASS CLUB."
	linefw "YOU'RE ", "<RAMNAME>", ", THE ONE"
	linefw "RESISTING TEAM GR, RIGHT?"
	linefw "WELL, CLUB MASTER NIKKI WAS DRIVEN"
	linefw "OUT OF THE CLUB BY GR No.2."
	linefw "OUR CLUB IS NOW UNFORTUNATELY THE"
	linefw "TERRITORY OF THE NEFARIOUS TEAM GR."
	linefw "IN ANY CASE, TAKE THIS."
	linefw "I MANAGED TO KEEP IT HIDDEN."
	done

Text0e8b:
	text "PLEASE ASK BRITTANY WHERE NIKKI"
	linefw "IS HIDING OUT."
	done

Text0e8c:
	text "PLEASE ASK BRITTANY WHERE NIKKI"
	linefw "IS HIDING OUT."
	linefw "BRITTANY'S SITTING DOWN AT THE"
	linefw "DUELLING TABLE OVER THERE."
	done

Text0e8d:
	text "PLEASE DEFEAT GR No.2"
	linefw "FO NIKKI'S SAKE!"
	done

Text0e8e:
	text "EVERYTHING SHOULD GO BACK TO NORMAL"
	linefw "SINCE YOU'VE BEATEN TEAM GR!"
	done

Text0e8f:
	text "I'M GLAD TO BE RID OF THOSE"
	linefw "TEAM GR CHARACTERS."
	linefw "STEALING KIDS' CARDS WAS JUST AN"
	linefw "ATROCIOUS THING TO DO!"
	linefw "WHY WOULD ANYONE DO SUCH A THING?"
	done

Text0e90:
	text "WE SHOULD ALL HAVE FUN PLAYING WITH"
	linefw "POKÉMON CARDS EACH AND EVERY DAY."
	linefw "IT TOOK TEAM GR A WHILE TO LEARN"
	linefw "THAT SIMPLE PRINCIPLE."
	done

Text0e91:
	text "I JUST HATE TEAM GR!"
	linefw "THEY TOOK AWAY ALL OF OUR CARDS!"
	linefw "WHY WOULD THEY DO SUCH A BAD THING?!"
	linefw "THAT'S AGAINST THE LAW, I'LL BET!"
	done

Text0e92:
	text "TEAM GR HAS DISAPPEARED!"
	linefw "EVERYTHING'S JUST GREAT!"
	done

Text0e93:
	text "SINCE TEAM GR CHANGED THEIR WAYS,"
	linefw "THEY'VE BECOME OUR GOOD FRIENDS."
	done

Text0e94:
	text "HOW COULD I POSSIBLY BE CHEERFUL"
	linefw "IF I CAN'T PLAY WITH MY CARDS?"
	linefw "EVER SINCE TEAM GR STOLE THEM,"
	linefw "I'VE BEEN SO SAD...SNIFF..."
	done

Text0e95:
	text "I GOT MY CARDS BACK."
	linefw "THANKS, ", "<RAMNAME>", "!"
	linefw "I NEVER KNEW JUST HOW MUCH MY CARDS"
	linefw "MADE ME HAPPY UNTIL THEY WERE GONE."
	done

Text0e96:
	text "I GET SO EXCITED WHEN I HEAR"
	linefw "STORIES ABOUT THE GRAND MASTERS."
	linefw "I DON'T THINK I'D WANT TO DUEL THEM,"
	linefw "BUT I'D LOVE TO SEE THEIR CARDS."
	done

Text0e97:
	text "GOOD AFTERNOON."
	linefw "MY NAME IS ISHIHARA."
	linefw "I LOVE COLLECTING RARE"
	linefw "POKÉMON TRADING CARDS."
	linefw "HOWEVER, TEAM GR SEEMS TO HAVE"
	linefw "EVERYONE'S CARDS AT THE MOMENT."
	linefw "TEAM GR HAS EFFECTIVELY SHUT DOWN"
	linefw "THE CLUBS AND CHALLENGE HALL."
	linefw "IS EVERYONE OKAY?"
	done

Text0e98:
	text "GOOD AFTERNOON."
	linefw "MY NAME IS ISHIHARA."
	linefw "TEAM GR HAS EFFECTIVELY SHUT DOWN"
	linefw "THE CLUBS AND CHALLENGE HALL."
	linefw "IS EVERYONE OKAY?"
	done

Text0e99:
	text "GOOD AFTERNOON."
	linefw "MY NAME IS ISHIHARA."
	linefw "I LOVE COLLECTING RARE"
	linefw "POKÉMON TRADING CARDS."
	linefw "BUT YOU MUST EXCUSE ME,"
	linefw "FOR NOW IS NOT THE TIME."
	linefw "PLEASE LISTEN TO THE REQUEST OF"
	linefw "MISS NIKKI OF THE GRASS CLUB."
	done

Text0e9a:
	text "GOOD AFTERNOON."
	linefw "MY NAME IS ISHIHARA."
	linefw "I LOVE COLLECTING RARE"
	linefw "POKÉMON TRADING CARDS."
	linefw "BUT YOU MUST EXCUSE ME,"
	linefw "FOR NOW IS NOT THE TIME."
	linefw "IF YOU FULFILL MISS NIKKI'S WISH,"
	linefw "I'LL TRADE CARDS WITH YOU."
	done

Text0e9b:
	text "GOOD AFTERNOON."
	linefw "WOULD YOU LIKE TO TRADE CARDS?"
	linefw "RIGHT NOW I'M LOOKING FOR A"
	linefw "CLEFAIRY Lv15 CARD."
	linefw "IT'S THE CLEFAIRY WITH THE ATTACK,"
	linefw "'FOLLOW ME'."
	linefw "I'M OFFERING MY RARE"
	linefw "FLYING PIKACHU CARD IN EXCHANGE."
	linefw "DO YOU HAPPEN TO HAVE A"
	linefw "CLEFAIRY Lv15 UP FOR TRADE?"
	done

Text0e9c:
	text "HELLO, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING YOUR POKÉMON CARDS?"
	linefw "RIGHT NOW, I'M LOOKING FOR A"
	linefw "CLEFAIRY Lv15 CARD."
	linefw "I'M OFFERING TO TRADE MY"
	linefw "FLYING PIKACHU CARD FOR IT."
	linefw "DO YOU HAVE A CLEFAIRY Lv15"
	linefw "YOU WOULDN'T MIND PARTING WITH?"
	done

Text0e9d:
	text "I SEE. THAT'S TOO BAD..."
	linefw "PERHAPS WE CAN TRADE LATER..."
	done

Text0e9e:
	text "THANKS, BUT YOU DON'T SEEM TO"
	linefw "HAVE THE CARD I'M LOOKING FOR."
	linefw "PERHAPS WE CAN TRADE LATER..."
	done

Text0e9f:
	text "OH, ARE YOU USING ALL OF YOUR"
	linefw "CLEFAIRY Lv15 CARDS IN YOUR DECKS?"
	linefw "YOU CAN'T TRADE A CARD THAT'S"
	linefw "PART OF YOUR GAME DECKS."
	linefw "PERHAPS WE COULD TRADE LATER..."
	done

Text0ea0:
	text "OH, MANY THANKS!"
	linefw "LET'S TRADE RIGHT AWAY."
	done

Text0ea1:
	text "<RAMNAME>", " TRADED A CLEFAIRY Lv15"
	linefw "CARD FOR A FLYING PIKACHU CARD!"
	done

Text0ea2:
	text "THANK YOU VERY MUCH FOR"
	linefw "YOUR CLEFAIRY Lv15 CARD."
	linefw "REALLY, I'M IN YOUR DEBT."
	linefw "YOU'RE VERY KIND."
	done

Text0ea3:
	text "HELLO, ", "<RAMNAME>", "."
	linefw "WELCOME TO MY HOUSE."
	linefw "I'M NOT LOOKING FOR ANY PARTICULAR"
	linefw "CARDS AT THE MOMENT, I'M AFRAID."
	linefw "I MAY BE SEEKING SOME IN THE FUTURE,"
	linefw "THOUGH, SO STOP BY LATER, WON'T YOU?"
	linefw "IN THE MEANTIME, FEEL FREE TO READ"
	linefw "THE BOOKS I WROTE IN MY LIBRARY."
	linefw "THE INFORMATION I SHARE WILL"
	linefw "SURELY HELP YOU WIN CARD BATTLES."
	done

Text0ea4:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "WOULD YOU LIKE TO TRADE CARDS?"
	linefw "I'M CURRENTLY LOOKING FOR A"
	linefw "CLEFABLE Lv34..."
	linefw "I'D LIKE TO TRADE MY TOGEPI Lv8"
	linefw "FOR IT, IF THAT'S OKAY WITH YOU."
	linefw "DO YOU HAVE A CLEFABLE Lv34?"
	done

Text0ea5:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING YOUR POKÉMON CARDS?"
	linefw "I'M CURRENTLY LOOKING FOR A"
	linefw "CLEFABLE Lv34..."
	linefw "I'D LIKE TO TRADE MY TOGEPI Lv8"
	linefw "FOR IT, IF THAT'S OKAY WITH YOU."
	linefw "DO YOU HAVE A CLEFABLE Lv34?"
	done

Text0ea6:
	text "YOU DON'T HAVE A CLEFABLE Lv34,"
	linefw "DO YOU?"
	linefw "I'M ONLY LOOKING TO TRADE MY"
	linefw "TOGEPI Lv8 FOR A CLEFABLE Lv34."
	linefw "STOP BY SOME OTHER TIME IF YOU WOULD"
	linefw "STILL LIKE TO TRADE WITH ME..."
	done

Text0ea7:
	text "IT SEEMS ALL OF YOUR CLEFABLE Lv43"
	linefw "CARDS ARE BEING USED IN YOUR DECKS."
	linefw "YOU CANNOT TRADE CARDS THAT YOU'RE"
	linefw "USING TO DUEL OTHERS WITH."
	linefw "STOP BY SOME OTHER TIME IF YOU WOULD"
	linefw "STILL LIKE TO TRADE WITH ME..."
	done

Text0ea8:
	text "OOH, THANK YOU SO MUCH!"
	linefw "LET US TRADE RIGHT AWAY..."
	done

Text0ea9:
	text "<RAMNAME>", " TRADED A CLEFABLE Lv34"
	linefw "CARD FOR A TOGEPI Lv8 CARD!"
	done

Text0eaa:
	text "YOU HAVE MY GRATITUDE FOR THIS"
	linefw "CLEFABLE Lv34."
	linefw "THANK YOU SO MUCH. I THINK I'LL"
	linefw "WRITE ABOUT THIS IN MY JOURNAL."
	done

Text0eab:
	text "HELLO, ", "<RAMNAME>", "."
	linefw "I HOPE YOU ARE DOING FINE."
	linefw "TODAY, I'M LOOKING FOR A"
	linefw "DRAGONITE Lv45 CARD."
	linefw "IN EXCHANGE FOR ONE, I WILL TRADE"
	linefw "THIS MARILL Lv17 CARD."
	linefw "DO YOU HAVE A DRAGONITE Lv45"
	linefw "YOU'RE WILLING TO TRADE?"
	done

Text0eac:
	text "TODAY I'M LOOKING TO TRADE FOR A"
	linefw "DRAGONITE Lv45 CARD."
	linefw "I'M OFFERING A MARILL Lv17"
	linefw "IN EXCHANGE FOR ONE."
	linefw "WOULD YOU HAPPEN TO HAVE AN EXTRA"
	linefw "DRAGONITE Lv45 TO TRADE?"
	done

Text0ead:
	text "OH, BUT IT DOESN'T LOOK LIKE"
	linefw "YOU HAVE A DRAGONITE Lv45 CARD. "
	linefw "I WANT TO TRADE MY MARILL Lv17"
	linefw "FOR A DRAGONITE Lv45 CARD."
	linefw "STOP BY SOME OTHER TIME IF YOU WOULD"
	linefw "STILL LIKE TO TRADE WITH ME..."
	done

Text0eae:
	text "ALL OF YOUR DRAGONITE Lv45"
	linefw "CARDS ARE BEING USED IN YOUR DECKS."
	linefw "YOU CANNOT TRADE CARDS THAT YOU'RE"
	linefw "USING TO DUEL OTHERS WITH."
	linefw "STOP BY SOME OTHER TIME IF YOU WOULD"
	linefw "STILL LIKE TO TRADE WITH ME..."
	done

Text0eaf:
	text "OOH, THANK YOU SO MUCH!"
	linefw "LET US TRADE RIGHT AWAY..."
	done

Text0eb0:
	text "<RAMNAME>", " TRADED A DRAGONITE Lv45"
	linefw "CARD FOR A MARILL Lv17 CARD!"
	done

Text0eb1:
	text "YOU HAVE MY GRATITUDE FOR THIS"
	linefw "DRAGONITE Lv45."
	linefw "THANK YOU SO MUCH. I THINK I'LL"
	linefw "WRITE ABOUT THIS IN MY JOURNAL."
	done

Text0eb2:
	text "THANK YOU VERY MUCH FOR TRADING"
	linefw "SO MUCH WITH ME, ", "<RAMNAME>", "."
	linefw "I THINK I'M GOING TO HEAD OUT TO"
	linefw "MY VILLA ON GR ISLAND."
	linefw "PLEASE FEEL FREE TO STOP BY"
	linefw "WHEN YOU'RE IN THE AREA."
	done

Text0eb3:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING YOUR POKÉMON CARDS?"
	linefw "I'VE RETURNED FROM DOING SOME"
	linefw "QUICK INVESTIGATIONS."
	linefw "I'M STILL A LITTLE BUSY CURRENTLY."
	linefw "PLEASE COME BACK LATER."
	done

Text0eb4:
	text "CONGRATULATIONS, ", "<RAMNAME>", "!"
	linefw "YOU'VE DONE WELL."
	linefw "THE NEWS HAS REACHED ME THAT YOU'VE"
	linefw "DEFEATED THE GR KING AT LAST!"
	linefw "I SUPPOSE THAT'S TO BE EXPECTED FROM"
	linefw "A POKÉMON CARD MASTER LIKE YOURSELF."
	linefw "WE'RE FREE TO COLLECT POKÉMON CARDS"
	linefw "AND BATTLE FOR ENJOYMENT NOW!"
	done

Text0eb5:
	text "YES, MY NAME IS NIKKI..."
	linefw "THE CLUB MASTER OF THE GRASS CLUB."
	linefw "YOU FOUGHT MISS BRITTANY TO LEARN"
	linefw "OF MY WHEREABOUTS, RIGHT?"
	linefw "THANK YOU VERY MUCH,"
	linefw "<RAMNAME>", "."
	linefw "SINCE YOU COULD DEFEAT BRITTANY,"
	linefw "SURELY YOU'RE TRUSTWORTHY."
	done

Text0eb6:
	text "PLEASE TAKE THIS."
	linefw " "
	linefw "IT MIGHT BE USEFUL WHEN"
	linefw "FIGHTING GR No.2."
	done

Text0eb7:
	text "<RAMNAME>", " GOT THE"
	linefw "GR No.2: DEFEAT! DECK!"
	done

Text0eb8:
	text "...YOU DON'T SEEM TO HAVE THE SPACE"
	linefw "NECESSARY TO MAKE THIS DECK."
	linefw "HERE, I'LL GIVE YOU ALL 60 CARDS"
	linefw "FROM THE GR No.2: DEFEAT! DECK."
	done

Text0eb9:
	text "<RAMNAME>", " GOT 60 CARDS"
	linefw "TO MAKE A NEW DECK!"
	done

Text0eba:
	text "I'LL FORWARD THE DECK INFORMATION TO"
	linefw "DR. MASON'S LAB FOR YOU."
	linefw "CHECK OUT HIS AUTO DECK MACHINE IF"
	linefw "YOU WANT TO BUILD IT QUICKLY."
	done

Text0ebb:
	text "PLEASE TAKE THIS AS WELL."
	done

Text0ebc:
	text "FEEL FREE TO USE IT AS YOU"
	linefw "LIKE IN ANY FUTURE DUELS."
	linefw "PLEASE DO YOUR BEST TO"
	linefw "SAVE THE GRASS CLUB!"
	done

Text0ebd:
	text "GR No.2 WAS FAR TOO POWERFUL"
	linefw "FOR ME TO DEFEAT MYSELF."
	linefw "<RAMNAME>", ","
	linefw "PLEASE DO YOUR BEST."
	done

Text0ebe:
	text "PLEASE DO YOUR BEST TO"
	linefw "SAVE THE GRASS CLUB!"
	done

Text0ebf:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "I HOPE YOU'RE ENJOYING THE ISLAND."
	linefw "I CAN SEE THAT YOU'RE BEING QUITE"
	linefw "AN ACTIVE PLAYER OVER HERE."
	linefw "AS YOU MAY KNOW,"
	linefw "THIS IS MY PERSONAL VILLA."
	linefw "I FREQUENTLY USE THIS AS A RETREAT"
	linefw "TO CONTEMPLATE COMPLEX STRATEGIES."
	linefw "IF YOU WISH TO SEE WHAT CARDS I AM"
	linefw "TRADING FOR, STOP BY SOMETIME."
	done

Text0ec0:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING BATTLING TEAM GR?"
	linefw "IT'S IMPORTANT TO TAKE SOME TIME OFF"
	linefw "TO STUDY YOUR POKÉMON CARDS DEEPLY."
	linefw "I'M SORRY TO SAY, BUT I'M NOT"
	linefw "LOOKING TO TRADE CARDS RIGHT NOW."
	linefw "YOU'RE WELCOME TO RETURN LATER,"
	linefw "HOWEVER. I'LL BE HERE STUDYING."
	done

Text0ec1:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING BATTLING TEAM GR?"
	linefw "I'M TAKING AN INTEREST IN LEGENDARY"
	linefw "FLYING POKÉMON CARDS AT THE MOMENT."
	linefw "SPECIFICALLY, I AM SEARCHING FOR"
	linefw "A MOLTRES Lv37 CARD."
	linefw "THIS PARTICULAR MOLTRES CARD HAS"
	linefw "THE ATTACK, 'DRY UP'."
	linefw "I'M OFFERING A SURFING PIKACHU CARD"
	linefw "IN EXCHANGE FOR ONE."
	linefw "DO YOU HAPPEN TO OWN AN EXPENDABLE"
	linefw "MOLTRES Lv37 CARD?"
	done

Text0ec2:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING YOUR POKÉMON CARDS?"
	linefw "I'M CURRENTLY RESEARCHING CARDS OF"
	linefw "LEGENDARY FLYING POKÉMON."
	linefw "CURRENTLY, I WISH TO OBTAIN A"
	linefw "MOLTRES Lv37 CARD."
	linefw "IN EXCHANGE FOR ONE, I AM WILLING TO"
	linefw "PART WITH MY SURFING PIKACHU CARD."
	linefw "DO YOU HAVE A MOLTRES Lv37 CARD"
	linefw "THAT YOU'D LIKE TO TRADE?"
	done

Text0ec3:
	text "THANKS FOR YOUR OFFER."
	linefw "I CAN SEE YOU REALLY WANT TO TRADE."
	linefw "HOWEVER, YOU DON'T SEEM TO OWN A"
	linefw "MOLTRES Lv37 CARD AT THE MOMENT."
	linefw "PERHAPS WE CAN TRADE LATER..."
	done

Text0ec4:
	text "OH, BUT AREN'T ALL OF YOUR"
	linefw "MOLTRES Lv37 CARDS IN YOUR DECKS?"
	linefw "YOU CANNOT TRADE CARDS THAT ARE"
	linefw "BEING USED IN GAME DECKS, YOU KNOW."
	linefw "OH WELL."
	linefw "PERHAPS WE CAN TRADE CARDS LATER..."
	done

Text0ec5:
	text "OH, THANK YOU VERY MUCH!"
	linefw "LET'S TRADE IMMEDIATELY..."
	done

Text0ec6:
	text "<RAMNAME>", " TRADED A MOLTRES Lv37"
	linefw "CARD FOR A SURFING PIKACHU CARD!"
	done

Text0ec7:
	text "I WHOLE-HEARTEDLY THANK YOU FOR"
	linefw "TRADING ME THIS MOLTRES Lv37."
	linefw "THIS IS THE FIRST CARD OF A"
	linefw "LEGENDARY POKÉMON I'VE GOTTEN."
	linefw "REALLY, THANK YOU SO MUCH!"
	linefw "I'LL RECORD THIS IN MY JOURNAL."
	done

Text0ec8:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING BATTLING TEAM GR?"
	linefw "I'M TAKING AN INTEREST IN LEGENDARY"
	linefw "FLYING POKÉMON CARDS AT THE MOMENT."
	linefw "I AM CURRENTLY SEARCHING FOR"
	linefw "AN ARTICUNO Lv34 CARD."
	linefw "THIS PARTICULAR ARTICUNO CARD HAS"
	linefw "THE POKÉMON POWER, 'AURORA VEIL'."
	linefw "I'M OFFERING ANOTHER SURFING"
	linefw "PIKACHU CARD IN EXCHANGE FOR ONE."
	linefw "THIS ONE, HOWEVER, IS DIFFERENT THAN"
	linefw "THE LAST ONE I HAD TRADED TO YOU."
	linefw "SO, HOW ABOUT IT? DO YOU HAVE A"
	linefw "SPARE ARTICUNO Lv34 CARD?"
	done

Text0ec9:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING YOUR POKÉMON CARDS?"
	linefw "I'M TAKING AN INTEREST IN LEGENDARY"
	linefw "FLYING POKÉMON CARDS AT THE MOMENT."
	linefw "I AM CURRENTLY SEARCHING FOR"
	linefw "AN ARTICUNO Lv34 CARD."
	linefw "I'M OFFERING ANOTHER SURFING"
	linefw "PIKACHU CARD IN EXCHANGE FOR ONE."
	linefw "THIS ONE, HOWEVER, IS DIFFERENT THAN"
	linefw "THE LAST ONE I HAD TRADED TO YOU."
	linefw "SO, HOW ABOUT IT? DO YOU HAVE A"
	linefw "SPARE ARTICUNO Lv34 CARD?"
	done

Text0eca:
	text "I THANK YOU FOR YOUR ENTHUSIASM,"
	linefw "BUT..."
	linefw "YOU DON'T ACTUALLY HAVE AN"
	linefw "ARTICUNO Lv34 CARD, DO YOU?"
	linefw "WELL, IF YOU DO HAPPEN TO COME UPON"
	linefw "ONE, COME BACK LATER TO TRADE."
	done

Text0ecb:
	text "THAT'S GREAT, BUT AREN'T ALL OF YOUR"
	linefw "ARTICUNO Lv34 CARDS IN YOUR DECKS?"
	linefw "YOU SIMPLY CANNOT TRADE CARDS WHILE"
	linefw "THEY'RE IN YOUR GAME DECKS."
	linefw "OH WELL."
	linefw "PERHAPS WE CAN TRADE CARDS LATER..."
	done

Text0ecc:
	text "OH, THANK YOU VERY MUCH!"
	linefw "LET'S TRADE IMMEDIATELY..."
	done

Text0ecd:
	text "<RAMNAME>", " TRADED AN ARTICUNO Lv34"
	linefw "CARD FOR A SURFING PIKACHU CARD!"
	done

Text0ece:
	text "MY THANKS TO YOU FOR TRADING ME"
	linefw "THIS ARTICUNO Lv34."
	linefw "THIS MAKES TWO CARDS OF A"
	linefw "LEGENDARY POKÉMON I'VE COLLECTED."
	linefw "REALLY, THANK YOU SO MUCH!"
	linefw "I'LL RECORD THIS IN MY JOURNAL."
	done

Text0ecf:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING BATTLING TEAM GR?"
	linefw "I'M CLOSE TO FINISHING MY COLLECTION"
	linefw "OF LEGENDARY FLYING POKÉMON CARDS."
	linefw "THE LAST ONE I NEED IS A"
	linefw "ZAPDOS Lv40 CARD."
	linefw "THAT ZAPDOS IS THE ONE WITH"
	linefw "THE 'THUNDERSTORM' ATTACK."
	linefw "I'M OFFERING ANOTHER FLYING"
	linefw "PIKACHU CARD IN EXCHANGE FOR ONE."
	linefw "THIS ONE HAS A DIFFERENT ILLUSTRATON"
	linefw "THAN OTHER FLYING PIKACHU CARDS."
	linefw "SO, HOW ABOUT IT? DO YOU HAVE AN"
	linefw "EXPENDABLE ZAPDOS Lv40 CARD?"
	done

Text0ed0:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING YOUR POKÉMON CARDS?"
	linefw "I'M HOPING TO COMPLETE MY COLLECTION"
	linefw "OF CARD OF LEGENDARY FLYING POKÉMON."
	linefw "THE LAST CARD I NEED TO ACCOMPLISH"
	linefw "THIS IS A ZAPDOS Lv40 CARD."
	linefw "IN RETURN, I'M OFFERING A RARE"
	linefw "FLYING PIKACHU CARD."
	linefw "THIS PARTICULAR FLYING PIKACHU HAS"
	linefw "AN ALTERNATE ILLUSTRATION."
	linefw "DO YOU HAPPEN TO HAVE AN EXTRA"
	linefw "ZAPDOS Lv40 YOU CAN TRADE ME?"
	done

Text0ed1:
	text "I AM VERY THANKFUL FOR YOUR"
	linefw "CONSIDERATION AND ENTHUSIASM."
	linefw "HOWEVER, IT SEEMS THAT YOU DON'T"
	linefw "OWN A ZAPDOS Lv40 CARD."
	linefw "WELL, PERHAPS WE CAN MAKE THE TRADE"
	linefw "LATER ON WHEN YOU DO HAVE ONE..."
	done

Text0ed2:
	text "OH, ALL OF YOUR ZAPDOS Lv40"
	linefw "CARDS ARE IN YOUR DECKS."
	linefw "YOU CAN'T TRADE CARDS THAT YOU'RE"
	linefw "USING TO PLAY THE GAME, REMEMBER."
	linefw "PERHAPS WE CAN TRADE LATER..."
	done

Text0ed3:
	text "OH, THANK YOU VERY MUCH!"
	linefw "LET'S TRADE IMMEDIATELY..."
	done

Text0ed4:
	text "<RAMNAME>", " TRADED A ZAPDOS Lv40"
	linefw "CARD FOR A FLYING PIKACHU CARD!"
	done

Text0ed5:
	text "THANK YOU EVER SO MUCH FOR THIS"
	linefw "ZAPDOS Lv40 CARD!"
	linefw "NOW MY COLLECTION OF LEGENDARY"
	linefw "FLYING POKÉMON CARDS IS COMPLETE!"
	linefw "REALLY, THANK YOU SO MUCH!"
	linefw "I'LL RECORD THIS IN MY JOURNAL."
	done
