Text1906:
	text "TAKE AN EVOLUTION CARD FROM YOUR"
	linefw "DISCARD PILE, SHOW IT TO YOUR"
	linefw "OPPONENT, AND PUT IT ON THE TOP OF"
	linefw "YOUR DECK."
	done

Text1907:
	text "POKÉDEX"
	done

Text1908:
	text "LOOK AT UP TO 5 CARDS FROM THE TOP"
	linefw "OF YOUR DECK AND REARRANGE THEM AS"
	linefw "YOU LIKE."
	done

Text1909:
	text "POKÉMON CENTER"
	done

Text190a:
	text "REMOVE ALL DAMAGE COUNTERS FROM ALL"
	linefw "OF YOUR OWN POKÉMON WITH DAMAGE"
	linefw "COUNTERS ON THEM, THEN DISCARD ALL"
	linefw "ENERGY CARDS ATTACHED TO THOSE"
	linefw "POKÉMON."
	done

Text190b:
	text "POKÉMON BREEDER"
	done

Text190c:
	text "PUT A STAGE 2 EVOLUTION CARD FROM"
	linefw "YOUR HAND ON THE MATCHING BASIC"
	linefw "POKÉMON. YOU CAN ONLY PLAY THIS CARD"
	linefw "WHEN YOU WOULD BE ALLOWED TO EVOLVE"
	linefw "THAT POKÉMON ANYWAY."
	done

Text190d:
	text "POKÉ FLUTE"
	done

Text190e:
	text "CHOOSE 1 BASIC POKÉMON CARD FROM"
	linefw "YOUR OPPONENT'S DISCARD PILE AND PUT"
	linefw "IT ONTO HIS OR HER BENCH. (YOU CAN'T"
	linefw "PLAY THIS CARD IF YOUR OPPONENT'S"
	linefw "BENCH IS FULL.)"
	done

Text190f:
	text "THE BOSS'S WAY"
	done

Text1910:
	text "SEARCH YOUR DECK FOR AN EVOLUTION"
	linefw "CARD WITH DARK IN ITS NAME. SHOW IT"
	linefw "TO YOUR OPPONENT AND PUT IT INTO"
	linefw "YOUR HAND. SHUFFLE YOUR DECK"
	linefw "AFTERWARD."
	done

Text1911:
	text "GOOP GAS ATTACK"
	done

Text1912:
	text "ALL POKÉMON POWERS STOP WORKING"
	linefw "UNTIL THE END OF YOUR OPPONENT'S"
	linefw "NEXT TURN."
	done

Text1913:
	text "BILL"
	done

Text1914:
	text "DRAW 2 CARDS."
	done

Text1915:
	text "BILL'S TELEPORTER"
	done

Text1916:
	text "FLIP A COIN. IF HEADS, DRAW 4 CARDS."
	done

Text1917:
	text "BILL'S COMPUTER"
	done

Text1918:
	text "BRING THIS CARD TO THE BILL'S"
	linefw "COMPUTER GAME AT THE GR GAME CENTER"
	linefw "ALONG WITH A COPY OF ANY OF THE"
	linefw "FOLLOWING CARDS AT ANY LEVEL:"
	linefw "OMANYTE, HAUNTER, MACHOKE, GRAVELER,"
	linefw "OR KADABRA."
	done

Text1919:
	text "GIVE UP BOTH CARDS AND"
	linefw "YOU WILL GET A SPECIAL PROMOTIONAL"
	linefw "CARD THROUGH THE MAIL IN RETURN."
	linefw "ASK FOR DETAILS AT THE GAME CENTER."
	linefw "(YOU CANNOT USE THIS CARD IN PLAY.)"
	done

Text191a:
	text "MASTER BALL"
	done

Text191b:
	text "LOOK AT 7 CARDS FROM THE TOP OF YOUR"
	linefw "DECK. YOU MAY CHOOSE A BASIC POKÉMON"
	linefw "OR EVOLUTION CARD FROM THOSE CARDS,"
	linefw "SHOW IT TO YOUR OPPONENT, THEN PUT"
	linefw "IT INTO YOUR HAND. SHUFFLE THE REST"
	linefw "INTO YOUR DECK."
	done

Text191c:
	text "LASS"
	done

Text191d:
	text "YOU AND YOUR OPPONENT SHOW EACH"
	linefw "OTHER YOUR HANDS, THEN SHUFFLE ALL"
	linefw "THE TRAINER CARDS FROM YOUR HANDS"
	linefw "INTO YOUR DECKS."
	done

Text191e:
	text "MAINTENENCE"
	done

Text191f:
	text "SHUFFLE 2 OF THE OTHER CARDS FROM"
	linefw "YOUR HAND INTO YOUR DECK IN ORDER"
	linefw "TO DRAW A CARD."
	done

Text1920:
	text "POKÉBALL"
	done

Text1921:
	text "FLIP A COIN. IF HEADS, YOU MAY"
	linefw "SEARCH YOUR DECK FOR ANY BASIC"
	linefw "POKÉMON OR EVOLUTION CARD. SHOW THAT"
	linefw "CARD TO YOUR OPPONENT, THEN PUT IT"
	linefw "INTO YOUR HAND. SHUFFLE YOUR DECK"
	linefw "AFTERWARD."
	done

Text1922:
	text "NIGHTLY GARBAGE RUN"
	done

Text1923:
	text "CHOOSE UP TO 3 BASIC POKÉMON CARDS,"
	linefw "EVOLUTION CARDS, AND/OR BASIC ENERGY"
	linefw "CARDS FROM YOUR DISCARD PILE. SHOW"
	linefw "THEM TO YOUR OPPONENT AND SHUFFLE"
	linefw "THEM INTO YOUR DECK."
	done

Text1924:
	text "RECYCLE"
	done

Text1925:
	text "FLIP A COIN. IF HEADS, PUT A CARD"
	linefw "IN YOUR DISCARD PILE ON TOP OF YOUR"
	linefw "DECK."
	done

Text1926:
	text "ROCKET'S SNEAK ATTACK"
	done

Text1927:
	text "LOOK AT YOUR OPPONENT'S HAND. IF"
	linefw "HE OR SHE HAS ANY TRAINER CARDS,"
	linefw "CHOOSE 1 OF THEM. YOUR OPPONENT"
	linefw "SHUFFLES THAT CARD INTO HIS OR HER"
	linefw "DECK."
	done

Text1928:
	text "HERE COMES TEAM ROCKET!"
	done

Text1929:
	text "EACH PLAYER PLAYS WITH HIS OR HER"
	linefw "PRIZE CARDS FACE UP FOR THE REST OF"
	linefw "THE GAME."
	done

Text192a:
	text "THE ROCKET'S TRAP"
	done

Text192b:
	text "FLIP A COIN. IF HEADS, CHOOSE UP TO"
	linefw "3 CARDS AT RANDOM FROM YOUR"
	linefw "OPPONENT'S HAND (DON'T LOOK AT"
	linefw "THEM). YOUR OPPONENT SHUFFLES THOSE"
	linefw "CARDS INTO HIS OR HER DECK."
	done
