Text1726:
	text "IT POSSESSES STRONG SPIRITUAL POWER."
	linefw "THE MORE DANGER IT FACES, THE"
	linefw "STRONGER ITS PSYCHIC POWER. "
	done

Text1727:
	text "ALAKAZAM "
	done

Text1728:
	text "DAMAGE SWAP"
	done

Text1729:
	text "AS OFTEN AS YOU LIKE DURING YOUR"
	linefw "TURN (BEFORE YOUR ATTACK), YOU MAY"
	linefw "MOVE 1 DAMAGE COUNTER FROM 1 OF YOUR"
	linefw "POKÉMON TO ANOTHER AS LONG AS YOU"
	linefw "DON'T KNOCK OUT THAT POKÉMON. THIS"
	linefw "POWER CAN'T BE USED IF ALAKAZAM IS"
	linefw "ASLEEP, CONFUSED, OR PARALYZED."
	done

Text172a:
	text "ITS HIGHLY DEVELOPED BRAIN IS ON PAR"
	linefw "WITH A SUPERCOMPUTER. IT CAN USE ALL"
	linefw "FORMS OF PSYCHIC ABILITIES."
	done

Text172b:
	text "TRANS DAMAGE"
	done

Text172c:
	text "DISCARD ALL ENERGY CARDS ATTACHED TO"
	linefw "ALAKAZAM IN ORDER TO SWITCH THE"
	linefw "NUMBER OF DAMAGE COUNTERS ON"
	linefw "ALAKAZAM WITH THE NUMBER OF DAMAGE"
	linefw "COUNTERS ON THE DEFENDING POKÉMON."
	linefw "(IT'S OKAY IF ONE OF THE POKÉMON"
	linefw "HAS NO DAMAGE COUNTERS ON IT.)"
	done

Text172d:
	text "ITS SUPERB MEMORY LETS IT RECALL"
	linefw "EVERYTHING IT HAS EXPERIENCED FROM"
	linefw "BIRTH. ITS IQ EXCEEDS 5,000. "
	done

Text172e:
	text "DARK ALAKAZAM "
	done

Text172f:
	text "TELEPORT BLAST"
	done

Text1730:
	text "YOU MAY SWITCH DARK ALAKAZAM WITH"
	linefw "ONE OF YOUR BENCHED POKÉMON."
	linefw "(DO THE DAMAGE BEFORE SWITCHING THE"
	linefw "POKÉMON.)"
	done

Text1731:
	text "CLOSING BOTH ITS EYES HEIGHTENS ALL"
	linefw "ITS OTHER SENSES. THIS ENABLES IT TO"
	linefw "USE ITS ABILITIES TO THEIR EXTREMES."
	done

Text1732:
	text "SLOWPOKE "
	done

Text1733:
	text "DOPEY"
	done

Text1734:
	text "ALTHOUGH SLOW, IT IS SKILLED AT"
	linefw "FISHING WITH ITS TAIL. IT DOES NOT"
	linefw "FEEL PAIN IF ITS TAIL IS BITTEN."
	done

Text1735:
	text "AFTERNOON NAP"
	done

Text1736:
	text "SEARCH YOUR DECK FOR A ", "<PSYCHIC>", " ENERGY"
	linefw "CARD AND ATTACH IT TO SLOWPOKE."
	linefw "SHUFFLE YOUR DECK AFTERWARD."
	done

Text1737:
	text "IT LAZES VACANTLY NEAR WATER. IF"
	linefw "SOMETHING BITES ITS TAIL, IT WON'T"
	linefw "EVEN NOTICE FOR A WHOLE DAY. "
	done

Text1738:
	text "SPACING OUT"
	done

Text1739:
	text "FLIP A COIN. IF HEADS, REMOVE A"
	linefw "DAMAGE COUNTER FROM SLOWPOKE. THIS"
	linefw "ATTACK CAN'T BE USED IF SLOWPOKE HAS"
	linefw "NO DAMAGE COUNTERS ON IT."
	done

Text173a:
	text "SCAVENGE"
	done

Text173b:
	text "DISCARD 1 ", "<PSYCHIC>", " ENERGY CARD FROM"
	linefw "SLOWPOKE IN ORDER TO USE THIS"
	linefw "ATTACK. PUT A TRAINER CARD FROM YOUR"
	linefw "DISCARD PILE INTO YOUR HAND."
	done

Text173c:
	text "A SWEET SAP LEAKS FROM ITS TAIL'S"
	linefw "TIP. ALTHOUGH NOT NUTRITIOUS, THE"
	linefw "TAIL IS PLEASANT TO CHEW ON. "
	done

Text173d:
	text "SLOWBRO "
	done

Text173e:
	text "STRANGE BEHAVIOR"
	done

Text173f:
	text "AS OFTEN AS YOU LIKE DURING YOUR"
	linefw "TURN (BEFORE YOUR ATTACK) YOU MAY"
	linefw "MOVE 1 DAMAGE COUNTER FROM 1 OF YOUR"
	linefw "POKÉMON TO SLOWBRO AS LONG AS YOU"
	linefw "DON'T KNOCK OUT SLOWBRO. THIS POWER"
	linefw "CAN'T BE USED IF SLOWBRO IS ASLEEP,"
	linefw "CONFUSED, OR PARALYZED."
	done

Text1740:
	text "HERMIT CRAB"
	done

Text1741:
	text "THOUGH USUALLY DIM WITTED, IT SEEMS"
	linefw "TO BECOME INSPIRED IF THE SHELLDER"
	linefw "ON ITS TAIL BITES DOWN."
	done

Text1742:
	text "BIG YAWN"
	done

Text1743:
	text "BOTH THE DEFENDING POKÉMON AND"
	linefw "SLOWBRO ARE NOW ASLEEP."
	done

Text1744:
	text "BIG SNORE"
	done

Text1745:
	text "YOU CAN ONLY USE THIS ATTACK IF"
	linefw "SLOWBRO IS ASLEEP."
	done

Text1746:
	text "NATURALLY DULL TO BEGIN WITH, IT"
	linefw "LOST ITS ABILITY TO FEEL PAIN DUE TO"
	linefw "SHELLDER'S SEEPING POISON. "
	done

Text1747:
	text "DARK SLOWBRO "
	done

Text1748:
	text "REEL IN"
	done

Text1749:
	text "WHEN YOU PLAY DARK SLOWBRO FROM"
	linefw "YOUR HAND, CHOOSE UP TO 3 BASIC"
	linefw "POKÉMON AND/OR EVOLUTION CARDS FROM"
	linefw "YOUR DISCARD PILE AND PUT THEM INTO"
	linefw "YOUR HAND."
	done

Text174a:
	text "FICKLE ATTACK"
	done

Text174b:
	text "IF THE TAIL-BITING SHELLDER IS"
	linefw "THROWN OFF IN A HARSH BATTLE, IT"
	linefw "REVERTS TO BEING A SLOWPOKE."
	done

Text174c:
	text "GASTLY "
	done

Text174d:
	text "SLEEPING GAS"
	done

Text174e:
	text "FLIP A COIN. IF HEADS, THE"
	linefw "DEFENDING POKÉMON IS NOW ASLEEP."
	done

Text174f:
	text "DESTINY BOND"
	done

Text1750:
	text "DISCARD 1 ", "<PSYCHIC>", " ENERGY CARD ATTACHED"
	linefw "TO GASTLY IN ORDER TO USE THIS"
	linefw "ATTACK. IF A POKÉMON KNOCKS OUT"
	linefw "GASTLY DURING YOUR OPPONENT'S NEXT"
	linefw "TURN, KNOCK OUT THAT POKÉMON."
	done

Text1751:
	text "GAS"
	done

Text1752:
	text "A POKÉMON BORN FROM POISON GASES."
	linefw "IT DEFEATS EVEN THE LARGEST FOES BY"
	linefw "ENVELOPING THEM IN GAS."
	done

Text1753:
	text "FRIGHTEN"
	done

Text1754:
	text "YOUR OPPONENT MAY NOT USE TRAINER"
	linefw "CARDS DURING HIS OR HER NEXT TURN."
	done

Text1755:
	text "DARKNESS"
	done

Text1756:
	text "THIS POKÉMON'S BODY IS 95 PERCENT"
	linefw "MADE UP OF GASES, WHICH ARE BLOWN"
	linefw "AWAY BY STRONG GUSTS OF WIND. "
	done

Text1757:
	text "LICK"
	done

Text1758:
	text "ENERGY CONVERSION"
	done

Text1759:
	text "PUT UP TO 2 ENERGY CARDS FROM YOUR"
	linefw "DISCARD PILE INTO YOUR HAND. GASTLY"
	linefw "DOES 10 DAMAGE TO ITSELF."
	done

Text175a:
	text "IT LICKS WITH ITS GASEOUS TONGUE TO"
	linefw "STEAL THE VICTIM'S LIFE FORCE. IT"
	linefw "LURKS IN DARKNESS FOR PREY."
	done

Text175b:
	text "HAUNTER "
	done

Text175c:
	text "TRANSPARENCY"
	done

Text175d:
	text "WHENEVER AN ATTACK DOES ANYTHING TO"
	linefw "HAUNTER, FLIP A COIN. IF HEADS,"
	linefw "PREVENT ALL EFFECTS OF THAT ATTACK,"
	linefw "INCLUDING DAMAGE, DONE TO HAUNTER."
	linefw "THIS POWER STOPS WORKING WHILE"
	linefw "HAUNTER IS ASLEEP, CONFUSED, OR"
	linefw "PARALYZED."
	done

Text175e:
	text "NIGHTMARE"
	done

Text175f:
	text "IT CAN SLIP THROUGH ANY OBSTACLE."
	linefw "IT LURKS INSIDE WALLS TO KEEP AN EYE"
	linefw "ON ITS FOES."
	done

Text1760:
	text "DREAM EATER"
	done

Text1761:
	text "YOU CAN'T USE THIS ATTACK UNLESS"
	linefw "THE DEFENDING POKÉMON IS ASLEEP."
	done

Text1762:
	text "EERIE LIGHT"
	done

Text1763:
	text "GRUDGE"
	done

Text1764:
	text "THIS ATTACK DOES 20 DAMAGE PLUS 10"
	linefw "MORE DAMAGE TIMES THE NUMBER OF"
	linefw "PRIZE CARDS YOUR OPPONENT HAS TAKEN."
	done

Text1765:
	text "IT LIKES TO LURK IN THE DARK AND TAP"
	linefw "SHOULDERS WITH A GASEOUS HAND. ITS"
	linefw "TOUCH CAUSES ENDLESS SHUDDERING. "
	done

Text1766:
	text "POLTERGEIST"
	done

Text1767:
	text "LOOK AT YOUR OPPONENT'S HAND. THIS"
	linefw "ATTACK DOES 10 DAMAGE TIMES THE"
	linefw "NUMBER OF TRAINER CARDS IN THEIR"
	linefw "HAND."
	done

Text1768:
	text "NIGHTMARE"
	done

Text1769:
	text "FLIP A COIN. IF HEADS, THE"
	linefw "DEFENDING POKÉMON IS NOW ASLEEP. IF"
	linefw "TAILS, THE DEFENDING POKÉMON IS NOW"
	linefw "CONFUSED."
	done

Text176a:
	text "DARK HAUNTER "
	done

Text176b:
	text "HARASS"
	done

Text176c:
	text "FLIP A COIN. IF HEADS, A"
	linefw "RANDOMLY SELECTED TRAINER CARD FROM"
	linefw "YOUR OPPONENT'S HAND IS SHUFFLED"
	linefw "BACK INTO HIS OR HER DECK."
	done

Text176d:
	text "IN TOTAL DARKNESS, WHERE NOTHING IS"
	linefw "VISIBLE, HAUNTER LURKS, SILENTLY"
	linefw "STALKING ITS NEXT VICTIM. "
	done

Text176e:
	text "GENGAR "
	done

Text176f:
	text "CURSE"
	done

Text1770:
	text "ONCE DURING YOUR TURN (BEFORE YOUR"
	linefw "ATTACK) YOU MAY MOVE 1 DAMAGE"
	linefw "COUNTER FROM 1 OF YOUR OPPONENT'S"
	linefw "POKÉMON TO ANOTHER (EVEN IF IT WOULD"
	linefw "KNOCK OUT THAT POKÉMON.) THIS POWER"
	linefw "CAN'T BE USED IF GENGAR IS ASLEEP,"
	linefw "CONFUSED, OR PARALYZED."
	done

Text1771:
	text "DARK MIND"
	done

Text1772:
	text "SHADOW"
	done

Text1773:
	text "LURKING IN THE SHADOWY CORNERS OF"
	linefw "ROOMS, IT AWAITS CHANCES TO STEAL"
	linefw "ITS PREY'S LIFE FORCE."
	done

Text1774:
	text "POWER OF DARKNESS"
	done

Text1775:
	text "WHEN YOU PLAY GENGAR FROM YOUR HAND,"
	linefw "YOU MAY FLIP A COIN. IF HEADS,"
	linefw "CHOOSE 1 OF YOUR OPPONENT'S POKÉMON."
	linefw "YOUR OPPONENT RETURNS THAT POKÉMON"
	linefw "AND ALL CARDS ATTACHED TO IT TO HIS"
	linefw "OR HER HAND. "
	done

Text1776:
	text "PSY HORROR"
	done

Text1777:
	text "UNDER A FULL MOON, THIS POKÉMON"
	linefw "LIKES TO MIMIC THE SHADOWS OF PEOPLE"
	linefw "AND LAUGH AT THEIR FRIGHT."
	done

Text1778:
	text "DARK GENGAR "
	done

Text1779:
	text "PLAY TRICKS"
	done

Text177a:
	text "ONCE DURING YOUR TURN (BEFORE YOUR"
	linefw "ATTACK) YOU MAY CHOOSE TO HAVE ALL"
	linefw "DAMAGE COUNTERS ON YOUR OPPONENT'S"
	linefw "POKÉMON RANDOMLY REARRANGED. THIS"
	linefw "POWER CAN'T BE USED IF DARK GENGAR"
	linefw "IS ASLEEP, CONFUSED, OR PARALYZED."
	done

Text177b:
	text "PUSH ASIDE"
	done

Text177c:
	text "FLIP A COIN. IF HEADS, YOUR"
	linefw "OPPONENT SHUFFLES A RANDOM BENCHED"
	linefw "POKÉMON AND ALL CARDS ATTACHED TO IT"
	linefw "INTO HIS OR HER DECK."
	done

Text177d:
	text "THE LEER THAT FLOATS IN DARKNESS"
	linefw "BELONGS TO A GENGAR DELIGHTING IN"
	linefw "CASTING CURSES ON PEOPLE. "
	done

Text177e:
	text "DROWZEE "
	done

Text177f:
	text "LONG-DISTANCE HYPNOSIS"
	done

Text1780:
	text "ONCE DURING YOUR TURN (BEFORE YOUR"
	linefw "ATTACK), YOU MAY FLIP A COIN. IF"
	linefw "HEADS, THE DEFENDING POKÉMON IS NOW"
	linefw "ASLEEP; IF TAILS, YOUR ACTIVE"
	linefw "POKÉMON IS NOW ASLEEP. THE POWER"
	linefw "CAN'T BE USED IF DROWZEE IS ASLEEP,"
	linefw "CONFUSED, OR PARALYZED."
	done

Text1781:
	text "HYPNOSIS"
	done

Text1782:
	text "IF YOU THINK THAT YOU HAD A GOOD"
	linefw "DREAM, BUT YOU CAN'T REMEMBER IT,"
	linefw "A DROWZEE HAS PROBABLY EATEN IT. "
	done

Text1783:
	text "IT CAN TELL WHAT PEOPLE ARE DREAMING"
	linefw "BY SNIFFING WITH ITS BIG NOSE. IT"
	linefw "LOVES FUN DREAMS."
	done

Text1784:
	text "HYPNO "
	done

Text1785:
	text "PUPPET MASTER"
	done

Text1786:
	text "IF A CLEFAIRY DOLL IS YOUR ACTIVE"
	linefw "POKÉMON, IT MAY USE ANY ATTACKS"
	linefw "HYPNO HAS AS LONG AS HYPNO HAS"
	linefw "ENOUGH ENERGY CARDS ATTACHED TO IT"
	linefw "TO PAY FOR THAT ATTACK'S ENERGY"
	linefw "COST."
	done

Text1787:
	text "ALWAYS HOLDING A PENDULUM THAT IT"
	linefw "SWINGS AT A STEADY RHYTHM, IT CAUSES"
	linefw "DROWSINESS IN ANYONE NEARBY. "
	done

Text1788:
	text "PROPHECY"
	done

Text1789:
	text "LOOK AT UP TO 3 CARDS FROM THE TOP"
	linefw "OF EITHER PLAYER'S DECK AND"
	linefw "REARRANGE THEM AS YOU LIKE."
	done

Text178a:
	text "SEEING ITS SWINGING PENDULUM CAN"
	linefw "INDUCE SLEEP IN THREE SECONDS, EVEN"
	linefw "IN SOMEONE WHO JUST WOKE UP."
	done

Text178b:
	text "DARK HYPNO "
	done

Text178c:
	text "PSYPUNCH"
	done

Text178d:
	text "BENCH MANIPULATION"
	done

Text178e:
	text "YOUR OPPONENT FLIPS A NUMBER OF"
	linefw "COINS EQUAL TO THE NUMBER OF POKÉMON"
	linefw "ON HIS OR HER BENCH. THIS ATTACK"
	linefw "DOES 20 DAMAGE TIMES THE NUMBER OF"
	linefw "TAILS. DON'T APPLY WEAKNESS OR"
	linefw "RESISTANCE FOR THIS ATTACK. (ANY"
	linefw "OTHER EFFECTS STILL HAPPEN.)"
	done

Text178f:
	text "WHEN IT IS VERY HUNGRY, IT PUTS"
	linefw "HUMANS IT MEETS TO SLEEP, THEN IT"
	linefw "FEASTS ON THEIR DREAMS. "
	done

Text1790:
	text "MR. MIME "
	done

Text1791:
	text "NEUTRAL DAMAGE"
	done

Text1792:
	text "DON'T APPLY WEAKNESS AND RESISTANCE"
	linefw "FOR ANY ATTACK. THIS POWER CAN'T BE"
	linefw "USED IF MR. MIME IS YOUR ACTIVE"
	linefw "POKÉMON."
	done

Text1793:
	text "JUGGLING"
	done

Text1794:
	text "FLIP 4 COINS. THIS ATTACK DOES 10"
	linefw "DAMAGE TIMES THE NUMBER OF HEADS."
	done

Text1795:
	text "BARRIER"
	done

Text1796:
	text "IT IS A PANTOMIME EXPERT THAT CAN"
	linefw "CREATE INVISIBLE BUT SOLID WALLS"
	linefw "USING MIMING GESTURES. "
	done

Text1797:
	text "INVISIBLE WALL"
	done

Text1798:
	text "WHENEVER AN ATTACK (INCLUDING YOUR"
	linefw "OWN) DOES 30 OR MORE DAMAGE TO MR."
	linefw "MIME (AFTER APPLYING WEAKNESS AND"
	linefw "RESISTANCE), PREVENT THAT DAMAGE."
	linefw "(ANY OTHER EFFECTS STILL HAPPEN.)"
	linefw "THIS POWER CAN'T USED IF MR. MIME IS"
	linefw "ASLEEP, CONFUSED, OR PARALYZED."
	done

Text1799:
	text "MEDITATE"
	done

Text179a:
	text "DOES 10 ADDITIONAL DAMAGE FOR EACH"
	linefw "DAMAGE COUNTER ON THE DEFENDING"
	linefw "POKÉMON."
	done

Text179b:
	text "EMANATIONS FROM ITS FINGERTIPS"
	linefw "SOLIDIFY THE AIR INTO INVISIBLE"
	linefw "WALLS THAT REPEL EVEN HARSH ATTACKS."
	done

Text179c:
	text "JYNX "
	done

Text179d:
	text "ICE PUNCH"
	done

Text179e:
	text "COLD BREATH"
	done

Text179f:
	text "HUMAN SHAPE"
	done

Text17a0:
	text "IT ROCKS ITS BODY RHYTHMICALLY."
	linefw "IT APPEARS TO ALTER THE RHYTHM"
	linefw "DEPENDING ON HOW IT IS FEELING. "
	done

Text17a1:
	text "ITS CRIES SOUND LIKE HUMAN SPEECH."
	linefw "HOWEVER, IT IS IMPOSSIBLE TO TELL"
	linefw "WHAT IT IS TRYING TO SAY."
	done

Text17a2:
	text "IT SPEAKS A LANGUAGE SIMILAR TO THAT"
	linefw "OF HUMANS. HOWEVER, IT SEEMS TO USE"
	linefw "DANCING TO COMMUNICATE. "
	done

Text17a3:
	text "MEWTWO "
	done

Text17a4:
	text "FLIP A COIN. IF HEADS, CHOOSE A"
	linefw "BASIC ENERGY CARD ATTACHED TO 1 OF"
	linefw "YOUR OPPONENT'S POKÉMON AND ATTACH"
	linefw "IT TO ANOTHER OF YOUR OPPONENT'S"
	linefw "POKÉMON OF YOUR CHOICE. "
	done

Text17a5:
	text "TELEKINESIS"
	done

Text17a6:
	text "CHOOSE 1 OF YOUR OPPONENT'S POKÉMON"
	linefw "AND DO 30 DAMAGE TO IT. DON'T APPLY"
	linefw "WEAKNESS AND RESISTANCE FOR THIS"
	linefw "ATTACK."
	done

Text17a7:
	text "GENETIC"
	done

Text17a8:
	text "BECAUSE ITS BATTLE ABILITIES WERE"
	linefw "RAISED TO THE ULTIMATE LEVEL, IT"
	linefw "THINKS ONLY OF DEFEATING ITS FOES."
	done

Text17a9:
	text "DISCARD 1 ENERGY CARD ATTACHED TO"
	linefw "MEWTWO IN ORDER TO PREVENT ALL"
	linefw "EFFECTS OF ATTACKS, INCLUDING"
	linefw "DAMAGE, DONE TO MEWTWO DURING YOUR"
	linefw "OPPONENT'S NEXT TURN."
	done

Text17aa:
	text "A POKÉMON CREATED BY RECOMBINING"
	linefw "MEW'S GENES. IT'S SAID TO HAVE THE"
	linefw "MOST SAVAGE HEART AMONG POKÉMON."
	done

Text17ab:
	text "PSY-CRASH"
	done

Text17ac:
	text "DOES 10 DAMAGE FOR EACH ", "<PSYCHIC>", " ENERGY"
	linefw "CARD ATTACHED TO ALL OF YOUR"
	linefw "OPPONENT'S POKÉMON."
	done

Text17ad:
	text "IT USUALLY REMAINS MOTIONLESS TO"
	linefw "CONSERVE ENERGY, SO THAT IT MAY"
	linefw "UNLEASH ITS FULL POWER IN BATTLE. "
	done

Text17ae:
	text "ENERGY ABSORPTION"
	done

Text17af:
	text "CHOOSE UP TO 2 ENERGY CARDS FROM"
	linefw "YOUR DISCARD PILE AND ATTACH THEM TO"
	linefw "MEWTWO."
	done

Text17b0:
	text "PSYBURN"
	done

Text17b1:
	text "A VICIOUS PSYCHIC POKÉMON CREATED BY"
	linefw "GENETIC ENGINEERING. ITS COLD EYES"
	linefw "STRIKE FEAR INTO ITS ENEMY. "
	done

Text17b2:
	text "COMPLETE RECOVERY"
	done

Text17b3:
	text "DISCARD ALL ENERGY CARDS ATTACHED TO"
	linefw "MEWTWO IN ORDER TO USE THIS ATTACK."
	linefw "REMOVE ALL DAMAGE COUNTERS AND ALL"
	linefw "OTHER COUNTERS FROM MEWTWO. IF"
	linefw "MEWTWO IS POISONED OR CONFUSED, IT"
	linefw "IS NO LONGER POISONED OR CONFUSED."
	done

Text17b4:
	text "PSY-BLAST"
	done

Text17b5:
	text "FLIP A COIN. IF HEADS, AND IF THE"
	linefw "DEFENDING POKÉMON HAS ANY ENERGY"
	linefw "CARDS ATTACHED TO IT, CHOOSE 1 OF"
	linefw "THEM AND DISCARD IT."
	done

Text17b6:
	text "ITS DNA IS ALMOST THE SAME AS MEW'S."
	linefw "HOWEVER, ITS SIZE AND DISPOSITION"
	linefw "ARE VASTLY DIFFERENT. "
	done

Text17b7:
	text "GR'S MEWTWO "
	done

Text17b8:
	text "DARK EDGE"
	done

Text17b9:
	text "ALL DAMAGE DONE BY DARK POKÉMON IS"
	linefw "INCREASED BY A RANDOM AMOUNT (0, 10,"
	linefw "OR 20). THIS POWER CAN'T BE USED IF"
	linefw "GR'S MEWTWO IS ASLEEP, CONFUSED,"
	linefw "OR PARALYZED."
	done

Text17ba:
	text "DARK POWER"
	done

Text17bb:
	text "FLIP A COIN FOR ALL DARK POKÉMON ON"
	linefw "YOUR BENCH. THIS ATTACK DOES 20"
	linefw "DAMAGE PLUS 20 MORE DAMAGE FOR EACH"
	linefw "HEADS."
	done

Text17bc:
	text "IT WAS CREATED BY A SCIENTIST AFTER"
	linefw "YEARS OF HORRIFIC GENE SPLICING AND"
	linefw "DNA ENGINEERING EXPERIMENTS. "
	done

Text17bd:
	text "MEW "
	done

Text17be:
	text "NEUTRALIZING SHIELD"
	done

Text17bf:
	text "PREVENT ALL EFFECTS OF ATTACKS,"
	linefw "INCLUDING DAMAGE, DONE TO MEW BY"
	linefw "EVOLVED POKÉMON (INCLUDING YOUR"
	linefw "OWN). THIS POWER STOPS WORKING WHILE"
	linefw "MEW IS ASLEEP, CONFUSED, OR"
	linefw "PARALYZED."
	done

Text17c0:
	text "NEW SPECIES"
	done

Text17c1:
	text "BECAUSE IT CAN USE ALL KINDS OF"
	linefw "MOVES, MANY SCIENTISTS BELIEVE MEW"
	linefw "TO BE THE ANCESTOR OF POKÉMON."
	done

Text17c2:
	text "MYSTERY ATTACK"
	done

Text17c3:
	text "DOES A RANDOM AMOUNT OF DAMAGE TO"
	linefw "THE DEFENDING POKÉMON AND MAY CAUSE"
	linefw "A RANDOM EFFECT TO THE DEFENDING"
	linefw "POKÉMON."
	done

Text17c4:
	text "SO RARE THAT IT IS STILL SAID TO BE"
	linefw "A MIRAGE BY MANY EXPERTS. ONLY A"
	linefw "FEW PEOPLE HAVE SEEN IT WORLDWIDE."
	done

Text17c5:
	text "PSYWAVE"
	done

Text17c6:
	text "DOES 10 DAMAGE TIMES THE NUMBER OF"
	linefw "ENERGY CARDS ATTACHED TO THE"
	linefw "DEFENDING POKÉMON."
	done

Text17c7:
	text "DEVOLUTION BEAM"
	done

Text17c8:
	text "CHOOSE AN EVOLVED POKÉMON (YOUR OWN"
	linefw "OR YOUR OPPONENT'S). RETURN THE"
	linefw "HIGHEST STAGE EVOLUTION CARD ON THAT"
	linefw "POKÉMON TO ITS PLAYER'S HAND. THAT"
	linefw "POKÉMON IS NO LONGER ASLEEP,"
	linefw "CONFUSED, PARALYZED, OR POISONED"
	linefw "(JUST AS IF YOU HAD EVOLVED IT)."
	done

Text17c9:
	text "APPARENTLY, IT APPEARS ONLY TO THOSE"
	linefw "PEOPLE WHO ARE PURE OF HEART AND"
	linefw "HAVE A STRONG DESIRE TO SEE IT. "
	done

Text17ca:
	text "PIDGEY "
	done

Text17cb:
	text "TINY BIRD"
	done

Text17cc:
	text "IT IS DOCILE AND PREFERS TO AVOID"
	linefw "CONFLICT. IF DISTURBED, HOWEVER,"
	linefw "IT CAN FEROCIOUSLY STRIKE BACK."
	done

Text17cd:
	text "GUST"
	done

Text17ce:
	text "IT USUALLY HIDES IN TALL GRASS."
	linefw "BECAUSE IT DISLIKES FIGHTING, IT"
	linefw "PROTECTS ITSELF BY KICKING UP SAND. "
	done

Text17cf:
	text "PIDGEOTTO "
	done

Text17d0:
	text "MIRROR MOVE"
	done

Text17d1:
	text "IF THIS POKÉMON WAS ATTACKED LAST"
	linefw "TURN, DO THE FINAL RESULT OF THAT"
	linefw "ATTACK TO THE DEFENDING POKÉMON."
	done

Text17d2:
	text "BEAK"
	done

Text17d3:
	text "IT FLIES OVER ITS WIDE TERRITORY IN"
	linefw "SEARCH OF PREY, DOWNING IT WITH ITS"
	linefw "HIGHLY DEVELOPED CLAWS."
	done

Text17d4:
	text "TWISTER"
	done

Text17d5:
	text "UNLESS THIS ATTACK KNOCKS OUT THE"
	linefw "DEFENDING POKÉMON, FLIP A COIN. IF"
	linefw "HEADS, RETURN ALL ENERGY CARDS AND"
	linefw "TRAINER CARDS ATTACHED TO THAT"
	linefw "POKÉMON TO YOUR OPPONENT'S HAND."
	done

Text17d6:
	text "FLIP A COIN. IF HEADS, DURING YOUR"
	linefw "OPPONENT'S NEXT TURN, PREVENT ALL"
	linefw "EFFECTS OF ATTACKS, INCLUDING"
	linefw "DAMAGE, DONE TO PIDGEOTTO. IF TAILS,"
	linefw "THIS ATTACK DOES NOTHING (NOT EVEN"
	linefw "DAMAGE)."
	done

Text17d7:
	text "IT HAS OUTSTANDING VISION. HOWEVER"
	linefw "HIGH IT FLIES, IT IS ABLE TO"
	linefw "DISTINGUISH THE MOVEMENTS OF PREY. "
	done

Text17d8:
	text "PIDGEOT "
	done

Text17d9:
	text "SLICING WIND"
	done

Text17da:
	text "DOES 30 DAMAGE TO 1 OF YOUR"
	linefw "OPPONENT'S POKÉMON CHOSEN AT RANDOM."
	linefw "DON'T APPLY WEAKNESS AND RESISTANCE"
	linefw "FOR THIS ATTACK. (ANY OTHER EFFECTS"
	linefw "THAT WOULD HAPPEN AFTER APPLYING"
	linefw "WEAKNESS AND RESISTANCE STILL"
	linefw "HAPPEN.)"
	done

Text17db:
	text "TORNADO"
	done

Text17dc:
	text "SWITCH PIDGEOT WITH 1 OF YOUR"
	linefw "BENCHED POKÉMON CHOSEN AT RANDOM."
	linefw "IF YOUR OPPONENT HAS ANY BENCHED"
	linefw "POKÉMON, SWITCH THE DEFENDING"
	linefw "POKÉMON WITH 1 OF THEM CHOSEN AT"
	linefw "RANDOM. (DO THE DAMAGE BEFORE"
	linefw "SWITCHING THE POKÉMON.)"
	done

Text17dd:
	text "BY FLAPPING ITS WINGS WITH ALL ITS"
	linefw "MIGHT, PIDGEOT CAN MAKE A GUST OF"
	linefw "WIND CAPABLE OF BENDING TALL TREES."
	done

Text17de:
	text "HURRICANE"
	done

Text17df:
	text "UNLESS THIS ATTACK KNOCKS OUT THE"
	linefw "DEFENDING POKÉMON, RETURN THE"
	linefw "DEFENDING POKÉMON AND ALL CARDS"
	linefw "ATTACHED TO IT TO YOUR OPPONENT'S"
	linefw "HAND."
	done

Text17e0:
	text "IT SPREADS ITS GORGEOUS WINGS WIDELY"
	linefw "TO INTIMIDATE ENEMIES. IT RACES"
	linefw "THROUGH THE SKIES AT MACH-2 SPEED. "
	done

Text17e1:
	text "RATTATA "
	done

Text17e2:
	text "CAUTIOUS IN THE EXTREME, ITS HARDY"
	linefw "VITALITY LETS IT LIVE IN ANY KIND OF"
	linefw "ENVIRONMENT."
	done

Text17e3:
	text "TRICKERY"
	done

Text17e4:
	text "ONCE DURING YOUR TURN (BEFORE YOUR"
	linefw "ATTACK), YOU MAY SWITCH 1 OF YOUR"
	linefw "PRIZES WITH THE TOP CARD OF YOUR"
	linefw "DECK. THIS POWER CAN'T BE USED IF"
	linefw "RATTATA IS ASLEEP, CONFUSED, OR"
	linefw "PARALYZED."
	done

Text17e5:
	text "IT EATS EVERYTHING. WHEREVER FOOD IS"
	linefw "AVAILABLE, IT WILL SETTLE DOWN AND"
	linefw "PRODUCE OFFSPRING CONTINUOUSLY. "
	done

Text17e6:
	text "LIVING WHEREVER THERE IS FOOD"
	linefw "AVAILABLE, IT CEASELESSLY SCAVENGES"
	linefw "FOR EDIBLES THE ENTIRE DAY. "
	done

Text17e7:
	text "RATICATE "
	done

Text17e8:
	text "SUPER FANG"
	done

Text17e9:
	text "DOES DAMAGE TO THE DEFENDING POKÉMON"
	linefw "EQUAL TO HALF THE DEFENDING"
	linefw "POKÉMON'S REMAINING HP (ROUNDED UP"
	linefw "TO THE NEAREST 10)."
	done

Text17ea:
	text "IT WHITTLES ITS CONSTANTLY GROWING"
	linefw "FANGS BY GNAWING ON HARD THINGS."
	linefw "IT CAN CHEW APART CINDER WALLS."
	done

Text17eb:
	text "DARK RATICATE "
	done

Text17ec:
	text "HYPER FANG"
	done

Text17ed:
	text "GNAWS ON ANYTHING WITH ITS TOUGH"
	linefw "FANGS. IT CAN EVEN TOPPLE CONCRETE"
	linefw "BUILDINGS BY GNAWING ON THEM. "
	done

Text17ee:
	text "SPEAROW "
	done

Text17ef:
	text "IT FLAPS ITS SHORT WINGS TO FLUSH"
	linefw "OUT INSECTS FROM TALL GRASS. IT THEN"
	linefw "PLUCKS THEM WITH ITS STUBBY BEAK. "
	done

Text17f0:
	text "FURY ATTACK"
	done

Text17f1:
	text "VERY PROTECTIVE OF ITS TERRITORY, IT"
	linefw "FLAPS ITS SHORT WINGS BUSILY TO DART"
	linefw "AROUND AT HIGH SPEED. "
	done

Text17f2:
	text "IT FLAPS ITS SMALL WINGS BUSILY TO"
	linefw "FLY. USING ITS BEAK, IT SEARCHES IN"
	linefw "GRASS FOR PREY."
	done

Text17f3:
	text "FEAROW "
	done

Text17f4:
	text "DRILL DIVE"
	done

Text17f5:
	text "BEAK"
	done

Text17f6:
	text "IT SHOOTS ITSELF SUDDENLY HIGH INTO"
	linefw "THE SKY, THEN PLUMMETS DOWN IN ONE"
	linefw "FELL SWOOP TO STRIKE ITS PREY. "
	done

Text17f7:
	text "DRILL PECK"
	done

Text17f8:
	text "IT HAS THE STAMINA TO KEEP FLYING"
	linefw "ALL DAY ON ITS BROAD WINGS. IT"
	linefw "FIGHTS BY USING ITS SHARP BEAK."
	done

Text17f9:
	text "DARK FEAROW "
	done

Text17fa:
	text "FLY HIGH"
	done

Text17fb:
	text "DURING YOUR NEXT TURN, DARK"
	linefw "FEAROW'S DRILL DIVE'S BASE DAMAGE IS"
	linefw "DOUBLED."
	done

Text17fc:
	text "DRILL DIVE"
	done

Text17fd:
	text "YOU CAN'T ATTACK OR RETREAT DURING"
	linefw "YOUR NEXT TURN."
	done

Text17fe:
	text "IT USES ITS LONG BEAK TO ATTACK. IT"
	linefw "HAS A SURPRISINGLY LONG REACH, SO IT"
	linefw "MUST BE TREATED WITH CAUTION. "
	done

Text17ff:
	text "CLEFAIRY "
	done

Text1800:
	text "METRONOME"
	done

Text1801:
	text "CHOOSE 1 OF THE DEFENDING POKÉMON'S"
	linefw "ATTACKS. METRONOME COPIES THAT"
	linefw "ATTACK EXCEPT FOR ITS ENERGY COSTS"
	linefw "AND ANYTHING ELSE REQUIRED IN ORDER"
	linefw "TO USE THAT ATTACK, SUCH AS"
	linefw "DISCARDING ENERGY CARDS. (THIS"
	linefw "POKÉMON'S TYPE IS STILL COLORLESS.)"
	done

Text1802:
	text "FAIRY"
	done

Text1803:
	text "IT FLIES USING THE WINGS ON ITS BACK"
	linefw "TO COLLECT MOONLIGHT. THIS POKÉMON"
	linefw "IS DIFFICULT TO FIND."
	done

Text1804:
	text "FOLLOW ME"
	done

Text1805:
	text "SHINING FINGERS"
	done

Text1806:
	text "THOUGHT TO LIVE WITH OTHERS ON QUIET"
	linefw "MOUNTAINS, IT IS POPULAR FOR ITS"
	linefw "ADORABLE NATURE. "
	done

Text1807:
	text "CLEFABLE "
	done

Text1808:
	text "ALL DAMAGE DONE BY ATTACKS TO"
	linefw "CLEFABLE DURING YOUR OPPONENT'S NEXT"
	linefw "TURN IS REDUCED BY 20 (AFTER"
	linefw "APPLYING WEAKNESS AND RESISTANCE)."
	done

Text1809:
	text "ITS HEARING IS SO ACUTE IT CAN HEAR"
	linefw "A PIN DROP OVER HALF A MILE AWAY. IT"
	linefw "LIVES ON QUIET MOUNTAINS."
	done

Text180a:
	text "DARK CLEFABLE "
	done

Text180b:
	text "DARKNESS VEIL"
	done

Text180c:
	text "ALL DAMAGE DONE TO DARK POKÉMON IS"
	linefw "REDUCED BY A RANDOM NUMBER (0, 10,"
	linefw "OR 20) AS LONG AS THAT POKÉMON IS"
	linefw "THE ACTIVE POKÉMON. THIS POWER STOPS"
	linefw "WORKING WHEN DARK CLEFABLE IS"
	linefw "ASLEEP, CONFUSED, OR PARALYZED."
	done

Text180d:
	text "DARK SONG"
	done

Text180e:
	text "FLIP A COIN. IF HEADS, THE"
	linefw "DEFENDING POKÉMON IS NOW ASLEEP AND"
	linefw "THIS ATTACK DOES 10 DAMAGE TO EACH"
	linefw "OF YOUR OPPONENT'S BENCHED POKÉMON."
	done

Text180f:
	text "RARELY SEEN BY PEOPLE, IT IS SAID TO"
	linefw "BE DRAWN BY THE FULL MOON TO PLAY AT"
	linefw "DESERTED LAKES. "
	done

Text1810:
	text "JIGGLYPUFF "
	done

Text1811:
	text "DOUBLE-EDGE"
	done

Text1812:
	text "BALLOON"
	done

Text1813:
	text "WHEN IT WAVERS ITS BIG, ROUND EYES,"
	linefw "IT BEGINS SINGING A LULLABY THAT"
	linefw "MAKES EVERYONE DROWSY."
	done

Text1814:
	text "FRIENDSHIP SONG"
	done

Text1815:
	text "FLIP A COIN. IF HEADS, PUT A BASIC"
	linefw "POKÉMON CARD CHOSEN AT RANDOM FROM"
	linefw "YOUR DECK ONTO YOUR BENCH. (YOU"
	linefw "CAN'T USE THIS ATTACK IF YOUR BENCH"
	linefw "IS FULL.)"
	done

Text1816:
	text "EXPAND"
	done

Text1817:
	text "ALL DAMAGE DONE TO JIGGLYPUFF DURING"
	linefw "YOUR OPPONENT'S NEXT TURN IS REDUCED"
	linefw "BY 10 (AFTER APPLYING WEAKNESS AND"
	linefw "RESISTANCE)."
	done

Text1818:
	text "IT CAPTIVATES FOES WITH ITS HUGE,"
	linefw "ROUND EYES, THEN LULLS THEM TO SLEEP"
	linefw "BY SINGING A SOOTHING MELODY. "
	done

Text1819:
	text "LULLABY"
	done

Text181a:
	text "IF IT INFLATES TO SING A LULLABY,"
	linefw "IT CAN PERFORM LONGER AND CAUSE SURE"
	linefw "DROWSINESS IN ITS AUDIENCE. "
	done

Text181b:
	text "WIGGLYTUFF "
	done

Text181c:
	text "DO THE WAVE"
	done
