Text1107:
	text "THEN LET'S TRA..."
	linefw "WHAT? IT'S BEING USED IN A DECK!"
	linefw "WE CAN'T TRADE IF YOUR CARD IS"
	linefw "STUCK IN A DECK, YOU KNOW!"
	done

Text1108:
	text "ALRIGHT!"
	linefw "HERE'S MY JIGGLYPUFF Lv12!"
	done

Text1109:
	text "THANKS A LOT!"
	done

Text110a:
	text "GOOD AFTERNOON!"
	linefw " "
	linefw "THANKS AGAIN FOR THE SNORLAX Lv20"
	linefw "CARD! I REALLY NEEDED IT!"
	done

Text110b:
	text "WHY, HELLO, LITTLE DEAR!"
	linefw "TELL ME, DO YOU KNOW ABOUT IMAKUNI?"
	linefw "HE'S A STRANGE LITTLE MAN WHO"
	linefw "DRESSES IN BLACK TIGHTS, YOU SEE!"
	linefw "HE TENDS TO WANDER AIMLESSLY FROM"
	linefw "CLUB TO CLUB ON THIS ISLAND."
	linefw "IF YOU FIND HIM, CHALLENGE HIM TO A"
	linefw "DUEL! YOU MAY LEARN SOMETHING!"
	done

Text110c:
	text "HEY, DID YOU KNOW?"
	linefw "THAT IMAKUNI? GUY..."
	linefw "HE USES A POKÉMON CARD"
	linefw "BASED OFF OF HIMSELF!"
	linefw "I WANT TO HAVE A DUEL WITH HIM."
	linefw "IT MUST BE SUCH A STRONG CARD!!"
	done

Text110d:
	text "WOW!!!"
	linefw "IMAKUNI'S HERE RIGHT NOW!"
	linefw "YOU SHOULD GO SPEAK WITH HIM."
	linefw "YOU MAY LEARN SOMETHING FROM HIM."
	done

Text110e:
	text "I'M SO EMBARRASSED!"
	linefw "TEAM GR HAS TAKEN ALL OF MY CARDS!"
	linefw "THEY'RE SUPPOSEDLY HERE RIGHT NOW"
	linefw "FIGHTING THE CLUB MASTER, GENE!"
	linefw "YAAH...THIS IS A BIG PROBLEM..."
	done

Text110f:
	text "I'VE HEARD THAT GENE DEFEATED"
	linefw "GR No.1 AND MADE HIM RUN AWAY."
	done

Text1110:
	text "SOME OF MY CARDS HAVE BEEN RETURNED."
	done

Text1111:
	text "ALL OF THE CARDS THAT WERE STOLEN"
	linefw "SEEMED TO HAVE RETURNED."
	linefw "THANK YOU VERY MUCH, ", "<RAMNAME>", "."
	linefw "IT WAS ALL THANKS TO YOUR EFFORTS."
	done

Text1112:
	text "SINCE TEAM GR TOOK EVERYONE'S CARDS,"
	linefw "NO ONE CAN PLAY CARDS ANY MORE."
	linefw "IT'S SO BORING NOW..."
	done

Text1113:
	text "DR. MASON HAS SOME OF THE STOLEN"
	linefw "CARDS BACK FROM TEAM GR."
	linefw "HE'S SLOWLY RETURNING THEM ALL"
	linefw "TO THEIR ORIGINAL OWNERS!!"
	done

Text1114:
	text "I DON'T JUST COLLECT CARDS."
	linefw "I MAKE DECKS WITH THEM, TOO!"
	done

Text1115:
	text "THANK YOU FOR VISITING. THIS IS"
	linefw "TEAM GR'S PSYCHIC STRONGHOLD."
	done

Text1116:
	text "THANK YOU FOR VISITING. THIS IS"
	linefw "TEAM GR'S PSYCHIC STRONGHOLD."
	linefw "THIS FORTRESS IS THE LAST STRUCTURE"
	linefw "PROTECTING GR CASTLE..."
	linefw "THE LEADER OF THE PSYCHIC STRONGHOLD"
	linefw "IS A WOMAN NAMED CLAIRE."
	linefw "ALONGSIDE HER ARE 4 OTHER"
	linefw "TEAM GR MEMBERS TO FIGHT."
	linefw "OUT OF THESE FOUR, YOU NEED ONLY"
	linefw "DEFEAT THREE MEMBERS TO MOVE ON."
	linefw "YOU'LL LEARN ABOUT EACH MEMBER'S"
	linefw "SPECIAL BATTLE RULES INSIDE."
	linefw "THAT IS ALL. PLEASE ENJOY DUELLING"
	linefw "IN TEAM GR'S PSYCHIC STRONGHOLD."
	done

Text1117:
	text "I'LL ADMIT, YOU ARE FAR MORE"
	linefw "ADEPT THAN I HAD ASSUMED."
	done

Text1118:
	text "THAT'S THE GR PSYCHIC COIN, A PRIZE"
	linefw "THAT IS REQUIRED TO ENTER GR CASTLE."
	linefw "THE OTHER NECESSITY FOR ENTRY"
	linefw "LIES IN THE COLORLESS ALTAR."
	done

Text1119:
	text "THAT'S THE GR PSYCHIC COIN, A PRIZE"
	linefw "THAT IS REQUIRED TO ENTER GR CASTLE."
	linefw "YOUR NEXT OBJECTIVE IS TO MEET WITH"
	linefw "KING VILLICCI IN GR CASTLE."
	done

Text111a:
	text "IT SEEMS THE CHILD IS JUST AS YOU'VE"
	linefw "SAID: TOUGH AND ENJOYS DUELLING..."
	linefw "I SEE NOW WHY YOU HAD NO WORRIES"
	linefw "WAITING HERE FOR ", "<RAMNAME>", "."
	done

Text111b:
	text "THEN HONOR YOUR PROMISE."
	done

Text111c:
	text "HAH! YOU'RE FREE TO DO AS YOU WISH."
	done

Text111d:
	text "<RAMNAME>", "."
	done

Text111e:
	text "I'M GRAND MASTER ROD. I WAS WAITING"
	linefw "FOR YOU TO WIN YOUR WAY HERE."
	linefw "IT IS MY BELIEF THAT ONLY YOU HOLD"
	linefw "THE POWER TO DEFEAT TEAM GR."
	linefw "I DON'T THINK IT'S WRONG TO USE"
	linefw "TEAM GR'S CARDS."
	linefw "HOWEVER, TAKING OTHERS' CARDS AWAY"
	linefw "FROM THEM IS A DIFFERENT STORY."
	linefw "I'M CERTAIN YOU UNDERSTAND BEST"
	linefw "AFTER ALL OF YOUR FIGHTS SO FAR."
	linefw "GO FIND THE GR KING VILLICCI!"
	linefw "FIND HIM AND DEFEAT HIM."
	linefw "I DON'T MEAN TO SOUND DEMANDING, BUT"
	linefw "YOU'RE THE ONLY ONE WHO CAN DO IT."
	linefw "I SINCERELY HOPE THAT THIS CARD"
	linefw "WILL HELP YOU ON YOUR JOURNEY."
	done

Text111f:
	text "I'M GOING TO GO RETURN"
	linefw "TO THE POKÉMON DOME."
	linefw "ONCE THERE, WE'LL BEGIN PREPARATIONS"
	linefw "FOR THE FINAL CUP."
	linefw "THE WINNER OF THAT CUP EARNS"
	linefw "THE LEGENDARY POKÉMON CARDS."
	linefw "I HOPE YOU'LL VISIT ONCE WE HAVE"
	linefw "EVERYTHING READY TO GO."
	linefw "THEN WE'LL SEE FOR SURE IF YOU HAVE"
	linefw "MORE POWER THAN THE GRAND MASTERS!"
	done

Text1120:
	text "I WILL REMAIN HERE IN CASE"
	linefw "YOU WOULD LIKE ANOTHER BATTLE."
	done

Text1121:
	text "JUST FOCUS ON WINNING YOUR BATTLE"
	linefw "WITH CLAIRE RIGHT NOW. "
	done

Text1122:
	text "I'VE BEEN MONITORING THE WAY YOU"
	linefw "DUEL WITH HIDDEN CAMERAS DOWN BELOW."
	linefw "I'M FAIRLY CERTAIN YOU DO NOT HAVE"
	linefw "THE CAPACITY TO DEFEAT ME IN BATTLE."
	linefw "IT'S A WHOLE DIFFERENT EXPERIENCE"
	linefw "WHEN YOU BATTLE AGAINST ME."
	linefw "NORMALLY, YOU DISCARD A K.O.'D"
	linefw "POKÉMON AND ITS ENERGY CARDS."
	linefw "UNDER MY RULES, THE DISCARDED BASIC"
	linefw "ENERGY CARDS RETURN TO THE HAND."
	linefw "SO? DO YOU UNDERSTAND MY TERMS?"
	done

Text1123:
	text "HEAR THE RULES AGAIN?"
	done

Text1124:
	text "THEN I SUPPOSE YOU'LL BE"
	linefw "CHALLENGING ME TO A DUEL NEXT?"
	done

Text1125:
	text "HAVE YOU COME TO CHALLENGE ME"
	linefw "TO A CARD BATTLE?"
	linefw "DO YOU REMEMBER MY RULES?"
	done

Text1126:
	text "IF YOU DON'T NEED TO HEAR THE RULES,"
	linefw "SHALL WE BEGIN OUR CARD BATTLE?"
	done

Text1127:
	text "WHEN A POKÉMON IS KNOCKED OUT,"
	linefw "IT'S PLACED IN THE DISCARD PILE."
	linefw "HOWEVER, ALL BASIC ENERGY ATTACHED"
	linefw "TO IT WILL RETURN TO YOUR HAND."
	linefw "DO YOU UNDERSTAND MY SIMPLE"
	linefw "BATTLE RULE?"
	done

Text1128:
	text "WOULD YOU LIKE TO DUEL CLAIRE?"
	done

Text1129:
	text "WE'LL USE 6 PRIZE CARDS."
	done

Text112a:
	text "THERE'S NOTHING FORCING YOU TO"
	linefw "HAVE A CARD BATTLE WITH ME."
	linefw "THEN AGAIN, IF YOU PLAN ON GETTING"
	linefw "TO GR CASTLE, YOU'LL HAVE TO."
	done

Text112b:
	text "I'D ENJOY HAVING ANOTHER PLEASANT"
	linefw "BATTLE AGAINST YOU, IF YOU LIKE."
	linefw "MY BATTLE CONDITIONS REMAIN"
	linefw "UNCHANGED."
	linefw "ANY TIME A POKÉMON IS PLACED INTO"
	linefw "YOUR DISCARD PILE..."
	linefw "ALL BASIC ENERGY CARDS ATTACHED"
	linefw "TO IT WILL BE RETURNED TO YOUR HAND."
	linefw "DO YOU UNDERSTAND MY TERMS?"
	linefw "IF SO, LET'S BATTLE!"
	done

Text112c:
	text "WELL, I'LL BE HERE IF YOU EVER FANCY"
	linefw "HAVING ANOTHER CARD BATTLE WITH ME."
	done

Text112d:
	text "YOU'RE GOOD, FIGHTING SO WELL"
	linefw "UNDER MY OWN TERMS."
	done

Text112e:
	text "EVERYTHING FOLLOWED MY"
	linefw "PREMONITIONS EXACTLY!"
	done

Text112f:
	text "WELL, WELL. I LOST."
	done

Text1130:
	text "THE MOST ENJOYABLE CARD BATTLES"
	linefw "ARE THE MOST DIFFICULT ONES."
	done

Text1131:
	text "DID YOU HAVE FUN, ", "<RAMNAME>", "?"
	done

Text1132:
	text "SO YOU'VE ARRIVED, THEN."
	done

Text1133:
	text "BEFORE WE START OUR BATTLE, ALLOW ME"
	linefw "TO SUMMON THE FORT'S SPECIAL GUEST."
	linefw "HE'S A YOUNG MAN MY MEMBERS HAPPENED"
	linefw "TO KIDNAP. HE'LL BE HERE SHORTLY."
	done

Text1134:
	text "IS IT AS YOU HAVE PREDICTED?"
	linefw "HAS ", "<RAMNAME>", "..."
	done

Text1135:
	text "I CAN'T SAY FOR CERTAIN!"
	linefw ""
	linefw "WE CAN ONLY GET CONFIRMATION BY"
	linefw "WATCHING THE FUTURE UNFOLD."
	done

Text1136:
	text "WELL, I'M READY FOR OUR BATTLE,"
	linefw "<RAMNAME>", "!"
	done

Text1137:
	text "WAIT RIGHT THERE..."
	linefw ""
	text "<RAMNAME>", "!"
	done

Text1138:
	text "THE NAME'S CLAIRE. I'M THE LEADER"
	linefw "OF TEAM GR'S PSYCHIC STRONGHOLD."
	done

Text1139:
	text "SO YOU'RE THE TROUBLEMAKER TRYING"
	linefw "TO RECOVER THE CARDS WE'VE STOLEN."
	linefw "YOU'VE INDEED COME FAR."
	linefw "I WON'T PRAISE YOUR EFFORTS, THOUGH."
	linefw "I ASSUME YOU'VE SET YOUR SIGHTS"
	linefw "ON GR CASTLE?"
	linefw "WELL, YOU'VE GOT TO GET THROUGH ME"
	linefw "FIRST, KID. I WON'T GO EASY ON YOU."
	linefw "HOWEVER, IF YOU DO HAPPEN TO"
	linefw "BEAT ME, I'LL ADMIT MY DEFEAT."
	linefw "ALLOW ME TO INTRODUCE MY FELLOW"
	linefw "STRONGHOLD MEMBERS."
	done

Text113a:
	text "FIRST IS CLYDE, TO MY LEFT!"
	done

Text113b:
	text "THANKS MUCH."
	linefw "I'M CLYDE..."
	done

Text113c:
	text "NEXT IS THE YOUNG AND TALENTED"
	linefw "VICTORIA!"
	done

Text113d:
	text "<RAMNAME>", "!"
	linefw "I'VE BEEN WAITING!"
	done

Text113e:
	text "EASY, VICTORIA! PLEASE WAIT FOR ME"
	linefw "TO COMPLETE MY INTRODUCTIONS."
	done

Text113f:
	text "I WASN'T THAAAAT LOUD..."
	linefw "YOU DON'T HAVE TO BE SO STRICT!"
	done

Text1140:
	text "THERE YOU GO AGAIN."
	linefw "YOU DON'T LISTEN TO A WORD I SAY!"
	done

Text1141:
	text "OKAY, OKAY! STOP IT, PLEEEASE!"
	linefw "I'LL BE QUIET..."
	done

Text1142:
	text "I BET YOU NEVER SUSPECTED THE FAMED"
	linefw "GR No.3 COULD BE SO PRETTY, EH?"
	linefw "THAT'S RIGHT! CUTE LITTLE VICTORIA"
	linefw "WAS GR No.3 THE WHOLE TIME!"
	done

Text1143:
	text "UP NEXT IS KEVIN!"
	done

Text1144:
	text "YEEEAH! HI, I'M KEVIN."
	linefw "WE'RE WELL MET, ", "<RAMNAME>", "."
	done

Text1145:
	text "FINALLY, ALLOW ME TO INTRODUCE"
	linefw "MY DAUGHTER, HEIDI."
	done

Text1146:
	text "YOU ONLY NEED TO DEFEAT 3 OF THESE"
	linefw "STRONGHOLD MEMBERS TO MOVE ON."
	linefw "IF YOU CAN MANAGE THAT,"
	linefw "I'LL TURN MY ELEVATOR ON FOR YOU."
	linefw "I'LL BE WAITING FOR YOU"
	linefw "IN THE UPPER ROOM."
	done

Text1147:
	text "SINCE YOU'VE DEFEATED 3 MEMBERS,"
	linefw "YOU MAY COME UP TO THE TOP FLOOR."
	linefw "I'LL BE WAITING FOR YOU TO ARRIVE"
	linefw "TO START OUR CARD DUEL."
	done

Text1148:
	text "ARE YOU CHOOSING ME AS ONE OF YOUR"
	linefw "BATTLE OPPONENTS?"
	linefw "ALRIIIGHT! I'M A STRONG, SERIOUS,"
	linefw "AND DETERMINED FIGHTER!"
	linefw "THERE'S NO WAY YOU'LL BE ABLE TO"
	linefw "TOP MY DECK THIS TIME. NOPE!"
	linefw "MY CHALLENGER REQUIREMENT IS A"
	linefw "RESTRICTION ON ENERGY TYPE!"
	linefw "THE ONLY ENERGY CARDS YOU'RE ALLOWED"
	linefw "TO USE ARE PSYCHIC ENERGY CARDS!"
	linefw "I HOPE YOUR DECK IS MADE WITH THE"
	linefw "PSYCHIC-TYPE IN MIND!"
	linefw "C'MON, C'MON! LET'S FIGHT!!"
	linefw "I'M GONNA BLOW YOU AWAY!"
	done

Text1149:
	text "I HOPE YOUR DECK IS MADE WITH ONLY"
	linefw "PSYCHIC-TYPE ENERGY CARDS!"
	linefw "IF IT IS, I'LL ACCEPT YOUR CHALLENGE"
	linefw "AND SHOW YOU HOW STRONG I'VE BECOME!"
	done

Text114a:
	text "WOULD YOU LIKE TO DUEL VICTORIA?"
	done

Text114b:
	text "WAIT WAAAIT!"
	linefw "WHAT DO YOU THINK YOU'RE DOING?!"
	linefw "YOU'VE GOT ENERGY CARDS THAT AREN'T"
	linefw "PSYCHIC-TYPE IN YOUR DECK!"
	linefw "YOU DO WANT TO TEST YOUR MIGHT"
	linefw "AGAINST ME, CORRECT?"
	linefw "THEN GET RIDDA THAT OTHER ENERGY AND"
	linefw "REPLACE IT WITH PSYCHIC-TYPE ENERGY!"
	done

Text114c:
	text "HAH! YOUR DECK'S ENERGY CARDS ARE"
	linefw "ALL PSYCHIC-TYPE!"
	linefw "THEN LET'S START THIS SHOW RIGHT"
	linefw "WITH 4 PRIZE CARDS!"
	done

Text114d:
	text "WHAT WHAT WHAAAAT?! ARE YOU GONNA"
	linefw "FIGHT THE OTHER MEMBERS INSTEAD?"
	linefw "FINE, GET OUTTA MY FACE, THEN!"
	done

Text114e:
	text "WHAAAT? YOU WANNA FIGHT AGAINST MY"
	linefw "SUPERIOR ABILITIES AGAIN?"
	linefw "DON'T GET TOO COCKY JUST BECAUSE"
	linefw "YOU'VE BEATEN ME IN PREVIOUS DUELS!"
	linefw "ALRIGHT! I'M READY AND RARING TO GO!"
	linefw "BUT REMEMBER, I HAVE SPECIAL RULES!"
	linefw "MY RESTRICTION IS THAT ALL ENERGY IN"
	linefw "YOUR DECK MUST BE PSYCHIC ENERGY."
	done

Text114f:
	text "ALL OF THE ENERGY CARDS IN YOUR DECK"
	linefw "ARE PSYCHIC-TYPE, RIGHT?"
	linefw "BECAUSE I REFUSE TO FIGHT YOU"
	linefw "UNLESS THEY ARE."
	done

Text1150:
	text "UH, THIS DECK HERE? IT HAS ENERGY"
	linefw "CARDS THAT AREN'T PSYCHIC-TYPE."
	linefw "DON'T FOOL AROUND WITH ME! ACCEPT"
	linefw "ONLY IF YOU FOLLOW MY RULES! YEESH!"
	done

Text1151:
	text "THE PRIZE CARD COUNT IS 4!"
	linefw ""
	linefw "THERE'S NO WAY I'M GONNA LOSE"
	linefw "THIS TIME!"
	done

Text1152:
	text "*SIGH* WELL THAT'S A LETDOWN."
	linefw "YOU'RE NO FUN AT AAAAALL..."
	linefw "I GUESS THAT'S TO BE EXPECTED"
	linefw "WHEN I'M SO STRONG, THOUGH!"
	done

Text1153:
	text "EEEEE! I CAN'T BELIEEEEVE IT!"
	linefw "I LOST...YOU'RE SO TOUGH...!"
	done

Text1154:
	text "IT'S NO WONDER I LOST SO BADLY"
	linefw "IN OUR PRIOR CONFRONTATIONS!"
	done

Text1155:
	text "SEE? I TOLD YOU I WAS TOUGH AND"
	linefw "FIGHTING SERIOUSLY THIS TIME!"
	linefw "I WON SO QUICKLY! YOU NEED TO TRAIN"
	linefw "10000 YEARS TO CATCH UP TO MY LEVEL!"
	done

Text1156:
	text "WHY? WHYYYY?"
	linefw "WHY DO I LOSE WHEN I'M SO STRONG?"
	done

Text1157:
	text "DON'T THINK YOU'RE HOT STUFF JUST"
	linefw "'CAUSE YOU OVERCAME MY STRENGTH!"
	done

Text1158:
	text "MY APOLOGIES! I'M SO STRONG THAT I"
	linefw "SIMPLY CAN'T HOLD MY POWER BACK!"
	done

Text1159:
	text "HEY, I'LL ACTIVATE MY SWITCH."
	linefw "YOU CAN THANK ME LATER!"
	done

Text115a:
	text "WHEN THE THREE LIGHTS ARE LIT,"
	linefw "THE ELEVATOR IS ACTIVATED."
	linefw "BUT I'LL BET YOU ALREADY KNEW"
	linefw "THAT FROM BEFORE, RIIIGHT?"
	linefw "YOU ALREADY BEAT ME WITH YOUR"
	linefw "STUPID SUPERHUMAN ABILITIES!!"
	linefw "YOU HAVE TO DEFEAT OTHER MEMBERS"
	linefw "NOW IF YOU WANT TO GO ON!!"
	done

Text115b:
	text "WHY WAS I THE LAST ONE YOU FOUGHT?!"
	linefw "BEING THE LAST IS SO LAAAME!!"
	done

Text115c:
	text "GO TO THE ELEVATOR QUICKLY!"
	linefw "CLAIRE SHOULD BE HERE SOON."
	done

Text115d:
	text "THE ELEVATOR IS MOVING!"
	linefw "I'LL HELP KEEP IT GOING, I GUESS."
	done

Text115e:
	text "BEATING ME ACCOMPLISHED NOTHING!"
	linefw "THE ELEVATOR'S ALREADY WORKING!"
	done

Text115f:
	text "I'M KEVIN, ONE OF TEAM GR'S"
	linefw "PSYCHIC FORTRESS MEMBERS."
	linefw "BATTLES WITH ME ARE A BIT EXTREME."
	linefw "I USE A CUSTOM RULE FOR RESISTANCE."
	linefw "INSTEAD OF THE USUAL -30 DAMAGE,"
	linefw "ALL RESISTANCE IS A -10 REDUCTION."
	linefw "IF YOU FEEL CONFIDENT WITH -10"
	linefw "RESISTANCE, LET US START THE DUEL."
	done

Text1160:
	text "'LO, ", "<RAMNAME>", "."
	linefw "ARE UP FOR A CARD BATTLE?"
	linefw "I LIKE TO CHANGE THE GAME MECHANICS"
	linefw "A BIT FOR RESISTANCE IN MY DUELS."
	linefw "RESISTANCE DAMAGE GOES FROM -30"
	linefw "TO -10. REMEMBER?"
	linefw "SHALL WE BEGIN, THEN?"
	done

Text1161:
	text "WOULD YOU LIKE TO DUEL KEVIN?"
	done

Text1162:
	text "4 PRIZE CARDS."
	done

Text1163:
	text "FEEL FREE TO CHALLENGE THE OTHER"
	linefw "MEMBERS IF YOU LIKE. IT'S A-OK."
	done

Text1164:
	text "BACK FOR ANOTHER CHALLENGE?"
	linefw "ARE YOU STILL OKAY WITH MY RULES?"
	linefw "RESISTANCE WILL BE -10 INSTEAD OF"
	linefw "-30 FOR THE DURATION OF OUR DUEL."
	linefw "IF THAT DOESN'T BOTHER YOU,"
	linefw "LET'S START THE FIGHT."
	done

Text1165:
	text "IF YOU DON'T THINK YOU CAN TAKE ME,"
	linefw "I'M A-OK WITH YOU BACKING OUT."
	done

Text1166:
	text "I GUESS I LOST!"
	linefw "YOU'RE TOUGH, ", "<RAMNAME>", "!"
	done

Text1167:
	text "IT'S RARE FOR MY PSYCHIC POWERS"
	linefw "TO BE SO INACCURATE."
	done

Text1168:
	text "EEYAH HA HAAAAA!!"
	linefw "I'M THE WINNER!"
	done

Text1169:
	text "OH NOOO!!"
	linefw "I'M THE LOSER!"
	done

Text116a:
	text "<RAMNAME>", ", YOUR PSYCHIC"
	linefw "POWERS SURPASS MY OWN!!"
	done

Text116b:
	text "YES! YES! YES!"
	linefw "I'M THE WINNER!"
	done

Text116c:
	text "OH, I GUESS I SHOULD ACTIVATE MY"
	linefw "ELEVATOR SWITCH FOR YOU, THEN."
	done

Text116d:
	text "WHEN 3 OF THE ELEVATOR'S LIGHTS ARE"
	linefw "LIT, YOU CAN USE IT TO MEET CLAIRE."
	linefw "YOU CAN'T REACH HER ANY OTHER WAY,"
	linefw "I'M AFRAID."
	done

Text116e:
	text "AHH, I GUESS I WAS THE LAST."
	linefw ""
	linefw "ALRIGHT, I'LL DO MY PART TO TURN"
	linefw "THE ELEVATOR ON."
	done

Text116f:
	text "SINCE THE ELEVATOR IS ACTIVATED,"
	linefw "YOU CAN GO MEET CLAIRE AT THE TOP."
	linefw "WHEN YOU GO UP THERE,"
	linefw "GIVE HER MY BEST REGARDS!"
	done

Text1170:
	text "I'LL ACTIVATE MY SWITCH FOR YA."
	done

Text1171:
	text "THE ELEVATOR'S ALREADY WORKING."
	linefw "MY SWITCH WON'T DO ANYTHING."
	done

Text1172:
	text "AH, YES. YOU WANT TO DUEL WITH ME?"
	linefw "OKAY, BUT I HAVE A SPECIAL RULE."
	linefw "I'D LIKE FOR YOUR DECK TO HAVE A"
	linefw "TOTAL OF 6 GASTLY AND HAUNTER CARDS."
	linefw "ANY COMBINATION OF THE TWO IS FINE."
	linefw "3 AND 3, 4 AND 2; WHATEVER WORKS."
	linefw "OF COURSE, YOU'RE FREE TO EVEN USE"
	linefw "4 HAUNTER AND 2 GASTLY IF YOU WANT."
	linefw "ANYWAY, WHEN YOUR DECK HAS AT LEAST"
	linefw "6 OF THESE GHOST CARDS, I'LL DUEL."
	linefw "SO ARE YOU READY TO FIGHT? FEEL FREE"
	linefw "TO BUILD A NEW DECK IF YOU NEED TO."
	done

Text1173:
	text "HAVE YOU PREPARED A DECK"
	linefw "FACILITATING MY REQUIREMENTS?"
	linefw "REMEMBER, I ONLY DUEL DECKS WITH A"
	linefw "TOTAL OF 6 GASTLY AND HAUNTER CARDS."
	linefw "IF YOU HAVE ANY COMBINATION OF THESE"
	linefw "TOTALING 6 CARDS, WE MAY BATTLE."
	done

Text1174:
	text "WOULD YOU LIKE TO DUEL CLYDE?"
	done

Text1175:
	text "YOUR DECK DOESN'T HAVE 6 TOTAL"
	linefw "GASTLY AND HAUNTER CARDS."
	linefw "I WON'T ACCEPT YOUR CHALLENGE"
	linefw "IN THAT CASE."
	done

Text1176:
	text "YEAH, YOU'VE GOT A COMBINATION OF"
	linefw "6 OF THE CARDS I REQUESTED!"
	linefw "WITH THAT ASIDE,"
	linefw "LET'S DUEL WITH 4 PRIZE CARDS."
	linefw "WELL, SHALL WE BEGIN?"
	done

Text1177:
	text "AH, OKAY."
	linefw "THEN WE WON'T HAVE A CARD BATTLE..."
	done

Text1178:
	text "ARE YOU CHALLENGING ME AGAIN?"
	linefw "MY REQUIREMENTS ARE STILL THE SAME."
	linefw "DOES YOUR DECK CONTAIN 6 TOTAL"
	linefw "GASTLY AND HAUNTER CARDS?"
	linefw "IF SO, LET US BEGIN OUR FIGHT."
	done

Text1179:
	text "YEP, ALL 6 ARE THERE, AS REQUESTED."
	linefw ""
	linefw "SET ASIDE 4 PRIZE CARDS AND"
	linefw "WE SHALL BEGIN OUR DUEL."
	done

Text117a:
	text "*SIGH*..."
	done

Text117b:
	text "Y-YEAH, I LOST."
	linefw "HERE ARE YOUR BOOSTER PACKS."
	done

Text117c:
	text "BUT HOW COULD I LOSE...?"
	linefw "BOO HOO HOO..."
	done

Text117d:
	text "IT'S ONLY NATURAL THAT I'D WIN"
	linefw "USING MY OWN SPECIAL RULE..."
	done

Text117e:
	text "SINCE I LOST, I GUESS I HAVE TO"
	linefw "GIVE YOU SOME BOOSTER PACKS."
	done

Text117f:
	text "I DIDN'T THINK A BATTLE USING MY"
	linefw "REQUIREMENT WOULD BE SO EASY..."
	done

Text1180:
	text "AHH, SORRY. I'LL DO MY PART TO HELP"
	linefw "ACTIVATE THE ELEVATOR."
	done

Text1181:
	text "UNLESS ITS 3 LIGHTS ARE LIT,"
	linefw "THE ELEVATOR WON'T BUDGE."
	linefw "DEFEAT SOME OTHER STRONGHOLD MEMBERS"
	linefw "TO FULLY ACTIVATE IT."
	done

Text1182:
	text "OH, I'LL TURN THE FINAL SWITCH ON."
	done

Text1183:
	text "SINCE THIS MEANS THE ELEVATOR IS"
	linefw "NOW OPERATIONAL, YOU CAN MOVE ON."
	linefw "CLAIRE SHOULD BE WAITING FOR YOU"
	linefw "AT THE TOP OF THE STRONGHOLD."
	done

Text1184:
	text "SINCE THE OTHER MEMBERS ACTIVATED"
	linefw "THEIR SWITCHES, SHOULD I, TOO?"
	done

Text1185:
	text "WELL, MY SWITCH IS ACTIVATED EVEN"
	linefw "THOUGH THE ELEVATOR'S BEEN WORKING."
	done

Text1186:
	text "I'M HEIDI, THE DAUGHTER OF THE"
	linefw "STRONGHOLD'S LEADER, CLAIRE."
	linefw "YOU CHOSE ME TO BE ONE OF YOUR"
	linefw "REQUIRED OPPONENTS, CORRECT?"
	linefw "IN THAT CASE, I MUST ASK YOU TO"
	linefw "FOLLOW MY OWN PERSONAL RULE."
	linefw "PLEASE DO NOT INCLUDE ANY TRAINER"
	linefw "CARDS IN YOUR DECK FOR OUR BATTLE."
	linefw "THIS MEANS YOU CAN'T HAVE ANY CARDS"
	linefw "LIKE POTIONS OR CLEFAIRY DOLLS."
	linefw "IF EVEN 1 IS INCLUDED IN YOUR DECK,"
	linefw "I WILL REFUSE TO BATTLE YOU."
	done

Text1187:
	text "WE ALL HAVE SPECIAL REQUIREMENTS"
	linefw "FOR OPPONENTS TO BATTLE US HERE."
	linefw "MINE ARE THAT YOUR DECK MUST NOT"
	linefw "CONTAIN ANY TRAINER CARDS."
	linefw "IF YOU HAVE SUCH A DECK READIED,"
	linefw "I SHALL ACCEPT YOUR CHALLENGE."
	done

Text1188:
	text "WOULD YOU LIKE TO DUEL HEIDI?"
	done

Text1189:
	text "EXCUSE ME, WERE YOU AWARE THAT YOU"
	linefw "HAVE TRAINER CARDS IN THAT DECK?"
	linefw "MY MOTHER TOLD ME TO BE STRICT WITH"
	linefw "MY REQUIREMENTS, NO MATTER WHAT."
	linefw "I APOLOGIZE."
	linefw "I CANNOT ACCEPT YOUR CHALLENGE."
	done

Text118a:
	text "YOU HAVE FOLLOWED MY REQUEST"
	linefw "MOST ADMIRABLY."
	linefw "IF YOU WOULD PLEASE,"
	linefw "PLACE 4 PRIZE CARDS SO WE MAY BEGIN."
	done

Text118b:
	text "I'M GOING TO CONTINUE GUARDING"
	linefw "MY MOM, JUST AS SHE TAUGHT ME."
	linefw "FEEL FREE TO RETURN FOR A BATTLE"
	linefw "IF YOU CHANGE YOUR MIND."
	done

Text118c:
	text "<RAMNAME>", ", SINCE I LOST TO YOU,"
	linefw "I FEEL LIKE I'VE LET MY MOTHER DOWN."
	linefw "I'D LIKE TO FIGHT YOU AGAIN TO WIN"
	linefw "BACK MY HONOR...BUT..."
	linefw "PLEASE ALLOW ME TO CONTINUE USING"
	linefw "MY CUSTOM DUEL REQUIREMENT."
	linefw "I'D LIKE TO FIGHT YOU ONLY IF"
	linefw "YOUR DECK CONTAINS NO TRAINER CARDS."
	done

Text118d:
	text "PARDON ME, BUT I CAN SEE THAT YOU"
	linefw "HAVE AT LEAST ONE TRAINER CARD."
	linefw "I'M STAUNCH ON THE RULE I'VE MADE"
	linefw "TO PROTECT MY MOTHER'S NAME."
	linefw "PLEASE COME BACK ONCE YOU REMOVE ALL"
	linefw "OF THE TRAINER CARDS FROM YOUR DECK."
	done

Text118e:
	text "WE SHALL FIGHT TO 4 PRIZE CARDS."
	done

Text118f:
	text "I UNDERSTAND. IT IS FINE"
	linefw "IF YOU DO NOT WISH TO PLAY."
	linefw "I HOPE YOUR FUTURE BATTLES ARE"
	linefw "PLEASANT AND ENJOYABLE."
	done

Text1190:
	text "MY MOTHER'S NAME HAS BEEN SHAMED BY"
	linefw "MY LOSS TO YOU IN OUR PREVIOUS DUEL."
	linefw "I WILL STRIVE MY HARDEST TO DEFEAT"
	linefw "YOU, ", "<RAMNAME>", "."
	linefw "WON'T YOU PLEASE DUEL ME AGAIN?"
	linefw "THE RULES ARE THE SAME AS BEFORE."
	linefw "YOUR DECK MUST HAVE NO TRAINER"
	linefw "CARDS. ARE YOU PREPARED?"
	done

Text1191:
	text "I HAVE RECEIVED PERMISSION FROM"
	linefw "MY MOTHER TO FIGHT YOU AGAIN."
	linefw "HOWEVER, I STILL DO NOT LIKE"
	linefw "USING TRAINER CARDS."
	linefw "PLEASE ACCEPT MY CHALLENGE USING A"
	linefw "DECK WITHOUT TRAINER CARDS."
	done

Text1192:
	text "AS EXPECTED, YOU'VE DEFEATED ME."
	done

Text1193:
	text "MOTHER, I HOPE IT IS ALRIGHT..."
	linefw "YOUR DAUGHTER HAS LOST..."
	done

Text1194:
	text "IT IS MY VICTORY."
	linefw ""
	linefw "IF YOU DO NOT FEEL THAT YOU CAN WIN"
	linefw "AGAINST ME, PLEASE DUEL THE OTHERS."
	done

Text1195:
	text "OH DEAR, I'VE LOST AGAIN..."
	linefw "WHY HAVE I BEEN PLAYING SO BADLY?"
	done

Text1196:
	text "IT'S FUN TO HAVE CARD BATTLES FOR"
	linefw "THE LOVE OF THE GAME."
	linefw "BY ALL MEANS,"
	linefw "CHALLENGE ME ANY TIME YOU LIKE."
	done

Text1197:
	text "MOTHER! YOUR DAUGHTER HEIDI HAS"
	linefw "DEFEATED THE MIGHTY ", "<RAMNAME>", "!"
	linefw "IT SEEMS YOU HAD QUITE A LOT OF"
	linefw "DIFFICULTY FIGHTING ON MY TERMS!"
	done

Text1198:
	text "I WAS DEFEATED, SO I'LL HELP YOU IN"
	linefw "YOUR TASK TO TURN ON THE ELEVATOR."
	done

Text1199:
	text "THE ELEVATOR WILL BE ACTIVATED"
	linefw "THE MOMENT YOU DEFEAT 3 OF US."
	done

Text119a:
	text "SINCE I WAS YOUR FINAL OPPONENT,"
	linefw "THE ELEVATOR WILL NOW WORK AGAIN."
	done

Text119b:
	text "PLEASE USE IT TO VISIT MY MOTHER."
	done

Text119c:
	text "I SUPPOSE I SHOULD STILL FOLLOW THE"
	linefw "PROTOCOL FOR ACTIVATING MY SWITCH."
	linefw "...EVEN THOUGH THE ELEVATOR IS"
	linefw "ALREADY AVAILABLE FOR USE."
	done

Text119d:
	text "BOY"
	done

Text119e:
	text "LITTLE MISS"
	done

Text119f:
	text "OOOH HOO HOO!"
	linefw "I WISH TO TRADE CARDS!"
	linefw "I'M LOOKING FOR"
	linefw "DARK HYPNO Lv26!"
	linefw "I CAN GIVE YOU MY RARE"
	linefw "MEWTWO Lv60 CARD IN EXCHANGE!"
	linefw "WHAT DO YOU SAY?"
	linefw "HMM, ", "<RAMTEXT>", "?"
	done

Text11a0:
	text "OOOH HOO HOO! I HAVE A PRECIOUS"
	linefw "MEWTWO Lv60 CARD THAT'S DEAR TO ME!"
	linefw "BUT...I NEED A DARK HYPNO Lv26!"
	linefw "I'D GLADLY TRADE MY MEWTWO FOR IT!"
	linefw "DOES THAT SOUND OKAY TO YOU?"
	done

Text11a1:
	text "I'M GIVING YOU A GREAT DEAL,"
	linefw "SO WHY DON'T YOU WANT TO TRADE?"
	linefw "I DON'T MEAN TO BE IMPOLITE,"
	linefw "BUT I REALLY DO NEED THAT CARD."
	linefw "YET I GUESS THERE'S NOTHING MORE"
	linefw "I CAN DO ABOUT IT."
	linefw "I'M SO SAD...."
	linefw "OOH HOO HOO HOO!!"
	done

Text11a2:
	text "OH, ", "<RAMTEXT>", "... DON'T YOU"
	linefw "REALIZE YOU DON'T HAVE THE CARD?"
	linefw "YOU'RE SO IRRESPONSIBLE, TRYING"
	linefw "TO TRADE THINGS YOU DON'T HAVE."
	done

Text11a3:
	text "OH, YOU'RE SO DISAPPOINTING!"
	linefw ""
	linefw "YOU'RE USING ALL COPIES OF THE CARD"
	linefw "I'D LIKE IN YOUR DECKS!"
	linefw "PLEASE, JUST TAKE ONE OUT OF YOUR"
	linefw "DECK SO YOU CAN TRADE IT TO ME!"
	done
