Text181d:
	text "DOES 10 DAMAGE PLUS 10 MORE DAMAGE"
	linefw "FOR EACH OF YOUR BENCHED POKÉMON."
	done

Text181e:
	text "ITS FINE FUR FEELS SUBLIME TO THE"
	linefw "TOUCH. IT CAN EXPAND ITS BODY BY"
	linefw "INHALING AIR."
	done

Text181f:
	text "HELPING HAND"
	done

Text1820:
	text "ONCE DURING YOUR TURN (BEFORE YOUR"
	linefw "ATTACK) YOU MAY FLIP A COIN. IF"
	linefw "HEADS, YOUR ACTIVE POKÉMON IS NO"
	linefw "LONGER ASLEEP, CONFUSED, PARALYZED,"
	linefw "OR POISONED. THIS POWER CAN'T BE"
	linefw "USED IF THIS CARD IS YOUR ACTIVE"
	linefw "POKÉMON."
	done

Text1821:
	text "IN THE OPPONENT'S NEXT TURN, ANY"
	linefw "DAMAGE WIGGLYTUFF RECEIVES IS"
	linefw "REDUCED BY 10 (AFTER APPLYING"
	linefw "WEAKNESS AND RESISTANCE)."
	done

Text1822:
	text "THEIR FUR FEELS SO GOOD THAT IF TWO"
	linefw "OF THEM SNUGGLE TOGETHER, THEY WON'T"
	linefw "WANT TO BE SEPARATED. "
	done

Text1823:
	text "MEOWTH "
	done

Text1824:
	text "COIN HURL"
	done

Text1825:
	text "CHOOSE 1 OF YOUR OPPONENT'S POKÉMON"
	linefw "AND FLIP A COIN. IF HEADS, THIS"
	linefw "ATTACK DOES 20 DAMAGE TO THAT"
	linefw "POKÉMON. WEAKNESS AND RESISTANCE"
	linefw "DO NOT APPLY. (ANY OTHER EFFECTS"
	linefw "STILL HAPPEN.)"
	done

Text1826:
	text "SCRATCH CAT"
	done

Text1827:
	text "IT IS FASCINATED BY ROUND OBJECTS."
	linefw "IT CAN'T STOP PLAYING WITH THEM"
	linefw "UNTIL IT TIRES AND FALLS ASLEEP. "
	done

Text1828:
	text "CAT PUNCH"
	done

Text1829:
	text "DOES 20 DAMAGE TO 1 OF YOUR"
	linefw "OPPONENT'S POKÉMON CHOSEN AT RANDOM."
	linefw "DON'T APPLY WEAKNESS AND RESISTANCE"
	linefw "FOR THIS ATTACK. (ANY OTHER EFFECTS"
	linefw "THAT WOULD HAPPEN AFTER APPLYING"
	linefw "WEAKNESS AND RESISTANCE STILL"
	linefw "HAPPEN.)"
	done

Text182a:
	text "IT IS NOCTURNAL IN NATURE. IF IT"
	linefw "SPOTS SOMETHING SHINY, ITS EYES"
	linefw "GLITTER BRIGHTLY."
	done

Text182b:
	text "EARN COINS"
	done

Text182c:
	text "FLIP A COIN UNTIL YOU GET TAILS,"
	linefw "THEN DRAW A CARD FOR EACH HEADS."
	done

Text182d:
	text "IT LOVES ANYTHING THAT SHINES. IT"
	linefw "ESPECIALLY ADORES COINS THAT IT"
	linefw "PICKS UP AND SECRETLY HOARDS. "
	done

Text182e:
	text "PAY DAY"
	done

Text182f:
	text "FLIP A COIN. IF HEADS, DRAW A CARD."
	done

Text1830:
	text "ADORES ROUND OBJECTS. IT WANDERS THE"
	linefw "STREETS ON A NIGHTLY BASIS TO LOOK"
	linefw "FOR DROPPED LOOSE CHANGE. "
	done

Text1831:
	text "IT LOVES THINGS THAT SPARKLE. WHEN"
	linefw "IT SEES A SHINY OBJECT, THE GOLD"
	linefw "COIN ON ITS HEAD SHINES TOO. "
	done

Text1832:
	text "PERSIAN "
	done

Text1833:
	text "POUNCE"
	done

Text1834:
	text "IF THE DEFENDING POKÉMON ATTACKS"
	linefw "PERSIAN DURING YOUR OPPONENT'S NEXT"
	linefw "TURN, DAMAGE IS REDUCED BY 10 AFTER"
	linefw "APPLYING WEAKNESS AND RESISTANCE."
	linefw "(BENCHING EITHER POKÉMON ENDS THIS"
	linefw "EFFECT.)"
	done

Text1835:
	text "CLASSY CAT"
	done

Text1836:
	text "A VERY HAUGHTY POKÉMON. AMONG FANS,"
	linefw "THE SIZE OF THE JEWEL IN ITS"
	linefw "FOREHEAD IS A TOPIC OF MUCH TALK."
	done

Text1837:
	text "DARK PERSIAN "
	done

Text1838:
	text "FASCINATE"
	done

Text1839:
	text "FLIP A COIN. IF HEADS, CHOOSE 1 OF"
	linefw "YOUR OPPONENT'S BENCHED POKÉMON AND"
	linefw "SWITCH IT WITH THE DEFENDING"
	linefw "POKÉMON. THIS ATTACK CAN'T BE USED"
	linefw "IF YOUR OPPONENT HAS NO BENCHED"
	linefw "POKÉMON."
	done

Text183a:
	text "POISON CLAWS"
	done

Text183b:
	text "POPULAR WITH WOMEN BECAUSE OF ITS"
	linefw "BEAUTIFUL FUR. THE LEADER OF THE"
	linefw "ROCKETS KEEPS ONE AS A PET. "
	done

Text183c:
	text "FARFETCH'D "
	done

Text183d:
	text "LEEK SLAP"
	done

Text183e:
	text "FLIP A COIN. IF TAILS, THIS ATTACK"
	linefw "DOES NOTHING. EITHER WAY, YOU CAN'T"
	linefw "USE THIS ATTACK AGAIN AS LONG AS"
	linefw "FARFETCH'D STAYS IN PLAY. (EVEN"
	linefw "PUTTING FARFETCH'D ON YOUR BENCH"
	linefw "WON'T LET YOU USE IT AGAIN.)"
	done

Text183f:
	text "POT SMASH"
	done

Text1840:
	text "WILD DUCK"
	done

Text1841:
	text "IT CAN'T LIVE WITHOUT THE STALK IT"
	linefw "HOLDS. THAT'S WHY IT DEFENDS THE"
	linefw "STALK FROM ATTACKERS WITH ITS LIFE."
	done

Text1842:
	text "FLIP A COIN. IF TAILS, THIS ATTACK"
	linefw "DOES NOTHING. EITHER WAY, YOU CAN'T"
	linefw "USE THIS ATTACK AGAIN AS LONG AS"
	linefw "FARFETCH'D STAYS IN PLAY (EVEN"
	linefw "PUTTING FARFETCH'D ON YOUR BENCH"
	linefw "WON'T LET YOU USE IT AGAIN)."
	done

Text1843:
	text "IF ANYONE TRIES TO DISTURB WHERE THE"
	linefw "ESSENTIAL PLANT STICKS GROW, IT USES"
	linefw "ITS OWN STICK TO THWART THEM. "
	done

Text1844:
	text "DODUO "
	done

Text1845:
	text "IF THE DEFENDING POKÉMON ATTACKS"
	linefw "DODUO DURING YOUR OPPONENT'S NEXT"
	linefw "TURN, THE DAMAGE DONE BY THE ATTACK"
	linefw "IS REDUCED BY 10 (AFTER APPLYING"
	linefw "WEAKNESS AND RESISTANCE). (BENCHING"
	linefw "EITHER POKÉMON ENDS THIS EFFECT.)"
	done

Text1846:
	text "TWIN BIRD"
	done

Text1847:
	text "BY ALTERNATELY RAISING AND LOWERING"
	linefw "ITS TWO HEADS, IT BALANCES ITSELF TO"
	linefw "BE MORE STABLE WHILE RUNNING. "
	done

Text1848:
	text "THE BRAINS IN ITS TWO HEADS APPEAR"
	linefw "TO COMMUNICATE EMOTIONS TO EACH"
	linefw "OTHER WITH A TELEPATHIC POWER."
	done

Text1849:
	text "DODRIO "
	done

Text184a:
	text "TRI ATTACK"
	done

Text184b:
	text "TRIPLEBIRD"
	done

Text184c:
	text "IF ONE OF THE HEADS GETS TO EAT,"
	linefw "THE OTHERS WILL BE SATISFIED, TOO,"
	linefw "AND THEY WILL STOP SQUABBLING."
	done

Text184d:
	text "RETREAT AID"
	done

Text184e:
	text "AS LONG AS DODRIO IS BENCHED, PAY ", "<COLORLESS>"
	linefw "LESS TO RETREAT YOUR ACTIVE POKÉMON."
	done

Text184f:
	text "WHEN DODUO EVOLVES INTO THIS ODD"
	linefw "BREED, ONE OF ITS HEADS SPLITS INTO"
	linefw "TWO. IT RUNS AT NEARLY 40 MPH."
	done

Text1850:
	text "LICKITUNG "
	done

Text1851:
	text "LICK"
	done

Text1852:
	text "LICKING"
	done

Text1853:
	text "WHEN IT EXTENDS ITS OVER-SIX-FOOT-"
	linefw "LONG TONGUE, ITS TAIL QUIVERS. THERE"
	linefw "IS A POSSIBILITY THEY ARE CONNECTED."
	done

Text1854:
	text "TONGUE WRAP"
	done

Text1855:
	text "INSTEAD OF HANDS, IT USES ITS"
	linefw "TONGUE, WHICH IS TWICE ITS HEIGHT."
	linefw "ITS STICKY SALIVA GRIPS ANYTHING."
	done

Text1856:
	text "CHANSEY "
	done

Text1857:
	text "DOUBLE SLAP"
	done

Text1858:
	text "IT IS SAID TO DELIVER HAPPINESS."
	linefw "BEING COMPASSIONATE, IT SHARES ITS"
	linefw "EGGS WITH INJURED PEOPLE. "
	done

Text1859:
	text "SCRUNCH"
	done

Text185a:
	text "CHANSEY DOES 80 DAMAGE TO ITSELF."
	done

Text185b:
	text "IT LAYS SEVERAL EGGS A DAY AND WON'T"
	linefw "SHARE THEM WITH THOSE WHO HAVE EVIL"
	linefw "IN THEIR HEARTS."
	done

Text185c:
	text "KANGASKHAN "
	done

Text185d:
	text "TAIL DROP"
	done

Text185e:
	text "PARENT"
	done

Text185f:
	text "TO PROTECT ITS YOUNG, IT WILL NEVER"
	linefw "GIVE UP DURING BATTLE, NO MATTER HOW"
	linefw "BADLY WOUNDED IT IS. "
	done

Text1860:
	text "DIZZY PUNCH"
	done

Text1861:
	text "THE INFANT RARELY VENTURES OUT OF"
	linefw "ITS MOTHER'S PROTECTIVE POUCH UNTIL"
	linefw "IT IS 3 YEARS OLD. "
	done

Text1862:
	text "FETCH"
	done

Text1863:
	text "DRAW A CARD."
	done

Text1864:
	text "COMET PUNCH"
	done

Text1865:
	text "IT RAISES ITS OFFSPRING IN ITS BELLY"
	linefw "POUCH. IT LETS THE BABY OUT TO PLAY"
	linefw "ONLY WHEN IT FEELS SAFE."
	done

Text1866:
	text "TAUROS "
	done

Text1867:
	text "RAMPAGE"
	done

Text1868:
	text "DOES 20 DAMAGE PLUS 10 MORE DAMAGE"
	linefw "FOR EACH DAMAGE COUNTER ON TAUROS."
	linefw "FLIP A COIN. IF TAILS, TAUROS IS NOW"
	linefw "CONFUSED (AFTER DOING DAMAGE)."
	done

Text1869:
	text "WILD BULL"
	done

Text186a:
	text "ONCE IT TAKES AIM AT ITS FOE, IT"
	linefw "MAKES A HEADLONG CHARGE. IT IS"
	linefw "FAMOUS FOR ITS VIOLENT NATURE."
	done

Text186b:
	text "KICKING AND STAMPING"
	done

Text186c:
	text "FLIP A COIN. IF HEADS, THIS ATTACK"
	linefw "DOES 20 DAMAGE PLUS 10 MORE DAMAGE."
	linefw "IF TAILS, THIS ATTACK DOES 20"
	linefw "DAMAGE, AND IF YOUR OPPONENT HAS ANY"
	linefw "BENCHED POKÉMON, HE OR SHE CHOOSES 1"
	linefw "OF THEM AND SWITCHES IT WITH THE"
	linefw "DEFENDING POKÉMON."
	done

Text186d:
	text "THEY FIGHT EACH OTHER BY LOCKING"
	linefw "HORNS. THE HERD'S PROTECTOR TAKES"
	linefw "PRIDE IN ITS BATTLE-SCARRED HORNS. "
	done

Text186e:
	text "DITTO "
	done

Text186f:
	text "MORPH"
	done

Text1870:
	text "REMOVE ALL DAMAGE COUNTERS FROM"
	linefw "DITTO. FOR THE REST OF THE GAME,"
	linefw "REPLACE DITTO WITH A COPY OF A BASIC"
	linefw "POKÉMON CARD (OTHER THAN DITTO)"
	linefw "CHOSEN AT RANDOM FROM YOUR DECK."
	done

Text1871:
	text "DITTO IS NO LONGER ASLEEP, CONFUSED,"
	linefw "PARALYZED, POISONED, OR ANYTHING"
	linefw "ELSE THAT MIGHT BE THE RESULT OF AN"
	linefw "ATTACK (JUST AS IF YOU HAD EVOLVED"
	linefw "IT)."
	done

Text1872:
	text "TRANSFORM"
	done

Text1873:
	text "IT HAS THE ABILITY TO RECONSTITUTE"
	linefw "ITS ENTIRE CELLULAR STRUCTURE TO"
	linefw "TRANSFORM INTO WHATEVER IT SEES."
	done

Text1874:
	text "EVOLUTION"
	done

Text1875:
	text "BECAUSE ITS GENETIC MAKEUP IS"
	linefw "IRREGULAR, IT QUICKLY CHANGES ITS"
	linefw "FORM DUE TO A VARIETY OF CAUSES. "
	done

Text1876:
	text "IF THE DEFENDING POKÉMON TRIES TO"
	linefw "ATTACK DURING YOUR OPPONENT'S NEXT"
	linefw "TURN, YOUR OPPONENT FLIPS A COIN. IF"
	linefw "TAILS, THAT ATTACK DOES NOTHING."
	done

Text1877:
	text "A RARE POKÉMON THAT ADAPTS TO HARSH"
	linefw "ENVIRONMENTS BY TAKING ON DIFFERENT"
	linefw "EVOLUTIONARY FORMS."
	done

Text1878:
	text "IT HAS THE ABILITY TO ALTER THE"
	linefw "COMPOSITION OF ITS BODY TO SUIT ITS"
	linefw "SURROUNDING ENVIRONMENT. "
	done

Text1879:
	text "PORYGON "
	done

Text187a:
	text "CONVERSION 1"
	done

Text187b:
	text "IF THE DEFENDING POKÉMON HAS A"
	linefw "WEAKNESS, YOU MAY CHANGE IT TO A"
	linefw "TYPE OF YOUR CHOICE OTHER THAN ", "<COLORLESS>", "."
	done

Text187c:
	text "CONVERSION 2"
	done

Text187d:
	text "CHANGE PORYGON'S RESISTANCE TO A"
	linefw "TYPE OF YOUR CHOICE OTHER THAN ", "<COLORLESS>", "."
	done

Text187e:
	text "COMPUTER GRAPHIC"
	done

Text187f:
	text "THE WORLD'S FIRST ARTIFICIALLY"
	linefw "CREATED POKÉMON. IT CAN TRAVEL"
	linefw "THROUGH ELECTRONIC SPACE."
	done

Text1880:
	text "3-D ATTACK"
	done

Text1881:
	text "FLIP 3 COINS. THIS ATTACK DOES 10"
	linefw "DAMAGE TIMES THE NUMBER OF HEADS."
	done

Text1882:
	text "A MAN-MADE POKÉMON CREATED USING"
	linefw "ADVANCED SCIENTIFIC MEANS. IT CAN"
	linefw "MOVE FREELY IN CYBERSPACE. "
	done

Text1883:
	text "IF THE DEFENDING POKÉMON HAS A"
	linefw "WEAKNESS, YOU MAY CHANGE IT TO A"
	linefw "TYPE OF YOUR CHOICE OTHER THAN ", "<COLORLESS>", "."
	done

Text1884:
	text "IT IS A MANMADE POKÉMON. SINCE IT"
	linefw "DOESN'T BREATHE, PEOPLE ARE EAGER"
	linefw "TO TRY IT IN ANY ENVIRONMENT. "
	done

Text1885:
	text "COOL PORYGON "
	done

Text1886:
	text "TEXTURE MAGIC"
	done

Text1887:
	text "YOU MAY CHANGE COOL PORYGON'S"
	linefw "RESISTANCE TO A TYPE OF YOUR CHOICE"
	linefw "OTHER THAN ", "<COLORLESS>", ". IF THE DEFENDING"
	linefw "POKÉMON HAS A WEAKNESS, YOU MAY"
	linefw "CHANGE IT TO A TYPE OF YOUR CHOICE"
	linefw "OTHER THAN ", "<COLORLESS>", ". (BENCHING EITHER"
	linefw "POKÉMON ENDS THIS EFFECT ON THEM.)"
	done

Text1888:
	text "FLIP 3 COINS. THIS ATTACK DOES 20"
	linefw "DAMAGE TIMES THE NUMBER OF HEADS."
	done

Text1889:
	text "SNORLAX "
	done

Text188a:
	text "THICK SKINNED"
	done

Text188b:
	text "SNORLAX CAN'T BECOME ASLEEP,"
	linefw "CONFUSED, PARALYZED, OR POISONED."
	linefw "THIS POWER CAN'T BE USED IF SNORLAX"
	linefw "IS ALREADY ASLEEP, CONFUSED, OR"
	linefw "PARALYZED."
	done

Text188c:
	text "SLEEPING"
	done

Text188d:
	text "IT STOPS EATING ONLY TO SLEEP. IT"
	linefw "DOESN'T FEEL FULL UNLESS IT EATS"
	linefw "NEARLY 900 POUNDS A DAY."
	done

Text188e:
	text "BLOCK PATH"
	done

Text188f:
	text "AS LONG AS SNORLAX IS YOUR ACTIVE"
	linefw "POKÉMON, THE DEFENDING POKÉMON CAN'T"
	linefw "RETREAT. THIS POWER STOPS WORKING"
	linefw "WHEN SNORLAX IS ASLEEP, CONFUSED,"
	linefw "OR PARALYZED."
	done

Text1890:
	text "ROLL OVER"
	done

Text1891:
	text "AFTER DEALING DAMAGE, SNORLAX IS NOW"
	linefw "ASLEEP. FLIP A COIN. IF HEADS, THE"
	linefw "DEFENDING POKÉMON IS NOW ASLEEP."
	done

Text1892:
	text "ITS STOMACH CAN DIGEST ANY KIND"
	linefw "OF FOOD, EVEN IF IT HAPPENS TO BE"
	linefw "MOLDY OR ROTTEN. "
	done

Text1893:
	text "HUNGRY SNORLAX "
	done

Text1894:
	text "EAT"
	done

Text1895:
	text "PLACE 1 FOOD COUNTER ON SNORLAX. YOU"
	linefw "CAN'T PLACE A FOOD COUNTER ON"
	linefw "SNORLAX IF IT ALREADY HAS 2 FOOD"
	linefw "COUNTERS."
	done

Text1896:
	text "WHEN YOU USE THIS ATTACK, YOU MAY"
	linefw "REMOVE AS MANY FOOD COUNTERS FROM"
	linefw "HUNGRY SNORLAX AS YOU LIKE. IF YOU"
	linefw "DO, THIS ATTACK DOES 20 DAMAGE PLUS"
	linefw "30 MORE DAMAGE FOR EACH FOOD COUNTER"
	linefw "YOU REMOVED."
	done

Text1897:
	text "WHAT SOUNDS LIKE ITS CRY MAY"
	linefw "ACTUALLY BE ITS SNORES OR THE"
	linefw "RUMBLINGS OF ITS HUNGRY BELLY. "
	done

Text1898:
	text "DRATINI "
	done

Text1899:
	text "IT IS CALLED THE ”MIRAGE POKÉMON”"
	linefw "BECAUSE SO FEW HAVE SEEN IT. ITS"
	linefw "SHED SKIN HAS BEEN FOUND."
	done

Text189a:
	text "IT IS BORN LARGE TO START WITH."
	linefw "IT REPEATEDLY SHEDS ITS SKIN AS"
	linefw "IT STEADILY GROWS LONGER. "
	done

Text189b:
	text "DRAGONAIR "
	done

Text189c:
	text "SLAM"
	done

Text189d:
	text "IF ITS BODY TAKES ON AN AURA, THE"
	linefw "WEATHER CHANGES INSTANTLY. IT IS"
	linefw "SAID TO LIVE IN SEAS AND LAKES."
	done

Text189e:
	text "DARK DRAGONAIR "
	done

Text189f:
	text "EVOLUTIONARY LIGHT"
	done

Text18a0:
	text "ONCE DURING YOUR TURN, YOU MAY"
	linefw "SEARCH YOUR DECK FOR AN EVOLUTION"
	linefw "CARD. SHOW IT TO YOUR OPPONENT AND"
	linefw "PUT IT INTO YOUR HAND. SHUFFLE YOUR"
	linefw "DECK AFTERWARD. THIS POWER CAN'T BE"
	linefw "USED IF DARK DRAGONAIR IS ASLEEP,"
	linefw "CONFUSED, OR PARALYZED."
	done

Text18a1:
	text "TAIL STRIKE"
	done

Text18a2:
	text "THEY SAY THAT IF IT EMITS AN AURA"
	linefw "FROM ITS WHOLE BODY, THE WEATHER"
	linefw "WILL BEGIN TO CHANGE INSTANTLY."
	done

Text18a3:
	text "DRAGONITE "
	done

Text18a4:
	text "HEALING WIND"
	done

Text18a5:
	text "WHEN YOU PUT DRAGONITE INTO PLAY,"
	linefw "REMOVE 2 DAMAGE COUNTERS FROM EACH"
	linefw "OF YOUR POKÉMON. IF A POKÉMON HAS"
	linefw "FEWER DAMAGE COUNTERS THAN THAT,"
	linefw "REMOVE THEM ALL."
	done

Text18a6:
	text "IT IS SAID TO MAKE ITS HOME"
	linefw "SOMEWHERE IN THE SEA. IT GUIDES"
	linefw "CREWS OF SHIPWRECKS TO SHORE."
	done

Text18a7:
	text "SPECIAL DELIVERY"
	done

Text18a8:
	text "ONCE DURING YOUR TURN (BEFORE YOUR"
	linefw "ATTACK), YOU MAY DRAW A CARD. IF YOU"
	linefw "DO, CHOOSE A CARD FROM YOUR HAND AND"
	linefw "PUT IT ON TOP OF YOUR DECK. THIS"
	linefw "POWER CAN'T BE USED IF DRAGONITE IS"
	linefw "ASLEEP, CONFUSED, OR PARALYZED."
	done

Text18a9:
	text "SUPERSONIC FLIGHT"
	done

Text18aa:
	text "IT IS SAID THAT THIS POKÉMON"
	linefw "CONSTANTLY FLIES OVER THE IMMENSE"
	linefw "SEAS AND RESCUES DROWNING PEOPLE. "
	done

Text18ab:
	text "STEP IN"
	done

Text18ac:
	text "ONCE DURING YOUR TURN (BEFORE YOUR"
	linefw "ATTACK), IF DRAGONITE IS ON YOUR"
	linefw "BENCH, YOU MAY SWITCH IT WITH YOUR"
	linefw "ACTIVE POKÉMON."
	done

Text18ad:
	text "FLIP 2 COINS. THIS ATTACK DOES 40"
	linefw "DAMAGE TIMES THE NUMBER OF HEADS."
	done

Text18ae:
	text "DARK DRAGONITE "
	done

Text18af:
	text "SUMMON MINIONS"
	done

Text18b0:
	text "WHEN YOU PLAY DARK DRAGONITE FROM"
	linefw "YOUR HAND, SEARCH YOUR DECK FOR UP"
	linefw "TO 2 BASIC POKÉMON AND PUT THEM"
	linefw "ONTO YOUR BENCH. SHUFFLE YOUR DECK"
	linefw "AFTERWARD."
	done

Text18b1:
	text "GIANT TAIL"
	done

Text18b2:
	text "IT CAN FLY IN SPITE OF ITS BIG AND"
	linefw "BULKY PHYSIQUE. IT CIRCLES THE GLOBE"
	linefw "IN JUST 16 HOURS. "
	done

Text18b3:
	text "TOGEPI "
	done

Text18b4:
	text "IF OPPONENT ATTACKS TOGEPI NEXT"
	linefw "TURN, ANY DAMAGE DONE BY THE ATTACK"
	linefw "IS REDUCED BY 20 (AFTER APPLYING"
	linefw "WEAKNESS AND RESISTANCE). (BENCHING"
	linefw "EITHER POKÉMON ENDS THIS EFFECT.)"
	done

Text18b5:
	text "FLIP A COIN. IF HEADS, CHOOSE 1 OF"
	linefw "THE DEFENDING POKÉMON'S ATTACKS."
	linefw "USE THAT ATTACK, IGNORING ITS NORMAL"
	linefw "ENERGY COST. (YOU MUST STILL DO"
	linefw "ANYTHING ELSE THAT ATTACK DEFINES.)"
	linefw "(TOGEPI'S TYPE IS STILL ", "<COLORLESS>", " NO"
	linefw "MATTER WHAT TYPE ITS OPPONENT IS.)"
	done

Text18b6:
	text "SPIKE BALL"
	done

Text18b7:
	text "ITS SHELL IS SAID TO BE STUFFED WITH"
	linefw "HAPPINESS THAT IT SHARES WITH"
	linefw "KINDHEARTED PEOPLE. "
	done

Text18b8:
	text "LUGIA "
	done

Text18b9:
	text "AEROBLAST"
	done

Text18ba:
	text "FLIP 2 COINS. THIS ATTACK DOES 20"
	linefw "DAMAGE PLUS 20 DAMAGE TIMES THE"
	linefw "NUMBER OF HEADS."
	done

Text18bb:
	text "DIVING"
	done

Text18bc:
	text "IT SLEEPS IN A DEEP-SEA TRENCH."
	linefw "IF IT FLAPS ITS WINGS, IT IS SAID"
	linefw "TO CAUSE A 40-DAY STORM. "
	done

Text18bd:
	text "SUPER POTION"
	done

Text18be:
	text "DISCARD 1 ENERGY CARD ATTACHED TO"
	linefw "ONE OF YOUR OWN POKÉMON IN ORDER TO"
	linefw "REMOVE UP TO 4 DAMAGE COUNTERS FROM"
	linefw "THAT POKÉMON."
	done

Text18bf:
	text "IMAKUNI?"
	done

Text18c0:
	text "YOUR ACTIVE POKÉMON IS NOW CONFUSED."
	linefw "IMAKUNI WANTS YOU TO PLAY HIM AS A"
	linefw "BASIC POKÉMON, BUT YOU CAN'T. A"
	linefw "MYSTERIOUS CREATURE NOT LISTED IN"
	linefw "THE POKÉDEX. HE ASKS KIDS AROUND"
	linefw "THE WORLD, ”WHO IS CUTER:"
	linefw "PIKACHU OR ME?”"
	done

Text18c1:
	text "ENERGY REMOVAL"
	done

Text18c2:
	text "CHOOSE 1 ENERGY CARD ATTACHED TO 1"
	linefw "OF YOUR OPPONENT'S POKÉMON AND"
	linefw "DISCARD IT."
	done

Text18c3:
	text "ENERGY RETRIEVAL"
	done

Text18c4:
	text "TRADE 1 OF THE OTHER CARDS IN YOUR"
	linefw "HAND FOR UP TO 2 BASIC ENERGY CARDS"
	linefw "FROM YOUR DISCARD PILE."
	done

Text18c5:
	text "ENERGY SEARCH"
	done

Text18c6:
	text "SEARCH YOUR DECK FOR A BASIC ENERGY"
	linefw "CARD AND PUT IT INTO YOUR HAND."
	linefw "SHUFFLE YOUR DECK AFTERWARD."
	done

Text18c7:
	text "PROFESSOR OAK"
	done

Text18c8:
	text "DISCARD YOUR HAND, THEN DRAW"
	linefw "7 CARDS."
	done

Text18c9:
	text "FOSSIL EXCAVATION"
	done

Text18ca:
	text "SEARCH YOUR DECK OR YOUR DISCARD"
	linefw "PILE FOR A CARD NAMED MYSTERIOUS"
	linefw "FOSSIL, SHOW IT TO YOUR OPPONENT,"
	linefw "AND PUT IT INTO YOUR HAND. IF YOU"
	linefw "TOOK THE CARD FROM YOUR DECK,"
	linefw "SHUFFLE YOUR DECK AFTERWARD."
	done

Text18cb:
	text "POTION"
	done

Text18cc:
	text "REMOVE UP TO 2 DAMAGE COUNTERS FROM"
	linefw "ONE OF YOUR POKÉMON."
	done

Text18cd:
	text "GAMBLER"
	done

Text18ce:
	text "SHUFFLE YOUR HAND INTO YOUR DECK."
	linefw "FLIP A COIN. IF HEADS, DRAW 8 CARDS."
	linefw "IF TAILS, DRAW 1 CARD."
	done

Text18cf:
	text "REVIVE"
	done

Text18d0:
	text "PUT 1 BASIC POKÉMON CARD FROM YOUR"
	linefw "DISCARD PILE ONTO YOUR BENCH. PUT"
	linefw "DAMAGE COUNTERS ON THAT POKÉMON"
	linefw "EQUAL TO HALF ITS HP (ROUNDED DOWN"
	linefw "TO THE NEAREST 10). (YOU CAN'T PLAY"
	linefw "REVIVE IF YOUR BENCH IS FULL.)"
	done

Text18d1:
	text "MAX REVIVE"
	done

Text18d2:
	text "DISCARD 2 ENERGY CARDS FROM YOUR"
	linefw "HAND IN ORDER TO PUT 1 BASIC POKÉMON"
	linefw "FROM YOUR DISCARD PILE ONTO YOUR"
	linefw "BENCH."
	done

Text18d3:
	text "(YOU CAN'T PLAY MAX REVIVE IF YOUR"
	linefw "BENCH IS FULL.)"
	done

Text18d4:
	text "SUPER SCOOP UP"
	done

Text18d5:
	text "FLIP A COIN. IF HEADS, CHOOSE 1 OF"
	linefw "YOUR POKÉMON AND PUT IT AND ALL"
	linefw "CARDS ATTACHED TO IT INTO YOUR HAND."
	done

Text18d6:
	text "DEVOLUTION SPRAY"
	done

Text18d7:
	text "CHOOSE 1 OF YOUR OWN POKÉMON IN"
	linefw "PLAY AND A STAGE OF EVOLUTION."
	linefw "DISCARD ALL EVOLUTION CARDS OF THAT"
	linefw "STAGE OR HIGHER ATTACHED TO THAT"
	linefw "POKÉMON. THAT POKÉMON IS NO LONGER"
	linefw "AFFLICTED WITH A STATUS CONDITION"
	linefw "(JUST AS IF YOU HAD EVOLVED IT)."
	done

Text18d8:
	text "ITEMFINDER"
	done

Text18d9:
	text "DISCARD 2 OF THE OTHER CARDS FROM"
	linefw "YOUR HAND IN ORDER TO PUT A TRAINER"
	linefw "CARD FROM YOUR DISCARD PILE INTO"
	linefw "YOUR HAND."
	done

Text18da:
	text "CHALLENGE!"
	done

Text18db:
	text "ASK YOUR OPPONENT IF THEY ACCEPT"
	linefw "YOUR CHALLENGE. IF YOUR OPPONENT"
	linefw "DECLINES, DRAW 2 CARDS. "
	linefw "IF THEY ACCEPT, YOU EACH SEARCH YOUR"
	linefw "DECKS FOR ANY NUMBER OF BASIC"
	linefw "POKÉMON AND PUT THEM FACE DOWN ONTO"
	linefw "YOUR BENCHES."
	done

Text18dc:
	text "(A PLAYER CAN'T DO THIS IF HIS OR"
	linefw "HER BENCH IS FULL.) WHEN YOU BOTH"
	linefw "HAVE FINISHED, SHUFFLE YOUR DECKS"
	linefw "AND TURN THOSE CARDS FACE UP."
	done

Text18dd:
	text "SUPER ENERGY RETRIEVAL"
	done

Text18de:
	text "TRADE 2 OF THE OTHER CARDS IN YOUR"
	linefw "HAND FOR UP TO 4 BASIC ENERGY CARDS"
	linefw "FROM YOUR DISCARD PILE."
	done

Text18df:
	text "SUPER ENERGY REMOVAL"
	done

Text18e0:
	text "DISCARD 1 ENERGY CARD ATTACHED TO"
	linefw "1 OF YOUR OWN POKÉMON IN ORDER TO"
	linefw "CHOOSE 1 OF YOUR OPPONENT'S POKÉMON"
	linefw "AND UP TO 2 ENERGY CARDS ATTACHED"
	linefw "TO IT. DISCARD THOSE CARDS."
	done

Text18e1:
	text "MOON STONE"
	done

Text18e2:
	text "SEARCH YOUR DECK FOR A COLORLESS"
	linefw "EVOLUTION CARD, SHOW IT TO YOUR"
	linefw "OPPONENT, AND PUT IT INTO YOUR HAND."
	linefw "SHUFFLE YOUR DECK AFTERWARD."
	done

Text18e3:
	text "DEFENDER"
	done

Text18e4:
	text "ATTACH DEFENDER TO ONE OF YOUR"
	linefw "POKÉMON. AT THE END OF YOUR"
	linefw "OPPONENT'S NEXT TURN, DISCARD"
	linefw "DEFENDER. DAMAGE DONE TO THAT"
	linefw "POKÉMON BY ATTACKS IS REDUCED BY 20"
	linefw "(AFTER APPLYING WEAKNESS AND"
	linefw "RESISTANCE)."
	done

Text18e5:
	text "GUST OF WIND"
	done

Text18e6:
	text "CHOOSE 1 OF YOUR OPPONENT'S BENCHED"
	linefw "POKÉMON AND SWITCH IT WITH HIS OR"
	linefw "HER ACTIVE POKÉMON."
	done

Text18e7:
	text "PLAY MYSTERIOUS FOSSIL AS IF IT"
	linefw "WERE A BASIC POKÉMON. WHILE IN PLAY,"
	linefw "MYSTERIOUS FOSSIL COUNTS AS A"
	linefw "POKÉMON (INSTEAD OF A TRAINER CARD)."
	linefw "MYSTERIOUS FOSSIL HAS NO ATTACKS,"
	linefw "CAN'T RETREAT, AND CAN'T BE ASLEEP,"
	linefw "CONFUSED, PARALYZED, OR POISONED."
	done

Text18e8:
	text "IF MYSTERIOUS FOSSIL IS KNOCKED OUT,"
	linefw "IT DOESN'T COUNT AS A KNOCKED OUT"
	linefw "POKÉMON. (DISCARD IT ANYWAY.) AT ANY"
	linefw "TIME DURING YOUR TURN BEFORE YOUR"
	linefw "ATTACK, YOU MAY DISCARD MYSTERIOUS"
	linefw "FOSSIL FROM PLAY."
	done

Text18e9:
	text "FULL HEAL"
	done

Text18ea:
	text "YOUR ACTIVE POKÉMON IS NO LONGER"
	linefw "ASLEEP, CONFUSED, PARALYZED, OR"
	linefw "POISONED."
	done

Text18eb:
	text "IMPOSTOR OAK'S REVENGE"
	done

Text18ec:
	text "DISCARD A CARD FROM YOUR HAND IN"
	linefw "ORDER TO PLAY THIS CARD. YOUR"
	linefw "OPPONENT SHUFFLES HIS OR HER HAND"
	linefw "INTO THEIR DECK AND THEN DRAWS 4"
	linefw "CARDS."
	done

Text18ed:
	text "IMPOSTOR PROFESSOR OAK"
	done

Text18ee:
	text "YOUR OPPONENT SHUFFLES HIS OR HER"
	linefw "HAND INTO HIS OR HER DECK, THEN"
	linefw "DRAWS 7 CARDS."
	done

Text18ef:
	text "SLEEP!"
	done

Text18f0:
	text "FLIP A COIN. IF HEADS, THE"
	linefw "DEFENDING POKÉMON IS NOW ASLEEP."
	done

Text18f1:
	text "COMPUTER ERROR!"
	done

Text18f2:
	text "YOU MAY DRAW UP TO 5 CARDS, THEN"
	linefw "YOUR OPPONENT MAY DRAW UP TO 5"
	linefw "CARDS. YOUR TURN IS OVER NOW (YOU"
	linefw "DON'T GET TO ATTACK)."
	done

Text18f3:
	text "COMPUTER SEARCH"
	done

Text18f4:
	text "DISCARD 2 OF THE OTHER CARDS FROM"
	linefw "YOUR HAND IN ORDER TO SEARCH YOUR"
	linefw "DECK FOR ANY CARD AND PUT IT INTO"
	linefw "YOUR HAND. SHUFFLE YOUR DECK"
	linefw "AFTERWARD."
	done

Text18f5:
	text "DIGGER"
	done

Text18f6:
	text "FLIP A COIN. IF TAILS, DO 10 DAMAGE"
	linefw "TO YOUR ACTIVE POKÉMON. IF HEADS,"
	linefw "YOUR OPPONENT FLIPS A COIN. IF"
	linefw "TAILS, YOUR OPPONENT DOES 10 DAMAGE"
	linefw "TO HIS OR HER ACTIVE POKÉMON. IF"
	linefw "HEADS, YOU FLIP A COIN. KEEP DOING"
	linefw "THIS UNTIL A PLAYER GETS TAILS."
	done

Text18f7:
	text "CLEFAIRY DOLL"
	done

Text18f8:
	text "PLAY CLEFAIRY DOLL AS IF IT WERE A"
	linefw "BASIC POKÉMON. WHILE IN PLAY,"
	linefw "CLEFAIRY DOLL COUNTS AS A POKÉMON"
	linefw "(INSTEAD OF A TRAINER CARD)."
	linefw "CLEFAIRY DOLL HAS NO ATTACKS, CAN'T"
	linefw "RETREAT, AND CAN'T BE ASLEEP,"
	linefw "CONFUSED, PARALYZED, OR POISONED."
	done

Text18f9:
	text "IF CLEFAIRY DOLL IS KNOCKED OUT,"
	linefw "IT DOESN'T COUNT AS A KNOCKED OUT"
	linefw "POKÉMON. AT ANY TIME DURING YOUR"
	linefw "TURN BEFORE YOUR ATTACK, YOU MAY"
	linefw "DISCARD CLEFAIRY DOLL."
	done

Text18fa:
	text "MR. FUJI"
	done

Text18fb:
	text "CHOOSE A POKÉMON ON YOUR BENCH."
	linefw "SHUFFLE IT AND ANY CARDS ATTACHED TO"
	linefw "IT INTO YOUR DECK."
	done

Text18fc:
	text "PLUSPOWER"
	done

Text18fd:
	text "ATTACH PLUSPOWER TO YOUR ACTIVE"
	linefw "POKÉMON. AT THE END OF YOUR TURN,"
	linefw "DISCARD PLUSPOWER. IF THIS POKÉMON'S"
	linefw "ATTACK DOES DAMAGE TO THE DEFENDING"
	linefw "POKÉMON (AFTER APPLYING WEAKNESS AND"
	linefw "RESISTANCE), THE ATTACK DOES 10 MORE"
	linefw "DAMAGE TO THE DEFENDING POKÉMON."
	done

Text18fe:
	text "SWITCH"
	done

Text18ff:
	text "SWITCH 1 OF YOUR BENCHED POKÉMON"
	linefw "WITH YOUR ACTIVE POKÉMON."
	done

Text1900:
	text "SCOOP UP"
	done

Text1901:
	text "CHOOSE 1 OF YOUR OWN POKÉMON IN"
	linefw "PLAY AND RETURN ITS BASIC POKÉMON"
	linefw "CARD TO YOUR HAND. (DISCARD ALL"
	linefw "CARDS ATTACHED TO THAT CARD.)"
	done

Text1902:
	text "POKÉMON TRADER"
	done

Text1903:
	text "TRADE 1 OF THE BASIC POKÉMON OR"
	linefw "EVOLUTION CARDS IN YOUR HAND FOR 1"
	linefw "OF THE BASIC POKÉMON OR EVOLUTION"
	linefw "CARDS FROM YOUR DECK."
	done

Text1904:
	text "SHOW BOTH CARDS TO YOUR OPPONENT."
	linefw "SHUFFLE YOUR DECK AFTERWARD."
	done

Text1905:
	text "POKÉMON RECALL"
	done
