Text11a4:
	text "OH, THANK GOODNESS!"
	linefw "LET'S GET TRADING, THEN!"
	linefw "I'LL ENTRUST MY DARLING"
	linefw "MEWTWO Lv60 CARD TO YOU."
	done

Text11a5:
	text "I AM SO VERY HAPPY!"
	linefw "OOOH HOO HOO HOO!!"
	done

Text11a6:
	text "OOOH HOO HOO! DO YOU REMEMBER THE"
	linefw "CARD YOU GAVE ME?"
	linefw "IT WAS DARK HYPNO Lv26!"
	linefw "I'VE BEEN USING IT WELL!"
	done

Text11a7:
	text "I'M TRYING MY HARDEST TO MAKE A GOOD"
	linefw "DECK FOR TEAM GR, BUT I JUST CAN'T."
	linefw "AFTER ALL, TEAM GR DECKS ARE KNOWN"
	linefw "AS THE BEST OF THE BEST!"
	linefw "ONCE I MAKE ONE...I'M GOING TO DUEL"
	linefw "HEIDI, A PSYCHIC MEMBER OF TEAM GR!"
	done

Text11a8:
	text "FUFUFU... I HAVE A FIERCE LONGING"
	linefw "TO MEET MISS HEIDI!"
	linefw "YOU'LL NEVER HAVE A CHANCE SINCE"
	linefw "YOU OPPOSE TEAM GR!"
	linefw "HOW REGRETTABLE!!"
	done

Text11a9:
	text "HOOHOO! SO YOU'VE ALREADY MADE IT"
	linefw "HERE, EH ", "<RAMNAME>", "?"
	linefw "THAT'S GREAT AND ALL, BUT YOU'LL"
	linefw "NEVER DEFEAT OUR KING, VILLICCI."
	linefw "MAYBE YOU SHOULD RETHINK YOUR"
	linefw "MOTIVES BEFORE CONTINUING ON."
	done

Text11aa:
	text "I'M SURPRISED! YOU MUST HAVE AMAZING"
	linefw "COURAGE TO DEFY KING VILLICCI!"
	linefw "I'LL BET YOU WERE A REAL TOUGH"
	linefw "COOKIE IN BATTLE, WEREN'T YOU?"
	linefw "OUR ORGANIZATION HAS HAD A HUGE"
	linefw "REFORM SINCE THEN IN OUR BELIEFS."
	done

Text11ab:
	text "THANK YOU FOR VISITING."
	linefw "THIS IS TEAM GR'S ELECTRIC FORTRESS."
	linefw "I'M SORRY, BUT I CANNOT ALLOW YOU"
	linefw "TO ENTER AT THIS TIME."
	linefw "ONCE YOU SHOW ME THE GR GRASS COIN,"
	linefw "YOU MAY ENTER THE FORTRESS."
	done

Text11ac:
	text "THANK YOU FOR VISITING."
	linefw "THIS IS TEAM GR'S ELECTRIC FORTRESS."
	done

Text11ad:
	text "THERE IS A CIRCULAR COIN-SIZED SLOT"
	linefw "UNDER AN IMAGE OF A GOLBAT."
	done

Text11ae:
	text "INSERT YOUR GR GRASS COIN?"
	done

Text11af:
	text "THANK YOU FOR VISITING."
	linefw "THIS IS TEAM GR'S ELECTRIC FORTRESS."
	linefw "ALLOW ME TO TELL YOU ABOUT YOUR"
	linefw "OPPONENTS AND EXPLAIN THE RULES."
	linefw "THE LEADER OF THE ELECTRIC FORTRESS"
	linefw "IS A WOMAN NAMED CATHERINE."
	linefw "IN ORDER TO FIGHT HER, YOU MUST"
	linefw "FIRST DEFEAT 2 GR FORTRESS MEMBERS."
	linefw "YOU'LL LEARN ABOUT EACH MEMBER'S"
	linefw "SPECIAL BATTLE RULES INSIDE."
	linefw "THAT IS ALL. PLEASE ENJOY DUELLING"
	linefw "IN TEAM GR'S ELECTRIC FORTRESS."
	done

Text11b0:
	text "I'M CHIP, A MEMBER OF TEAM GR."
	linefw "HOWEVER, YOU MAY REMEMBER ME AS..."
	done

Text11b1:
	text "THE AMAZING LEADER GR No.3!"
	linefw "THAT'S RIGHT!"
	linefw "YOU MAY HAVE BEATEN ME BEFORE,"
	linefw "BUT YOU CAN'T DEFEAT ME HERE!"
	done

Text11b2:
	text "I HAVE A SPECIAL REQUIREMENT FOR"
	linefw "CHALLENGERS HERE, HOWEVER!"
	linefw "THE ONLY ENERGY ALLOWED IN YOUR"
	linefw "DECK IS ELECTRIC ENERGY!"
	linefw "I WON'T PLAY AGAINST A DECK"
	linefw "CONTAINING ANY OTHER ENERGY TYPE!"
	linefw "A VICTORY HERE WINS YOU SOME CARDS"
	linefw "AND THE RELEASE OF OUR GRAND MASTER."
	linefw "THE ONE NAMED...STAN OR SOMETHING?"
	linefw "ANYWAY, HE'S FINE."
	done

Text11b3:
	text "YOUR DECK MUST HAVE ELECTRIC AS ITS"
	linefw "ONLY ENERGY TYPE TO BATTLE ME."
	linefw "IF IT HAS ANY OTHER ENERGY TYPES IN"
	linefw "IT, I'LL REFUSE TO FIGHT."
	linefw "HAVE YOU PREPARED AN ACCOMODATING"
	linefw "DECK?"
	done

Text11b4:
	text "WOULD YOU LIKE TO DUEL CHIP?"
	done

Text11b5:
	text "YOU CHOWDERHEAD!! THERE'RE OTHER"
	linefw "ENERGY TYPES IN THERE!"
	linefw "REBUILD YOUR DECK SO IT ONLY HAS"
	linefw "ELECTRIC-TYPE ENERGY CARDS!"
	linefw "I WON'T BATTLE WITH YOU UNTIL YOU'VE"
	linefw "DONE THAT ONE SIMPLE THING!!"
	done

Text11b6:
	text "AHA! SO YOUR DECK DOES HAVE PURELY"
	linefw "ELECTRIC-TYPE ENERGY CARDS."
	linefw "IN THAT CASE, LET'S DUEL!"
	linefw "WE'LL USE 4 PRIZE CARDS!!"
	done

Text11b7:
	text "I GUESS WE CAN'T BATTLE IF YOU'RE"
	linefw "RUNNING AWAY!"
	done

Text11b8:
	text "OH, ", "<RAMNAME>", "."
	linefw "HAVE YOU COME HERE FOR SOMETHING?"
	linefw "IF YOU'RE ITCHING TO TAKE ME ON,"
	linefw "I HAVE A SPECIAL DUELLING RULE."
	linefw "YOUR DECK MAY ONLY HAVE"
	linefw "ELECTRIC-TYPE ENERGY CARDS."
	linefw "IF YOU AGREE WITH THAT RULE,"
	linefw "WOULD YOU CARE TO HAVE A BATTLE?"
	done

Text11b9:
	text "HAVE YOU FORGOTTEN OUR PREVIOUS"
	linefw "BOUTS? MAYBE I SHOULD REMIND YOU."
	linefw "REMEMBER THAT PART ABOUT USING ONLY"
	linefw "ELECTRIC-TYPE ENERGY CARDS?"
	linefw "WE CAN FIGHT IF YOU REBUILD YOUR"
	linefw "DECK TO FOLLOW THAT RULE."
	done

Text11ba:
	text "IT'S A DUEL, THEN!"
	linefw "LAY ASIDE 4 PRIZE CARDS!"
	done

Text11bb:
	text "IT'S INTERESTING FIGHTING WITH"
	linefw "CONFINED DECK CHOICES. "
	linefw "IF YOU EVER GET BORED OF NORMAL"
	linefw "DUELS, I'LL BE WAITING HERE!"
	done

Text11bc:
	text "GRRRRR..."
	done

Text11bd:
	text "I DIDN'T EXPECT TO BE DEFEATED"
	linefw "WITH SUCH BRUTE FORCE."
	linefw "ALRIGHTY, THEN, ", "<RAMNAME>", "!"
	linefw "I'LL KEEP MY WORD!"
	done

Text11be:
	text "IN ALL TRUTH AND FAIRNESS,"
	linefw "I'VE WON."
	done

Text11bf:
	text "NOOO, YOU DID IT AGAIN!"
	linefw "I'VE LOST COMPLETELY..."
	done

Text11c0:
	text "EVERY TIME I TAKE YOU ON, YOU SEEM"
	linefw "TO BE STRONGER THAN THE LAST TIME."
	linefw "IN EACH DUEL, I LEARN A LITTLE MORE"
	linefw "ABOUT WHAT INADEQUACIES MY DECK HAS."
	done

Text11c1:
	text "THAT'S ABOUT RIGHT."
	linefw "I DIDN'T THINK I SHOULD BE LOSING."
	done

Text11c2:
	text "THERE'S A SPECIAL METHOD TO OPEN"
	linefw "THAT CAPTURE POD."
	linefw "OKAY, YOU."
	linefw "GO STAND IN FRONT OF THE POD."
	done

Text11c3:
	text "GAAAAAAAAHHH!!!"
	done

Text11c4:
	text "THANK YOU, ", "<RAMNAME>", "."
	linefw "YOU'VE DONE WELL, AS USUAL."
	linefw "I WAS CAPTURED BECAUSE I WASN'T"
	linefw "ABLE TO BEAT TEAM GR."
	linefw "HERE, TAKE THIS GIFT."
	done

Text11c5:
	text "I'M GOING TO RETURN TO THE"
	linefw "POKÉMON DOME."
	done

Text11c6:
	text "HOLD IT, STAN!"
	done

Text11c7:
	text "WHAT IS IT?"
	done

Text11c8:
	text "TAKE THESE BOOSTER PACKS TO"
	linefw "REDISTRIBUTE OVER THERE, WILL YOU?"
	done

Text11c9:
	text "OH, THANKS A LOT, SIR."
	linefw "YOU'RE A GOOD MAN."
	done

Text11ca:
	text "YOU'D LIKE TO FIGHT AGAINST ME AT"
	linefw "THE POKÉMON DOME, RIGHT?"
	linefw "I'LL BE THERE WAITING FOR YOU!"
	done

Text11cb:
	text "I MUST FOLLOW THE RULES OF"
	linefw "TEAM GR'S ELECTRIC FORTRESS."
	linefw "I'LL OPEN THE DOORS LEADING TO"
	linefw "CATHERINE FOR YOU NOW!"
	done

Text11cc:
	text "GYAAAAAAAHHHH!!!"
	done

Text11cd:
	text "THE FORTRESS LEADER IS BACK THERE."
	linefw "DO YOUR BEST AGAINST HER!"
	done

Text11ce:
	text "GRAND MASTER STEVE IS BEING HELD"
	linefw "IN HERE SOMEWHERE."
	linefw "I DON'T HEAR HIM AROUND HERE,"
	linefw "THOUGH."
	done

Text11cf:
	text "THUNDER...VZZZZZT!"
	linefw "EH?"
	done

Text11d0:
	text "OH! YOU'RE ", "<RAMNAME>", "!"
	linefw "SO YOU'VE FINALLY COME HERE."
	linefw "I SUPPOSE YOU WISH TO FIGHT FOR"
	linefw "OWNERSHIP OF A GR THUNDER COIN."
	linefw "BUT THIS WON'T BE YOUR ORDINARY"
	linefw "CARD BATTLE."
	linefw "ALL DAMAGE DONE BY ELECTRIC-TYPE"
	linefw "POKÉMON IS INCREASED BY 10. "
	linefw "KNOWING THAT, THEN, IS YOUR DECK"
	linefw "GOOD TO GO?"
	done

Text11d1:
	text "OH! ", "<RAMNAME>", "."
	linefw "YOU'VE COME AGAIN, EH?"
	linefw "ARE YOU OKAY TO START BATTLING?"
	linefw "REMEMBER MY ADDED RULE:"
	linefw "ELECTRIC-TYPE POKÉMON DO 10 EXTRA"
	linefw "DAMAGE FOR EACH OF THEIR ATTACKS."
	linefw "ARE YOU PREPARED TO FIGHT?"
	linefw "DO YOU ACCEPT MY CHALLENGE?"
	done

Text11d2:
	text "WOULD YOU LIKE TO DUEL CATHERINE?"
	done

Text11d3:
	text "WE'LL USE 6 PRIZE CARDS."
	linefw "FIGHT! FIGHT!"
	linefw "THUNDER FIGHT!"
	linefw "LET'S MAKE SOME SPARKS!"
	done

Text11d4:
	text "OH! SO YOU'RE NOT PREPARED TO"
	linefw "FIGHT WITH ME JUST YET."
	linefw "WELL, ONCE YOUR DECK IS PREPARED,"
	linefw "LET'S FIGHT! FIGHT THE GOOD FIGHT!"
	done

Text11d5:
	text "OH! ", "<RAMNAME>", "."
	linefw "YOU'VE COME AGAIN, EH?"
	linefw "ARE YOU OKAY TO START BATTLING?"
	linefw "REMEMBER MY ADDED RULE:"
	linefw "ELECTRIC-TYPE POKÉMON DO 10 EXTRA"
	linefw "DAMAGE FOR EACH OF THEIR ATTACKS."
	linefw "ARE YOU PREPARED TO FIGHT?"
	linefw "DO YOU ACCEPT MY CHALLENGE?"
	done

Text11d6:
	text "OH NOOOO! I'VE BEEN DEFEATED"
	linefw "USING MY OWN RULES!"
	done

Text11d7:
	text "HEY HEY HEEEEY!"
	linefw "VZZZT! THAT'S THE POWER OF THUNDER!"
	linefw "<RAMNAME>", ", YOU'RE WEAK."
	linefw "YOU NEED TO POWER YOURSELF UP!"
	done

Text11d8:
	text "I'VE BEEN NUMBED BY YOUR POWER!"
	linefw "VZZZT VZZZZT!"
	done

Text11d9:
	text "SINCE YOU WERE THE WINNER,"
	linefw "TAKE THIS GR THUNDER COIN."
	done

Text11da:
	text "USING THAT COIN, YOU MAY ENTER BOTH"
	linefw "THE GR FIRE AND GR WATER FORTRESSES."
	linefw "IT'S ALL YOU, ", "<RAMNAME>", "!"
	linefw "GO, GO, GO!"
	done

Text11db:
	text "UH, UM... HELLO THERE."
	linefw "MY NAME'S CASSIE."
	linefw "IF YOU CAN BEAT ME IN A CARD BATTLE,"
	linefw "YOU CAN ENTER THE NEXT ROOM."
	linefw "BUT I HAVE A REQUEST ALL CHALLENGERS"
	linefw "MUST AGREE ON FIRST...SORRY!"
	linefw "PLEASE INCLUDE 4 PIKACHU CARDS IN"
	linefw "YOUR ACTIVE DECK BEFORE WE START."
	linefw "I DON'T MEAN FLYING PIKACHU, EITHER."
	linefw "JUST REGULAR CUTE PIKACHU CARDS."
	linefw "ARE YOU WILLING TO DO THAT AND"
	linefw "HAVE A DUEL WITH ME?"
	done

Text11dc:
	text "WOULD YOU LIKE TO DUEL CASSIE?"
	done

Text11dd:
	text "UHH...YOU DON'T HAVE ENOUGH PIKACHU"
	linefw "CARDS IN YOUR DECK, I'M AFRAID."
	linefw "I'D LIKE YOUR DECK TO HAVE 4 PIKACHU"
	linefw "CARDS IN IT BEFORE WE BATTLE."
	linefw "PLEASE DO ME FAVOR AND PUT THEM"
	linefw "INTO YOUR DECK."
	done

Text11de:
	text "YOU HAVE...4 PIKACHU CARDS, RIGHT?"
	linefw "THANK YOU VERY MUCH."
	linefw "AS FOR PRIZE CARDS..."
	linefw "PLEASE PLACE 4, OKAY?"
	done

Text11df:
	text "I'D LIKE IT IF YOU COULD PUT 4"
	linefw "PIKACHU CARDS IN YOUR DECK."
	linefw "THOSE ARE MY CONDITIONS AS A MEMBER"
	linefw "OF TEAM GR'S ELECTRIC FORTRESS..."
	done

Text11e0:
	text "GREETINGS, ", "<RAMNAME>", "."
	linefw "I'M FARING WELL TODAY."
	linefw "DO YOU WANT TO BATTLE ME WITH A DECK"
	linefw "CONTAINING 4 PIKACHU CARDS AGAIN?"
	done

Text11e1:
	text "EXCUSE ME, BUT YOU DON'T HAVE"
	linefw "4 PIKACHU CARDS IN YOUR DECK."
	linefw "WITHOUT 4 REGULAR PIKACHU CARDS,"
	linefw "I WON'T PLAY AGAINST YOU."
	linefw "PLEASE COME BACK WHEN YOU PUT SOME"
	linefw "INTO YOUR DECK."
	done

Text11e2:
	text "SINCE YOU HAVE ALL OF THOSE PIKACHU"
	linefw "CARDS, WE CAN BEGIN THE MATCH."
	linefw "PLEASE SET ASIDE 4 PRIZE CARDS."
	done

Text11e3:
	text "THAT'S FINE. I'LL BE AROUND HERE"
	linefw "IF YOU EVER WANT TO PLAY AGAIN."
	done

Text11e4:
	text "I DIDN'T THINK YOU COULD WIN,"
	linefw "I THOUGHT...OH WELL, I LOST."
	done

Text11e5:
	text "<RAMNAME>", ", YOU'RE REALLY STRONG,"
	linefw "AREN'T YOU? YOU HAVE MY RESPECT."
	linefw "EVEN MORESO SINCE YOU FREELY CAME TO"
	linefw "GR ISLAND AND YOU'RE FIGHTING ALONE."
	linefw "THAT TAKES SOME REAL COURAGE."
	linefw "I'D LIKE TO BE COURAGEOUS, TOO..."
	linefw "I'M GOING TO TRY MY BEST TO BE"
	linefw "JUST AS BRAVE AS YOU! "
	done

Text11e6:
	text "UMMM...I'VE WON."
	linefw "...PLEASE EXCUSE ME..."
	done

Text11e7:
	text "AHHH, I THOUGHT I MIGHT LOSE AGAIN."
	linefw "I'LL GIVE YOU A BOOSTER PACK."
	done

Text11e8:
	text "I LEARN A LOT DURING OUR BATTLES."
	linefw ""
	linefw "I'LL TRY MY BEST TO GET BETTER,"
	linefw "SO COME PLAY ME AGAIN LATER!"
	done

Text11e9:
	text "UMM...YOU CAN'T GO THROUGH THERE..."
	linefw "NOT WITHOUT DEFEATING ME FIRST..."
	done

Text11ea:
	text "NOW TO INPUT THE PASSWORD SO THE"
	linefw "DOORS WILL OPEN..."
	done

Text11eb:
	text "THE NEXT ROOM IS GUARDED BY CHIP."
	linefw "WE ALSO HAVE A GRAND MASTER THERE."
	linefw "I'M FAIRLY CERTAIN...IT'S STEVE."
	linefw ""
	linefw "PLEASE TRY YOUR BEST, AS CHIP IS"
	linefw "A STRONG CARD PLAYER."
	done

Text11ec:
	text "HEY, CAN I ASK A FAVOR OF YOU?"
	linefw "SEE THAT MEAN GUY OVER THERE?"
	linefw "HE REFUSES TO TRADE WITH ME. IF YOU"
	linefw "HAVE WHAT I NEED, COULD WE TRADE?"
	linefw "IF I CAN'T BUILD MY DECK,"
	linefw "I CAN'T JOIN TEAM GR..."
	linefw "SO DO YOU HAVE A DARK RAICHU Lv31?"
	linefw "DO YOU?"
	linefw "ALL I HAVE IS THIS PIKACHU Lv16."
	linefw "PLEASE TRADE WITH ME!"
	linefw "IT'S ACTUALLY A PRETTY RARE"
	linefw "PIKACHU CARD, I THINK."
	done

Text11ed:
	text "DON'T YOU WANT THIS RARE"
	linefw "PIKACHU Lv16 CARD?"
	linefw "YOU KNOW, I'D STILL LIKE A"
	linefw "DARK RAICHU Lv31..."
	done

Text11ee:
	text "YOU STINK! YOU'RE JUST AS MEAN"
	linefw "AS THAT OTHER GUY!"
	done

Text11ef:
	text "HUNH? YOU DON'T EVEN HAVE A"
	linefw "DARK RAICHU Lv31!"
	linefw "C'MON, DON'T BE MEAN!"
	done

Text11f0:
	text "OH DEAR. YOU HAVE THE CARD, BUT IT'S"
	linefw "BEING USED IN ONE OF YOUR DECKS."
	linefw "THIS IS IMPORTANT FOR MY CAREER"
	linefw "WITH TEAM GR."
	linefw "IF YOUR CARD IS IN A DECK,"
	linefw "THEN YOU CAN'T TRADE IT."
	linefw "IF YOU STILL WANT TO TRADE,"
	linefw "FIRST TAKE IT OUT OF YOUR DECK."
	done

Text11f1:
	text "THEN LET'S GET TRADING!"
	done

Text11f2:
	text "I FINALLY HAVE MY"
	linefw "DARK RAICHU Lv31!"
	linefw "TEAM GR MEMBERS ARE SUPPOSED TO HAVE"
	linefw "DARK POKÉMON CARDS, YOU KNOW!"
	done

Text11f3:
	text "HEH HEH... WHAT A GREAT TRADE."
	linefw "THANK YOU VERY MUCH!"
	done

Text11f4:
	text "DO YOU KNOW ABOUT IMAKUNI??"
	linefw "THAT MAN CERTAINLY MAKES ME BLUSH!"
	linefw "I'VE BEEN WAITING FOR HIM HERE"
	linefw "SINCE HE SHOWS UP IN RANDOM PLACES."
	linefw "AREN'T YOU FROM MY HOME ISLAND?"
	linefw "I BELIEVE YOUR NAME'S ", "<RAMNAME>", "."
	linefw "SO THEN, ", "<RAMNAME>", ","
	linefw "ARE YOU WONDERING WHY I'M HERE?"
	linefw "I'VE COME ON A PERSONAL QUEST:"
	linefw "TO GET MY CARDS BACK FROM TEAM GR."
	linefw "GRANTED, IT'S IMPOSSIBLE TO FIGHT"
	linefw "TEAM GR WITHOUT ANY CARDS."
	linefw "WHAT COUNTS IS THAT I'M HERE,"
	linefw "TRYING MY BEST AGAINST THOSE GOONS."
	linefw "OH, I'M SORRY! MY STORY HAS GOTTEN"
	linefw "A BIT TOO LONG, EH?"
	linefw "IF YOU CAN'T TELL, I DO LIKE"
	linefw "TO TALK! OH HO HO HO...."
	done

Text11f5:
	text "DO YOU USE THE COMPUTERS IN EACH"
	linefw "FORTRESS VERY OFTEN?"
	linefw "HAVE YOU EVER SEEN ANYTHING MORE"
	linefw "CONVENIENT THAN THOSE COMPUTERS?"
	linefw "ANYWAY, I'VE ONLY JUST MOVED TO THIS"
	linefw "ISLAND MYSELF, ", "<RAMNAME>", "."
	linefw "EVERYONE HERE JUST JABBERS ON ABOUT"
	linefw "WINNING, WINNING, WINNING."
	linefw "TEAM GR HAS HIGH STANDARDS FOR"
	linefw "RECRUITS AND WHAT CARDS THEY HAVE."
	linefw "IT SEEMS LIKE A VERY RUDE WAY TO"
	linefw "GAIN NEW FAITHFUL FOLLOWERS."
	linefw "OH, I'M SORRY! MY STORY HAS GOTTEN"
	linefw "A BIT TOO LONG, EH?"
	linefw "IF YOU CAN'T TELL, I DO LIKE"
	linefw "TO TALK! OH HO HO HO...."
	done

Text11f6:
	text "MY FRIENDS TELL ME THAT ALL THE"
	linefw "STOLEN CARDS HAVE BEEN RETURNED."
	linefw "THEY ALSO SAY THAT THE GRAND MASTERS"
	linefw "HAVE RETURNED TO YOUR ISLAND."
	linefw "WAS THAT ALL YOUR OWN DOING,"
	linefw "<RAMNAME>", "?"
	linefw "I DON'T KNOW WHY YOU'RE TRYING SO"
	linefw "HARD TO DEFY KING VILLICCI."
	linefw "IT'S JUST PLAIN STUPID TO CHALLENGE"
	linefw "KING VILLICCI, FOUNDER OF TEAM GR."
	linefw "YOU'LL ONLY END UP CRYING FROM A"
	linefw "MOST SHAMEFUL DEFEAT, YOU KNOW."
	linefw "OH, I'M SORRY! MY STORY HAS GOTTEN"
	linefw "A BIT TOO LONG, EH?"
	linefw "IF YOU CAN'T TELL, I DO LIKE"
	linefw "TO TALK! OH HO HO HO...."
	done

Text11f7:
	text "I WAS ALWAYS OPPOSED TO TEAM GR'S"
	linefw "PLOT TO TAKE EVERYONE'S CARDS AWAY."
	linefw "IT JUST DIDN'T SIT RIGHT WITH ME"
	linefw "TO SIMPLY UP AND TAKE THEM ALL."
	linefw "BY THE BY, DO YOU KNOW ABOUT"
	linefw "THE SEALED FORTRESS?"
	linefw "SUPPOSEDLY THERE ARE POWERFUL DECKS"
	linefw "CALLED THE CATASTROPHE DECKS INSIDE."
	linefw "NO ONE I KNOW HAS EVER SET FOOT"
	linefw "INTO THAT STRANGE PLACE."
	linefw "EVERYONE SHOUTS AND ARGUES ABOUT"
	linefw "HOW THEY CAN GET INSIDE FOR A PEEK."
	linefw "I WONDER IF YOU'LL END UP RILED UP"
	linefw "AND DISAPPOINTED, TOO?"
	linefw "OH, DEAR. MY STORY HAS BECOME"
	linefw "RATHER LONG, HASN'T IT?"
	linefw "I'M SORRY, BUT I DO LIKE TO GOSSIP!"
	linefw "HOOHOOHOO!"
	done

Text11f8:
	text "I WISH THAT GIRL WOULD SHUT UP ABOUT"
	linefw "THAT DUMB DARK RAICHU Lv31 CARD."
	linefw "AS IF ANYONE WOULD HELP HER MAKE"
	linefw "A DECK TO JOIN TEAM GR."
	done

Text11f9:
	text "EH, THAT GIRL GAVE YOU A RARE CARD?"
	linefw "CRAP! I WISH SHE GAVE IT TO ME!"
	linefw "I DIDN'T THINK THERE WERE ANY KIND-"
	linefw "HEARTED PEOPLE LEFT AROUND HERE."
	linefw "YEAH! I'VE DECIDED!"
	linefw "I'LL WORK HARD TO BE KINDER NOW!"
	done

Text11fa:
	text "OH? IF IT ISN'T ", "<RAMNAME>", ","
	linefw "THE KID THAT BEAT THE GRAND MASTERS!"
	linefw "I'VE HEARD RUMORS ABOUT YOU."
	linefw "WHAT ARE YOU DOING HERE, THOUGH?"
	linefw "...I GUESS I SHOULD INTRODUCE MYSELF"
	linefw "FIRST, EH? THE NAME'S PETER."
	linefw "I CAME TO THIS ISLAND BECAUSE"
	linefw "TEAM GR FASCINATES ME."
	linefw "I'VE BEEN HAVING BATTLES WITH MANY"
	linefw "DIFFERENT TEAM GR MEMBERS."
	linefw "I'VE COMPILED A COOL DECK FROM MY"
	linefw "VICTORIES. CARE TO HAVE A DUEL?"
	linefw "IF YOU BEAT ME,"
	linefw "I'LL GIVE YOU A BOOSTER PACK OR TWO."
	done

Text11fb:
	text "HELLO. HOW ARE YOU, ", "<RAMNAME>", "?"
	linefw "HAVE YOU COME TO DUEL ME?"
	linefw "I'M UP FOR A CARD BATTLE ANY TIME."
	linefw "ARE YOU READY TO FIGHT?"
	done

Text11fc:
	text "WOULD YOU LIKE TO DUEL PETER?"
	done

Text11fd:
	text "GOOD TO HEAR!"
	linefw "WE'LL USE 4 PRIZE CARDS."
	done

Text11fe:
	text "OH, I'M SORRY TO HEAR THAT."
	linefw ""
	linefw "JUST KEEP ME IN MIND IF YOU'RE EVER"
	linefw "LOOKING FOR A ROUSING CARD BATTLE."
	done

Text11ff:
	text "WAAH!!"
	linefw "...OH, PLEASE EXCUSE ME."
	linefw "I GUESS I LOST. I'LL GIVE YOU YOUR"
	linefw "BOOSTER PACKS IMMEDIATELY."
	done

Text1200:
	text "IF YOU'D BE UP FOR IT,"
	linefw "I'D LOVE A REMATCH SOMETIME."
	done

Text1201:
	text "OH, I'M SORRY,"
	linefw "BUT I SEEM TO HAVE BEATEN YOU."
	linefw "IF I MAY SAY SO, THOUGH, IT WAS"
	linefw "CERTAINLY AN IMPRESSIVE MATCH!"
	done

Text1202:
	text "...*SHHH*...*GOHHH*..."
	linefw "WATER...!!"
	linefw "WATER! I'M ALEX! *SHHH*..."
	linefw "ONE OF TEAM GR'S WATER MEMBERS..."
	linefw "*GOHHH*...ERM, IF YOU'D LIKE TO"
	linefw "GO ON, FIGHT ME...WATER!"
	linefw "*SHHH*...HOWEVER...*GOHHH*..."
	linefw "I HAVE A SPECIAL RULE...*SHHH*..."
	linefw "*GOHHH*...YOUR BENCH..."
	linefw "MAY ONLY HAVE 3 POKÉMON."
	done

Text1203:
	text "*SHHH*...*GOHHH*..."
	linefw "WATERRRRR!!"
	linefw "ONLY 3 BENCHED POKÉMON ARE ALLOWED"
	linefw "IN FIGHTS AGAINST ME...*GOHHH*..."
	done

Text1204:
	text "WOULD YOU LIKE TO DUEL ALEX?"
	done

Text1205:
	text "LAY OUT 4 PRIZE CARDS AND WE SHALL"
	linefw "BEGIN! WATERRRRRR!"
	done

Text1206:
	text "*SHHH*...*GOHHH*..."
	linefw "WATERRRRR!!!!"
	done

Text1207:
	text "*SHHH*...*GOHHH*..."
	linefw "I WON'T LOSE THIS TIME! WATERRR!"
	done

Text1208:
	text "4 PRIZE CARDS."
	linefw "*SHHH*...*GOHHH*..."
	done

Text1209:
	text "WATERRRRR!!!!"
	done

Text120a:
	text "WA...TER..."
	done

Text120b:
	text "*SHHH*...*GOHHH*..."
	linefw "I'M DRAINED AND DEFEATED...WATER!!"
	done

Text120c:
	text "WATERRRRRR!!!!"
	done

Text120d:
	text "*SHHH*...*GOHHH*..."
	linefw "...*SHHH*...*GOHHH*..."
	done

Text120e:
	text "WAAAATERRRR..."
	linefw "*SHHH*...*GOHHH*..."
	done

Text120f:
	text "*SHHH*...I'LL OPEN THE DOORS..."
	linefw "*GOHHH*..."
	done

Text1210:
	text "WATERRRRR!!!"
	done

Text1211:
	text "*SHHH*...DOORS OPENED..."
	linefw "*SHHH*...ADVANCE...*GOHHH*..."
	done

Text1212:
	text "THANK YOU FOR VISITING."
	linefw "THIS IS TEAM GR'S WATER FORTRESS."
	linefw "I'M SORRY, BUT I CANNOT ALLOW YOU"
	linefw "TO ENTER AT THIS TIME."
	linefw "SHOW ME THE GR LIGHTNING COIN,"
	linefw "AND YOU MAY ENTER THE FORTRESS."
	done

Text1213:
	text "THANK YOU FOR VISITING."
	linefw "THIS IS TEAM GR'S WATER FORTRESS."
	done

Text1214:
	text "THERE IS A CIRCULAR COIN-SIZED SLOT"
	linefw "UNDER AN IMAGE OF A MAGNEMITE."
	done

Text1215:
	text "INSERT YOUR GR THUNDER COIN?"
	done

Text1216:
	text "THANK YOU FOR VISITING."
	linefw "THIS IS TEAM GR'S WATER FORTRESS."
	linefw "ALLOW ME TO TELL YOU ABOUT YOUR"
	linefw "OPPONENTS AND EXPLAIN THE RULES."
	linefw "THE LEADER OF THE WATER FORTRESS"
	linefw "IS A WOMAN NAMED BROOKE."
	linefw "IN ORDER TO FIGHT HER, YOU MUST"
	linefw "FIRST DEFEAT 3 GR FORTRESS MEMBERS."
	linefw "YOU'LL LEARN ABOUT EACH MEMBER'S"
	linefw "SPECIAL BATTLE RULES INSIDE."
	linefw "THAT IS ALL. PLEASE ENJOY DUELLING"
	linefw "IN TEAM GR'S WATER FORTRESS."
	done

Text1217:
	text "HI THERE! I'M BROOKE, THE LEADER OF"
	linefw "TEAM GR'S WATER FORTRESS."
	linefw "AND I IMAGINE YOU'RE ", "<RAMNAME>", ","
	linefw "THE ONE FAMED FOR DEFYING TEAM GR."
	linefw "ARE YOU HERE TO CLAIM THE"
	linefw "GR WATER COIN FROM ME?"
	linefw "THE PROCESS IS EXACTLY THE SAME AS"
	linefw "THE OTHER TEAM GR FORTRESS LEADERS':"
	linefw "IF YOU CAN BEAT ME IN A CARD BATTLE,"
	linefw "YOU'LL WIN THE WATER COIN YOU SEEK."
	linefw "THERE'S SO MUCH WATER HERE FOR MY"
	linefw "ADORABLE WATER POKÉMON."
	linefw "BECAUSE OF IT, WATER POKÉMON PAY"
	linefw "1 LESS ENERGY CARD TO RETREAT HERE."
	linefw "3 ENERGY CARDS BECOME 2."
	linefw "2 ENERGY CARDS BECOME 1."
	linefw "UNDERSTAND?"
	linefw "IF YOU'VE GOT IT, LET'S FIGHT!"
	done

Text1218:
	text "HEY ", "<RAMNAME>", "!"
	linefw ""
	linefw "HAVE YOU COME BACK TO FIGHT FOR"
	linefw "THE GR WATER COIN?"
	linefw "IN THAT CASE, I'M READY TO GO!"
	linefw ""
	linefw "THE WATER AROUND HERE IS IDEAL FOR"
	linefw "MY ADORABLE WATER POKÉMON."
	linefw "BECAUSE OF IT, ALL WATER POKÉMON"
	linefw "PAY 1 LESS ENERGY CARD TO RETREAT."
	linefw "JUST A QUICK REMINDER."
	linefw "SHALL WE DUEL?"
	done

Text1219:
	text "WOULD YOU LIKE TO DUEL BROOKE?"
	done

Text121a:
	text "JUST LIKE THE OTHER LEADERS,"
	linefw "WE'LL USE 6 PRIZE CARDS."
	done

Text121b:
	text "ARE YOU CONSIDERING USING SOME"
	linefw "OTHER DECK?"
	linefw "I'LL BE WAITING FOR YOU HERE."
	linefw "RETURN AT YOUR LEISURE."
	done

Text121c:
	text "HEY ", "<RAMNAME>", "!"
	linefw "LET'S HAVE A CARD BATTLE!"
	linefw "REMEMBER THAT I HAVE AN EXTRA FUN"
	linefw "RULE WHEN YOU BATTLE WITH ME HERE."
	linefw "I'VE GOT A LOT OF WATER HERE FOR"
	linefw "ADORABLE WATER POKÉMON."
	linefw "BECAUSE OF IT, WATER POKÉMON PAY"
	linefw "1 LESS ENERGY CARD TO RETREAT."
	linefw "NOW THAT WE'RE DONE WITH"
	linefw "EXPLANATIONS, CARE TO DUEL?"
	done

Text121d:
	text "OOH, OOH! 6 PRIZE CARDS!"
	linefw "LET'S BEGIN!"
	done

Text121e:
	text "AWWW, SHUCKS. THAT'S TOO BAD."
	linefw "I WAS ANXIOUS TO PLAY."
	linefw "IF YOU CHANGE YOUR MIND,"
	linefw "PLEASE C'MON BACK."
	done

Text121f:
	text "UWAAAH! THE RUMORS WERE TRUE!"
	linefw "YOU REALLY ARE ONE TOUGH COOKIE!"
	done

Text1220:
	text "AND I WILL NOW HAPPILY PRESENT YOU"
	linefw "WITH THE GR WATER COIN."
	done

Text1221:
	text "OH HO HO, I WON! YOU LASTED LONGER"
	linefw "THAN I THOUGHT YOU WOULD!"
	linefw "YOU WON'T WIN PLAYING LIKE THAT!"
	linefw "TRY HARDER, ", "<RAMNAME>", "!"
	done

Text1222:
	text "AUGH, THAT'S A SHAME."
	linefw "I THOUGHT YOU WERE DONE FOR."
	linefw "YEAH, YEAH, HERE'RE YOUR"
	linefw "BOOSTER PACKS."
	done

Text1223:
	text "WELL, IT WAS FUN!"
	linefw "COME BACK AGAIN FOR A REMATCH!"
	done

Text1224:
	text "OH HO HO, I WON!"
	linefw "I'M SO EXCITED!"
	linefw "WIN OR LOSE, I ALWAYS HAVE FUN"
	linefw "PLAYING AGAINST YOU."
	linefw "COME BACK FOR A REMATCH SOMETIME!"
	done

Text1225:
	text "HERE YOU GO!"
	linefw "YOU'VE EARNED IT!"
	done

Text1226:
	text "IT LOOKS LIKE YOU STILL DON'T HAVE"
	linefw "THE GR FIRE COIN."
	linefw "BEFORE YOU MAY ENTER THE GR FIGHTING"
	linefw "FORTRESS, YOU'LL NEED TO WIN THAT."
	linefw "I SUPPOSE YOUR NEXT DESTINATION IS"
	linefw "THE GR FIRE FORTRESS, THEN!"
	done

Text1227:
	text "OH, YOU ALREADY HAVE THE"
	linefw "GR FIRE COIN? AMAZING!"
	linefw "YOU'RE QUALIFIED TO ENTER THE"
	linefw "GR FIGHTING FORTRESS NOW."
	linefw "ARE YOU GOING TO GO?"
	linefw "DO YOUR BEST!"
	done
