Text1297:
	text "USE AERODACTYL'S PREHISTORIC POWER"
	linefw "TO PREVENT ALL POKÉMON EVOLUTION."
	linefw "DO YOU HAVE YOUR OWN POKÉMON THAT"
	linefw "YOU'D LIKE TO EVOLVE? WELL, THEN..."
	linefw "USE DEVOLUTION SPRAY TO TEMPORARILY"
	linefw "TURN AERODACTYL BACK INTO A FOSSIL."
	linefw "ONCE YOU'RE DONE EVOLVING POKÉMON,"
	linefw "PLAY AERODACTYL AGAIN!"
	linefw "PREHISTORIC POWER IS TRULY A"
	linefw "POWERFUL ABILITY!"
	done

Text1298:
	text "IF A POKÉMON HAS A WEAKNESS,"
	linefw "IT TAKES DOUBLE DAMAGE FROM ANY"
	linefw "ATTACK BY A POKÉMON OF THAT TYPE."
	linefw "FOR EXAMPLE, A FIRE POKÉMON"
	linefw "WILL TAKE DOUBLE DAMAGE FROM AN"
	linefw "ATTACK BY A WATER POKÉMON!"
	linefw "IF A POKÉMON HAS A RESISTANCE,"
	linefw "IT TAKES 30 LESS DAMAGE WHEN"
	linefw "ATTACKED BY A POKÉMON OF THAT TYPE."
	linefw ""
	linefw "SO, IF A POKÉMON GETS HIT FOR"
	linefw "30 DAMAGE BY A TYPE IT RESISTS,"
	linefw "IT WILL NOT RECEIVE ANY DAMAGE!"
	linefw ""
	linefw "MAKE SURE YOU KNOW THE WEAKNESSES"
	linefw "AND RESISTANCES OF YOUR POKÉMON!"
	done

Text1299:
	text "THE FULL NAME OF TEAM GR IS"
	linefw "'TEAM GREAT ROCKET'."
	linefw "THIS EVIL TEAM THINKS THEY CAN WIN"
	linefw "IF THEY MAKE THEIR OWN CARDS."
	linefw "IN ORDER TO RECLAIM MY STOLEN CARDS,"
	linefw "I'LL HAVE TO FIGHT TEAM GR."
	linefw "TEAM GR CHANGES THE STANDARD RULES"
	linefw "FOR DUELLING, TOO."
	linefw "THEY ARE THE ENEMIES OF EVERYONE"
	linefw "WHO LOVES THE POKÉMON CARD GAME!"
	done

Text129a:
	text "THERE EXISTS A GAME CENTER ON"
	linefw "GR ISLAND."
	linefw "IF YOU COLLECT ENOUGH CHIPS, YOU CAN"
	linefw "EXCHANGE THEM FOR CARDS OR COINS."
	linefw "IT'S RUMORED THAT A CARD EXISTS"
	linefw "WHICH YOU CAN ONLY GET THERE..."
	done

Text129b:
	text "DIFFERENT CARDS OF THE SAME POKÉMON"
	linefw "EXIST, CLASSIFIED BY POKÉMON LEVEL."
	linefw "IF THE LEVEL DIFFERS, THE POKÉMON'S"
	linefw "HP, ATTACKS, AND MORE MAY DIFFER."
	linefw "FOR EXAMPLE, PIKACHU CAN BE "
	linefw "Lv5, Lv12, Lv13, Lv14, OR Lv16."
	linefw "HOWEVER, YOU MAY STILL ONLY HAVE UP"
	linefw "TO 4 OF ONE POKÉMON IN A DECK."
	linefw "CHOOSE BETWEEN THE DIFFERENT"
	linefw "VERSIONS CAREFULLY WHEN BUILDING."
	done

Text129c:
	text "A QUICK LIST OF CHARACTERISTICS"
	linefw "FOR ROCK POKÉMON CARDS:"
	linefw "- STRONG AGAINST ELECTRIC POKÉMON"
	linefw "- WEAK AGAINST GRASS POKÉMON"
	linefw "- THEIR ATTACKS RELY MOSTLY ON"
	linefw "  ", "<FIGHTING>", " ENERGY CARDS"
	done

Text129d:
	text "FIGHTING POKÉMON WILL HAVE A HARD"
	linefw "TIME AGAINST STAGE 2 POKÉMON,"
	linefw "AS MANY STAGE 2 POKÉMON ARE"
	linefw "RESISTANT TO FIGHTING ATTACKS."
	linefw "TRY TO KNOCK OUT YOUR OPPONENT'S"
	linefw "POKÉMON BEFORE THEY EVOLVE."
	done

Text129e:
	text "IT'S NOT ALWAYS A GOOD IDEA TO USE"
	linefw "FIGHTING POKÉMON AGAINST COLORLESS."
	linefw "THIS IS BECAUSE FLYING POKÉMON "
	linefw "RESIST FIGHTING-TYPE ATTACKS."
	linefw "TO COUNTER THIS, TRYING SHARING YOUR"
	linefw "FIGHTING DECK WITH ELECTRIC POKÉMON."
	done

Text129f:
	text "A QUICK LIST OF CHARACTERISTICS"
	linefw "FOR FIGHTING POKÉMON CARDS:"
	linefw "- STRONG AGAINST ELECTRIC POKÉMON"
	linefw "- WEAK AGAINST PSYCHIC POKÉMON"
	linefw "- THEIR ATTACKS RELY MOSTLY ON"
	linefw "  ", "<FIGHTING>", " ENERGY CARDS"
	done

Text12a0:
	text "FIGHTING POKÉMON DON'T REALLY HAVE"
	linefw "ANY EASY COMBOS TO WRITE ABOUT."
	linefw "THIS IS DUE TO THE RARITY OF POKÉMON"
	linefw "POWERS IN THEIR TYPE FAMILY."
	linefw "EVEN IF THERE ARE NO COMBOS, THOUGH,"
	linefw "THEIR ATTACKS ARE VERY POWERFUL!"
	done

Text12a1:
	text "FIGHTING POKÉMON USUALLY HAVE A"
	linefw "WEAKNESS TO PSYCHIC POKÉMON."
	linefw "AS SUCH, PUTTING CARDS IN YOUR DECK"
	linefw "THAT RESIST PSYCHIC ATTACKS HELP."
	linefw "TRY USING KANGASKHAN, CLEFAIRY,"
	linefw "TAUROS, AND OTHER COLORLESS POKÉMON."
	done

Text12a2:
	text "A QUICK LIST OF CHARACTERISTICS"
	linefw "FOR GRASS POKÉMON CARDS:"
	linefw "- STRONG AGAINST ROCK POKÉMON"
	linefw "- WEAK AGAINST FIRE POKÉMON"
	linefw "- THEY ARE ADDITIONALLY SOMETIMES"
	linefw "  STRONG AGAINST WATER POKÉMON"
	linefw "- THEIR ATTACKS RELY MOSTLY ON"
	linefw "  ", "<GRASS>", " ENERGY CARDS"
	done

Text12a3:
	text "MANY GRASS POKÉMON ARE CAPABLE OF"
	linefw "EVOLVING INTO STAGE 2 FORMS."
	linefw "USE THE POKÉMON BREEDER TRAINER"
	linefw "CARD TO QUICKLY EVOLVE YOUR POKÉMON."
	linefw "YOU'LL BE ABLE TO USE POWERFUL"
	linefw "ATTACKS EARLIER IN THE DUEL."
	done

Text12a4:
	text "GRASS POKÉMON HAVE A COMMON"
	linefw "WEAKNESS AGAINST FIRE POKÉMON."
	linefw "THIS MAKES WATER POKÉMON THEIR IDEAL"
	linefw "PARTNERS, AS FIRE IS WEAK TO WATER."
	linefw "THIS WAY, IF YOUR OPPONENT SENDS OUT"
	linefw "A FIRE POKÉMON, YOU CAN COUNTER IT."
	done

Text12a5:
	text "A QUICK LIST OF CHARACTERISTICS"
	linefw "FOR POISON POKÉMON CARDS:"
	linefw "- STRONG AGAINST ROCK AND GROUND"
	linefw "  POKÉMON"
	linefw "- WEAK AGAINST PSYCHIC POKÉMON"
	linefw ""
	linefw "- THEY SPECIALIZE IN POISON, SLEEP,"
	linefw "  AND CONFUSION STATUS EFFECTS"
	linefw "- THEIR ATTACKS RELY MOSTLY ON"
	linefw "  ", "<GRASS>", " ENERGY CARDS"
	done

Text12a6:
	text "POISON POKÉMON ARE KNOWN FOR SLEEP,"
	linefw "POISON, AND CONFUSION STATUS MOVES."
	linefw "IF YOU RELY ON POKÉMON POWERS, HAVE"
	linefw "SOME FULL HEAL CARDS IN YOUR DECK."
	linefw "THIS WAY, YOU DON'T HAVE TO WORRY"
	linefw "ABOUT STATUS STOPPING YOUR POWERS!"
	done

Text12a7:
	text "MOST POISON POKÉMON ARE WEAK"
	linefw "AGAINST PSYCHIC POKÉMON."
	linefw "TRY PUTTING POKÉMON RESISTANT TO"
	linefw "PSYCHIC-TYPES IN YOUR POISON DECK."
	linefw "JIGGLYPUFF, LICKITUNG, AND SNORLAX"
	linefw "ARE ALL GOOD CHOICES."
	done

Text12a8:
	text "A QUICK LIST OF CHARACTERISTICS"
	linefw "FOR WATER POKÉMON CARDS:"
	linefw "- STRONG AGAINST FIRE POKÉMON"
	linefw "- WEAK AGAINST ELECTRIC POKÉMON"
	linefw "- THEY ARE SOMETIMES WEAK AGAINST"
	linefw "  GRASS POKÉMON"
	linefw "- THEIR ATTACKS RELY MOSTLY ON"
	linefw "  ", "<WATER>", " ENERGY CARDS"
	done

Text12a9:
	text "WATER GUN AND HYDRO PUMP ARE ATTACKS"
	linefw "WHICH HAVE VARIABLE DAMAGE."
	linefw "THE MORE WATER ENERGY YOU ATTACH,"
	linefw "THE MORE POWERFUL THE ATTACK IS!"
	linefw "THESE ATTACKS ONLY BENEFIT FROM UP"
	linefw "TO 2 EXTRA ENERGY CARDS, THOUGH."
	done

Text12aa:
	text "PSYDUCK AND GOLDUCK HAVE ATTACKS"
	linefw "THAT REQUIRE PSYCHIC ENERGY."
	linefw "THEY ARE IDEAL FOR A DUAL-TYPE DECK"
	linefw "OF PSYCHIC AND WATER POKÉMON."
	linefw "HOWEVER, THEY ARE STILL GOOD POKÉMON"
	linefw "FOR ANY PSYCHIC-THEMED DECK!"
	done

Text12ab:
	text "A QUICK LIST OF CHARACTERISTICS"
	linefw "FOR FIRE POKÉMON CARDS:"
	linefw "- STRONG AGAINST GRASS POKÉMON"
	linefw "- WEAK AGAINST WATER POKÉMON"
	linefw "- HOWEVER, SOME GRASS POKÉMON AREN'T"
	linefw "  WEAK TO FIRE"
	linefw "- THEIR ATTACKS RELY MOSTLY ON"
	linefw "  ", "<FIRE>", " ENERGY CARDS"
	done

Text12ac:
	text "MANY FIRE POKÉMON ATTACKS REQUIRE"
	linefw "AN ENERGY CARD TO BE DISCARDED."
	linefw "BE SURE TO INCLUDE MANY ENERGY"
	linefw "CARDS IN DECKS WITH FIRE POKÉMON."
	linefw "ENERGY RETRIEVAL CARDS MIGHT"
	linefw "ALSO BE A WISE ADDITION."
	done

Text12ad:
	text "WATER POKÉMON ATTACKS EASILY"
	linefw "DOUSE MOST FIRE POKÉMON. "
	linefw "IF THEY'RE TROUBLING YOU, TRY ADDING"
	linefw "SOME ELECTRIC POKÉMON TO YOUR DECK."
	linefw "QUICKLY SWITCH TO ONE WHEN YOUR"
	linefw "OPPONENT BRINGS OUT A WATER POKÉMON."
	done

Text12ae:
	text "A QUICK LIST OF CHARACTERISTICS"
	linefw "FOR ELECTRIC POKÉMON CARDS:"
	linefw "- STRONG AGAINST WATER POKÉMON"
	linefw "- WEAK AGAINST FIGHTING POKÉMON"
	linefw "- THEIR ATTACKS RELY MOSTLY ON"
	linefw "  ", "<LIGHTNING>", " ENERGY CARDS"
	done

Text12af:
	text "ELECTRIC POKÉMON COMMONLY HAVE A"
	linefw "WEAKNESS TO FIGHTING POKÉMON."
	linefw "A DECENT CHOICE TO PROVIDE SOME"
	linefw "SUPPORT ARE FLYING-TYPE POKÉMON."
	linefw "THERE'S A VARIETY OF PIKACHU THAT"
	linefw "FLIES AND RESISTS FIGHTING, TOO."
	linefw "DON'T BE AFRAID TO SWITCH TO THESE"
	linefw "POKÉMON AGAINST A FIGHTING POKÉMON!"
	done

Text12b0:
	text "FLYING-TYPE POKÉMON ARE TYPICALLY"
	linefw "COLORLESS POKÉMON CARDS."
	linefw "MOST FLYING-TYPES RESIST FIGHTING"
	linefw "POKÉMON ATTACKS."
	linefw "AS COLORLESS POKÉMON, THEY CAN USE"
	linefw "ANY TYPE OF ENERGY TO ATTACK."
	linefw "ADDITIONALLY, THEIR ABILITY TO FLY"
	linefw "ALLOWS THEM TO RETREAT EASILY."
	done

Text12b1:
	text "A QUICK LIST OF CHARACTERISTICS"
	linefw "FOR PSYCHIC POKÉMON CARDS:"
	linefw "- BOTH STRONG AND WEAK AGAINST"
	linefw "  PSYCHIC POKÉMON"
	linefw "- SOME COLORLESS POKÉMON RESIST"
	linefw "  THEIR ATTACKS"
	linefw "- THEIR ATTACKS RELY MOSTLY ON"
	linefw "  ", "<PSYCHIC>", " ENERGY CARDS"
	done

Text12b2:
	text "PSYCHIC POKÉMON HAVE MANY USEFUL"
	linefw "POKÉMON POWERS."
	linefw "THESE INCLUDE DAMAGE SWAP, CURSE,"
	linefw "INVISIBLE WALL, & STRANGE BEHAVIOR."
	linefw "IF YOU'RE BUILDING A PSYCHIC DECK,"
	linefw "MAKE SURE YOU LOOK AT YOUR OPTIONS!"
	done

Text12b3:
	text "WHILE IN A DUEL, THE B BUTTON MAY BE"
	linefw "USED WITH THE CONTROL PAD TO VIEW"
	linefw "YOUR OWN OR YOUR OPPONENT'S"
	linefw "PLAY AREA OR DISCARD PILE!"
	linefw "B + DOWN : YOUR PLAY AREA"
	linefw "B + LEFT : YOUR DISCARD PILE"
	linefw "B + UP : OPPONENT'S PLAY AREA"
	linefw "B + RIGHT : OPPONENT'S DISCARD PILE"
	linefw "REMEMBER THESE HANDY FUNCTIONS!"
	done

Text12b4:
	text "COLORLESS POKÉMON ARE VERY EASY"
	linefw "TO USE IN DUELS."
	linefw "YOU MAY USE ANY TYPE OF ENERGY"
	linefw "TO POWER THEIR ATTACKS."
	linefw "AS SUCH, THEY MAY BE INCLUDED IN"
	linefw "DECKS OF ANY ENERGY TYPE."
	linefw "THERE ARE MANY COLORLESS POKÉMON,"
	linefw "SO CHECK THEM ALL OUT!"
	done

Text12b5:
	text "THERE'RE OTHER WAYS TO GET NEW CARDS"
	linefw "BESIDES DEFEATING OTHER PLAYERS."
	linefw "IF YOU CARD POP! WITH A FRIEND,"
	linefw "YOU WILL BOTH RECEIVE A NEW CARD."
	linefw "HOWEVER, YOU CAN ONLY GET ONE CARD"
	linefw "FROM EACH FRIEND."
	linefw "YOU SHOULD CARD POP! WITH MANY"
	linefw "FRIENDS TO COLLECT LOTS OF CARDS!"
	done

Text12b6:
	text "THE 6 ENERGY TYPES ARE GRASS, WATER,"
	linefw "FIRE, ELECTRIC, PSYCHIC, & FIGHTING."
	linefw "THERE ALSO EXIST SPECIAL ENERGY"
	linefw "CARDS BEYOND THESE 6 BASIC TYPES."
	linefw "ANY NUMBER OF BASIC ENERGY CARDS"
	linefw "CAN BE PUT INTO A DECK,"
	linefw "BUT ONLY 4 OF EACH SPECIAL ENERGY"
	linefw "CARD IS ALLOWED."
	done

Text12b7:
	text "THE FIRST LEGENDARY POKÉMON CARD"
	linefw "IS MOLTRES Lv37."
	linefw "FIRE ENERGY COMES TO YOUR HAND"
	linefw "THANKS TO ITS FIREGIVER PKMN POWER!"
	linefw "DIVEBOMB, ITS ATTACK, DOES"
	linefw "SERIOUS DAMAGE WHEN IT HITS!"
	linefw "GRAND MASTER COURTNEY, THE FIRE"
	linefw "QUEEN, HAS THIS CARD!"
	done

Text12b8:
	text "THE SECOND LEGENDARY POKÉMON CARD"
	linefw "IS ZAPDOS Lv68."
	linefw "ITS POWER, PEAL OF THUNDER, DOES"
	linefw "DAMAGE JUST FROM BEING PUT IN PLAY!"
	linefw "NO POKÉMON IS SAFE FROM ITS"
	linefw "BIG THUNDER ATTACK!"
	linefw "THE ELECTRIC GRAND MASTER, STEVE,"
	linefw "PROUDLY OWNS THIS CARD!"
	done

Text12b9:
	text "THE THIRD LEGENDARY POKÉMON CARD"
	linefw "IS THE CHILLING ARTICUNO Lv37."
	linefw "WHEN PUT IN PLAY, ITS POKÉMON POWER,"
	linefw "QUICKFREEZE, MAY PARALYZE THE FOE!"
	linefw "ITS ICE BREATH ATTACK IS TRULY"
	linefw "POWERFUL AS WELL!"
	linefw "THIS IS THE CARD GRAND MASTER JACK,"
	linefw "THE ICE-MAN, IS KNOWN FOR!"
	done

Text12ba:
	text "THE FOURTH LEGENDARY POKÉMON CARD"
	linefw "IS DRAGONITE Lv41."
	linefw "WHEN PUT INTO PLAY, ITS HEALING WIND"
	linefw "HEALS DAMAGE DONE TO YOUR POKÉMON!"
	linefw "ITS ATTACK, SLAM, IS FEARSOME WHEN"
	linefw "YOU FLIP HEADS ON THE COIN TOSS!"
	linefw "THE GRAND MASTER LEADER, ROD,"
	linefw "OWNS THIS CARD!"
	done

Text12bb:
	text "THERE ARE FOUR GRAND MASTERS WHO"
	linefw "DEFEND THE LEGENDARY POKÉMON CARDS:"
	linefw "COURTNEY, STEVE,"
	linefw "JACK, AND ROD."
	linefw "THEY'RE ALL MASTER PLAYERS OF"
	linefw "THE POKÉMON TRADING CARD GAME!"
	done

Text12bc:
	text "COINS ARE USED FOR CERTAIN ATTACKS"
	linefw "AND OTHER EVENTS DURING PLAY."
	linefw "THERE ARE PURPORTEDLY 24 DIFFERENT"
	linefw "COINS FOR PLAYERS TO COLLECT."
	linefw "YOU'LL GET COINS FROM ALL SORTS OF"
	linefw "PLACES. GOOD LUCK FINDING THEM ALL!"
	done

Text12bd:
	text "CARD POP! IS THE ONLY WAY YOU CAN"
	linefw "ACQUIRE CERTAIN CARDS."
	linefw "TWO SUCH CARDS ARE VENUSAUR Lv64"
	linefw "AND MEW Lv15."
	linefw "THERE ARE RUMORS THAT THERE ARE TWO"
	linefw "OTHER CARDS ONLY GOTTEN THIS WAY."
	linefw "CURRENTLY, NO ONE HAS REPORTED"
	linefw "SEEING THEM. I WONDER WHAT THEY ARE?"
	linefw "THEY'RE APTLY NAMED 'PHANTOM CARDS'."
	linefw "         -- MR. ISHIHARA"
	done

Text12be:
	text "TEAM GR IS INFAMOUS FOR THEIR"
	linefw "ADORATION OF DARK EVOLUTION CARDS."
	linefw "DARK EVOLUTION CARDS HAVE SOME"
	linefw "POWERFUL ATTACKS AND POKÉMON POWERS."
	linefw "THEY USUALLY HAVE LESS HP THAN"
	linefw "STANDARD EVOLUTIONS, HOWEVER."
	done

Text12bf:
	text "IT'S POSSIBLE TO USE MANY VAPOREON,"
	linefw "JOLTEON, AND FLAREON IN ONE DECK."
	linefw "TO SUPPORT THEM ALL, USE 4 EEVEE"
	linefw "AND 4 DITTO Lv19 CARDS."
	linefw "DITTO'S TRANSFORM ATTACK MAKES IT"
	linefw "A VERY VERSATILE POKÉMON."
	linefw "IT INCREASES THE POTENTIAL NUMBER"
	linefw "OF EEVEE CARDS IN THE DECK TO 8."
	done

Text12c0:
	text "THE GR KING, VILLICCI, IS SAID TO"
	linefw "POSSESS A SPECIAL CARD."
	linefw "THAT CARD IS NONE OTHER THAN THE"
	linefw "GR'S MEWTWO CARD!"
	linefw "IT HAS THE DARK WAVE POKÉMON POWER"
	linefw "AND DARK AMPLIFICATION ATTACK."
	linefw "IT'S UNKNOWN WHAT KIND OF ABILITIES"
	linefw "IT HAS. IT MUST BE A POWERFUL CARD."
	done

Text12c1:
	text "THERE ARE 5 SPECIAL ENERGY CARDS"
	linefw "IN ADDITION TO THE 6 BASIC TYPES."
	linefw "DOUBLE COLORLESS ENERGY AND"
	linefw "RAINBOW ENERGY ARE EXAMPLES."
	linefw "THERE'RE ALSO POTION, FULL HEAL, AND"
	linefw "RECYCLE ENERGY. EACH HAS ITS USE."
	linefw "THESE CARDS HAVE A LIMIT OF 4 PER"
	linefw "DECK, HOWEVER, UNLIKE BASIC ENERGY."
	linefw "THINK CAREFULLY ABOUT BALANCE"
	linefw "WHEN CHOOSING YOUR ENERGY CARDS."
	done

Text12c2:
	text "YOU CAN COLLECT UP TO 24"
	linefw "COINS TOTAL."
	linefw "YOU'LL FIND MANY BY BATTLING THE"
	linefw "LEADERS OF CLUBS OR FORTRESSES."
	linefw "THERE ARE ALSO A COUPLE IN THE GAME"
	linefw "CENTER AND AT CHALLENGE CUPS."
	linefw "ONE ESPECIALLY TOUGH ONE TO GET"
	linefw "IS HELD BY THE GR KING!"
	linefw "TRY TO COLLECT THEM ALL, AND"
	linefw "CHANGE YOUR COIN EVERY NOW AND THEN!"
	done

Text12c3:
	text "OHH?"
	linefw "WHAT CAN I DO FOR YOU?"
	linefw "EH? WHO AM I?! WELL!"
	linefw "DON'T YOU KNOW ME?"
	linefw "IT IS I, THE SUPER MUSICAL STAR"
	linefw "IMAKUNI?!"
	linefw "BUT I'M SAD RIGHT NOW... THERE ARE"
	linefw "NO POKÉMON CARDS LEFT...OR RIGHT!"
	linefw "HEY, YOU!"
	linefw "CARD POP! WITH ME!"
	linefw "EVEN IF YOU DON'T WANT TO!"
	linefw "LET'S CARD POP!"
	done

Text12c4:
	text "WE BOTH GOT A CARD!"
	linefw "LET'S SAVE OUR DATTATA!!"
	done

Text12c5:
	text "THE CARD I GOT WAS"
	linefw "<RAMTEXT>", ", HOORAY!"
	linefw "YOU GOT...AN IMAKUNI? CARD?"
	linefw "YOU'RE SO LUCKY! BE GLAD!"
	linefw "YEAH! SINCE WE HAD A CARD POP!,"
	linefw "WE BOTH GOT CARDS WE NEVER HAD!"
	done

Text12c6:
	text "I'M THE SUPER MUSICAL STAR,"
	linefw "IMAKUNI?!"
	linefw "HMM, WHAT IS IT?"
	linefw "OH, IT'S YOU AGAIN!"
	linefw "YOU ALREADY HAD A CARD POP! WITH ME."
	linefw "WE CAN'T HAVE ANOTHER, YOU KNOW!"
	linefw "MAYBE WE'LL GET MORE CARDS LATER!"
	linefw "SEE YA!!"
	done

Text12c7:
	text "HMM?"
	linefw "CAN I HELP YOU?"
	linefw "EH? WHO AM I?"
	linefw "DON'T YOU KNOW ME?"
	linefw "IT IS I, THE SUPER MUSICAL STAR,"
	linefw "IMAKUNI?!"
	linefw "HMM? CARDS?"
	linefw "OH, WOULD YOU LIKE A CARD BATTLE?"
	done

Text12c8:
	text "I'M THE SUPER MUSICAL STAR,"
	linefw "IMAKUNI?!"
	linefw "WHAT IS IT?"
	linefw "OH, IT'S YOU! YOU'RE PERSISTENT!"
	linefw "ARE THOSE YOUR CARDS?"
	linefw "WOULD YOU LIKE A CARD BATTLE?"
	linefw "DON'T BE SHY. YOU'D LIKE TO HAVE"
	linefw "A DUEL WITH ME, WOULDN'T YOU?"
	linefw "HAVE I TRAINED ENOUGH?"
	linefw "WE'LL SEE!"
	done

Text12c9:
	text "WOULD YOU LIKE TO DUEL IMAKUNI??"
	done

Text12ca:
	text "6 PRIZE CARDS!"
	linefw "WE'RE BATTLING SERIOUSLY!!"
	done

Text12cb:
	text "I'M LONELY, CAN'T YOU SEEEE?"
	linefw "NO ONE TO PLAY CARDS WITH MEEEE."
	linefw "WOE IS ME...I'D PLAY WITH MY"
	linefw "PARTNER...BUT I DON'T HAVE A WIFE! "
	done

Text12cc:
	text "AYEEE..."
	linefw "I'VE DONE IT!"
	linefw "I HAVE DEFEATED YOU!"
	linefw "BUT YOU WERE SO STRONG!"
	done

Text12cd:
	text "WELL, THEN, I GUESS I'LL"
	linefw "CONTINUE TO GO WANDER AROUND."
	done

Text12ce:
	text "WHAT IS IT, KID, THAT"
	linefw "MAKES YOU SO STRONG?!"
	linefw "IF I GIVE YOU THESE BOOSTER PACKS,"
	linefw "PROMISE NOT TO TELL ANYONE I LOST!"
	done

Text12cf:
	text "KID, YOU'VE BEATEN ME 3 TIMES NOW."
	linefw "ARE YOU HAPPY? ARE YOU HAPPY?"
	done

Text12d0:
	text "IT'S SO HUMILIATING FOR ME TO"
	linefw "LOSE 6 TIMES TO ANYONE!"
	linefw "YOU'RE TRYING TO HUMILIATE ME,"
	linefw "AREN'T YOU, KID?!"
	done

Text12d1:
	text "WHAT DOES THAT MAKE IT,"
	linefw "9 TIMES YOU'VE BEATEN ME?!"
	linefw "I FEEL SO DISAPPOINTED!"
	linefw "CRAP!"
	done

Text12d2:
	text "AGAIN, THE KID WON..."
	linefw "AND IN FRONT OF EVERYONE TO BOOT..."
	linefw "I DON'T EVEN THINK I'M GOING TO"
	linefw "KEEP TRACK OF YOUR WINS ANY MORE."
	linefw "BECAUSE OF THIS, PLEASE TAKE"
	linefw "IT EASY ON ME NEXT TIME!"
	done

Text12d3:
	text "I AM THE SOMEHOW-RED"
	linefw "VERSION OF IMAKUNI!"
	linefw "YOU MIGHT BE EXPECTING ME TO BE THE"
	linefw "SAME AS THAT BLACK IMAKUNI? FELLOW."
	linefw "BUT THAT GUY'S A FAKE FOR SURE!"
	linefw "I'M THE REAL DEAL, KID!"
	linefw "HEY, WHY DON'T WE CARD POP!?"
	linefw "C'MON!"
	linefw "EVEN IF YOU DON'T WANT TO, KID,"
	linefw "LET'S CARD POP!"
	done

Text12d4:
	text "I GOT A RARE CARD!"
	linefw "LET'S SAVE OUR DATA NOW!"
	done

Text12d5:
	text "THANK YOU VERY MUCH, I'VE BEEN"
	linefw "WANTING THIS CARD BADLY!"
	linefw "YOU HAVE MY THANKS."
	linefw "I'LL BE SURE TO REMEMBER YOU, KID!"
	done

Text12d6:
	text "HMM?"
	linefw "HOW MAY I HELP YOU?"
	linefw "OH? WHO AM I, YOU ASK?"
	linefw "DON'T YOU KNOW ME?"
	linefw "'TIS I, THE SUPER MUSICAL STAR,"
	linefw "IMAKUNI?!"
	linefw "WHAT? YOU SAY IMAKUNI? WEARS BLACK?"
	linefw "NO WAY! DON'T YOU KNOW ANYTHING?"
	linefw "I'M THE ONE AND ONLY IMAKUNI?,"
	linefw "AND YOU CAN CLEARLY SEE I WEAR RED!"
	linefw "YOU'RE SAYING YOU'VE SEEN A BLACK"
	linefw "VERSION OF ME? PREPOSTEROUS!"
	linefw "I'M RED!"
	linefw "DON'T TRY AND DISPUTE THE FACTS!"
	linefw "WHAT?"
	linefw "WOULD I LIKE TO PLAY CARDS WITH YOU?"
	linefw "SURE THING KID! I'M JUST ITCHING"
	linefw "TO CATCH 'EM ALL!"
	done

Text12d7:
	text "I'M RED IMAKUNI?,"
	linefw "THE ROUGE ROGUE OF STARDOM!"
	linefw "OH, I REMEMBER YOU."
	linefw "WHAT DO YOU WANT?"
	linefw "DID YOU COME TO WATCH ME DANCE?"
	linefw "OH, OR ARE YOU AFTER AN AUTOGRAPH?"
	linefw "EH? IT'S NOT LIKE THAT AT ALL?"
	linefw "YOU JUST WANT TO PLAY CARDS?"
	linefw "ALRIGHTY!"
	linefw "I'M READY TO CATCH 'EM ALL!"
	done

Text12d8:
	text "WOULD YOU LIKE TO DUEL RED IMAKUNI??"
	done

Text12d9:
	text "6 PRIZE CARDS!"
	linefw "I DON'T LIKE SHORT DUELS!"
	done

Text12da:
	text "WHAT, NOW YOU DON'T WANT TO PLAY?"
	linefw "WHY NOT?!"
	linefw "I WAS JUST GETTING PRIMED AND"
	linefw "READY TO CATCH 'EM ALL!"
	linefw "GEEZ, IT CERTAINLY IS BORING HERE."
	linefw "IT'S NOT EASY BEING RED..."
	done

Text12db:
	text "AND THAT'S THE GAME!"
	linefw "THOUGH I'M NOT TOO SATISFIED."
	linefw "YOU STOP FEELING THE THRILL OF"
	linefw "VICTORY WHEN YOU WIN SO MUCH."
	linefw "ANYWAY, I'M OFF."
	linefw "KEEP AN EYE OUT FOR MY REDNESS!"
	done

Text12dc:
	text "I'M MORE DANGEROUS THAN YOU THINK!"
	linefw "YOU DIDN'T THINK YOU COULD LOSE, EH?"
	linefw "HUH? WHAT? DID I LOSE? YOU'RE SAYING"
	linefw "YOU BEAT ME 3 TIMES NOW?"
	linefw "WELL I HAD NO IDEA! TAKE THIS CARD."
	linefw "IT'S BEEN WORTHLESS TO ME!"
	done

Text12dd:
	text "SEE YA, KID. I'LL LEAVE YOU, THOUGH"
	linefw "MY ONLY CRIME SIN IS BEING CRIMSON!"
	done

Text12de:
	text "OOH, I'M A BEAST!"
	linefw "SEE YA, I'M GONNA TAKE OFF..."
	linefw "EH? WHAT? I LOST? AND THIS IS THE"
	linefw "SIXTH TIME I LOST TO YOU?"
	linefw "WHY DO I LOSE SO MUCH?! I DON'T GET"
	linefw "IT! TAKE THIS AS A REWARD, THOUGH."
	done

Text12df:
	text "NEXT TIME YOU SEE ME, I'LL BE EVEN"
	linefw "REDDER AND READIER THAN BEFORE!"
	done

Text12e0:
	text "WELL IT WAS A GOOD EFFORT ON YOUR"
	linefw "PART. WANT TO TRY AGAIN?"
	linefw "EH? YOU WON AGAIN! WHY WHY WHY?!"
	linefw "AND THAT'S YOUR NINTH WIN?"
	linefw "WELL I GUESS I'M HAPPY TO HAVE YOU"
	linefw "REMINDING ME WHAT IT'S LIKE TO LOSE."
	done

Text12e1:
	text "SEE YA AROUND. I'M OFF TO TRAVEL"
	linefw "AND BECOME EVEN REDDER!"
	done

Text12e2:
	text "I'M GOING TO TAKE YOU OUT AND"
	linefw "PUT YOU ON THE CLEARANCE RACK!"
	linefw "EH? I LOST?"
	linefw "WELL...TAKE THIS, THEN."
	done

Text12e3:
	text "WHEN YOU SEE ME NEXT,"
	linefw "I'LL BE EVEN REDDER THAN I AM NOW!"
	linefw "I'M OFF TO CONTINUE MY VACATION!"
	linefw "I JUST LOVE TRAVELING. SEE YOU!"
	done

Text12e4:
	text "HELLO!"
	linefw "WELCOME TO THE BATTLE CENTER!"
	linefw "YOU MAY WIN BOOSTER PACKS HERE FOR"
	linefw "PARTICIPATING IN DUELS WITH FRIENDS."
	linefw "YOU WILL WIN 3 BOOSTER PACKS FOR A"
	linefw "VICTORY AND 1 PACK FOR A LOSS."
	done

Text12e5:
	text "WOULD YOU LIKE TO DUEL A FRIEND?"
	done

Text12e6:
	text "THANK YOU FOR USING THE"
	linefw "BATTLE CENTER."
	done

Text12e7:
	text "WE HOPE TO SEE YOU AGAIN!"
	done

Text12e8:
	text "CONGRATULATIONS!"
	linefw "YOU'VE WON THE LINK BATTLE!"
	linefw "YOU GET THESE THREE BOOSTER PACKS"
	linefw "FOR WINNING, ", "<RAMNAME>", "!"
	done

Text12e9:
	text "AHH, BAD LUCK, I SEE..."
	linefw ""
	linefw "YOU'RE STILL AWARDED WITH 1"
	linefw "BOOSTER PACK, THOUGH, ", "<RAMNAME>", "!"
	done

Text12ea:
	text "CONGRATULATIONS, ", "<RAMNAME>", "!"
	linefw "YOU'VE WON 50 LINK BATTLES!"
	linefw "FOR YOUR ACCOMPLISHMENT,"
	linefw "YOU'RE AWARDED THIS COIN!"
	done

Text12eb:
	text "WE LOOK FORWARD TO YOUR FUTURE"
	linefw "DUELS IN THE BATTLE CENTER!"
	done

Text12ec:
	text "CONGRATULATIONS, ", "<RAMNAME>", "!"
	linefw "YOU'VE WON 100 LINK BATTLES!"
	linefw "FOR YOUR ACCOMPLISHMENT,"
	linefw "YOU'RE AWARDED THIS COIN!"
	done

Text12ed:
	text "GRASS ENERGY"
	done

Text12ee:
	text "BASIC ENERGY CARD"
	linefw ""
	linefw "THIS CARD PROVIDES 1 ", "<GRASS>", " ENERGY."
	done

Text12ef:
	text "FIRE ENERGY"
	done

Text12f0:
	text "BASIC ENERGY CARD"
	linefw ""
	linefw "THIS CARD PROVIDES 1 ", "<FIRE>", " ENERGY."
	done

Text12f1:
	text "WATER ENERGY"
	done

Text12f2:
	text "BASIC ENERGY CARD"
	linefw ""
	linefw "THIS CARD PROVIDES 1 ", "<WATER>", " ENERGY."
	done

Text12f3:
	text "ELECTRIC ENERGY"
	done

Text12f4:
	text "BASIC ENERGY CARD"
	linefw ""
	linefw "THIS CARD PROVIDES 1 ", "<LIGHTNING>", " ENERGY."
	done

Text12f5:
	text "FIGHTING ENERGY"
	done

Text12f6:
	text "BASIC ENERGY CARD"
	linefw ""
	linefw "THIS CARD PROVIDES 1 ", "<FIGHTING>", " ENERGY."
	done

Text12f7:
	text "PSYCHIC ENERGY"
	done

Text12f8:
	text "BASIC ENERGY CARD"
	linefw ""
	linefw "THIS CARD PROVIDES 1 ", "<PSYCHIC>", " ENERGY."
	done

Text12f9:
	text "DOUBLE COLORLESS ENERGY"
	done

Text12fa:
	text "SPECIAL ENERGY CARD"
	linefw ""
	linefw "THIS CARD PROVIDES 2 ", "<COLORLESS>"
	linefw "ENERGY. IT DOES NOT COUNT AS A"
	linefw "BASIC ENERGY CARD."
	done

Text12fb:
	text "POTION ENERGY"
	done

Text12fc:
	text "SPECIAL ENERGY CARD"
	linefw ""
	linefw "IF YOU PLAY THIS CARD FROM YOUR"
	linefw "HAND, REMOVE 1 DAMAGE COUNTER FROM"
	linefw "THE POKÉMON YOU ATTACH IT TO, IF IT"
	linefw "HAS ANY."
	done

Text12fd:
	text "THIS CARD PROVIDES 1 ", "<COLORLESS>", " ENERGY."
	done

Text12fe:
	text "FULL HEAL ENERGY"
	done

Text12ff:
	text "SPECIAL ENERGY CARD"
	linefw ""
	linefw "IF YOU PLAY THIS CARD FROM YOUR"
	linefw "HAND, THE POKÉMON YOU ATTACH IT TO"
	linefw "IS NO LONGER ASLEEP, CONFUSED,"
	linefw "PARALYZED, OR POISONED."
	done

Text1300:
	text "RAINBOW ENERGY"
	done

Text1301:
	text "SPECIAL ENERGY CARD"
	linefw ""
	linefw "THIS CARD PROVIDES ONE TYPE OF"
	linefw "BASIC ENERGY AT ANY GIVEN TIME."
	linefw "THE POKÉMON THIS CARD IS ATTACHED TO"
	linefw "RECEIVES 10 DAMAGE ON THE TURN"
	linefw "IT WAS ATTACHED."
	done
