Text0ed6:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING BATTLING TEAM GR?"
	linefw "I'VE RECENTLY COME UPON AN UNUSUAL"
	linefw "CARD CALLED 'BILL'S COMPUTER'."
	linefw "IT SEEMS THAT YOU CANNOT USE IT"
	linefw "IN CARD BATTLES..."
	linefw "IF YOU'RE INTERESTED IN IT, I COULD"
	linefw "USE A DARK DRAGONITE Lv33 CARD."
	linefw "WHAT DO YOU SAY?"
	linefw "WOULD YOU LIKE TO TRADE?"
	done

Text0ed7:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING YOUR POKÉMON CARDS?"
	linefw "WOULD YOU LIKE TO TRADE ME FOR THIS"
	linefw "BILL'S COMPUTER CARD?"
	linefw "I'LL GIVE IT TO YOU IN EXCHANGE FOR"
	linefw "A DARK DRAGONITE Lv33 CARD."
	linefw "DO YOU FIND THAT TRADE AGREEABLE?"
	done

Text0ed8:
	text "I APPRECIATE YOUR ENTHUSIASM"
	linefw "TOWARD TRADING CARDS WITH ME."
	linefw "HOWEVER, YOU DON'T SEEM TO OWN A"
	linefw "DARK DRAGONITE Lv33 CARD."
	linefw "PERHAPS WE CAN TRADE LATER"
	linefw "IF YOU HAPPEN TO FIND ONE..."
	done

Text0ed9:
	text "ALL OF YOUR DARK DRAGONITE Lv33"
	linefw "CARDS ARE IN YOUR DECKS, IT SEEMS."
	linefw "YOU SIMPLY CANNOT TRADE CARDS YOU'RE"
	linefw "USING TO PLAY THE GAME WITH."
	linefw "MAYBE WE CAN TRADE CARDS LATER..."
	done

Text0eda:
	text "OH, THANK YOU VERY MUCH!"
	linefw "LET'S TRADE IMMEDIATELY..."
	done

Text0edb:
	text "<RAMNAME>", " TRADED A DARK DRAGONITE"
	linefw "CARD FOR A BILL'S COMPUTER CARD!"
	done

Text0edc:
	text "THANK YOU VERY MUCH FOR THIS"
	linefw "DARK DRAGONITE Lv33 CARD."
	linefw "I BELIEVE I'VE FINALLY COLLECTED ALL"
	linefw "OF THE CARDS I'VE BEEN LOOKING FOR."
	linefw "YOU HAVE MY UTMOST GRATITUDE"
	linefw "FOR HELPING ME ACCOMPLISH THIS."
	linefw "I CAN FINALLY BATTLE OTHERS AS WELL"
	linefw "AS TRADE CARDS NOW."
	done

Text0edd:
	text "HELLO, ", "<RAMNAME>", "."
	linefw "WELCOME TO MY HOUSE."
	linefw "I'M NOT LOOKING FOR ANY PARTICULAR"
	linefw "CARDS AT THE MOMENT, I'M AFRAID."
	linefw "IN THE MEANTIME, FEEL FREE TO READ"
	linefw "THE BOOKS I WROTE IN MY LIBRARY."
	linefw "LOTS OF TEAM GR MEMBERS STOP BY"
	linefw "TO READ MY PUBLICATIONS."
	linefw "THE INFORMATION I SHARE WILL SURELY"
	linefw "AID YOU, TOO, IN FIGHTING TEAM GR."
	done

Text0ede:
	text "OH, ", "<RAMNAME>", "?"
	linefw "DID YOU DECIDE TO VISIT TODAY, TOO?"
	linefw "MR. ISHIHARA HAS AN AWE-INSPIRING"
	linefw "LIBRARY OF BOOKS ABOUT CARD BATTLES."
	linefw "AS A TOP EXECUTIVE, I NEED TO STUDY"
	linefw "NEW AND INTERESTING DUEL STRATEGIES."
	linefw "OH, IS THAT WHY YOU'RE HERE, TOO?"
	linefw "...WELL, THAT'S FINE."
	linefw "LET'S HAVE A REMATCH SOMETIME SOON."
	linefw "I WON'T LOSE NEXT TIME!"
	linefw "HOWEVER, IT'S BETTER TO DO IT AT"
	linefw "GR CASTLE THAN RIGHT HERE..."
	linefw "I'LL SEE YOU LATER, ", "<RAMNAME>", "."
	done

Text0edf:
	text "AS ALWAYS, THANK YOU KINDLY,"
	linefw "MR. ISHIHARA..."
	done

Text0ee0:
	text "NO, NO. I'M JUST HAPPY MY BOOKS"
	linefw "COULD BE OF USE."
	done

Text0ee1:
	text "PLEASE PARDON ME,"
	linefw "MR. ISHIHARA..."
	done

Text0ee2:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING YOUR POKÉMON CARDS?"
	linefw "THANKS TO YOU, I'VE COLLECTED ALL OF"
	linefw "THE CARDS I'VE WANTED AT LAST."
	linefw "THUS, I NO LONGER NEED TO"
	linefw "TRADE ANY MORE!"
	linefw "NOW I CAN USE MY CARDS TO HAVE SOME"
	linefw "EXCITING BATTLES."
	linefw "WHAT DO YOU SAY, ", "<RAMNAME>", "?"
	linefw "WOULD YOU LIKE TO BATTLE ME?"
	done

Text0ee3:
	text "GOOD AFTERNOON, ", "<RAMNAME>", "."
	linefw "ARE YOU ENJOYING YOUR POKÉMON CARDS?"
	linefw "I'VE BEEN HAVING A GREAT TIME"
	linefw "CHALLENGING DIFFERENT PLAYERS."
	linefw "THE MORE I BATTLE, THE MORE I GET TO"
	linefw "UNDERSTAND ALL OF THE GAME'S CARDS."
	linefw "WHAT DO YOU SAY, ", "<RAMNAME>", "?"
	linefw "WOULD YOU LIKE TO DUEL ME?"
	done

Text0ee4:
	text "WOULD YOU LIKE TO DUEL MR. ISHIHARA?"
	done

Text0ee5:
	text "THANK YOU VERY MUCH, ", "<RAMNAME>", "."
	linefw "I HOPE OUR BATTLE IS MOST ENJOYABLE."
	linefw "IF YOU WOULD OBLIGE,"
	linefw "WE SHALL PLAY WITH 6 PRIZE CARDS."
	done

Text0ee6:
	text "IS THAT SO?"
	linefw "WELL, THAT'S A BIT OF A LETDOWN."
	linefw "PERHAPS WE CAN HAVE A BATTLE"
	linefw "NEXT TIME..."
	done

Text0ee7:
	text "INDEED, ", "<RAMNAME>", "."
	linefw "IT SEEMS THAT I HAVE LOST THE MATCH."
	linefw "HOWEVER, IT WAS A TRULY FUN BATTLE."
	linefw "HERE, TAKE THIS AS YOUR PRIZE."
	done

Text0ee8:
	text "PLEASE USE THE CARDS YOU JUST"
	linefw "RECEIVED TO MAKE A NEW DECK."
	linefw "I'LL BE MORE THAN HAPPY TO CHALLENGE"
	linefw "YOUR NEW CREATION, TOO!"
	linefw "IN ANY CASE, ", "<RAMNAME>", ","
	linefw "YOU'RE WELCOME TO RETURN ANY TIME."
	done

Text0ee9:
	text "AHHH..."
	linefw "SO I HAVE WON THE MATCH."
	linefw "THAT WAS QUITE THE ENJOYABLE DUEL,"
	linefw "<RAMNAME>", "!"
	linefw "BY ALL MEANS,"
	linefw "YOU'RE WELCOME TO RETURN ANY TIME."
	done

Text0eea:
	text "HA-HAH! I SEE..."
	linefw "CLEVER...."
	done

Text0eeb:
	text "WHAT? I'M LEARNING SOME NEW"
	linefw "STRATEGIES FOR POKÉMON CARD DUELS."
	linefw "THE BOOKS MR. ISHIHARA HAS WRITTEN"
	linefw "ARE FILLED WITH GREAT TIPS."
	linefw "YOU OUGHT TO GIVE 'EM A READ."
	linefw "THEY'LL REALLY RAMP UP YOUR GAME."
	done

Text0eec:
	text "THIS IS AUTO DECK MACHINE 1!"
	done

Text0eed:
	text "WOULD YOU LIKE TO MAKE A DECK?"
	done

Text0eee:
	text "THIS IS AUTO DECK MACHINE 2!"
	done

Text0eef:
	text "WOULD YOU LIKE TO MAKE A DECK?"
	done

Text0ef0:
	text "THIS IS THE DECK RECORD MACHINE!"
	done

Text0ef1:
	text "USE THE DECK RECORD MACHINE?"
	done

Text0ef2:
	text "THIS AUTOMATIC DECK MACHINE WORKS"
	linefw "WONDERS!"
	linefw "WHEN YOU HAVE ALL THE CARDS NEEDED"
	linefw "TO MAKE A DECK,"
	linefw "THIS MACHINE WILL AUTOMATICALLY"
	linefw "CREATE THE DECK FOR YOU!"
	linefw "THE MORE OPPONENTS YOU DEFEAT, THE"
	linefw "MORE DECKS THE MACHINE CAN BUILD."
	linefw "COME REVISIT IT AFTER DUELLING"
	linefw "SOME NEW OPPONENTS!"
	done

Text0ef3:
	text "CONGRATULATIONS, ", "<RAMNAME>", "!"
	linefw "TEAM GR WAS FINALLY DEFEATED!"
	linefw "WAS THIS AUTO DECK MACHINE HELPFUL?"
	done

Text0ef4:
	text "HEY, ", "<RAMNAME>", ". THIS DEVICE IS"
	linefw "IS OUR DECK RECORD MACHINE."
	linefw "IT SAVES RECORDS FOR ANY DECKS THAT"
	linefw "YOU HAVE MADE YOURSELF."
	linefw "ONCE RECORDED, A DECK CAN BE REBUILT"
	linefw "AT ANY TIME YOU LIKE,"
	linefw "EVEN IF SOME CARDS ARE BEING USED BY"
	linefw "ANOTHER DECK YOU CURRENTLY HAVE."
	linefw "IT'S ALSO LINKED TO YOUR MINI-COM,"
	linefw "SO YOU CAN USE IT WHENEVER YOU LIKE!"
	done

Text0ef5:
	text "TEAM GREAT ROCKET SEEMS TO"
	linefw "HAVE COME FROM ANOTHER ISLAND."
	linefw "THEY SUPPOSEDLY USE CARDS THAT EVEN"
	linefw "WE HAVE NOT SEEN BEFORE."
	linefw "I WONDER WHERE ON EARTH THEY'VE"
	linefw "COME FROM?"
	done

Text0ef6:
	text "HEY, ", "<RAMNAME>", ". HOW ARE YOU"
	linefw "FARING ON GR ISLAND?"
	linefw "RUMOR HAS IT THAT THEY'RE DEVELOPING"
	linefw "NEW RULES FOR POKÉMON CARD DUELS."
	linefw "I'D LIKE TO VISIT GR ISLAND"
	linefw "SOMETIME, MYSELF."
	done

Text0ef7:
	text "THANKS TO YOUR FIELD RECORDS, WE"
	linefw "MAY STUDY LOTS OF TEAM GR'S DECKS."
	linefw "PERHAPS WE CAN GO TO GR ISLAND SOON"
	linefw "SINCE TEAM GR IS GOOD NOW."
	done

Text0ef8:
	text "HEY, ", "<RAMNAME>", "!"
	linefw "DID YOU KNOW?"
	linefw "DR. MASON INVENTED THE AUTOMATIC"
	linefw "DECK BUILDING MACHINE."
	linefw "EVEN IF YOU DON'T HAVE ALL OF THE"
	linefw "CARDS NEEDED, IT WILL BUILD A DECK."
	linefw "MISSING CARDS WILL BE REPLACED BY"
	linefw "OTHERS IN YOUR COLLECTION."
	linefw "HOWEVER, YOU MUST HAVE ENOUGH CARDS"
	linefw "AVAILABLE TO MAKE A FULL DECK."
	done

Text0ef9:
	text "I'M GLAD YOU'VE COME,"
	linefw "<RAMNAME>", "."
	linefw "I'M PROUD TO REPORT THAT OUR NEWEST"
	linefw "AUTOMATIC DECK MACHINE IS COMPLETED!"
	linefw "OUR IMPROVED AUTO DECK MACHINE 2 CAN"
	linefw "ASSEMBLE DECKS WITH TEAM GR'S CARDS."
	linefw "COME BACK AND SEE WHAT DECKS YOU CAN"
	linefw "MAKE WHEN YOU COLLECT NEW CARDS."
	done

Text0efa:
	text "YOU DID IT, ", "<RAMNAME>", "!"
	linefw "YOU'VE DEFEATED TEAM GR AT LAST!"
	linefw "BUT WE'RE NOT FINISHED JUST YET."
	linefw "YOU CAN STILL USE OUR DECK MACHINE!"
	linefw "YOU SHOULD TRY OUT SOME OF THE DECKS"
	linefw "THAT HAVE BEEN COLLECTED HERE."
	done

Text0efb:
	text "OH, THANK HEAVENS!"
	linefw "YOU'RE SAFE, ", "<RAMNAME>", "!"
	linefw "IT'S AWFUL! A GROUP CALLED TEAM"
	linefw "GREAT ROCKET, OR ”TEAM GR”, INVADED!"
	linefw "THIS ISLAND'S CARD CLUBS WERE"
	linefw "ATTACKED ONE BY ONE!"
	linefw "EVERYBODY'S CARDS WERE STOLEN, AND"
	linefw "MANY CLUB MEMBERS WERE KIDNAPPED!"
	linefw "TEAM GR STOLE THE LEGENDARY POKÉMON"
	linefw "CARDS FROM THE GRAND MASTERS, TOO!"
	linefw "PLEASE HELP US GET THE CARDS BACK"
	linefw "FROM THOSE VILLAINS!"
	done

Text0efc:
	text "WILL YOU ACCEPT DR. MASON'S REQUEST?"
	done

Text0efd:
	text "I BEG YOU, ", "<RAMNAME>", "!"
	linefw "WE NEED YOUR HELP!"
	linefw "RONALD CAN'T DO IT ALONE."
	linefw "PLEASE, ", "<RAMNAME>", "!"
	done

Text0efe:
	text "THANK YOU, ", "<RAMNAME>", "!"
	done

Text0eff:
	text "YOU CAN HAVE THIS MINI COMPUTER"
	linefw "AS WELL!"
	done

Text0f00:
	text "YOU'VE RECEIVED A MINI-COM!"
	done

Text0f01:
	text "THAT MINI-COMPUTER IS A HANDY TOOL"
	linefw "THAT HELPS ORGANIZE YOUR CARDS."
	linefw "IT CAN LIST YOUR CARD COLLECTION,"
	linefw "CHECK MAIL, AND EVEN RECORD DECKS!"
	linefw "ALL RECORDED DECKS ARE SENT TO OUR"
	linefw "LAB'S DECK RECORD MACHINES, TOO."
	linefw "I'M COUNTING ON YOU TO GET EVERY-"
	linefw "ONE'S CARDS BACK, ", "<RAMNAME>", "!"
	done

Text0f02:
	text "SINCE THEY TOOK YOUR CARDS, YOU'LL"
	linefw "NEED A REPLACEMENT DECK."
	linefw "THAT WAY YOU CAN USE YOUR DECK TO"
	linefw "BATTLE WITH OTHERS."
	linefw "HERE, TAKE THIS DECK. LUCKILY,"
	linefw "IT WASN'T STOLEN BY TEAM GR!"
	done

Text0f03:
	text "YOU'VE RECEIVED A STARTER DECK!"
	done

Text0f04:
	text "<RAMNAME>", ", WAIT!"
	done

Text0f05:
	text "BE CAREFUL!"
	linefw "TEAM GR IS STRONG!"
	linefw "ARE YOU SURE YOU KNOW THE RULES OF"
	linefw "THE POKÉMON TRADING CARD GAME?"
	linefw "YOU CAN LEARN THE BASICS FROM SAM"
	linefw "AT THE TABLE TO YOUR LEFT."
	linefw "FOR MORE ADVANCED INFORMATION,"
	linefw "VISIT AARON IN OUR TRAINING ROOM."
	done

Text0f06:
	text "YOUR CHALLENGE MACHINE WIN STREAK"
	linefw "DATA WAS BROKEN."
	linefw "START A NEW STREAK ON THE MACHINE"
	linefw "AND SEE HOW HIGH YOU CAN MAKE IT!"
	done

Text0f07:
	text "SINCE YOU'VE GOTTEN 50 CONSECUTIVE"
	linefw "WINS, YOU GET THIS SPECIAL COIN."
	done

Text0f08:
	text "DO YOU LIKE IT? PLEASE USE IT"
	linefw "FOR YOUR FUTURE CARD BATTLES!"
	done

Text0f09:
	text "YOU MUST FIND ALL OF THE MEMBERS"
	linefw "OF TEAM GR."
	linefw "RONALD AND THE OTHERS NEED YOUR"
	linefw "HELP. SEARCH ALL OF THE CLUBS!"
	done

Text0f0a:
	text "THERE SEEM TO BE 5 MEMBERS OF"
	linefw "TEAM GR STILL ON THE ISLAND."
	linefw "THE HIGHEST-RANKING MEMBER IS"
	linefw "IN CONTROL OF THE POKÉMON DOME."
	linefw "THE OTHER FOUR, NUMBERED GR No.1"
	linefw "TO GR No.4, HAVE SEIZED THE CLUBS!"
	linefw "IF YOU CAN DEFEAT THEM ALL, I'M SURE"
	linefw "THIS CONFUSION WILL DIE DOWN."
	linefw "PLEASE DO SOMETHING, ", "<RAMNAME>", "!"
	done

Text0f0b:
	text "ACCORDING TO RONALD, TEAM GR HAS"
	linefw "ABDUCTED SOME OF THE CLUB MASTERS."
	linefw "SUPPOSEDLY, EVEN THE GRAND MASTERS"
	linefw "HAVE BEEN TAKEN TO GR ISLAND."
	linefw "YOU'VE GOT TO TRAVEL TO THE ISLAND"
	linefw "AND FREE THOSE WHO ARE IMPRISONED!"
	linefw "PLEASE DO YOUR BEST, ", "<RAMNAME>", "."
	done

Text0f0c:
	text "OH, ", "<RAMNAME>", "!"
	linefw "I HAVE NEWS!"
	linefw "IT SEEMS TEAM GR IS USING A NEW KIND"
	linefw "OF CARD: DARK EVOLUTION CARDS."
	linefw "FOR EXAMPLE, DARK CHARMELEON IS THE"
	linefw "DARK EVOLUTION OF CHARMANDER."
	linefw "BASIC POKÉMON CAN EVOLVE INTO EITHER"
	linefw "THEIR NORMAL OR DARK VERSIONS."
	linefw "THERE ARE EVEN STAGE 2 DARK"
	linefw "EVOLUTIONS OUT THERE!"
	linefw "REMEMBER, THOUGH, THAT DARK POKÉMON"
	linefw "CAN ONLY EVOLVE BY DARK EVOLUTION."
	linefw "BE CAREFUL! MAKE SURE YOUR EVOLUTION"
	linefw "CARDS ARE COMPATABLE WITH ONE OTHER!"
	done

Text0f0d:
	text "HOW ARE YOU, ", "<RAMNAME>", "?"
	linefw "ARE YOU REGULARLY READING YOUR MAIL?"
	linefw "YOU CAN READ A LOT OF INFORMATION"
	linefw "ABOUT TEAM GR'S DECKS IF YOU DO!"
	linefw "THE KNOWLEDGE COULD SAVE YOU FROM"
	linefw "UNPLEASANT SURPRISES MID-DUEL."
	linefw "YOU MIGHT ALSO BE ABLE TO CREATE A"
	linefw "SPECIAL DECK TO COUNTER THE FOE'S."
	linefw "FIGHT ON, ", "<RAMNAME>", "!"
	linefw "WITH PERSEVERENCE, YOU'LL PREVAIL!"
	done

Text0f0e:
	text "OOH, ", "<RAMNAME>", "."
	linefw "I HAVE GOOD NEWS!"
	linefw "YOUR FIGHT AGAINST TEAM GR IS"
	linefw "IN ITS FINAL STAGES!"
	linefw "DON'T RUSH YOURSELF, THOUGH."
	linefw "YOU MAY ERR IF YOU HURRY TOO MUCH!"
	linefw "TAKE SOME TIME TO VISIT THE CLUBS"
	linefw "AND COLLECT SOME NEW CARDS."
	linefw "THE LARGER YOUR COLLECTION IS, THE"
	linefw "TOUGHER YOU CAN MAKE YOUR DECKS."
	linefw "DO YOUR BEST, ", "<RAMNAME>", "."
	linefw "YOUR GOAL IS IN SIGHT!"
	done

Text0f0f:
	text "<RAMNAME>", "! CONGRATULATIONS!!"
	linefw "TEAM GR WAS DEFEATED AT LAST!"
	linefw "HOWEVER..."
	linefw "I WON'T HOLD A GRUDGE AGAINST THEM!"
	linefw "ANYONE WHO LOVES POKÉMON CARDS"
	linefw "WILL NEVER BE AN ENEMY TO ME."
	linefw "THEY'RE NOW A PART OF OUR"
	linefw "POKÉMON CARD FAMILY, TOO."
	linefw "I WILL DO MY BEST TO KEEP TEACHING"
	linefw "ALL WHO LOVE POKÉMON CARDS."
	linefw "NOW GO OUT THERE AND DO YOUR BEST"
	linefw "AS A CARD MASTER, ", "<RAMNAME>", "!"
	done

Text0f10:
	text "AH, BACK SO SOON! HAVE YOU ALREADY"
	linefw "TRIED MY NEW CHALLENGE MACHINE?"
	linefw "I'VE PUT A LOT OF EFFORT INTO"
	linefw "BUILDING THAT PARTICULAR MACHINE!"
	linefw "BY ALL MEANS, TRY IT OUT!"
	linefw ""
	linefw "I HOPE YOU HAVE FUN PLAYING AGAINST"
	linefw "THE MACHINE'S MANY OPPONENTS."
	done

Text0f11:
	text "OH, IT'S ", "<RAMNAME>", "!"
	linefw "DID YOU DEFEAT TEAM GR'S KING?"
	linefw "IT'S ALL BECAUSE OF MY GREAT SUPPORT"
	linefw "THAT YOU DEFEATED TEAM GR, YOU KNOW!"
	linefw "FEEL FREE TO THANK ME,"
	linefw "<RAMNAME>", "!"
	done

Text0f12:
	text "IF IT ISN'T ", "<RAMNAME>", "!"
	linefw "WAIT JUST A SEC!"
	linefw "I'VE BEEN HARD AT WORK CONSTRUCTING"
	linefw "A KILLER DECK. IT'S NEARLY DONE!"
	linefw "I'M GONNA USE IT TO CHALLENGE THE"
	linefw "GRAND MASTERS WHEN IT'S COMPLETE!"
	done

Text0f13:
	text "WHAT WOULD YOU LIKE TO DO?"
	done

Text0f14:
	text "LET'S HAVE A BATTLE WITH"
	linefw "DR. MASON'S ADVICE."
	done

Text0f15:
	text "BATTLE WITH SAM?"
	done

Text0f16:
	text "IF YOU EVER FORGET HOW TO PLAY, I'LL"
	linefw "BE HERE TO EXPLAIN AND HELP YOU OUT!"
	done

Text0f17:
	text "LET'S HAVE A PRACTICE DUEL USING"
	linefw "A SMALL DECK!"
	done

Text0f18:
	text "THERE WILL BE NO ADVICE THIS TIME,"
	linefw "AND WE'LL HAVE ONLY 2 PRIZE CARDS."
	done

Text0f19:
	text "REMEMBER, PRACTICE IS IMPORTANT!"
	done

Text0f1a:
	text "YOU HAVE A GOOD MEMORY, DON'T YOU?"
	done

Text0f1b:
	text "PLEASE USE YOUR SKILLS TO WIN"
	linefw "FUTURE DUELS."
	done

Text0f1c:
	text "IF YOU TAKE YOUR TIME AND THINK,"
	linefw "YOU'LL BE MUCH MORE VICTORIOUS."
	linefw "WHY DON'T YOU TRY PLAYING AGAINST"
	linefw "MY PRACTICE DECK FIRST?"
	done

Text0f1d:
	text "HOW WAS IT?"
	linefw "DO YOU UNDERSTAND HOW TO PLAY?"
	linefw "I HOPE YOU HAVE FUN PLAYING THE"
	linefw "POKÉMON CARD GAME WITH OTHERS!"
	done

Text0f1e:
	text "LONG TIME NO SEE, ", "<RAMNAME>", "!"
	linefw "IT'S ME, TECH SAM!"
	done

Text0f1f:
	text "HAVE A PRACTICE DUEL WITH SAM?"
	done

Text0f20:
	text "IF YOU EVER NEED TO RELEARN THE"
	linefw "BASICS, COME AT ANY TIME!"
	linefw "I'M HERE WHENEVER YOU'D LIKE TO HAVE"
	linefw "A BEGINNER'S TRAINING DUEL."
	done

Text0f21:
	text "DR. MASON, PLEASE COME OVER HERE!"
	linefw "WE'RE BEGINNING A PRACTICE DUEL."
	done

Text0f22:
	text "FIRST, REVIEW SOME BASIC INFORMATION"
	linefw "ON THE CARD GAME WITH SAM."
	done

Text0f23:
	text "ALRIGHT, ", "<RAMNAME>", "."
	linefw "WHAT WOULD YOU LIKE TO LEARN ABOUT?"
	done

Text0f24:
	text "ARE YOU FINISHED ASKING QUESTIONS?"
	done

Text0f25:
	text "ONCE FAMILIAR WITH THE LESSON,"
	linefw "YOU CAN TRY IT OUT ON YOUR OWN."
	linefw "BUT LET'S BEGIN USING THIS DECK"
	linefw "FOR PRACTICE!"
	linefw "SINCE THIS IS JUST PRACTICE, TRY TO"
	linefw "REMEMBER THE PROCESS STEP BY STEP."
	linefw "AS WE PLAY THE DUEL, I'LL GIVE YOU"
	linefw "ADVICE ON WHAT TO DO NEXT."
	linefw "PLEASE FOLLOW MY INSTRUCTIONS"
	linefw "EXACTLY FOR THIS CARD BATTLE."
	linefw "I'LL WRITE THEM DOWN FOR YOU TO"
	linefw "READ AND MEMORIZE BEFORE EACH TURN."
	linefw "IF YOU'RE READY TO PLAY,"
	linefw "THEN LET'S START THE CARD BATTLE!"
	done

Text0f26:
	text "SO, DID YOU UNDERSTAND AND"
	linefw "REMEMBER EVERYTHING FROM THE BATTLE?"
	linefw "KEEP IN MIND THAT THOSE EXACT STEPS"
	linefw "ARE ONLY GOOD FOR OUR PRACTICE DUEL."
	linefw "DON'T BE AFRAID TO TRY NEW THINGS"
	linefw "IN ACTUAL CARD BATTLES!"
	linefw "WOULD YOU LIKE TO TRY"
	linefw "AN ACTUAL GAME NOW?"
	linefw "OR, WOULD YOU RATHER PLAY"
	linefw "THE PRACTICE DUEL AGAIN?"
	done

Text0f27:
	text "PLAY A PRACTICE DUEL?"
	done

Text0f28:
	text "THEN LET'S BATTLE AGAIN!"
	done

Text0f29:
	text "IS THAT SO?"
	linefw "I'M GLAD YOU UNDERSTAND NOW."
	linefw "I HOPE YOU'LL RETURN SOMETIME"
	linefw "FOR A CARD BATTLE AGAINST ME."
	done

Text0f2a:
	text "I UNDERSTAND..."
	linefw "YOU'RE WELCOME AT ANY TIME."
	linefw "I'M ALWAYS AVAILABLE FOR A PRACTICE"
	linefw "BATTLE IF YOU'RE SO INCLINED."
	done

Text0f2b:
	text "IF YOU'D LIKE TO SAVE YOUR GAME,"
	linefw "FIRST PRESS THE START BUTTON."
	linefw "THEN, CHOOSE 'DIARY' FROM THE MENU"
	linefw "AND SELECT 'YES'."
	linefw "YOU'LL BE ABLE TO RETURN TO THE"
	linefw "GAME AT THE LAST PLACE YOU SAVED."
	linefw "YOU SHOULD SAVE YOUR GAME OFTEN!"
	done

Text0f2c:
	text "THIS IS THE CHALLENGE MACHINE"
	linefw "THAT DR. MASON RECENTLY COMPLETED!"
	linefw "THE CHALLENGE MACHINE CAN BE USED"
	linefw "TO SIMULATE POKÉMON CARD BATTLES."
	linefw "THE RULES ARE SIMPLE."
	linefw ""
	linefw "YOU WILL CHALLENGE 5 DECKS IN THE"
	linefw "MACHINE WITH 1 OF YOUR OWN DECKS."
	linefw "YOU'LL CLEAR THE CHALLENGE IF YOUR"
	linefw "1 DECK DEFEATS 5 OF THE MACHINE'S."
	linefw "SEE HOW MANY CUMULATIVE VICTORIES"
	linefw "YOU CAN EARN AS A CHALLENGER!"
	linefw "GO ON AND MAKE THE BEST DECK"
	linefw "YOU CAN, ", "<RAMNAME>", "!"
	done

Text0f2d:
	text "I BELIEVE THERE ARE 8 DIFFERENT"
	linefw "CARD CLUBS ON THIS ISLAND:"
	linefw "FIGHTING, WATER, LIGHTNING, GRASS,"
	linefw "PSYCHIC, FIRE, ROCK, AND SCIENCE."
	linefw "HOWEVER, THEY SEEM TO BE CLOSED DUE"
	linefw "TO TEAM GR'S ATTACKS..."
	done

Text0f2e:
	text "IS IT TRUE THAT TEAM GR HAS"
	linefw "FINALLY BEEN DEFEATED?"
	linefw "JUST AS I THOUGHT!"
	linefw "THAT'S AMAZING NEWS!"
	done

Text0f2f:
	text "WHEN YOU WIN CARD DUELS, YOU'LL"
	linefw "BE REWARDED WITH BOOSTER PACKS."
	linefw "EACH BOOSTER PACK HAS 10 CARDS."
	linefw ""
	linefw "THE CARDS YOU CAN RECEIVE DEPEND ON"
	linefw "THE TYPE OF BOOSTER PACK."
	linefw "EACH BOOSTER PACK WILL CONTAIN"
	linefw "RANDOM CARDS FROM ITS SERIES."
	linefw "SINCE TEAM GR TOOK ALL OF YOUR"
	linefw "CARDS, YOU'LL HAVE TO GET NEW ONES."
	linefw "IF YOU DON'T WIN DUELS, YOU'LL NEVER"
	linefw "REBUILD YOUR COLLECTION!"
	done

Text0f30:
	text "CONGRATULATIONS, ", "<RAMNAME>", ","
	linefw "ON YOUR VICTORY OVER TEAM GR!"
	linefw "WE'VE GOTTEN MORE BOOSTER PACKS TO"
	linefw "CELEBRATE! TEAM GR GOT SOME, TOO!"
	linefw "POKÉMON CARD BATTLES SHOULD BE"
	linefw "A LOT MORE FUN FOR EVERYONE NOW."
	done

Text0f31:
	text "THE ROOM TO THE RIGHT HOLDS THE "
	linefw "LAB'S COMPUTERS AND DECK MACHINES."
	linefw "THESE INCLUDE OUR DECK RECORD"
	linefw "AND AUTOMATIC DECK MACHINES."
	linefw "THE AUTO DECK MACHINES ARE FOR"
	linefw "PLAYERS WHO HAVE SOME EXPERIENCE."
	linefw "IF YOU'RE LOOKING FOR TRAINING, TRY"
	linefw "THE ROOM ON THE LEFT."
	linefw "DR. MASON CREATED IT FOR PLAYERS NEW"
	linefw "TO THE POKÉMON TRADING CARD GAME."
	linefw "YOU OUGHT TO TRY IT OUT AT LEAST"
	linefw "ONCE, THOUGH!"
	done

Text0f32:
	text "AT LAST,"
	linefw "THE GR KING HAS BEEN DEFEATED."
	linefw "WE'VE GATHERED THE DETAILS ABOUT THE"
	linefw "DECKS YOU'VE FOUGHT IN YOUR BATTLES."
	linefw "WE'VE ALREADY UPLOADED THAT INFO"
	linefw "INTO OUR AUTO DECK MACHINE."
	linefw "SINCE THE POKÉMON CARD GAME IS SO"
	linefw "DEEP, OUR STUDIES WILL NEVER END."
	done

Text0f33:
	text "IN ORDER TO DO ANYTHING,"
	linefw "POKÉMON MUST HAVE ENERGY CARDS."
	linefw "IF NO ENERGY CARDS ARE ATTACHED,"
	linefw "THE POKÉMON CAN'T ATTACK OR RETREAT."
	linefw "THERE ARE 7 DIFFERENT TYPES OF"
	linefw "ENERGY CARDS:"
	linefw "FIGHTING, FIRE, GRASS, ELECTRIC,"
	linefw "PSYCHIC, WATER, AND COLORLESS."
	linefw "THE TYPE OF ENERGY REQUIRED FOR EACH"
	linefw "ATTACK DEPENDS ON THE POKÉMON."
	linefw "BE SURE TO LEARN WHICH ENERGY TYPES"
	linefw "YOUR POKÉMON NEED TO ATTACK!"
	done

Text0f34:
	text "YOUR POKÉMON DAMAGES THE OPPONENT'S"
	linefw "DEFENDING POKÉMON BY ATTACKING."
	linefw "POKÉMON NEED CERTAIN ENERGY CARDS"
	linefw "IN ORDER TO USE ATTACKS."
	linefw "FOR EXAMPLE, THE ENERGY REQUIRED"
	linefw "TO USE SEAKING'S WATERFALL ATTACK"
	linefw "IS ", "<WATER>", "<COLORLESS>", ", WHICH STANDS FOR 1 WATER"
	linefw "ENERGY AND 1 ENERGY OF ANY TYPE."
	linefw "THE ENERGY REQUIRED DIFFERS"
	linefw "DEPENDING ON THE ATTACK."
	done

Text0f35:
	text "TO SWITCH YOUR ACTIVE POKÉMON"
	linefw "WITH A BENCHED POKÉMON,"
	linefw "CHOOSE THE RETREAT COMMAND"
	linefw "FROM YOUR BATTLE MENU."
	linefw "IF THE ACTIVE POKÉMON IS IN DANGER,"
	linefw "MOVE IT BACK TO YOUR BENCH."
	linefw "ENERGY IS USUALLY REQUIRED IN ORDER"
	linefw "TO RETREAT, AND IT IS DISCARDED."
	linefw "THE NUMBER OF ENERGY CARDS"
	linefw "REQUIRED VARIES FOR EACH POKÉMON."
	done

Text0f36:
	text "THERE ARE 3 TYPES OF POKÉMON"
	linefw "MONSTER CARDS:"
	linefw "BASIC POKÉMON, STAGE 1 POKÉMON,"
	linefw "AND STAGE 2 POKÉMON."
	linefw "BASIC POKÉMON ARE THE ONLY CARDS"
	linefw "THAT CAN BE PUT DIRECTLY INTO PLAY."
	linefw "A BASIC POKÉMON CAN BE EVOLVED INTO"
	linefw "A STAGE 1 POKÉMON."
	linefw "SIMILARLY, A STAGE 1 POKÉMON MAY BE"
	linefw "EVOLVED INTO A STAGE 2 POKÉMON."
	linefw "FOR EXAMPLE, SQUIRTLE IS A BASIC"
	linefw "POKÉMON, WARTORTLE IS A STAGE 1"
	linefw "POKÉMON, AND BLASTOISE IS"
	linefw "A STAGE 2 POKÉMON."
	linefw "THUS, YOU MUST FIRST PLAY A SQUIRTLE"
	linefw "AND THEN A WARTORTLE IN ORDER TO"
	linefw "PLAY A BLASTOISE."
	done

Text0f37:
	text "SOME POKÉMON HAVE SPECIAL ABILITIES"
	linefw "CALLED POKÉMON POWERS."
	linefw "SOME POKÉMON POWERS ARE USED"
	linefw "AS SOON AS THE POKÉMON IS IN PLAY,"
	linefw "WHILE OTHERS MUST BE USED BY"
	linefw "CHOOSING THE 'PKMN POWER' COMMAND."
	linefw "THERE ARE MANY DIFFERENT POWERS,"
	linefw "SO READ EACH CARD'S TEXT CAREFULLY."
	done

Text0f38:
	text "YOUR TURN ENDS AFTER YOU ATTACK."
	linefw "IF YOU DO NOT HAVE ENOUGH ENERGY"
	linefw "TO ATTACK, OR IF YOUR POKÉMON CANNOT"
	linefw "MOVE DUE TO A STATUS CONDITION,"
	linefw "YOU CAN END YOUR TURN BY"
	linefw "CHOOSING THE 'DONE' COMMAND."
	linefw "THIS WILL CAUSE YOUR TURN TO END"
	linefw "AND YOUR OPPONENT'S TURN TO BEGIN."
	linefw "IF YOU ARE UNABLE TO DO ANYTHING,"
	linefw "YOU SHOULD CHOOSE 'DONE'."
	done

Text0f39:
	text "GENERALLY, THE WIN OR LOSS OF A DUEL"
	linefw "IS DECIDED BY PRIZE CARDS."
	linefw "PRIZE CARDS ARE DRAWN WHEN YOU"
	linefw "KNOCK OUT AN OPPONENT'S POKÉMON."
	linefw "YOU WIN IF YOU KNOCK OUT AS MANY OF"
	linefw "YOUR OPPONENT'S POKÉMON AS THERE ARE"
	linefw "PRIZES TO BE DRAWN. THE PRIZE COUNT"
	linefw "IS SET AT THE START OF THE DUEL."
	linefw "YOU WILL ALSO LOSE THE DUEL IF YOU"
	linefw "HAVE NO CARDS REMAINING IN YOUR"
	linefw "DECK AT THE START OF YOUR TURN"
	linefw "OR IF YOU HAVE NO POKÉMON"
	linefw "IN YOUR PLAY AREA, SO BE CAREFUL!"
	done

Text0f3a:
	text "HOOHOO! YAH!"
	linefw "SO YOU'VE COME, ", "<RAMNAME>", "!"
	linefw "HOW DO YOU LIKE OUR NEW"
	linefw "TRAINING ROOM?"
	linefw "IT WAS BUILT TO HELP TUTOR PLAYERS"
	linefw "OF THE POKÉMON CARD GAME!"
	linefw "YOU CAN START YOUR TRAINING"
	linefw "AT STEP 1!"
	done

Text0f3b:
	text "HOOHOO! ARE YOU LOOKING FOR SOME"
	linefw "TRAINING, ", "<RAMNAME>", "?"
	linefw "OUR TRAINING REGIMENT HAS MANY"
	linefw "INTENSIVE STAGES!"
	done
