Text0d3f:
	text "NEAT!"
	linefw "YOU GOT 3 HEADS IN A ROW!"
	linefw "YOU'VE WON 20 CHIPS!"
	linefw "CONGRATULATIONS!"
	done

Text0d40:
	text "PLEASE COME AND PLAY AGAIN SOON!"
	done

Text0d41:
	text "COOL!"
	linefw "YOU GOT 4 HEADS IN A ROW!"
	linefw "YOU'VE WON 40 CHIPS!"
	linefw "CONGRATULATIONS!"
	done

Text0d42:
	text "WOW!"
	linefw "YOU GOT 5 HEADS IN A ROW!"
	linefw "YOU'VE WON 100 CHIPS!"
	linefw "CONGRATULATIONS!"
	done

Text0d43:
	text "SWEET!"
	linefw "YOU GOT 6 HEADS IN A ROW!"
	linefw "YOU'VE WON 200 CHIPS!"
	linefw "CONGRATULATIONS!"
	done

Text0d44:
	text "OH, MY!"
	linefw "YOU GOT 7 HEADS IN A ROW!"
	linefw "YOU'VE WON 500 CHIPS!"
	linefw "CONGRATULATIONS!"
	done

Text0d45:
	text "AMAZING!"
	linefw "YOU GOT 8 HEADS IN A ROW!"
	linefw "YOU'VE WON 1000 CHIPS!"
	linefw "CONGRATULATIONS!"
	done

Text0d46:
	text "UNBELIEVEABLE!"
	linefw "YOU GOT 9 HEADS IN A ROW!"
	linefw "IF YOU WOULD'VE HAD ONE MORE,"
	linefw "YOU WOULD HAVE WON THE GRAND PRIZE! "
	linefw "OH, BUT LOOK ON THE BRIGHT SIDE!"
	linefw "YOU'VE WON 3000 CHIPS!"
	done

Text0d47:
	text "THE 10-HEAD COMBO WAS IN SIGHT!"
	linefw "PLEASE COME AND PLAY AGAIN SOON!"
	done

Text0d48:
	text "CONGRATULATIONS, YOU'VE DONE IT!"
	linefw " "
	linefw "YOU GOT A 10-HEAD COMBO IN OUR"
	linefw "COIN FLIP COMBO GAME!"
	linefw "YOU'VE WON A MEW Lv8 CARD!"
	linefw "HERE, TAKE YOUR PRIZE!!"
	done

Text0d49:
	text "YOU'RE QUITE THE LUCKY PLAYER!"
	done

Text0d4a:
	text "TURNED ON THE BLACK BOX."
	done

Text0d4b:
	text "TURNED ON BILL'S COMPUTER."
	done

Text0d4c:
	text "THANK YOU FOR COMING! THIS GAME HERE"
	linefw "IS CALLED 'THE BLACK BOX'."
	linefw "IT'S QUITE A FUN MACHINE."
	linefw "DO YOU WANT TO KNOW HOW TO USE IT?"
	done

Text0d4d:
	text "LISTEN TO MACHINE'S INSTRUCTIONS?"
	done

Text0d4e:
	text "IT TAKES 5 GAME CHIPS TO USE"
	linefw "THE BLACK BOX."
	linefw "5 POKÉMON CARDS ARE THEN PLACED"
	linefw "INTO THE BOX."
	linefw "THEN THE CARDS TRANSFORM INTO"
	linefw "DIFFERENT CARDS!"
	linefw "YOU WILL RECEIVE YOUR TRANSFORMED"
	linefw "CARDS THROUGH THE MAIL!"
	linefw "BE SURE YOU HAVE MAILBOX SPACE"
	linefw "BEFORE YOU PLAY THE BLACK BOX."
	linefw "IF YOUR MAILBOX IS FULL,"
	linefw "YOU CAN'T RECEIVE YOUR CARDS."
	linefw "IT'S REALLY QUITE SIMPLE, BUT IF YOU"
	linefw "NEED ANOTHER EXPLANATION, JUST ASK."
	linefw "PLEASE ENJOY YOURSELF WHILE USING"
	linefw "THE BLACK BOX!"
	done

Text0d4f:
	text "AH, SO YOU DON'T NEED INSTRUCTIONS."
	linefw "THAT'S GOOD TO HEAR!"
	linefw "JUST REMEMBER THE MACHINE'S"
	linefw "PROTOCOL FOR PRIZE DISTRIBUTION."
	linefw "ANY PRIZES YOU WIN FROM THE BLACK"
	linefw "BOX WILL BE SENT TO YOUR MAILBOX."
	linefw "YOU CAN'T GET CARDS IF YOU"
	linefw "HAVE NO ROOM FOR NEW MAIL."
	done

Text0d50:
	text "HELLO! THIS ATTRACTION IS CALLED"
	linefw "'BILL'S COMPUTER'!"
	linefw "IT'S PRETTY EASY TO USE, BUT I CAN"
	linefw "EXPLAIN HOW IT WORKS IF YOU LIKE."
	done

Text0d51:
	text "LISTEN TO THE EXPLANATION?"
	done

Text0d52:
	text "ALRIGHT, THEN, I'LL EXPLAIN."
	linefw " "
	linefw "YOU CAN USE BILL'S COMPUTER"
	linefw "TO GET NEW CARDS."
	linefw "YOU'LL NEED A SPECIFIC CARD BEFORE"
	linefw "YOU CAN GET ANY OTHERS, THOUGH."
	linefw "THAT CARD IS THE SPECIAL PROMO,"
	linefw "BILL'S COMPUTER."
	linefw "YOU'LL ADDITIONALLY NEED 20 CHIPS"
	linefw "TO PERFORM THE TRADE."
	linefw "CHECK WHICH CARDS YOU CAN TRADE IN"
	linefw "AND CHOOSE YOUR PRIZE CAREFULLY."
	linefw "AND SO ENDS MY EXPLANATION OF"
	linefw "BILL'S COMPUTER. TRY IT OUT!"
	done

Text0d53:
	text "IS THAT SO? WELL, IF YOU EVER NEED"
	linefw "HELP WITH THE MACHINE, I'LL BE HERE."
	linefw "EXPERIMENTATION MIGHT ALSO BE"
	linefw "A GOOD WAY TO LEARN."
	done

Text0d54:
	text "HELLO! THIS TABLE IS FOR OUR"
	linefw "'COIN TOSS COMBO' GAME!"
	linefw "HOW MANY TIMES CAN YOU GET HEADS"
	linefw "BEFORE A TAILS RUINS YOUR STREAK? "
	linefw "IF YOU CAN GET 10 HEADS IN A ROW,"
	linefw "YOU'LL WIN A MEW Lv8 CARD!"
	linefw "IT COSTS 1 CHIP TO PLAY A GAME"
	linefw "OF COIN TOSS COMBO."
	linefw "DOESN'T IT SOUND LIKE FUN?"
	linefw "WOULD YOU LIKE TO PLAY?"
	done

Text0d55:
	text "PLAY COIN TOSS COMBO?"
	done

Text0d56:
	text "COME PLAY COIN TOSS COMBO!"
	done

Text0d57:
	text "I'M SORRY, BUT YOU DON'T SEEM TO"
	linefw "HAVE ANY CHIPS TO PLAY WITH."
	linefw "IF YOU WOULD LIKE TO PLAY COIN TOSS"
	linefw "COMBO, YOU'LL NEED TO PAY 1 CHIP."
	done

Text0d58:
	text "PLEASE COME AGAIN!"
	done

Text0d59:
	text "AHHH, WHAT GAME SHOULD I PLAY?"
	done

Text0d5a:
	text "YOU ONLY BUILD UP A COMBO IN"
	linefw "COIN TOSS COMBO IF YOU GET HEADS."
	linefw "SUPPOSEDLY, IF YOU GET 10 HEADS,"
	linefw "YOU'LL WIN A SWEET CARD!"
	done

Text0d5b:
	text "MY HEART IS BEATING SO FAST..."
	linefw "WILL THE NEXT FLIP BE A HEADS?"
	linefw "THIS THUMPING IS ENOUGH TO MAKE ME"
	linefw "START LOSING SOME WEIGHT, I SWEAR!"
	done

Text0d5c:
	text "THERE'S NOTHING LIKE COIN TOSS COMBO"
	linefw "TO GET MY HEART RACING TOO FAST."
	linefw "MAYBE...MAYBE I SHOULD PLAY"
	linefw "SOMETHING SLOWER-PACED?"
	done

Text0d5d:
	text "GOOD AFTERNOON."
	linefw "THESE ARE OUR FAMOUS SLOT MACHINES."
	linefw "CLOSE YOUR EYES, PULL THE ARM,"
	linefw "AND TEST YOUR LUCK!"
	linefw "EACH GAME COSTS ONLY 1 CHIP."
	linefw "WANNA HEAR HOW TO PLAY?"
	done

Text0d5e:
	text "WOULD YOU LIKE TO LEARN HOW TO PLAY?"
	done

Text0d5f:
	text "IT'S NOT TERRIBLY DIFFICULT,"
	linefw "BUT I'LL EXPLAIN AS BEST AS I CAN."
	linefw "YOU'LL WIN CHIPS IF YOU LINE UP"
	linefw "3 OF THE SAME SYMBOL ON THE WHEELS."
	linefw "IF YOU MATCH RAINBOW ENERGY, THOUGH,"
	linefw "YOU'LL GET TO PLAY A BONUS GAME!"
	linefw "DO YOUR BEST TO WIN THE BONUS GAME!"
	linefw "YOU COULD WIN A PRESENT PACK."
	linefw "GOOD LUCK!"
	done

Text0d60:
	text "WHY NOT GIVE IT A TRY?"
	linefw "IT'S ONLY 1 CHIP PER GAME!"
	done

Text0d61:
	text "HELLO! HOW ARE YOU TODAY?"
	linefw "WANNA PLAY WITH THE SLOT MACHINES?"
	linefw "THESE MACHINES REQUIRE 5 CHIPS"
	linefw "TO PLAY PER GAME."
	linefw "WOULD YOU LIKE ME TO EXPLAIN"
	linefw "HOW TO PLAY?"
	done

Text0d62:
	text "WOULD YOU LIKE TO LEARN HOW TO PLAY?"
	done

Text0d63:
	text "BOTH OF OUR SLOT MACHINES PLAY"
	linefw "EXACTLY THE SAME WAY."
	linefw "AFTER PAYING YOUR CHIPS,"
	linefw "PULL THE ARM TO START THE GAME."
	linefw "MATCH 3 SYMBOLS ON THE WHEELS,"
	linefw "AND YOU'LL SCORE SOME CHIPS."
	linefw "IF YOU GET 3 RAINBOW ENERGY SYMBOLS,"
	linefw "YOU'LL GET TO PLAY THE BONUS STAGE!"
	linefw "IF YOU MATCH 3 SYMBOLS IN THE BONUS"
	linefw "STAGE, YOU'LL WIN A PRESENT PACK."
	linefw "HOW ABOUT IT? IT'S QUITE SIMPLE."
	linefw "GIVE IT A TRY!"
	done

Text0d64:
	text "I'M SURE YOU'VE HEARD IT 1000 TIMES"
	linefw "BEFORE. ANYWAY, GOOD LUCK!"
	done

Text0d65:
	text "WELCOME!"
	linefw "THIS IS THE CARD DUNGEON!"
	linefw "IT'S 10 CHIPS PER GAME."
	linefw "WOULD YOU LIKE TO PLAY?"
	done

Text0d66:
	text "PLAY IN THE CARD DUNGEON?"
	done

Text0d67:
	text "I'M SORRY, BUT YOU DON'T HAVE"
	linefw "ENOUGH CHIPS TO PLAY."
	linefw "PLEASE COME BACK LATER WITH"
	linefw "10 CHIPS TO PLAY THE GAME."
	done

Text0d68:
	text "ALRIGHT!"
	linefw "FIRST, LET'S REVIEW THE RULES."
	done

Text0d69:
	text "YOU MAY NOW ENTER THE DUNGEON."
	done

Text0d6a:
	text "COME ON BACK IF YOU EVER WANT TO"
	linefw "PLAY IN THE CARD DUNGEON!"
	done

Text0d6b:
	text "I HEARD THAT YOU DEFEATED THE QUEEN."
	linefw "CONGRATULATIONS!"
	linefw "FEEL FREE TO COME BACK AND PLAY"
	linefw "AGAIN, ANY TIME!"
	done

Text0d6c:
	text "THANKS FOR PLAYING."
	linefw "COME BACK AGAIN SOON!"
	done

Text0d6d:
	text "OH, DID YOU FINISH BATTLING?"
	linefw "PLEASE COME AGAIN!"
	done

Text0d6e:
	text "I JUST CHALLENGED THE CARD DUNGEON."
	linefw ""
	linefw "I USED MY BEST TRICKS FOR MY CARD"
	linefw "BATTLES! ...BUT I DIDN'T WIN..."
	linefw "EVEN AGAINST PAWN, THE FIRST DUEL!"
	linefw "IT'S SO IMPOSSIBLE!!!"
	done

Text0d6f:
	text "YAH HA HA HA HA!"
	linefw "I DEFEATED PAWN, AT LONG LAST!"
	linefw "BUT...I'VE LOST AGAINST ROOK"
	linefw "4 TIMES TOTAL SO FAR..."
	linefw "ROOK IS A TOUGH OPPONENT, TOO..."
	done

Text0d70:
	text "IT'S SO POINTLESS!!!"
	linefw "I'LL NEVER WIIIIIN!!!!"
	linefw "I'VE GIVEN UP ON EVER COMPLETING"
	linefw "THE CARD DUNGEON..."
	done

Text0d71:
	text "NOOO, I DON'T WANT TO GO TO WORK..."
	linefw "YOU SEE, I'M FROM GR CASTLE."
	linefw "THE KING OF TEAM GR IS A BUSY GUY,"
	linefw "BUT IT'S NOT LIKE HE NEEDS ME."
	linefw "I DON'T THINK HE'LL MISS ME,"
	linefw "SO I'M BIDING MY TIME AT THE SLOTS!"
	done

Text0d72:
	text "NOOO, I DON'T WANT TO GO TO WORK..."
	linefw "YOU SEE, I'M FROM GR CASTLE."
	linefw "EVER SINCE YOUR VICTORY, THOUGH,"
	linefw "ALL WORK THERE HAS BEEN CANCELED."
	linefw "I DON'T HAVE ANYTHING BETTER TO DO,"
	linefw "SO I'M BIDING MY TIME AT THE SLOTS!"
	done

Text0d73:
	text "DON'T BOTHER ME, KID!"
	linefw "CAN'T YOU SEE I'M PLAYING THE SLOTS?"
	linefw "YOU NEED TO MATCH UP ENERGY SYMBOLS"
	linefw "IF YOU WANNA WIN SOME CHIPS."
	linefw "WHAT YOU REALLY WANT ARE 3 RAINBOW"
	linefw "ENERGY SYMBOLS FOR THE BONUS GAME!"
	linefw "IF YOU'D LIKE TO PLAY, TOO,"
	linefw "WHY DON'T YOU GO GET SOME CHIPS?"
	done

Text0d74:
	text "HEY, KEEP QUIET, KID!"
	linefw "YOU'RE THROWING OFF MY STREAK..."
	linefw "...GAAH!! I LOST IT!!"
	linefw "IT'S ALL YOUR FAULT!"
	linefw "IT WAS ALL BECAUSE OF YOUR GABBING!"
	linefw "GO BOTHER SOMEONE ELSE!"
	done

Text0d75:
	text "HEY, PIPE DOWN, YOU NUISANCE!"
	linefw "YOU'RE GONNA STOP MY STREAK..."
	linefw "...AHHH!! JACKPOT!!"
	linefw "ALL BECAUSE YOU TALKED TO ME!"
	linefw "C'MON, KID!"
	linefw "KEEP TALKIN' SO I KEEP WINNIN'!"
	done

Text0d76:
	text "HELLO, AND WELCOME TO"
	linefw "THE CHIP COUNTER!"
	linefw "YOU CAN LEAVE AND RECLAIM"
	linefw "ANY GAME CHIPS YOU'VE WON HERE."
	done

Text0d77:
	text "I CURRENTLY HAVE ", "<RAMNUM>", " CHIPS"
	linefw "UNDER YOUR NAME."
	done

Text0d78:
	text "WOULD YOU LIKE YOUR CHIPS BACK?"
	done

Text0d79:
	text "HERE ARE YOUR ", "<RAMNUM>", " CHIPS."
	done

Text0d7a:
	text "PLEASE LEAVE YOUR CHIPS WITH ME"
	linefw "BEFORE LEAVING THE GAME CENTER."
	done

Text0d7b:
	text "PLEASE LET ME KNOW WHEN YOU"
	linefw "WOULD LIKE TO MANAGE YOUR CHIPS."
	done

Text0d7c:
	text "WOULD YOU LIKE TO LEAVE YOUR CHIPS?"
	done

Text0d7d:
	text "I'LL KEEP THESE ", "<RAMNUM>", " CHIPS"
	linefw "UNDER YOUR NAME."
	done

Text0d7e:
	text "HELLO!"
	linefw "WELCOME TO THE GAME CENTER!"
	linefw "YOU DON'T HAVE ANY CHIPS, DO YOU?"
	linefw "HERE, I'LL GIVE YOU 10 CHIPS!"
	done

Text0d7f:
	text "<RAMNAME>", " GOT 10 CHIPS"
	linefw "FOR THE GAME CENTER!"
	done

Text0d80:
	text "ALRIGHTY, THEN! PLEASE ENJOY"
	linefw "YOUR TIME AT THE GAME CENTER!"
	linefw "JUST REMEMBER THAT YOU CAN'T TAKE"
	linefw "THE CHIPS OUTSIDE OF THE CENTER."
	done

Text0d81:
	text "HUNH? OH, YOU DON'T HAVE ANY CHIPS."
	linefw "DON'T YOU WORRY!"
	linefw "TAKE THESE 10 CHIPS AND GO HAVE FUN!"
	done

Text0d82:
	text "GOOD AFTERNOON."
	linefw "WELCOME TO THE GAME CENTER!"
	linefw "OH, I SEE."
	linefw "YOU DON'T SEEM TO HAVE ANY CHIPS."
	linefw "PLEASE TAKE THESE 10 COMPLEMETARY"
	linefw "CHIPS, FREE OF CHARGE."
	done

Text0d83:
	text "I HOPE YOU HAVE A GOOD TIME"
	linefw "AT OUR GAME CENTER."
	done

Text0d84:
	text "IF YOU EVER RUN OUT OF CHIPS,"
	linefw "PLEASE SEE ME AGAIN."
	linefw "I'LL GIVE YOU A FEW MORE, THOUGH"
	linefw "IT'LL ONLY BE A MEASLY 10 CHIPS."
	done

Text0d85:
	text "YOU CAN'T TAKE GAME CHIPS AWAY"
	linefw "FROM THE GAME CENTER."
	linefw "PLEASE LEAVE ANY REMAINING CHIPS"
	linefw "AT THE LEFT COUNTER BEFORE LEAVING."
	done

Text0d86:
	text "EXCUSE ME, COULD YOU COME HERE?"
	linefw "YOU STILL HAVE CHIPS, CORRECT?"
	linefw "I'M SORRY, BUT THE GAME CENTER"
	linefw "REQUIRES ALL CHIPS TO BE KEPT HERE."
	linefw "PLEASE LEAVE YOUR CHIPS WITH US"
	linefw "BEFORE YOU LEAVE."
	linefw "TALK WITH THE RECEPTIONIST ON THE"
	linefw "LEFT TO MANAGE YOUR CHIP RECORD."
	done

Text0d87:
	text "I WAS STUDYING THE GAMES HERE TO"
	linefw "FIGURE OUT HOW TO ENSURE WINS."
	linefw "BUT EVERY TIME I PLAY, IT'S"
	linefw "LOSE, LOSE, LOSE! I ALWAYS LOSE!"
	linefw "IN THE END..."
	linefw "I HAVEN'T LEARNED A THING!"
	done

Text0d88:
	text "IT'S YOU...", "<RAMNAME>", "!"
	linefw "WHAT ARE YOU DOING HERE?"
	linefw "HA HA, ARE YOU PLAYING AROUND HERE"
	linefw "BECAUSE YOU CAN'T BEAT TEAM GR?"
	linefw "AAH, YOU'RE SO HOPELESS!"
	done

Text0d89:
	text "I HAVE NO REGRETS ABOUT WHAT HAS"
	linefw "HAPPENED SINCE KING VILLICCI LOST."
	done

Text0d8a:
	text "I STARTED PLAYING ONE OF THE GAMES"
	linefw "THEY HAVE HERE AND GOT HOOKED."
	linefw "IT TOOK ME YEARS BEFORE I STOPPED,"
	linefw "AND I WAS SO OLD BY THEN..."
	linefw "I'M JUST KIDDING, OF COURSE!"
	linefw " "
	linefw "SERIOUSLY, THOUGH, PLEASE BE CAREFUL"
	linefw "THAT YOU DON'T GET AN ADDICTION."
	done

Text0d8b:
	text "SINCE YOU'VE REACHED YOUR GOAL,"
	linefw "IT'S A GREAT TIME TO UNWIND HERE."
	done

Text0d8c:
	text "THANK YOU FOR VISITING."
	linefw "THIS IS TEAM GR'S GRASS FORTRESS."
	done

Text0d8d:
	text "THANK YOU FOR VISITING."
	linefw "THIS IS TEAM GR'S GRASS FORTRESS."
	linefw "ALLOW ME TO TELL YOU ABOUT YOUR"
	linefw "OPPONENTS AND EXPLAIN THE RULES."
	linefw "THE LEADER OF THE GRASS FORTRESS"
	linefw "IS A MAN NAMED PARKER."
	linefw "IN ORDER TO FIGHT HIM, YOU MUST"
	linefw "FIRST DEFEAT 3 GR FORTRESS MEMBERS."
	linefw "YOU'LL LEARN ABOUT EACH MEMBER'S"
	linefw "SPECIAL BATTLE RULES INSIDE."
	linefw "THAT IS ALL. PLEASE ENJOY DUELLING"
	linefw "IN TEAM GR'S GRASS FORTRESS."
	done

Text0d8e:
	text "<RAMNAME>", ", IT'S ME!"
	linefw "RICK, THE SCIENCE CLUB MASTER."
	linefw "WHAT ARE YOU DOING ON GR ISLAND?"
	linefw " "
	linefw "OH? YOU'RE HERE TO FIGHT TEAM GR"
	linefw "AND WIN BACK THE STOLEN CARDS?"
	linefw "I SEE... I'LL GIVE YOU SOME"
	linefw "INFORMATION TO HELP YOU ON YOUR WAY."
	linefw "IT APPEARS THAT CERTAIN COINS MUST"
	linefw "BE PRESENTED TO ENTER FORTRESSES."
	linefw "EACH FORTRESS LEADER IS ENTRUSTED"
	linefw "WITH A COIN."
	linefw "IF YOU CAN DEFEAT THE LEADERS IN"
	linefw "CARD BATTLES, YOU'LL GET THEIR COIN."
	linefw "I'M SURE YOU'LL BE OKAY, HAVING"
	linefw "DEFEATED THE GRAND MASTERS BEFORE."
	linefw "STILL, PLEASE TAKE CARE OF YOURSELF."
	linefw "DO YOUR BEST FOR EVERYONE'S SAKE!"
	done

Text0d8f:
	text "I HAD OVERHEARD SOME GR MEMBERS"
	linefw "TALKING ABOUT A KING OF TEAM GR."
	linefw "WHILE THE KING OF TEAM GR REMAINS"
	linefw "UNDEFEATED, PEACE IS IMPOSSIBLE."
	linefw "KNOWING YOUR SKILL, YOU'LL SURELY"
	linefw "BE ABLE TO BEAT TEAM GR'S KING."
	linefw "PLEASE TRY YOUR BEST FOR"
	linefw "EVERYONE'S SAKE."
	done

Text0d90:
	text "GOOD AFTERNOON."
	linefw "ARE YOU ", "<RAMNAME>", "?"
	linefw "I'M MELISSA, ONE OF THE MEMBERS"
	linefw "OF TEAM GR'S GRASS FORTRESS."
	linefw "IT'S NICE TO FINALLY MEET YOU."
	linefw "I WAS TOLD YOU WOULD BE COMING!"
	linefw "AS PER TEAM GR'S ORDERS,"
	linefw "YOU MUST FIGHT ME TO OPEN THIS GATE!"
	linefw "SO, WILL YOU HAVE A DUEL WITH ME?"
	linefw "WIN, AND YOU'LL GET SOME NEW CARDS."
	linefw "OF COURSE, YOU MAY ALSO ADVANCE"
	linefw "AND WILL FREE THIS GUY BEHIND ME."
	done

Text0d91:
	text "ISN'T HE THE MASTER OF THE"
	linefw "SCIENCE CLUB ON YOUR ISLAND?"
	done

Text0d92:
	text "HE'S FREE TO GO..."
	linefw "IF YOU CAN DEFEAT ME, OF COURSE."
	done

Text0d93:
	text "HEY, C'MON! LET'S PLAY!"
	linefw " "
	linefw "YOU DO REALIZE YOU HAVE NO CHOICE"
	linefw "BUT TO FIGHT ME FIRST, RIGHT?"
	done

Text0d94:
	text "WOULD YOU LIKE TO DUEL MELISSA?"
	done

Text0d95:
	text "OKEYDOKEY! WE'LL HAVE A"
	linefw "PLEASANT MATCH WITH 4 PRIZE CARDS!"
	done

Text0d96:
	text "SAY WHAT? WOW, IT'S BAD NEWS"
	linefw "IF YOU WON'T FIGHT."
	linefw "YOU'LL HAVE TO BATTLE IF YOU WANT"
	linefw "TO VISIT THE OTHER GR FORTRESSES."
	done

Text0d97:
	text "HEY THERE, ", "<RAMNAME>", "."
	linefw "I WANT TO PLAY POKÉMON CARDS AGAIN!"
	linefw "C'MON, C'MON! LET'S DUEL!"
	done

Text0d98:
	text "WHY DON'T WE USE A LEISURELY"
	linefw "4 PRIZE CARDS, THEN?"
	done

Text0d99:
	text "MAAAAN, IT'S SO BORING HERE."
	linefw "...BUT I GUESS IT'S A LOST CAUSE."
	linefw "JUST BE SURE TO COME BACK HERE IF"
	linefw "YOU EVER WANT TO PLAY AGAIN, OKAY?"
	done

Text0d9a:
	text "OH, WELL. I GUESS I LOST."
	done

Text0d9b:
	text "I DID MY BEST."
	linefw "I HAVE NO REGRETS."
	linefw "BECAUSE YOU DEFEATED MY DECK,"
	linefw "I'LL OPEN THE GATE."
	done

Text0d9c:
	text "AWW, IT'S ALREADY OVER..."
	linefw "C'MON BACK AND TRY AGAIN SOON!"
	done

Text0d9d:
	text "OH? I LOST AGAIN."
	linefw "OH, WHY CAN'T I DO IT?"
	done

Text0d9e:
	text "IT'S FINE! BUT WATCH OUT!"
	linefw "I WON'T LOSE IN OUR NEXT BATTLE!"
	linefw "I'LL BE WAITING HERE FOR YOU"
	linefw "TO CHALLENGE ME AGAIN!"
	done

Text0d9f:
	text "I DID IT! I WON!"
	linefw "I'M SO HAPPY!"
	linefw "PLEASE COME BACK AND PLAY AGAIN"
	linefw "SOMETIME SOON!"
	done

Text0da0:
	text "RICK WILL BE FREE TO LEAVE HIS"
	linefw "CAGE AS WELL."
	done

Text0da1:
	text "THANKS FOR YOUR HELP,"
	linefw "<RAMNAME>", "."
	linefw "PLEASE TAKE THIS CARD AS THANKS"
	linefw "FOR YOUR VALIANT RESCUE."
	done

Text0da2:
	text "I HOPE YOU'LL HAVE AS MUCH SUCCESS"
	linefw "WITH YOUR FUTURE DUELS."
	linefw "AS FOR ME, I'M GOING TO RETURN"
	linefw "TO THE SCIENCE CLUB."
	linefw "FEEL FREE TO STOP BY WHEN YOU'RE"
	linefw "BACK ON OUR ISLAND."
	linefw "I'D BE MORE THAN HAPPY TO HAVE A"
	linefw "DUEL OR TWO WITH YOU IF YOU'RE GAME."
	done

Text0da3:
	text "YOU MAY PROCEED TO THE NEXT ROOM."
	linefw "JAMES IS WAITING FOR YOU THERE."
	linefw "YOU'LL BATTLE HIM, TOO, CORRECT?"
	done

Text0da4:
	text "OH, IS IT MY TURN ALREADY?"
	linefw "JAMES IS SO UNRELIABLE."
	linefw "I AM LIZ. OF COURSE, I AM ALSO"
	linefw "A MEMBER OF TEAM GR."
	linefw "I AM ADDRESSING ", "<RAMNAME>", ","
	linefw "THE CHILD DEFYING TEAM GR, CORRECT?"
	linefw "I SUPPOSE YOU'RE LOOKING TO BATTLE"
	linefw "PARKER FOR A GR GRASS COIN."
	linefw "IN ORDER TO GET THROUGH TO HIM,"
	linefw "THOUGH, YOU'LL NEED TO DEFEAT ME."
	linefw "THEN LET'S DUEL! ...BUT I WANT TO"
	linefw "FINISH TENDING TO THESE FLOWERS..."
	linefw "BUT BATTLES COME BEFORE BEGONIAS."
	linefw "I HAVE SPECIAL TERMS FOR DUELLING."
	linefw "I ONLY FIGHT AGAINST DECKS WITH"
	linefw "GRASS AS THEIR ONLY ENERGY CARDS."
	linefw "THAT IS MY ONLY CONDITION."
	linefw "UP FOR A DUEL, ", "<RAMNAME>", "?"
	done

Text0da5:
	text "OH, BACK SO SOON?"
	linefw "I HOPE YOU'VE BEEN WELL."
	linefw "OUR KING HAS ENTRUSTED ME WITH THE"
	linefw "DUTY OF GUARDING THIS ROOM'S DOOR."
	linefw "DO YOU RECALL MY TERMS FOR DUELLING?"
	linefw "YOU MAY ONLY USE GRASS ENERGY."
	linefw "IF YOU PUT ANY OTHER TYPE OF ENERGY"
	linefw "IN YOUR DECK, I WON'T FIGHT YOU."
	linefw "HAVE YOU FOLLOWED MY WISHES?"
	linefw "ARE YOU PREPARED, ", "<RAMNAME>", "?"
	done

Text0da6:
	text "WOULD YOU LIKE TO DUEL LIZ?"
	done

Text0da7:
	text "STOP RIGHT THERE! IS THAT ENERGY"
	linefw "THAT'S NOT GRASS ENERGY? "
	linefw "DIDN'T YOU LISTEN TO MY TERMS? YOUR"
	linefw "DECK MUST ONLY HAVE GRASS ENERGY."
	linefw "MAKE A DECK WITH THAT RESTRICTION"
	linefw "BEFORE TRYING TO DUEL WITH ME!"
	done

Text0da8:
	text "OH, YOUR DECK ONLY HAS GRASS ENERGY."
	linefw "GREAT, WE MAY BEGIN OUR FIGHT, THEN!"
	linefw "WE SHALL HAVE A DUEL WITH 4"
	linefw "PRIZE CARDS!"
	done

Text0da9:
	text "YOU'LL NEED TO GATHER PLENTY OF"
	linefw "GRASS ENERGY IF YOU WANT TO FIGHT."
	linefw "IT'S RATHER HARD TO COME BY ENERGY"
	linefw "ON GR ISLAND, THOUGH..."
	linefw "BUT I HATE DECKS THAT DON'T HAVE"
	linefw "GRASS ENERGY, AND ONLY GRASS ENERGY!"
	done

Text0daa:
	text "DO YOU REMEMBER MY SPECIAL"
	linefw "CONDITION FOR CARD BATTLES?"
	linefw "I WON'T BATTLE YOU UNLESS YOU FOLLOW"
	linefw "THE TERMS I USE FOR ALL CHALLENGERS."
	linefw "I WILL ONLY DUEL AGAINST DECKS THAT"
	linefw "USE GRASS AS THEIR ONLY ENERGY TYPE."
	linefw "ARE YOU STILL UP FOR A BATTLE?"
	done

Text0dab:
	text "DID YOU NOT LISTEN TO THE TERMS"
	linefw "I LAID OUT FOR OUR BATTLE?"
	linefw "I REFUSE TO FIGHT YOU IF YOUR DECK"
	linefw "HAS ENERGY TYPES THAT AREN'T GRASS."
	linefw "COME BACK TO FIGHT WHEN YOU HAVE"
	linefw "A DECK THAT FITS THAT RULE."
	done

Text0dac:
	text "GOOD, GOOD! I SEE YOUR DECK ONLY"
	linefw "USES GRASS-TYPE ENERGY CARDS."
	linefw "I'VE GOT TO GET BACK TO MY FLOWERS,"
	linefw "SO LET'S HAVE A DUEL WITH 4 PRIZES."
	linefw "LET'S START THE BATTLE!"
	done

Text0dad:
	text "IF YOU DON'T LIKE MY CONDITIONS,"
	linefw "THEN WE DON'T HAVE TO BATTLE."
	linefw "HOWEVER, IF YOU'D LIKE A DUEL THAT'S"
	linefw "CHALLENGING AND FUN, COME ON BACK."
	done

Text0dae:
	text "OH, DEAR."
	linefw "IT SEEMS I'VE BEEN BESTED."
	done

Text0daf:
	text "I'M SURPRISED. YOU HAVE QUITE A LOT"
	linefw "OF SKILL, ", "<RAMNAME>", "."
	done

Text0db0:
	text "YES! I'LL SEE YOU LATER, I WAGER,"
	linefw "AFTER YOU FIX UP YOUR STRATEGY."
	linefw "I DO HOPE YOU'RE NOT HELPLESS WHEN"
	linefw "RESTRICTED TO ONLY GRASS ENERGY."
	linefw "I REFUSE TO FIGHT ANY OTHER WAY!"
	done

Text0db1:
	text "YOU SEEM TO HAVE GROWN QUITE"
	linefw "ACCUSTOMED TO MY BATTLE CONDITION."
	done

Text0db2:
	text "IF YOU'D LIKE TO PLAY UNDER MY TERMS"
	linefw "AGAIN, FEEL FREE TO STOP BY."
	done

Text0db3:
	text "YOUR DECK WAS NICE, BUT IT WASN'T"
	linefw "QUITE ON PAR WITH MINE. SO SORRY!"
	done

Text0db4:
	text "SINCE YOU HAVE DEFEATED ME, I SHALL"
	linefw "OPEN THE DOORS LEADING TO PARKER."
	linefw "PLEASE WAIT JUST A MOMENT."
	done

Text0db5:
	text "GO ON AHEAD."
	linefw "YOU SHOULDN'T LEAVE PARKER WAITING!"
	linefw "I HAVE MY OWN BUSINESS HERE TAKING"
	linefw "CARE OF THIS FLOWER GARDEN."
	done

Text0db6:
	text "WELCOME TO THE GARDEN OF LIGHT!"
	linefw "I'M PARKER, THE GR LEADER OF GRASS!"
	linefw "YES, I AM INDEED PARKER, BUT YOU..."
	linefw "YOU ARE ", "<RAMNAME>", ", CORRECT?"
	linefw "I ASSUME YOU'RE AFTER MY"
	linefw "COVETED GR GRASS COIN."
	linefw "IF THAT'S THE CASE, YOU MUST FIRST"
	linefw "CHALLENGE ME TO A BATTLE AND WIN."
	linefw "BY THE BY, THERE ARE SPECIAL"
	linefw "RULES WHEN YOU DUEL HERE."
	linefw "GRASS POKÉMON ARE IMMUNE TO SLEEP,"
	linefw "POISON, PARALYSIS, AND CONFUSION."
	linefw "NO STATUS CONDITIONS AT ALL."
	linefw "IT'S AN AMAZING ADDITION!"
	linefw "NOW THAT YOU'RE AWARE,"
	linefw "SHALL WE DUEL?"
	done

Text0db7:
	text "HEY THERE, ", "<RAMNAME>", "."
	linefw "WELCOME BACK TO MY GARDEN."
	linefw "ISN'T IT EXHILARATING TO HAVE A CARD"
	linefw "BATTLE WHEN SURROUNDED BY NATURE?"
	linefw "GRASS POKÉMON ARE ALWAYS SO"
	linefw "ENERGETIC WHEN IN MY GARDEN."
	linefw "THEY'RE IMMUNE TO POISON, PARALYSIS,"
	linefw "SLEEP, AND CONFUSION HERE, IN FACT."
	linefw "THEY SIMPLY CANNOT GET STATUS"
	linefw "CONDITIONS IN DUELS HERE."
	linefw "THAT ASIDE, SHALL WE HAVE A DUEL?"
	linefw " "
	linefw "IF YOU MANAGE A WIN, YOU'LL EARN"
	linefw "THE GR GRASS COIN."
	done

Text0db8:
	text "WOULD YOU LIKE TO DUEL PARKER?"
	done

Text0db9:
	text "LET'S NOT PLAY TOO QUICKLY."
	linefw "WE'LL USE 6 PRIZE CARDS."
	done

Text0dba:
	text "YOU'VE DECLINED BECAUSE YOU'RE"
	linefw "PARALYZED IN FEAR FROM MY RULE, EH?"
	linefw "WELL, THAT'S TO BE EXPECTED."
	linefw "REBUILD YOUR DECK AND RETURN LATER."
	linefw "I'LL STILL BE WAITING HERE FOR YOU."
	linefw "NO NEED TO RUSH OR ANYTHING."
	done

Text0dbb:
	text "I USED TO HAVE A REPUTATION AMONG"
	linefw "TEAM GR FOR MY DUELLING SKILLS."
	linefw "EVER SINCE YOU DEFEATED ME AND LIZ,"
	linefw "NO ONE SEEMS TO CARE ABOUT US."
	linefw "THAT'S WHY I'D LIKE TO CHALLENGE YOU"
	linefw "AGAIN AND WIN BACK OUR RESPECT."
	linefw "REMEMBER THAT I USE MY SPECIAL"
	linefw "CHLOROPHYLL RULE FOR BATTLING."
	linefw "GRASS POKÉMON ARE IMMUNE TO POISON,"
	linefw "PARALYSIS, SLEEP, AND CONFUSION."
	linefw "I MUST FIGHT OR FADE INTO"
	linefw "OBSCURITY!"
	done

Text0dbc:
	text "MY DECK IS IN TIP-TOP FORM,"
	linefw "IF I MAY SAY SO MYSELF."
	linefw "IT'S ALL THANKS TO THE VITALITY MY"
	linefw "POKÉMON GET WHILE HERE IN MY GARDEN."
	linefw "MY GRASS POKÉMON ARE IMMUNE TO"
	linefw "STATUS EFFECTS IN THIS GREENERY."
	linefw "POISON, PARALYSIS, SLEEP, CONFUSION;"
	linefw "NONE HAVE ANY EFFECT WHATSOEVER!"
	linefw "DO YOU THINK YOU COULD DEFEAT ME"
	linefw "IN MY MYSTERIOUS GARDEN?"
	done

Text0dbd:
	text "WE'LL USE 6 PRIZE CARDS FOR A SLOW,"
	linefw "CAREFUL MATCH."
	done

Text0dbe:
	text "I FEEL POWERLESS IF I CAN'T HAVE"
	linefw "A DECENT BATTLE EVERY NOW AND THEN."
	linefw "POKÉMON CARDS ARE NO FUN IF YOU"
	linefw "DON'T PLAY THE GAME WITH THEM!"
	done
