Text08fa:
	text "SINCE YOU'VE DEFEATED US BOTH,"
	linefw "IT'S TIME FOR YOU TO MEET VILLICCI."
	linefw "PLEASE FOLLOW."
	done

Text08fb:
	text "NOW THAT WE'RE HERE,"
	linefw "LET'S START THE BATTLE."
	linefw "BUT I HAVE SPECIAL REQUIREMENTS FOR"
	linefw "OUR DUEL THAT YOU MUST UPHOLD!"
	linefw "I'VE HEARD SO MUCH PRAISE ABOUT THE"
	linefw "POKÉMON CARDS OF LEGEND..."
	linefw "YOU'VE UNDOUBTEDLY HEARD ABOUT THEM."
	linefw "THEY ARE THE FOLLOWING FOUR CARDS:"
	linefw "MOLTRES Lv40!! ARTICUNO Lv37!!"
	linefw "ZAPDOS Lv68!! DRAGONITE Lv41!!"
	linefw "PUT ALL FOUR OF THESE CARDS OF"
	linefw "LEGEND INTO A SINGLE DECK."
	linefw "IF YOU DO THAT, I WOULD BE MORE"
	linefw "THAN HAPPY TO HAVE A DUEL WITH YOU."
	done

Text08fc:
	text "MOLTRES Lv40!! ARTICUNO Lv37!!"
	linefw "ZAPDOS Lv68!! DRAGONITE Lv41!!"
	linefw "PUT ALL FOUR OF THESE CARDS OF"
	linefw "LEGEND INTO A SINGLE DECK."
	linefw "DO IT! THOSE ARE MY TERMS"
	linefw "FOR FIGHTING YOU."
	linefw "IF YOU'VE ALREADY DONE SO,"
	linefw "WE MAY START OUR FIGHT IMMEDIATELY."
	done

Text08fd:
	text "WOULD YOU LIKE TO DUEL CLAY?"
	done

Text08fe:
	text "DON'T PLAY AROUND, ", "<RAMNAME>", "!!"
	linefw "DO YOU TAKE ME FOR A FOOL?!"
	linefw "DON'T PRETEND YOU DON'T KNOW WHERE"
	linefw "THE POKÉMON CARDS OF LEGEND ARE!"
	linefw "IF YOU DON'T HAVE THEM, THEN THE"
	linefw "GRAND MASTERS MUST STILL HAVE THEM!"
	linefw "COLLECT THE POKÉMON CARDS OF LEGEND!"
	linefw "IF YOU DON'T, I WON'T DUEL YOU!"
	done

Text08ff:
	text "6 PRIZE CARDS."
	linefw ""
	linefw "I'LL SHOW YOU HOW PATHETIC YOUR"
	linefw "POWER TRULY IS, YOU LITTLE WHELP!"
	done

Text0900:
	text "DO YOU NOT HAVE THE"
	linefw "POKÉMON CARDS OF LEGEND?"
	linefw "IF NOT, YOU'LL HAVE TO STRIKE SOME"
	linefw "SORT OF DEAL WITH THE GRAND MASTERS!"
	done

Text0901:
	text "GIVE IT UP, WHELP."
	linefw "EXECUTIVE ALLISON WILL WASTE YOU!"
	done

Text0902:
	text "I'VE BEEN STRATEGIZING A LOT"
	linefw "WHILE SPARRING WITH ALLISON."
	linefw "DO YOU WANT TO BATTLE ME?"
	linefw "I HAVE DECK REQUIREMENTS, REMEMBER."
	linefw "I WANT YOUR DECK TO CONTAIN"
	linefw "ALL OF THE POKÉMON CARDS OF LEGEND."
	linefw "IF YOU'VE GOT A DECK HANDY"
	linefw "SATISFYING THOSE RULES, LET'S FIGHT!"
	done

Text0903:
	text "WAIT JUST A SECOND,"
	linefw "<RAMNAME>", "."
	linefw "YOUR DECK DOESN'T CONTAIN ALL OF"
	linefw "THE POKÉMON CARDS OF LEGEND!"
	linefw "I DON'T WANT TO FIGHT AGAINST"
	linefw "ANYTHING ELSE. SORRY, BUDDY."
	done

Text0904:
	text "THEN PLEASE, GO SIT DOWN!"
	linefw "LET'S START OUR BATTLE."
	done

Text0905:
	text "SET DOWN 6 PRIZE CARDS."
	linefw "LET'S GO, ", "<RAMNAME>", "!"
	done

Text0906:
	text "I GET BORED FIGHTING AGAINST THE"
	linefw "SAME OLD CARDS DAY AFTER DAY."
	linefw "IF YOU DON'T MIND,"
	linefw "COME BACK SOMETIME FOR A BATTLE."
	done

Text0907:
	text "JUST LIKE KING VILLICCI,"
	linefw "I'VE LEARNED FROM MY MISTAKES."
	linefw "POKÉMON CARDS SHOULD BE LOVED"
	linefw "IN BATTLE AND OUT, ALL THE SAME."
	linefw "SINCE I'VE CHANGED MY BELIEFS,"
	linefw "WHAT DO YOU SAY? WANT TO BATTLE?"
	linefw "MY CONDITIONS ARE THE SAME: USE ALL"
	linefw "OF THE POKÉMON CARDS OF LEGEND."
	linefw "DOES THAT SOUND GOOD, ", "<RAMNAME>", "?"
	done

Text0908:
	text "I GUESS IT'S NO FLUKE THAT"
	linefw "YOU'VE MADE IT THIS FAR."
	done

Text0909:
	text "I WON'T LIE, WHELP... I ADMIT THAT"
	linefw "YOU DO HAVE SOME STRENGTH."
	linefw "YOU MAY HAVE WON AGAINST ME..."
	linefw "BUT ALLISON IS STILL HERE!!"
	linefw "THERE'S NO WAY YOU'LL BEAT HER."
	linefw "YOU'LL NEVER MAKE IT TO VILLICCI!"
	linefw "GO ON!"
	linefw "IT'S TIME TO FIGHT ALLISON!"
	done

Text090a:
	text "BAH...WHAT A WASTE OF MY TIME."
	linefw ""
	linefw "I'VE HAD BETTER DUELS FIGHTING THOSE"
	linefw "WIMPY CLUB MASTERS OF YOURS."
	done

Text090b:
	text "...YOUR BOOSTER PACKS."
	done

Text090c:
	text "THOUGH I LOST, I HAVE A STRANGE"
	linefw "FEELING...WHAT FEELING IS THIS?"
	done

Text090d:
	text "IT'S MY WIN, BUT..."
	linefw "IT MAY BE DIFFERENT NEXT TIME."
	done

Text090e:
	text "I GUESS I WAS DEFEATED AFTER ALL."
	linefw "BUT I STILL STAND BY ONE THOUGHT:"
	linefw "THE MOST IMPORTANT THING TO HAVE"
	linefw "DURING A CARD BATTLE IS FUN."
	done

Text090f:
	text "STRANGE...I WON, BUT I DON'T"
	linefw "FEEL HAPPY FOR THAT REASON."
	linefw "I THINK I GET MORE JOY OUT OF THE"
	linefw "ACT OF BATTLING THAN THE RESULT."
	linefw "IT FEELS FULFILLING..."
	done

Text0910:
	text "YOU CANNOT CHALLENGE ME YET."
	linefw "YOU MUST DEFEAT CLAY FIRST."
	done

Text0911:
	text "CLAY, PLEASE STEP ASIDE. EVERYTHING"
	linefw "RESTS ON MY SHOULDERS NOW."
	done

Text0912:
	text "AHH..."
	done

Text0913:
	text "HO HO... EVEN IF YOU DID BEAT CLAY,"
	linefw "YOU STILL MUST DEFEAT ME AS WELL."
	linefw "I USE ONE OF THREE SPECIAL RULES"
	linefw "AGAINST MY CHALLENGERS."
	done

Text0914:
	text "THE FIRST RULE IS 'TOUGH ESCAPE'."
	linefw ""
	linefw "ALL POKÉMON RETREATING TO THE BENCH"
	linefw "PAY 1 EXTRA ENERGY CARD TO DO SO."
	linefw "AS SUCH, POKÉMON NORMALLY PAYING 1"
	linefw "ENERGY TO RETREAT MUST NOW PAY 2."
	linefw "MY SECOND RULE IS 'BLACK HOLE'."
	linefw ""
	linefw "ALL CARDS PLACED INTO THE DISCARD"
	linefw "PILE ARE REMOVED FROM THE GAME."
	linefw "FINALLY, I MAY IMPLEMENT THE"
	linefw "'LOW RESISTANCE' RULE."
	linefw "THE REDUCTION THAT RESISTANCE HAS"
	linefw "ON ATTACKS IS -10 INSTEAD OF -30."
	linefw "WHEN YOU DUEL AGAINST ME, ONE OF"
	linefw "THESE 3 RULES WILL BE IN EFFECT."
	linefw "THAT SAID, WILL YOU FIGHT ME"
	linefw "OR WILL YOU WITHDRAW?"
	done

Text0915:
	text "WOULD YOU LIKE TO DUEL ALLISON?"
	done

Text0916:
	text "FOR THIS BATTLE, WE'LL USE THE"
	linefw "'TOUGH ESCAPE' RULE."
	linefw "ALL POKÉMON MUST PAY 1 ADDITIONAL"
	linefw "ENERGY CARD TO RETREAT."
	done

Text0917:
	text "LET'S GET STARTED WITH OUR"
	linefw "6 PRIZE CARD DUEL!"
	done

Text0918:
	text "FOR THIS BATTLE, WE'LL USE THE"
	linefw "'BLACK HOLE' RULE."
	linefw "ALL CARDS PLACED INTO THE DISCARD"
	linefw "PILE ARE REMOVED FROM PLAY."
	done

Text0919:
	text "FOR THIS BATTLE, WE'LL USE THE"
	linefw "'LOW RESISTANCE' RULE."
	linefw "ALL RESISTANCE REDUCTIONS ARE"
	linefw "-10 INSTEAD OF -30."
	done

Text091a:
	text "DO YOU NEED TIME TO PREPARE?"
	linefw "WELL, THAT'S JUST TIME WASTED."
	linefw "NO MATTER WHAT YOU CONJURE UP, THE"
	linefw "RESULT OF OUR DUEL WILL BE THE SAME."
	linefw "MY DECK IS PREPARED TO HANDLE ANY"
	linefw "CHALLENGER WITH EASE."
	done

Text091b:
	text "I UNDERSTAND NOW."
	linefw ""
	linefw "UNDER NO CIRCUMSTANCES SHOULD"
	linefw "ANYONE'S CARDS BE STOLEN."
	linefw "THE IMPORTANT THING IS TO HAVE FUN"
	linefw "WHILE PLAYING WITH YOUR CARDS."
	linefw "BUT MY SENSE OF FUN COMES FROM"
	linefw "THE THREE SPECIAL RULES I USE."
	done

Text091c:
	text "THEN PLEASE HAVE A SEAT"
	linefw "AT THE OTHER SIDE OF THE TABLE."
	done

Text091d:
	text "6 PRIZE CARDS WILL BE USED."
	linefw "LET'S HAVE A FUN CARD BATTLE!"
	done

Text091e:
	text "WHAT'S THE MATTER?"
	linefw "DON'T YOU FIND CARD BATTLES FUN?"
	done

Text091f:
	text "YOU'VE DONE WELL, ", "<RAMNAME>", "."
	done

Text0920:
	text "IT'S NO SURPRISE THAT YOU'VE WON"
	linefw "AGAINST BOTH CLAY AND ME."
	linefw "YOU HAVE SOME VERY UNIQUE AND"
	linefw "CUNNING TACTICS INDEED."
	done

Text0921:
	text "OH HO HO...THAT'S TOO BAD."
	linefw ""
	linefw "IF YOU CAN'T DEFEAT ME, YOU DON'T"
	linefw "STAND A CHANCE AGAINST VILLICCI."
	done

Text0922:
	text "YOU ARE INDEED STRONG."
	linefw "I ENJOYED OUR CARD BATTLE."
	done

Text0923:
	text "OH HO HO...IT FEELS GREAT TO HAVE"
	linefw "SUCH THRILLING CARD BATTLES."
	linefw "TAKE IT EASY, FRIEND!"
	done

Text0924:
	text "SO? DID YOU HAVE FUN"
	linefw "IN OUR CARD BATTLE?"
	done

Text0925:
	text "YOU CANNOT GO ON UNTIL YOU HAVE"
	linefw "DEFEATED THE BOTH OF US."
	done

Text0926:
	text "YOU CANNOT GO ON UNTIL YOU HAVE"
	linefw "DEFEATED ALLISON."
	done

Text0927:
	text "WHAT IN THE..."
	linefw "I'VE LOST..."
	linefw "HOW COULD I HAVE BEEN DEFEATED IN A"
	linefw "CARD BATTLE AGAINST YOU...TWICE?"
	linefw "YET I HAD INSURMOUNTABLE FUN"
	linefw "IN THESE DUELS...HOW COULD THIS BE?"
	linefw "MY HEART..."
	linefw "IT'S STILL BEATING SO FAST!"
	linefw "I'VE NEVER HAD SUCH FUN PLAYING"
	linefw "THE POKÉMON CARD GAME BEFORE!"
	linefw "THIS IS THE FIRST TIME I'VE EVER"
	linefw "LOST PLAYING THE POKÉMON CARD GAME."
	linefw "DO YOU REMEMBER WHAT I SAID BEFORE?"
	linefw "'CARDS ARE ONLY MEANT TO BE USED.'"
	linefw "I THOUGHT CARDS WERE ONLY USEFUL"
	linefw "WHEN THEY BROUGHT POWER TO A DECK."
	linefw "NOW I SEE DIFFERENTLY...THEY'RE ALL"
	linefw "TO HAVE FUN, EVEN WHEN COLLECTING!"
	linefw "NO MATTER HOW YOU USE YOUR POKÉMON"
	linefw "CARDS, YOU MUST ENJOY YOURSELF!"
	linefw "YOU MADE ME REALIZE THIS DURING"
	linefw "OUR CARD BATTLES!"
	linefw "<RAMNAME>", "..."
	linefw "THANK YOU VERY MUCH!"
	linefw "I GIVE MY WORD THAT WE SHALL STOP"
	linefw "STEALING CARDS FROM INNOCENT PEOPLE."
	linefw "POKÉMON CARDS OUGHT TO BE IN THE"
	linefw "HANDS OF THE PEOPLE WHO LOVE THEM."
	linefw "IF I'VE LEARNED ANYTHING FROM MY"
	linefw "CARDS, IT'S THE VALUE OF FRIENDS."
	linefw "HERE, TAKE THE INSIGNIA OF MY"
	linefw "FRIENDSHIP NOW!"
	done

Text0928:
	text "I'LL ALSO GIVE YOU THIS VERY RARE"
	linefw "CARD AS A GIFT FROM TEAM GR."
	done

Text0929:
	text "THAT RESOLVES OUR DISPUTE, THEN!"
	linefw "DON'T YOU AGREE, ", "<RAMNAME>", "?"
	linefw "LET'S BOTH CONTINUE ON, SHARING"
	linefw "PASSION FOR OUR POKÉMON CARDS!"
	done

Text092a:
	text "KING VILLICCI! YOUR EXECUTIVE,"
	linefw "CLAY, HAS BEEN DEFEATED!"
	done

Text092b:
	text "KING VILLICCI! YOUR EXECUTIVE,"
	linefw "ALLISON, HAS BEEN DEFEATED!"
	done

Text092c:
	text "HOHO, SO YOU MANAGED TO BEST BOTH"
	linefw "CLAY AND ALLISON, I SEE."
	linefw "THE TIME HAS COME FOR YOU AND I"
	linefw "TO HAVE OUR DECISIVE CARD BATTLE."
	linefw "CLAY! ALLISON!"
	linefw "BEGONE!"
	done

Text092d:
	text "WHEN YOU LOSE MISERABLY TO VILLICCI,"
	linefw "YOU'LL COME TO UNDERSTAND HIS POWER."
	linefw "YOU'LL FIND OUT THE HARD WAY"
	linefw "THAT TEAM GR IS IN THE RIGHT."
	done

Text092e:
	text "I'LL BE PLEASANTLY SURPRISED"
	linefw "IF YOU CAN DEFEAT VILLICCI."
	done

Text092f:
	text "WELL NOW,"
	linefw "<RAMNAME>", "!"
	done

Text0930:
	text "'POKÉMON CARDS ARE TO BE USED"
	linefw "SOLELY TO FIGHT AND WIN!'"
	linefw "IT IS UNDER THIS PHILOSOPHY"
	linefw "THAT I HAVE FOUNDED TEAM GR!"
	linefw "WHAT'S THE POINT IN COLLECTING CARDS"
	linefw "IF THEY ARE NOT USEFUL IN BATTLE?"
	done

Text0931:
	text "THEY MUST BE USED, I SAY!"
	done

Text0932:
	text "I HAVE RESCUED THE CARDS FROM THOSE"
	linefw "PATHETIC HOARDERS ON YOUR ISLAND."
	linefw "I HAVE INVENTED NEW WAYS TO BATTLE,"
	linefw "PUTTING THOSE WASTED CARDS TO USE!"
	linefw "THIS IS THE ULTIMATE FORM OF"
	linefw "DEVOTION TOWARDS POKÉMON CARDS!"
	linefw "THEY ARE NOT MEANT TO BE STASHED"
	linefw "AWAY LIKE OUR FOES DO WITH THEM!"
	done

Text0933:
	text "ONLY ONE WITH THE UTMOST RESPECT FOR"
	linefw "CARDS CAN BE THE MASTER OF THEM."
	linefw "I WILL NEVER BE DEFEATED BY A"
	linefw "SIMPLETON WHO MERELY COLLECTS THEM!"
	linefw "BUT THE TIME HAS COME! HAVE A SEAT."
	linefw "I SHALL DESTROY YOU IN A FIERY DUEL!"
	done

Text0934:
	text "I WILL BE SWITCHING BETWEEN MY FOUR"
	linefw "DECKS DURING OUR CARD BATTLES."
	linefw "OF COURSE, YOU WILL HAVE THE CHANCE"
	linefw "TO DO THE SAME WITH YOUR DECKS, TOO."
	linefw "LET US BEGIN OUR DECISIVE BATTLE."
	linefw ""
	linefw "THE FIRST PLAYER TO GAINS 2 TOTAL"
	linefw "WINS WILL BE DECLARED THE VICTOR."
	done

Text0935:
	text "SO YOU HAVE RETURNED TO DO BATTLE"
	linefw "WITH ME AT LAST. AM I CORRECT?"
	linefw "THE FIRST PLAYER TO GET 2 TOTAL"
	linefw "WINS WILL BE THE VICTOR."
	linefw "YOU'LL SOON LEARN TO FEAR THE POWER"
	linefw "OF MY FOUR FORMIDABLE DECKS."
	done

Text0936:
	text "WOULD YOU LIKE TO DUEL VILLICCI?"
	done

Text0937:
	text "SET ASIDE 6 PRIZE CARDS."
	linefw "NOW, WHICH DECK SHALL I USE?"
	done

Text0938:
	text "THAT IS FINE!"
	linefw "I WILL PATIENTLY WAIT."
	linefw "DO WHAT YOU FEEL YOU NEED TO DO WITH"
	linefw "YOUR CARDS TO PREPARE YOURSELF."
	linefw "NO MATTER! IT IS IMPOSSIBLE TO MATCH"
	linefw "THE STRENGTH OF MY CARDS!"
	linefw "EVEN SO, I WILL GLADLY ENTERTAIN A"
	linefw "CARD BATTLE WITH YOU!"
	linefw "MAKE YOUR PREPARATIONS AND RETURN"
	linefw "WHEN YOU ARE READY!"
	done

Text0939:
	text "GREETINGS, ", "<RAMNAME>", "."
	linefw "HOW HAVE YOUR BATTLES BEEN GOING?"
	linefw "WOULD YOU LIKE TO HAVE A CASUAL"
	linefw "BATTLE OR TWO WITH ME?"
	linefw "AS BEFORE,"
	linefw "WE'LL FIGHT TO TWO TOTAL VICTORIES."
	linefw "I'LL BE HAVING FUN USING MY FOUR"
	linefw "SPECIALLY CRAFTED DECKS!"
	done

Text093a:
	text "THEN LET'S HAVE SOME FUN!"
	linefw "WE'LL USE 6 PRIZE CARDS."
	done

Text093b:
	text "IN THAT CASE, I THINK I'LL GO HAVE"
	linefw "FUN CHALLENGING SOME OF MY MEMBERS."
	done

Text093c:
	text "I DO HOPE YOU DECIDE TO CHALLENGE"
	linefw "ME AGAIN. IT'LL BE FUN!"
	done

Text093d:
	text "THAT'S YOUR FIRST WIN!"
	linefw "LET'S CONTINUE ONTO THE NEXT DUEL!"
	linefw "YOU ARE FREE TO CHANGE YOUR DECKS."
	linefw "WHAT WILL YOU DO?"
	done

Text093e:
	text "THAT'S MY FIRST WIN."
	linefw "IF I WIN AGAIN, IT'S ALL OVER."
	linefw "YOU ARE FREE TO CHANGE YOUR DECKS."
	linefw "WHAT WILL YOU DO?"
	done

Text093f:
	text "SO NOW YOU HAVE ONE WIN"
	linefw "AND I HAVE ONE WIN..."
	linefw "THE NEXT DUEL WILL DETERMINE THE"
	linefw "ULTIMATE VICTOR OF OUR CARD BATTLE!"
	linefw "THERE'S NO WAY I COULD EVER LOSE AT"
	linefw "THE POKÉMON CARD GAME TO YOU."
	linefw "YOU MAY CHANGE YOUR DECKS IF YOU"
	linefw "LIKE. WHAT SAY YOU?"
	done

Text0940:
	text "WILL YOU SWITCH YOUR DECK?"
	done

Text0941:
	text "ARE YOU FINISHED MANAGING YOUR"
	linefw "DECKS, ", "<RAMNAME>", "?"
	done

Text0942:
	text "GOOD..."
	linefw "THEN LET US BEGIN THE NEXT BATTLE!"
	linefw "SET ASIDE YOUR 6 PRIZE CARDS"
	linefw "AND WE'LL START THE COMPETITION."
	done

Text0943:
	text "THAT'S YOUR FIRST WIN!"
	linefw "LET'S CONTINUE ONTO THE NEXT DUEL!"
	linefw "YOU ARE FREE TO CHANGE YOUR DECKS."
	linefw "WHAT WILL YOU DO?"
	done

Text0944:
	text "THAT'S MY FIRST WIN."
	linefw ""
	linefw "YOU MAY CHANGE YOUR DECKS IF YOU"
	linefw "LIKE. WHAT WILL YOU DO?"
	done

Text0945:
	text "SO NOW YOU HAVE 1 WIN"
	linefw "AND I HAVE 1 WIN..."
	linefw "THE NEXT DUEL WILL DETERMINE THE"
	linefw "ULTIMATE VICTOR OF OUR CARD BATTLE!"
	linefw "I WILL BE PLEASED NO MATTER WHO"
	linefw "WINS. FIGHTING YOU IS QUITE FUN!"
	linefw "YOU MAY CHANGE YOUR DECKS IF YOU"
	linefw "LIKE. WHAT SAY YOU?"
	done

Text0946:
	text "ARE YOU FINISHED MANAGING YOUR"
	linefw "DECKS, ", "<RAMNAME>", "?"
	done

Text0947:
	text "WE'LL USE 6 PRIZE CARDS."
	linefw "LET'S START DUEL NUMBER ", "<RAMNUM>", "."
	done

Text0948:
	text "I'VE WON!"
	linefw "I HAVE WON OUR DEFINITIVE BATTLE."
	linefw "HOWEVER..."
	linefw " "
	linefw "YOU DON'T SEEM TO ACCEPT THIS LOSS"
	linefw "AS THE END OF YOUR EFFORTS."
	linefw "I CAN SEE YOU'RE STILL PASSIONATE"
	linefw "ABOUT THE POKÉMON CARD GAME!"
	linefw "SHOW THAT FERVER TO ME! EVEN AT"
	linefw "YOUR BEST, I'LL ALWAYS DEFEAT YOU."
	done

Text0949:
	text "NO, NO!"
	linefw "I LOST AGAIN!"
	linefw "NO MATTER, THOUGH! I THOROUGHLY"
	linefw "ENJOYED OUR BATTLES, ", "<RAMNAME>", "."
	linefw "I THINK THAT FUN WAS WORTH GIVING"
	linefw "YOU ANOTHER SPECIAL CARD."
	done

Text094a:
	text "IT IS NOW MY BELIEF THAT THE PURPOSE"
	linefw "OF POKÉMON CARDS IS TO HAVE FUN."
	linefw "YOU'RE WELCOME IN OUR CASTLE ANY"
	linefw "TIME YOU WISH TO HAVE A CARD BATTLE."
	linefw "I SHALL ALSO GIVE YOU PERMISSION TO"
	linefw "TO ENTER THE SEALED FORTRESS."
	linefw "THERE ARE FORMIDABLE DECKS CONTAINED"
	linefw "WITHIN THAT BUILDING'S WALLS."
	linefw "THEY ARE DECKS EVEN I, THE GR KING,"
	linefw "AM AFRAID OF CONFRONTING."
	linefw "IT'S YOUR CHOICE TO INVESTIGATE IT"
	linefw "OR LET SUCH POWER BE."
	linefw "...EITHER WAY, BE CAREFUL. THEIR"
	linefw "POWER IS UNPREDICTABLE AND FIERCE."
	linefw "ALL I WISH IS FOR EVERYONE TO HAVE"
	linefw "FUN WITH THEIR POKÉMON CARDS!"
	done

Text094b:
	text "SINCE YOU'VE WON, I'LL REWARD YOU"
	linefw "WITH SOME BOOSTER PACKS."
	done

Text094c:
	text "MY BELIEF NOW IS THAT POKÉMON CARDS"
	linefw "ARE MEANT TO BE ENJOYED PERSONALLY."
	linefw "I ENJOY BATTLES, SO YOU'RE FREE TO"
	linefw "ASK FOR A DUEL WHENEVER YOU PLEASE."
	linefw "LET'S BOTH PURSUE OUR OWN DREAMS"
	linefw "WITH OUR POKÉMON CARDS!"
	done

Text094d:
	text "IT WAS MY VICTORY THIS TIME,"
	linefw "<RAMNAME>", "."
	linefw "YOU CAN'T EXPECT THE GREAT GR KING"
	linefw "TO LOSE TIME AFTER TIME!"
	done

Text094e:
	text "WE'RE CURRENTLY HOLDING A"
	linefw "CHALLENGE CUP TOURNAMENT!"
	linefw "THE WINNER OF THE TOURNAMENT WILL"
	linefw "GET A RARE MEWTWO Lv30 CARD."
	linefw "EACH DUEL IS WITH 4 PRIZE CARDS!"
	linefw "ONE LOSS, AND YOU'RE OUT!"
	linefw "NEW PARTICIPANTS CAN REGISTER"
	linefw "HERE WITH ME."
	linefw "WOULD YOU LIKE TO PARTICIPATE"
	linefw "IN THE CHALLENGE CUP?"
	done

Text094f:
	text "WE'RE CURRENTLY HOLDING A"
	linefw "CHALLENGE CUP TOURNAMENT!"
	linefw "THE WINNER OF THE TOURNAMENT WILL"
	linefw "GET A RARE PIKACHU Lv13 CARD."
	linefw "THE FIRST 2 MATCHES ARE WITH 4 PRIZE"
	linefw "CARDS! LOSE ONCE, AND YOU'RE OUT!"
	linefw "THE FINAL MATCH IS A NO-HOLDS-BARRED"
	linefw "DUEL WITH 6 PRIZE CARDS!"
	linefw "NEW PARTICIPANTS CAN REGISTER"
	linefw "HERE WITH ME."
	linefw "WOULD YOU LIKE TO PARTICIPATE"
	linefw "IN THE CHALLENGE CUP?"
	done

Text0950:
	text "WE'RE CURRENTLY HOLDING A"
	linefw "CHALLENGE CUP TOURNAMENT!"
	linefw "THE WINNER OF THE TOURNAMENT WILL"
	linefw "WIN THIS ", "<RAMTEXT>", " CARD."
	linefw "THE FIRST 2 MATCHES ARE WITH 4 PRIZE"
	linefw "CARDS! LOSE ONCE, AND YOU'RE OUT!"
	linefw "THE FINAL MATCH IS A NO-HOLDS-BARRED"
	linefw "DUEL WITH 6 PRIZE CARDS!"
	linefw "NEW PARTICIPANTS CAN REGISTER"
	linefw "HERE WITH ME."
	linefw "WOULD YOU LIKE TO PARTICIPATE"
	linefw "IN THE CHALLENGE CUP?"
	done

Text0951:
	text "CHALLENGERS WHO HAVE ALREADY PLAYED"
	linefw "MAY NOT PARTICIPATE IN THE SAME CUP."
	linefw "PLEASE TRY AGAIN IN THE NEXT"
	linefw "CHALLENGE CUP COMPETITION."
	done

Text0952:
	text "CHALLENGERS WHO HAVE ALREADY PLAYED"
	linefw "MAY NOT PARTICIPATE IN THE SAME CUP."
	linefw "PLEASE TRY AGAIN IN THE NEXT"
	linefw "CHALLENGE CUP COMPETITION."
	done

Text0953:
	text "PARTICIPATE IN THE CHALLENGE CUP?"
	done

Text0954:
	text "THEN PLEASE GO UP ONTO THE STAGE!"
	done

Text0955:
	text "I SEE. THAT'S TOO BAD."
	linefw "PLEASE COME AGAIN."
	done

Text0956:
	text "WE AREN'T CURRENTLY ACCEPTING"
	linefw "NEW CHALLENGERS HERE."
	linefw "PLEASE SPEAK TO THE RECEPTIONIST"
	linefw "ON THE OTHER SIDE OF THE STAGE."
	done

Text0957:
	text "AH, IT'S NO USE..."
	linefw "I SHOULDN'T HAVE EVEN COME."
	linefw "THERE WON'T BE A CHALLENGE CUP HELD"
	linefw "UNTIL EVERYONE'S CARDS ARE RETURNED."
	linefw "IF YOU DIDN'T KNOW, THE CHALLENGE"
	linefw "CUP IS A FAMOUS CARD TOURNAMENT."
	linefw "THE PRIZE FOR WINNING IT IS"
	linefw "A SPECIAL PROMOTIONAL CARD!"
	linefw "BUT I GUESS TEAM GR HAS TO GO AWAY"
	linefw "BEFORE IT CAN START, HUH?"
	done

Text0958:
	text "ARE YOU WAITING FOR THE"
	linefw "NEXT CHALLENGE CUP, TOO?"
	linefw "I CAN'T WAIT TO SEE WHAT RARE"
	linefw "CARD IS THE NEXT CUP'S PRIZE!"
	done

Text0959:
	text "WE'LL BE STARTING A NEW"
	linefw "CHALLENGE CUP IN A SHORT WHILE."
	linefw "I'VE SEEN YOU HERE QUITE A NUMBER OF"
	linefw "TIMES BEFORE. I HOPE YOU COME AGAIN!"
	linefw "THE MORE PLAYERS THAT JOIN IN,"
	linefw "THE MORE FUN THE EVENT BECOMES!"
	done

Text095a:
	text "THE CHALLENGE CUP IS UNDERWAY!"
	linefw ""
	linefw "HERE'S OUR CURRENT UNDEFEATED"
	linefw "PLAYER, ", "<RAMTEXT>", "!"
	done

Text095b:
	text "HERE'S OUR NEXT CHALLENGER,"
	linefw "<RAMNAME>", "!"
	done

Text095c:
	text "THE CHALLENGE CUP IS UNDERWAY!"
	linefw ""
	linefw "HERE'S OUR CURRENT UNDEFEATED"
	linefw "PLAYER, ", "<RAMTEXT>", "!"
	done

Text095d:
	text "HERE'S OUR NEW CHALLENGER!"
	linefw " "
	linefw "EVERYONE RECOGNIZES THIS PLAYER!"
	linefw "IT'S ", "<RAMNAME>", "!"
	done

Text095e:
	text "THE CHALLENGE CUP IS WELL UNDERWAY,"
	linefw "AND WE MAY HAVE OUR CHAMPION SOON!"
	linefw "PRESENTLY, ", "<RAMTEXT>"
	linefw "IS THE CONTENDER TO BEAT!"
	done

Text095f:
	text "EVERYONE HERE SHOULD RECOGNIZE"
	linefw "THIS NEW CHALLENGER!"
	linefw "IT'S THE POKÉMON CARD MASTER,"
	linefw "<RAMNAME>", "!"
	done

Text0960:
	text "ARE YOU BOTH READY?"
	linefw "PLACE YOUR 4 PRIZE CARDS FIRST!"
	linefw "NOW THEN!!"
	linefw "START THE COMPETITION!"
	done

Text0961:
	text "<RAMNAME>", " HAS WON!"
	linefw "CONGRATULATIONS!"
	linefw "<RAMNAME>", "!"
	linefw "YOU'VE GOT YOUR FIRST WIN!!"
	done

Text0962:
	text "ALRIGHT! NEXT CHALLENGER,"
	linefw "PLEASE COME UP ON THE STAGE!"
	done

Text0963:
	text "NEXT CHALLENGER!"
	linefw "PLEASE COME UP ON THE STAGE!"
	done

Text0964:
	text "<RAMNAME>", " HAS WON THE MATCH!"
	linefw "WHAT A TRUE POKÉMON CARD MASTER!"
	linefw "THAT WAS A SPECTACULAR DUEL!"
	linefw "<RAMNAME>", "!"
	linefw "YOU REMAIN UNDEFEATED!!"
	done

Text0965:
	text "NEXT CHALLENGER!"
	linefw "PLEASE COME UP ON THE STAGE!"
	done

Text0966:
	text "IT'S ", "<RAMTEXT>", "'S VICTORY!"
	linefw " "
	linefw "THAT'S ", "<RAMTEXT>", "'S FIRST WIN!"
	linefw "TWO MORE, AND WE HAVE A WINNER!"
	done

Text0967:
	text "IT'S ", "<RAMTEXT>", "'S VICTORY!"
	linefw " "
	linefw "THAT'S ", "<RAMTEXT>", "'S FIRST WIN!"
	linefw "TWO MORE, AND WE HAVE A WINNER!"
	done

Text0968:
	text "WHAT'S THIS?! THE POKÉMON CARD"
	linefw "MASTER ", "<RAMNAME>", " WAS DEFEATED!"
	linefw "<RAMTEXT>", " HAS WON THE MATCH!"
	linefw " "
	linefw "THAT'S ", "<RAMTEXT>", "'S FIRST WIN!"
	linefw "TWO MORE, AND WE HAVE A WINNER!"
	done

Text0969:
	text "WHAT BAD LUCK, ", "<RAMTEXT>", "."
	linefw "PLEASE TRY AGAIN NEXT TIME."
	done

Text096a:
	text "MEET OUR NEW CHALLENGER,"
	linefw "<RAMTEXT>", "!"
	done

Text096b:
	text "THE NEXT DUEL WILL BE"
	linefw "WITH 4 PRIZE CARDS."
	done

Text096c:
	text "<RAMNAME>", ", WOULD YOU LIKE TO"
	linefw "MODIFY OR CHANGE YOUR DECK?"
	done

Text096d:
	text "THEN PLEASE MAKE YOUR CHANGES!"
	done

Text096e:
	text "<RAMNAME>", " IS NOW READY!"
	linefw "LET'S START THE MATCH!"
	done

Text096f:
	text "CONGRATULATIONS, ", "<RAMNAME>", "!"
	linefw "YOU'VE GOT TWO TOTAL WINS!!"
	linefw "YOU'RE WELL ON YOUR WAY TO"
	linefw "BECOMING THE CHAMPION!"
	done

Text0970:
	text "WELL, WHO IS OUR NEXT CHALLENGER?"
	done

Text0971:
	text "FOR THE THIRD AND FINAL DUEL, WE'LL"
	linefw "REQUEST A CLUB MASTER TO COME FORTH!"
	linefw "WELL? WHICH CLUB MASTER WILL"
	linefw "CHALLENGE THIS PLAYER?"
	done

Text0972:
	text "THE NEXT BATTLE WITH BE A FULL"
	linefw "6-PRIZE-CARD BOUT!"
	linefw "WELL, WHO IS THE NEXT CHALLENGER?"
	done

Text0973:
	text "<RAMTEXT>", " HAS WON THE MATCH!"
	linefw " "
	linefw "THAT'S ", "<RAMTEXT>", "'S FIRST WIN!"
	linefw "TWO MORE DEFEATS SPELL VICTORY!"
	done

Text0974:
	text "<RAMTEXT>", " HAS WON!"
	linefw " "
	linefw "THE POKÉMON CARD MASTER"
	linefw "HAS BEEN DEFEATED!"
	linefw "THAT'S ", "<RAMTEXT>", "'S FIRST WIN!"
	linefw "TWO MORE SPELLS VICTORY!"
	done

Text0975:
	text "HERE'S OUR NEXT CHALLENGER,"
	linefw "<RAMTEXT>", "!"
	done

Text0976:
	text "THE FINAL CHALLENGER IS"
	linefw "CLUB MASTER ", "<RAMTEXT>", "!"
	done

Text0977:
	text "THE NEXT CHALLENGER IS"
	linefw "CLUB MASTER ", "<RAMTEXT>", "!"
	done

Text0978:
	text "THE FINAL CHALLENGER IS"
	linefw "<RAMTEXT>", ", FROM TEAM GR!"
	done

Text0979:
	text "AHH, WHAT A SURPRISE!"
	linefw "IT'S ", "<RAMTEXT>", "!"
	done

Text097a:
	text "I'M SORRY TO SAY IT, BUT YOU'RE"
	linefw "GOING TO LOSE TO THE MIGHTY RONALD!"
	done

Text097b:
	text "THIS CARD BATTLE WILL BE WAGED"
	linefw "WITH 6 PRIZE CARDS!"
	done

Text097c:
	text "<RAMNAME>", "! THIS IS YOUR"
	linefw "THIRD AND FINAL CHALLENGER! BEGIN!"
	done

Text097d:
	text "CONGRATULATIONS!"
	linefw "WE FOUND OUR TOURNAMENT WINNER!"
	done

Text097e:
	text "WE FOUND THE WINNER OF THE CHALLENGE"
	linefw "CUP COMPETITION! IT'S ", "<RAMNAME>", "!"
	done

Text097f:
	text "WE FOUND THE WINNER OF THE CHALLENGE"
	linefw "CUP, A TRUE POKÉMON CARD MASTER!"
	linefw "IT'S ", "<RAMNAME>", "!!"
	done

Text0980:
	text "IT'S ", "<RAMTEXT>", "'S WIN!"
	linefw " "
	linefw "THAT'S ", "<RAMTEXT>", "'S FIRST WIN!"
	linefw "TWO MORE, AND WE HAVE A WINNER!"
	done

Text0981:
	text "THE WIN GOES TO"
	linefw "CLUB MASTER ", "<RAMTEXT>", "!"
	linefw "<RAMNAME>", " WAS DEFEATED"
	linefw "BY THE CLUB MASTER!"
	done

Text0982:
	text "OH, WHAT BAD LUCK!"
	linefw "<RAMNAME>", " HAS LOST!!"
	linefw "THAT'S ", "<RAMTEXT>", "'S FIRST WIN!"
	linefw "TWO MORE, AND WE HAVE A WINNER!"
	done

Text0983:
	text "HERE YOU GO, ", "<RAMNAME>", ":"
	linefw "YOUR NEW MEWTWO Lv30 CARD!"
	done

Text0984:
	text "HERE YOU GO, ", "<RAMNAME>", ":"
	linefw "YOUR NEW PIKACHU Lv13 CARD!"
	done

Text0985:
	text "HERE YOU GO, ", "<RAMNAME>", ":"
	linefw "YOUR NEW ", "<RAMTEXT>", " CARD!"
	done

Text0986:
	text "WOW, ", "<RAMNAME>", "! ISN'T THIS"
	linefw "YOUR 10TH CHALLENGE CUP VICTORY?"
	linefw "TO COMMEMORATE YOUR 10TH WIN,"
	linefw "YOU GET A SPECIAL COIN!"
	done

Text0987:
	text "CONGRATULATIONS FOR BEING THE WINNER"
	linefw "OF 10 TOTAL CHALLENGE CUPS!"
	linefw "WELL DONE, ", "<RAMNAME>", "!"
	linefw "TAKE THIS PONYTA COIN!"
	done

Text0988:
	text "<RAMNAME>", "! ONCE MORE!"
	linefw "CONGRATULATIONS!"
	done

Text0989:
	text "SO SORRY, ", "<RAMNAME>", "."
	linefw "PLEASE TRY AGAIN NEXT TIME."
	done
