Text051a:
	text "A KNOCKED OUT ACTIVE POKÉMON MUST BE"
	linefw "REPLACED BY A POKÉMON ON THE BENCH."
	linefw "THE POKÉMON CURRENTLY ON YOUR BENCH"
	linefw "ARE PIDGEY AND NIDORAN."
	linefw "CHOOSE NIDORAN♂ TO PUT INTO THE"
	linefw "ARENA AS YOUR ACTIVE POKÉMON."
	done

Text051b:
	text "YOU MAY PRESS THE SELECT BUTTON AT"
	linefw "THIS TIME TO LOOK AT THE PLAY AREA."
	linefw "IT'S IMPORTANT TO KEEP TRACK OF"
	linefw "YOUR HAND AND WHAT'S IN PLAY."
	done

Text051c:
	text "PLEASE SELECT NIDORAN♂."
	done

Text051d:
	text "1. PUT THE MACHOP YOU JUST PICKED UP"
	linefw "   ONTO YOUR BENCH."
	done

Text051e:
	text "2. ATTACH ANOTHER ", "<GRASS>", " ENERGY TO"
	linefw "   NIDORAN♂."
	done

Text051f:
	text "3. USE NIDORAN♂'S HORN HAZARD"
	linefw "ATTACK."
	done

Text0520:
	text "REMEMBER TO PLACE ANY BASIC"
	linefw "POKÉMON YOU PICK UP ONTO YOUR BENCH."
	linefw "PUT THE MACHOP YOU JUST DREW"
	linefw "ONTO YOUR BENCH FIRST."
	done

Text0521:
	text "NIDORAN♂ CAN EVOLVE INTO NIDORINO,"
	linefw "BUT DON'T PLAY THAT CARD JUST YET."
	linefw "NIDORINO REQUIRES MORE ENERGY"
	linefw "TO USE ONE OF ITS ATTACKS."
	linefw "FOR NOW, LEAVE NIDORAN♂ AS IT IS AND"
	linefw "ATTACH A GRASS ENERGY TO IT."
	done

Text0522:
	text "FINALLY, USE NIDORAN♂'S "
	linefw "HORN HAZARD ATTACK."
	linefw "YOU WILL HAVE TO FLIP A COIN"
	linefw "TO SEE IF IT WORKS, THOUGH."
	done

Text0523:
	text "1. PLAY YOUR NIDORINO CARD ON YOUR"
	linefw "   NIDORAN♂ TO EVOLVE IT."
	done

Text0524:
	text "2. ATTACH A ", "<GRASS>", " ENERGY TO"
	linefw "   NIDORINO."
	done

Text0525:
	text "3. USE NIDORINO'S DOUBLE KICK"
	linefw "   ON SEAKING."
	done

Text0526:
	text "NOW IT'S TIME TO EVOLVE NIDORAN♂"
	linefw "INTO NIDORINO."
	linefw "CHOOSE NIDORINO FROM YOUR HAND AND"
	linefw "PLACE IT ON NIDORAN♂ TO EVOLVE IT."
	done

Text0527:
	text "NOW WE CAN GIVE NIDORINO ENOUGH"
	linefw "ENERGY TO USE ONE OF ITS ATTACKS."
	linefw "ATTACH A ", "<GRASS>", " FROM YOUR HAND TO"
	linefw "NIDORINO."
	done

Text0528:
	text "LET'S USE NIDORINO'S DOUBLE KICK"
	linefw "ATTACK!"
	linefw "THIS ATTACK REQUIRES COIN FLIPS TO"
	linefw "DETERMINE THE DAMAGE DONE."
	linefw "FLIP 2 COINS. YOU CAN DO UP TO"
	linefw "60 DAMAGE."
	linefw "IF YOU'RE LUCKY, YOU CAN KNOCK OUT"
	linefw "SEAKING IN ONE TURN. TRY IT!"
	done

Text0529:
	text "STEP 1"
	done

Text052a:
	text "STEP 2"
	done

Text052b:
	text "STEP 3"
	done

Text052c:
	text "STEP 4"
	done

Text052d:
	text "ADVICE 1"
	done

Text052e:
	text "ADVICE 2"
	done

Text052f:
	text "ADVICE 3"
	done

Text0530:
	text "ADVICE 4"
	done

Text0531:
	text "END"
	done

Text0532:
	text "   STEP 1   "
	linefw "CHECK DECK"
	linefw "ADVICE 1"
	linefw "ADVICE 2"
	linefw "ADVICE 3"
	linefw "RETURN"
	done

Text0533:
	text "   STEP 2   "
	linefw "ADVICE 1"
	linefw "ADVICE 2"
	linefw "ADVICE 3"
	linefw "RETURN"
	done

Text0534:
	text "   STEP 3   "
	linefw "ADVICE 1"
	linefw "ADVICE 2"
	linefw "ADVICE 3"
	linefw "RETURN"
	done

Text0535:
	text "   STEP 4   "
	linefw "ADVICE 1"
	linefw "ADVICE 2"
	linefw "ADVICE 3"
	linefw "ADVICE 4"
	linefw "RETURN"
	done

Text0536:
	text "<RAMTEXT>", " DECK"
	done

Text0537:
	text "ENERGY CARDS          "
	linefw "BASIC POKÉMON CARDS   "
	linefw "STAGE 1 POKÉMON CARDS "
	linefw "STAGE 2 POKÉMON CARDS "
	linefw "TRAINER CARDS         "
	done

Text0538:
	text "GRASS"
	done

Text0539:
	text "WATER"
	done

Text053a:
	text "ELECTRIC"
	done

Text053b:
	text "FIRE"
	done

Text053c:
	text "FIGHTING"
	done

Text053d:
	text "PSYCHIC"
	done

Text053e:
	text "WELCOME TO DR. MASON'S"
	linefw "DECK DIAGNOSIS PROGRAM!"
	done

Text053f:
	text "BASIC DECK-BUILDING ADVICE"
	done

Text0540:
	text "ADVICE FOR NOVICES"
	done

Text0541:
	text "ADVICE FOR INTERMEDIATE PLAYERS"
	done

Text0542:
	text "ADVICE FOR EXPERT PLAYERS"
	done

Text0543:
	text "END DIAGNOSIS"
	done

Text0544:
	text "I TAKE A LOOK AT ONE OF YOUR DECKS!"
	done

Text0545:
	text "BASIC POKÉMON ARE THE FOUNDATION"
	linefw "OF YOUR POKÉMON CARD DECK!"
	done

Text0546:
	text "DON'T FORGET TO PUT IN ENOUGH"
	linefw "ENERGY CARDS!"
	done

Text0547:
	text "THINK ABOUT BALANCE WHEN"
	linefw "YOU USE EVOLUTION CARDS!"
	done

Text0548:
	text "RETURN TO MAIN MENU"
	done

Text0549:
	text "START WITH BILL AND"
	linefw "PROFESSOR OAK CARDS."
	done

Text054a:
	text "TRY USING MORE"
	linefw "POTION AND SWITCH CARDS."
	done

Text054b:
	text "CONFUSION, PARALYSIS, POISON, "
	linefw "AND SLEEP CALL FOR FULL HEAL!"
	done

Text054c:
	text "FIRST, TRY A DECK WITH 2 TYPES!"
	done

Text054d:
	text "NEXT, TRY A DECK WITH 3 TYPES!"
	done

Text054e:
	text "LET'S THINK ABOUT"
	linefw "THE DECK'S PROBLEMS"
	done

Text054f:
	text "LET'S TALK ABOUT THE COMMON"
	linefw "CHARACTERISTICS OF EACH ENERGY TYPE."
	done

Text0550:
	text "INCLUDING COLORLESS POKÉMON CAN"
	linefw "REALLY HELP YOU OUT!"
	done

Text0551:
	text "HOW TO USE THE PROF. OAK CARD."
	done

Text0552:
	text "HOW TO FIGHT AGAINST SPEEDY"
	linefw "AND DEFENSIVE DECKS"
	done

Text0553:
	text "WHICH DECK WOULD YOU LIKE TO CHECK?"
	done

Text0554:
	text "CHECKING YOUR "
	linefw "<RAMTEXT>", " DECK..."
	done

Text0555:
	text "THESE ARE THE CARD TYPE AMOUNTS FOR"
	linefw "YOUR ", "<RAMTEXT>", " DECK."
	done

Text0556:
	text "RARE CARDS:"
	linefw "<RAMTEXT>"
	done

Text0557:
	text "CARDS WITH NO EVOLUTIONS:"
	linefw "<RAMTEXT>"
	done

Text0558:
	text "MISMATCHING ENERGY CARDS:"
	linefw "<RAMTEXT>"
	done

Text0559:
	text "CARDS WITH POKÉMON POWERS:"
	linefw "<RAMTEXT>"
	done

Text055a:
	text "DO YOU WANT TO CHECK ANOTHER DECK?"
	done

Text055b:
	text "BASIC POKÉMON CARDS ARE THE"
	linefw "FOUNDATION OF ANY POKÉMON CARD DECK."
	linefw "FROM THE START OF A DUEL, YOU CAN"
	linefw "PLAY THEM AND BE READY TO FIGHT."
	linefw "IF YOU DON'T HAVE ANY BASIC POKÉMON"
	linefw "CARDS, YOU CAN'T BATTLE AT ALL."
	linefw "ADDITIONALLY, YOU WON'T BE ABLE"
	linefw "TO PLAY EVOLUTION CARDS!"
	done

Text055c:
	text "BECAUSE OF THIS, YOU'LL WANT TO"
	linefw "INCLUDE A FAIR NUMBER OF BASIC"
	linefw "POKÉMON CARDS IN YOUR DECK."
	linefw "12 SHOULD BE A GOOD NUMBER."
	done

Text055d:
	text "DON'T FORGET TO PUT ENOUGH"
	linefw "ENERGY CARDS INTO YOUR DECK!"
	linefw "WITHOUT ENERGY, YOUR POKÉMON WON'T"
	linefw "BE ABLE TO USE ANY OF THEIR ATTACKS!"
	linefw "IF YOU CAN'T ATTACK, YOU CAN'T"
	linefw "PROPERLY BATTLE ANY OPPONENT."
	linefw "IT'S FOR THIS REASON THAT ENERGY"
	linefw "CARDS ARE ESSENTIAL TO ANY DECK."
	done

Text055e:
	text "ENERGY TYPE IS IMPORTANT TO NOTE"
	linefw "AS WELL. IF YOUR ENERGY TYPE DOES"
	linefw "NOT MATCH THE TYPE REQUIRED FOR YOUR"
	linefw "POKÉMON'S ATTACKS, MANY ATTACKS MAY"
	linefw "NOT BE USED. MAKE SURE YOUR POKÉMON"
	linefw "ATTACK REQUIREMENTS MATCH YOUR"
	linefw "ENERGY TYPES!"
	done

Text055f:
	text "EVERY POKÉMON MONSTER CARD IS ONE"
	linefw "OF 3 DIFFERENT STAGES. BASIC POKÉMON"
	linefw "MAY BE PLAYED IMMEDIATELY AT ANY"
	linefw "TIME. STAGE 1 EVOLUTION CARDS CAN"
	linefw "ONLY BE PLAYED ONTO THEIR SPECIFIED"
	linefw "BASIC POKÉMON CARDS, AND STAGE 2"
	linefw "EVOLUTION CARDS CAN ONLY BE PLAYED"
	linefw "ONTO THEIR SPECIFIED STAGE 1 CARDS."
	done

Text0560:
	text "BECAUSE OF THESE RESTRICTIONS, IT'S"
	linefw "USUALLY BEST TO MAKE A CASCADE OF"
	linefw "EVOLUTION CARDS. SO, IF YOU HAVE"
	linefw "FOUR BASIC POKÉMON, INCLUDE THREE"
	linefw "STAGE 1 EVOLUTION CARDS AND TWO"
	linefw "STAGE 2 EVOLUTION CARDS."
	done

Text0561:
	text "BILL AND PROFESSOR OAK TRAINER CARDS"
	linefw "ARE A GREAT ASSET TO ANY DECK!"
	linefw "IT'S GENERALLY A GOOD IDEA TO"
	linefw "INCLUDE 2 OF EACH IN YOUR DECKS."
	done

Text0562:
	text "TO KEEP YOUR DECK FIGHTING FIT,"
	linefw "TRY USING SWITCH AND POTION CARDS."
	linefw "I'D SUGGEST AROUND 3 POTIONS"
	linefw "AND 2 SWITCH CARDS FOR MAXIMUM"
	linefw "EFFECTIVENESS."
	done

Text0563:
	text "YOUR POKÉMON WILL BE IN TROUBLE"
	linefw "IF THEY GET AFFLICTED WITH SLEEP,"
	linefw "CONFUSION, PARALYSIS, OR POISON!"
	linefw "THE FULL HEAL TRAINER CARD WILL"
	linefw "INSTANTLY CURE THESE CONDITIONS."
	linefw "TRY USING 1-2 OF THESE CARDS"
	linefw "IN YOUR DECK TO BE SAFE!"
	done

Text0564:
	text "A SIMPLE MONO-TYPE DECK CAN BE MADE"
	linefw "OF 2 TYPES: COLORLESS AND ONE OTHER"
	linefw "TYPE OF YOUR CHOICE."
	linefw "SINCE COLORLESS POKÉMON DO NOT HAVE"
	linefw "SPECIFIC ENERGY TYPE REQUIREMENTS,"
	linefw "YOU'LL NEVER HAVE ENERGY TYPE"
	linefw "ISSUES. WATCH OUT FOR COMMON"
	linefw "WEAKNESSES, HOWEVER!"
	done

Text0565:
	text "FOR EXAMPLE, A DECK MADE ENTIRELY"
	linefw "OF ELECTRIC POKÉMON HAS NO REAL"
	linefw "DEFENSE AGAINST A DECK OF FIGHTING"
	linefw "POKÉMON."
	linefw "FIGHTING POKÉMON, ON THE OTHER HAND,"
	linefw "ARE USUALLY WEAK TO PSYCHIC POKÉMON,"
	linefw "THOUGH SOME COLORLESS CARDS"
	linefw "(NORMAL TYPES) RESIST PSYCHIC."
	done

Text0566:
	text "FIRE POKÉMON ARE COMMONLY WEAK TO"
	linefw "WATER, SO TRY TO BALANCE THE DECK"
	linefw "WITH POKÉMON STRONG AGAINST WATER."
	linefw "ELECTRIC POKÉMON ARE WEAK TO"
	linefw "FIGHTING, SO TRY USING SOME"
	linefw "COLORLESS POKÉMON WHICH RESIST"
	linefw "FIGHTING (FLYING TYPES)."
	done

Text0567:
	text "IN OTHER WORDS,"
	linefw "A DECK OF FIRE, ELECTRIC, AND"
	linefw "COLORLESS (FLYING TYPES) POKÉMON"
	linefw "IS READY FOR ANYTHING."
	done

Text0568:
	text "USING 3 TYPES CAN MAKE FOR"
	linefw "QUITE A FASCINATING DECK!"
	linefw "TO FACILITATE THE USE OF 3"
	linefw "DIFFERENT TYPES OF ENERGY CARDS,"
	linefw "MAKE SURE TO INCLUDE 2-4"
	linefw "ENERGY RETRIEVAL CARDS."
	done

Text0569:
	text "FOR EXAMPLE,"
	linefw "A FIRE, ELECTRIC, AND GRASS DECK"
	linefw "MAY MAKE YOU STUMPED OR BURNT OUT"
	linefw "TRYING TO CHARGE YOUR POKÉMON..."
	linefw "HA HA HA!"
	done

Text056a:
	text "AFTER YOU'VE BATTLED USING YOUR"
	linefw "DECK A FEW TIMES, TRY TO THINK OF"
	linefw "THE PROBLEMS ITS BALANCE MAY HAVE."
	linefw "IF YOUR BENCH IS FREQUENTLY EMPTY,"
	linefw "ADD SOME MORE BASIC POKÉMON CARDS."
	linefw "IF YOU'RE ALWAYS LOW ON ENERGY,"
	linefw "INCREASE THE NUMBER OF ENERGY CARDS."
	done

Text056b:
	text "BALANCE IS A VERY IMPORTANT PART"
	linefw "OF ANY DECK."
	linefw "YOU MAY NEED TO FOREGO SOME"
	linefw "TRAINER OR EVOLUTION CARDS TO"
	linefw "MAKE ROOM FOR THE NECESSITIES."
	linefw "EXPERIMENT WITH DIFFERENT"
	linefw "COMBINATIONS TO ENJOY YOUR DUELS!"
	done

Text056c:
	text " -CHARACTERISTICS OF ENERGY TYPES-"
	linefw ""
	linefw "IF YOUR DECK HAS LOTS OF FIRE-TYPE"
	linefw "POKÉMON IN IT, TRY TO HAVE AT LEAST"
	linefw "2 ENERGY RETRIEVAL CARDS. MANY FIRE"
	linefw "POKÉMON REQUIRE DISCARDING ENERGY"
	linefw "IN ORDER TO USE THEIR ATTACKS."
	done

Text056d:
	text "ELECTRIC POKÉMON ARE KNOWN FOR"
	linefw "HAVING ATTACKS THAT DAMAGE"
	linefw "THEMSELVES AS WELL AS THEIR"
	linefw "OPPONENTS. IT WOULD BE A GOOD IDEA"
	linefw "TO INCLUDE 2 DEFENDER CARDS TO"
	linefw "OFFSET SOME OF THAT SELF-INFLICTED"
	linefw "DAMAGE."
	done

Text056e:
	text "SINCE GRASS POKÉMON TYPICALLY HAVE"
	linefw "STAGE 2 EVOLUTION FORMS, YOU'LL"
	linefw "WANT TO FACILITATE THAT GROWTH."
	linefw "TRY USING A COUPLE POKÉMON BREEDERS"
	linefw "AND POKÉMON TRADER CARDS TO ENSURE"
	linefw "YOUR POKÉMON POWER UP."
	done

Text056f:
	text "THERE ARE LOTS OF WATER POKÉMON"
	linefw "WITH ATTACKS THAT GET ENHANCED"
	linefw "DAMAGE DEPENDING ON THE AMOUNT OF"
	linefw "EXTRA WATER ENERGY CARDS ATTACHED."
	linefw "IF YOU USE THESE POKÉMON, MAKE SURE"
	linefw "TO INCLUDE PLENTY OF ENERGY CARDS."
	done

Text0570:
	text "FIGHTING POKÉMON USUALLY REQUIRE"
	linefw "A LOT OF ENERGY TO RETREAT."
	linefw "IF YOUR DECK SPORTS A FAIR AMOUNT"
	linefw "OF FIGHTING POKÉMON, MAKE SURE"
	linefw "TO HAVE 2-4 SWITCH CARDS."
	done

Text0571:
	text "TO GET AROUND THE COMMON RESISTANCES"
	linefw "TO PSYCHIC POKÉMON ATTACKS, INCLUDE"
	linefw "2-4 GUST OF WIND CARDS IN YOUR DECK."
	linefw ""
	linefw "IF YOU HAVE SOME COLORLESS POKÉMON"
	linefw "IN YOUR DECK, MAKE SURE TO HAVE 4"
	linefw "DOUBLE COLORLESS ENERGY CARDS, TOO."
	done

Text0572:
	text "COLORLESS POKÉMON ARE EASY TO"
	linefw "INCLUDE IN ANY DECK SINCE YOU CAN"
	linefw "POWER UP THEIR ATTACKS WITH ANY"
	linefw "ENERGY TYPE. FLYING-TYPE POKÉMON"
	linefw "HAVE RESISTANCES THAT COVER NORMAL"
	linefw "POKÉMON'S WEAKNESSES, TOO!"
	done

Text0573:
	text "IF YOU DECIDE TO USE COLORLESS"
	linefw "POKÉMON IN YOUR DECK, REMEMBER TO"
	linefw "INCLUDE 2-4 DOUBLE COLORLESS ENERGY"
	linefw "CARDS AS WELL."
	linefw "COLORLESS ENERGY IS USEFUL IN DECKS"
	linefw "OF ANY TYPE, TOO, AND MAY MAKE SOME"
	linefw "POKÉMON POWER UP ATTACKS FASTER."
	done

Text0574:
	text "SOME EXAMPLES OF NON-COLORLESS"
	linefw "POKÉMON ATTACKS THAT WOULD BENEFIT"
	linefw "FROM DOUBLE COLORLESS ENERGY ARE"
	linefw "MACHOP'S PUNCH, PONYTA'S SMASH KICK,"
	linefw "SQUIRTLE'S SHELL ATTACKS, AND"
	linefw "SCYTHER'S SLASH."
	done

Text0575:
	text "PROF. OAK IS A HELPFUL CARD THAT CAN"
	linefw "GET YOU OUT OF STICKY SITUATIONS."
	linefw "IF, FOR INSTANCE, YOU START A DUEL"
	linefw "WITH FEW BASIC POKÉMON IN YOUR HAND"
	linefw "OR LITTLE ENERGY, YOU CAN DISCARD"
	linefw "THE WHOLE THING AND DRAW 7 NEW"
	linefw "CARDS!"
	done

Text0576:
	text "ADVANCING YOUR CARDS COULD"
	linefw "DRASTICALLY AFFECT THE OUTCOME OF"
	linefw "THE MATCH AND GIVE YOU A COMPLETE"
	linefw "REVERSAL OF FORTUNE."
	linefw "IT'S ALWAYS A GOOD IDEA TO KEEP"
	linefw "2 PROF. OAK CARDS IN YOUR DECKS."
	done

Text0577:
	text "         -SPEEDY DECKS-"
	linefw "POKÉMON LIKE STARYU, MACHOP, OR"
	linefw "VOLTORB HAVE ATTACKS THAT DO 20"
	linefw "DAMAGE AND ONLY TAKE 1 ENERGY CARD."
	linefw "THIS FAST DAMAGE IS GREAT, BUT IT"
	linefw "CAN BECOME HARD TO KEEP THESE"
	linefw "POKÉMON ALIVE IN LONGER DUELS."
	done

Text0578:
	text "        -DEFENSIVE DECKS-"
	linefw "BASIC POKÉMON LIKE ONIX, CHANSEY,"
	linefw "AND LICKITUNG HAVE A LOT OF HP."
	linefw "THEY EFFECTIVELY COUNTER SPEEDY"
	linefw "POKÉMON WITH FAST, HARD-HITTING"
	linefw "ATTACKS."
	done

Text0579:
	text "YOU SEEM TO HAVE A SMALL NUMBER OF"
	linefw "BASIC POKÉMON CARDS IN THIS DECK."
	linefw "PUT IN A FEW MORE BASIC POKÉMON AND"
	linefw "IT SHOULD BE MUCH MORE EFFECTIVE."
	done

Text057a:
	text "YOU SHOULD IDEALLY HAVE UP TO THREE"
	linefw "TYPES OF POKÉMON IN A DECK."
	linefw "FEEL FREE TO USE COLORLESS POKÉMON"
	linefw "WITH ANY OTHER TYPES, THOUGH."
	done

Text057b:
	text "YOU DON'T SEEM TO HAVE ENOUGH"
	linefw "POKÉMON CARDS INCLUDED IN THIS DECK."
	linefw "PUT A FEW MORE POKÉMON MONSTER CARDS"
	linefw "IN OF YOUR CHOICE."
	done

Text057c:
	text "YOU SEEM TO HAVE TOO MANY POKÉMON"
	linefw "MONSTER CARDS INCLUDED IN THIS DECK."
	linefw "REDUCE THE NUMBER OF POKÉMON CARDS"
	linefw "AND ADD IN SOME OTHER CARD TYPES."
	done

Text057d:
	text "YOUR ENERGY CARD COUNT IS"
	linefw "DANGEROUSLY LOW!"
	linefw "PUT IN SOME MORE ENERGY CARDS"
	linefw "TO SUPPORT YOUR POKÉMON."
	done

Text057e:
	text "YOUR ENERGY CARD COUNT IS"
	linefw "EXCESSIVELY HIGH!"
	linefw "REDUCE THE NUMBER OF ENERGY CARDS"
	linefw "IN YOUR DECK."
	done

Text057f:
	text "YOU BLOCKHEAD! YOU DON'T HAVE A"
	linefw "SINGLE ENERGY CARD IN THIS DECK!"
	linefw "WITHOUT ENERGY CARDS, YOUR POKÉMON"
	linefw "CAN'T DO ANYTHING!!"
	done

Text0580:
	text "YOU HAVE EVOLUTION CARDS WITHOUT"
	linefw "THE POKÉMON CARDS THEY EVOLVE FROM."
	done

Text0581:
	text "SOME OF YOUR EVOLUTION CARDS ARE"
	linefw "MISSING THEIR PRE-EVOLUTION CARDS."
	done

Text0582:
	text "YOU NEED TO BALANCE YOUR BASIC,"
	linefw "STAGE 1, AND STAGE 2 POKÉMON CARDS."
	done

Text0583:
	text "YOU NEED TO BALANCE YOUR DARK"
	linefw "EVOLUTION CARD COUNT."
	done

Text0584:
	text "YOU SHOULD BALANCE THE DIFFERENT"
	linefw "TYPES OF POKÉMON AND ENERGY CARDS."
	done

Text0585:
	text "YOUR ENERGY CARD TYPES DON'T MATCH"
	linefw "THE TYPES OF YOUR POKÉMON."
	done

Text0586:
	text "THERE SEEMS TO BE TOO LITTLE ENERGY"
	linefw "COMPARED TO THE NUMBER OF POKÉMON."
	linefw "INCREASE YOUR ENERGY CARD COUNT SO"
	linefw "YOUR POKÉMON CAN ATTACK WELL!"
	done

Text0587:
	text "THERE SEEMS TO BE FAR TOO MUCH"
	linefw "<RAMTEXT>", " ENERGY."
	linefw "WHY NOT TRY REDUCING THE AMOUNT OF"
	linefw "<RAMTEXT>", " ENERGY CARDS?"
	done

Text0588:
	text "YOU DON'T SEEM TO HAVE ENOUGH"
	linefw "<RAMTEXT>", " ENERGY IN THIS DECK."
	linefw "WHY DON'T YOU TRY INCREASING THE"
	linefw "<RAMTEXT>", " ENERGY CARD COUNT?"
	done

Text0589:
	text "THERE SEEMS TO BE FAR TOO MANY"
	linefw "<RAMTEXT>", " ENERGY CARDS."
	linefw "WHY NOT TRY ADJUSTING THE RATIO OF"
	linefw "<RAMTEXT>", " ENERGY CARDS?"
	done

Text058a:
	text "THERE IS A DECENT AMOUNT OF BASIC"
	linefw "POKÉMON IN THIS DECK."
	linefw "IN THAT CASE, THIS DECK IS IN PRIME"
	linefw "SHAPE TO BATTLE RIGHT AWAY!"
	done

Text058b:
	text "THE NUMBER OF BASIC POKÉMON"
	linefw "IN THIS DECK IS ALRIGHT."
	linefw "THAT'S THE MOST IMPORTANT THING"
	linefw "FOR ANY DECK TO HAVE."
	linefw "YOU HAVEN'T USED A SINGLE"
	linefw "TRAINER CARD, THOUGH!"
	linefw "TRAINER CARDS ARE VERY USEFUL."
	linefw "I SUGGEST TRYING SOME OUT."
	done
