Text1228:
	text "OH, OH? YOU'RE NOT IN TEAM GR."
	linefw "I WONDER WHAT YOUR BUSINESS HERE IS?"
	linefw "ME? I'M JACOB, ONE OF TEAM GR'S"
	linefw "WATER FORTRESS MEMBERS."
	linefw "I USED THE POWER OF WATER TO BECOME"
	linefw "ONE SMOOTH DUDE. JUST KIDDING!"
	linefw "I THINK I'VE GOT THE PICTURE."
	linefw "YOU'RE ", "<RAMNAME>", ", RIGHT?"
	linefw "TEAM GR'S WATER LEADER, BROOKE,"
	linefw "TOTALLY ADMIRES YOU, KID!"
	linefw "HAVE A CARD BATTLE WITH ME!"
	linefw "IF YOU WIN, I'LL OPEN THE DOORS."
	linefw "BUT I HAVE A SPECIAL RULE!"
	linefw "I WON'T BATTLE WITHOUT USING IT!"
	linefw "THE ONLY TYPE OF ENERGY CARD YOU MAY"
	linefw "USE IN YOUR DECK IS WATER ENERGY!"
	linefw "I'M SURE YOU UNDERSTAND!"
	linefw "IF YOU'VE GOT IT, LET'S BATTLE!"
	done

Text1229:
	text "IF YOU'RE AFTER A BRAWL WITH BROOKE,"
	linefw "YOU NEED TO FIGHT ME FIRST, KID!"
	linefw "BUT YOU CAN ONLY USE WATER ENERGY"
	linefw "CARDS IN YOUR DUELLING DECK!"
	linefw "I'M SURE YOU DIDN'T FORGET!"
	linefw "IF YOU REMEMBERED, LET'S FIGHT!"
	done

Text122a:
	text "WOULD YOU LIKE TO DUEL JACOB?"
	done

Text122b:
	text "WAIT! YOU NEED TO CHANGE UP YOUR"
	linefw "DECK TO CONFORM TO MY RULE FIRST!"
	linefw "YOU HAVE ENERGY IN YOUR DECK RIGHT"
	linefw "NOW THAT ISN'T WATER ENERGY!"
	linefw "YOU GET THE RULE NOW?"
	linefw "GO ON, MAKE YOUR CHANGES!"
	done

Text122c:
	text "BECAUSE I LIKE THE NUMBER 4,"
	linefw "WE'LL USE 4 PRIZE CARDS!"
	done

Text122d:
	text "OH, RUN ALONG THEN!"
	linefw "I DON'T MIND, KID."
	linefw "IT'S NO SKIN OFFA MY BACK!"
	done

Text122e:
	text "DID YOU COME BACK? SO PERSISTENT!"
	linefw "I GET YOUR VIBES. LET'S FIGHT!"
	linefw "I'LL ONLY FIGHT YOU IF YOUR DECK HAS"
	linefw "PURELY WATER-TYPE ENERGY CARDS."
	linefw "SINCE IT'S INEVITABLE, I'LL DUEL YA."
	linefw "I HOPE YOU'RE PREPARED!"
	done

Text122f:
	text "HEY, NOW, YOU'D BETTER COMPOSE YOUR"
	linefw "DECK A LITTLE BETTER THAN THAT!"
	linefw "YOU'VE GOT ENERGY THAT'S NOT WATER-"
	linefw "TYPE IN YOUR DECK, SO IT'S A NO-GO!"
	done

Text1230:
	text "I'LL FIGHT YOU WITH 4 PRIZE CARDS,"
	linefw "AND ONLY 4 PRIZE CARDS!"
	done

Text1231:
	text "IF YOU'RE NOT INTERESTED IN A DUEL,"
	linefw "PLEASE DON'T SPEAK TO ME, KID!"
	linefw "I'VE GOT STRICT ORDERS GIVEN"
	linefw "TO ME BY BROOKE TO UPHOLD!"
	done

Text1232:
	text "KEEEE!! UNBELIEVEABLE!"
	linefw "I WAS DEFEATED!!"
	linefw "CRAP!"
	linefw "I GOTTA GIVE YOU A BOOSTER PACK!"
	linefw "IF I HAD IT MY WAY?"
	linefw "I WOULD GIVE YOU DIDDLEY-SQUAT."
	linefw "I'M ONLY GIVING THIS TO YOU BECAUSE"
	linefw "BROOKE GAVE ME SPECIAL ORDERS!!"
	done

Text1233:
	text "ERGH...EVEN THOUGH I DON'T LIKE IT,"
	linefw "I HAVE TO BE COURTEOUS."
	linefw "THAT'S ANOTHER OF BROOKE'S ORDERS."
	done

Text1234:
	text "DUDE"
	done

Text1235:
	text "GIRL"
	done

Text1236:
	text "HOOHOO! WITH A DECK LIKE THAT,"
	linefw "YOU'LL NEVER BE ABLE TO BEAT ME!!"
	linefw "WHY DON'T YOU TRY CHANGING IT UP"
	linefw "A BIT BEFORE DUELLING AGAIN?"
	linefw "MAYBE YOU'LL MAKE IT A LITTLE"
	linefw "BETTER, ", "<RAMTEXT>", "."
	done

Text1237:
	text "WHAT? AFTER ALL OF THAT PLANNING!"
	linefw "I LOST AGAIN! NOOOOO!!!"
	done

Text1238:
	text "I'LL NEVER ADMIT THIS LOSS TO"
	linefw "ANYONE!!"
	done

Text1239:
	text "HOOHOO! YOU COULDN'T DEFEAT ME"
	linefw "THIS TIME!! WANNA KNOW WHY?"
	linefw "'CAUSE I'M ONE TOUGH COOKIE!"
	done

Text123a:
	text "I'LL OPEN THE DOORS LEADING TO CODY!"
	done

Text123b:
	text "LOOK, WE'RE DONE HERE!"
	linefw " "
	linefw "GO ON AHEAD QUICKLY."
	linefw "I'M TIRED OF SEEING YOUR FACE!!"
	done

Text123c:
	text "HEY THERE, I'M CODY!"
	linefw "I'M A WATER TEAM GR MEMBER!"
	linefw "WE'RE THE ONES WHO CAUGHT AND ARE"
	linefw "HOLDING GRAND MASTER JACK!"
	linefw "I'LL RELEASE JACK AND LET YOU INTO"
	linefw "THE NEXT ROOM IF YOU CAN BEAT ME!"
	linefw "OF COURSE, YOU'LL ALSO WIN A FREE"
	linefw "BOOSTER PACK FOR A VICTORY."
	linefw "TO FIGHT, I REQUIRE OPPONENTS TO USE"
	linefw "4 MAGIKARP CARDS IN THEIR DECKS."
	linefw "I CAN'T WAIT TO DUEL."
	linefw "DO YOU WANT TO DUEL NOW?"
	done

Text123d:
	text "DOES YOUR DECK CONTAIN"
	linefw "4 MAGIKARP CARDS?"
	linefw "IF SO, I'D LOVE TO BATTLE YOU!"
	done

Text123e:
	text "WOULD YOU LIKE TO DUEL CODY?"
	done

Text123f:
	text "IT'S NO GOOD! IT'S NO GOOD!"
	linefw "YOU DON'T HAVE 4 MAGIKARP CARDS!"
	linefw "IF YOU DON'T INCLUDE 4 MAGIKARP"
	linefw "CARDS IN YOUR DECK, I WON'T FIGHT!"
	done

Text1240:
	text "MAGIKARP...ALL ACCOUNTED FOR!"
	linefw "SET ASIDE 4 PRIZE CARDS."
	linefw "ALRIGHT! LET'S DUEL!"
	done

Text1241:
	text "OH? YOU DON'T WANT TO DUEL?"
	linefw "OKAY, I UNDERSTAND."
	linefw "I'VE BEEN WAITING FOR A GOOD DUEL."
	linefw "C'MON BACK TO PLAY LATER."
	done

Text1242:
	text "YEAAAH! I'M CODY!"
	linefw "LET'S DUEL! LET'S DUEL!"
	linefw "DO YOU HAVE MAGIKARP CARDS?"
	linefw "4! YOU NEED 4!"
	linefw "IF YOU HAVE THEM IN YOUR DECK,"
	linefw "I'LL BATTLE WITH YOU."
	done

Text1243:
	text "YOU SHOULDN'T HAVE FORGOTTEN!"
	linefw "YOU NEED 4 MAGIKARP CARDS."
	linefw "YOU'VE GOTTA HAVE 'EM IN YOUR DECK"
	linefw "BEFORE TRYING TO BATTLE WITH ME."
	linefw "ONCE YOU HAVE A DECK CONTAINING"
	linefw "4 MAGIKARP CARDS, WE CAN DUEL."
	done

Text1244:
	text "WE'LL USE 4 PRIZE CARDS."
	linefw "OKEYDOKE, READY OR NOT!"
	done

Text1245:
	text "WE'RE NOT GOING TO BATTLE?"
	linefw "AWW, I STILL WANNA..."
	done

Text1246:
	text "AH HA HA HA HA HAAAA!"
	linefw "...I LOST."
	done

Text1247:
	text "YOU HAD QUITE A LOT OF STRENGTH,"
	linefw "EVEN UNDER MY DUELLING TERMS."
	done

Text1248:
	text "CODY IS SO STRONG!!"
	linefw "CODY IS SO COOL!!"
	linefw "HEH HEH, SINCE I WON AND NO ONE GAVE"
	linefw "ME ANY PRAISE, I GAVE IT MYSELF!"
	done

Text1249:
	text "SO STROOONG!"
	done

Text124a:
	text "YOU'RE GREAT! YOU'RE TOUGH!"
	linefw "I'M GONNA GO! GO TAKE A REST!"
	done

Text124b:
	text "CODY WON THE MATCH!"
	linefw "I'M SO STRONG AND GREAT!"
	linefw "THE ONLY WAY I GET PRAISE IS IF"
	linefw "I GIVE IT MYSELF, HEH HEH HEH."
	done

Text124c:
	text "UMMM, I GUESS I HAVE TO RELEASE"
	linefw "JACK NOW."
	done

Text124d:
	text "MR. JAAAACK!"
	linefw "YOU'RE FREE TO GOOO!"
	done

Text124e:
	text "I HAVEN'T SEEN YOU FOR SOME TIME,"
	linefw "<RAMNAME>", "."
	linefw "IT'S ME, JACK,"
	linefw "THE POKÉMON CARD GRAND MASTER."
	linefw "FOR YOUR SELFLESS HELP,"
	linefw "YOU HAVE MY UTMOST GRATITUDE."
	linefw "I'LL GIVE YOU A SPECIAL CARD"
	linefw "TO EXPRESS MY THANKS."
	linefw "PLEASE USE IT TO MAKE AN ABSOLUTELY"
	linefw "GORGEOUS DECK."
	done

Text124f:
	text "I BELIEVE GRAND MASTER COURTNEY IS"
	linefw "STILL IN NEED OF YOUR HELP."
	linefw "IF YOU COULD, ", "<RAMNAME>", ","
	linefw "PLEASE GO TO HER AID."
	done

Text1250:
	text "I BELIEVE GRAND MASTER ROD IS STILL"
	linefw "IN NEED OF YOUR HELP."
	linefw "IF YOU COULD, ", "<RAMNAME>", ","
	linefw "PLEASE GO TO HIS AID."
	done

Text1251:
	text "I'M GOING TO RETURN TO MY PLACE"
	linefw "AT THE POKÉMON DOME."
	linefw "PLEASE STOP BY SOMETIME FOR A"
	linefw "CARD BATTLE OR TWO."
	linefw "I'LL BE WAITING TO FIGHT YOU"
	linefw "WITH MY GORGEOUS DECK!"
	done

Text1252:
	text "I GUESS I SHOULD OPEN THE WAY TO"
	linefw "ALEX'S ROOM, HUH?"
	done

Text1253:
	text "I'LL JUST PLACE THIS HERE..."
	linefw "GERONIMO!"
	done

Text1254:
	text "THERE YOU ARE."
	linefw "YOU MAY NOW GO INTO ALEX'S ROOM."
	linefw "ALEX IS A FASCINATING GUY."
	linefw "I HOPE YOU BOTH HAVE A GREAT DUEL!"
	done

Text1255:
	text "EH? THAT DECK..."
	linefw "YOU'RE NOT IN TEAM GR EITHER, THEN."
	linefw "I'D LIKE TO JOIN TEAM GR, BUT I"
	linefw "DON'T HAVE THE RIGHT CARDS YET..."
	linefw "YOU WOULDN'T HAPPEN TO OWN A"
	linefw "DARK BLASTOISE Lv28, WOULD YOU?"
	linefw "IF YOU DO, I COULD GIVE YOU A"
	linefw "BLASTOISE Lv52 FOR IT."
	done

Text1256:
	text "I THINK I'LL MAKE THE CUT TO JOIN"
	linefw "TEAM GR IF I CAN COMPLETE THIS DECK."
	linefw "I'M MISSING A DARK BLASTOISE Lv28,"
	linefw "THOUGH. CAN YOU TRADE ME ONE?"
	linefw "I'LL GIVE YOU THIS ART VARIATION"
	linefw "BLASTOISE Lv28 FOR IT!"
	done

Text1257:
	text "THOUGH I'D LIKE TO BE IN TEAM GR,"
	linefw "I NEED A DARK BLASTOISE Lv28 FIRST."
	linefw "I'LL BE OPEN TO TRADE ANY TIME IF "
	linefw "YOU HAPPEN TO CHANGE YOUR MIND..."
	done

Text1258:
	text "I WAS SERIOUS ABOUT MY DESIRE"
	linefw "TO JOIN TEAM GR, YOU KNOW."
	linefw "IF YOU DON'T HAVE THE CARD,"
	linefw "DON'T SAY 'YES'!"
	linefw "I'D APPRECIATE IT IF YOU COULD BE"
	linefw "SERIOUS, TOO, AND NOT PULL MY LEG!!"
	done

Text1259:
	text "UHH, IT'S USELESS TO TRY TO TRADE"
	linefw "IF THE CARD'S IN ONE OF YOUR DECKS."
	linefw "YOU CAN'T BREAK APART YOUR DECK"
	linefw "ON THE FLY LIKE THAT."
	linefw "OUR TRADE IS CLOSED UNTIL YOU REMOVE"
	linefw "THAT DARK BLASTOISE Lv28!"
	done

Text125a:
	text "THANK YOU VERY MUCH!"
	linefw "LET'S TRADE!!"
	done

Text125b:
	text "ALRIGHT!"
	linefw "TEAM GR, HERE I COME!!"
	done

Text125c:
	text "HEY, IT'S YOU! I'M WELL ON"
	linefw "MY WAY TO JOINING TEAM GR."
	linefw "THANKS SO MUCH. THE CARD YOU"
	linefw "TRADED ME WAS A BIG HELP."
	done

Text125d:
	text "HEY, IT'S YOU!"
	linefw "I FINALLY GOT ACCEPTED INTO TEAM GR!"
	linefw "IT'S ALL THANKS TO THAT AMAZING DARK"
	linefw "BLASTOISE Lv28 YOU TRADED TO ME."
	linefw "HUNH? WHAT HAPPEN TO MY GLASSES?"
	linefw "OH, I GOT CONTACTS TO LOOK COOLER!"
	done

Text125e:
	text "I FINALLY MADE IT INTO TEAM GR,"
	linefw "AND IT'S ALL THANKS TO YOU!"
	linefw "REALLY, THANK YOU SO MUCH!"
	done

Text125f:
	text "AHH, SO YOU'RE ", "<RAMNAME>", "."
	linefw "YOU SEEM TO BE DOING WELL."
	linefw "YOU'LL NEED 2 COINS IF YOU'D LIKE TO"
	linefw "ENTER THE GR FIGHTING FORTRESS."
	linefw "YOU CAN'T OPEN THE FORTRESS DOOR"
	linefw "WITHOUT THE FIRE AND WATER COINS."
	linefw "IT'S A GOOD TIP TO REMEMBER."
	done

Text1260:
	text "AHH, YOU'RE ", "<RAMNAME>", "."
	linefw "YOU SEEM TO BE DOING WELL."
	linefw "ME? I'M JUST FINE SINCE I'VE GOTTEN"
	linefw "A FEW POKÉMON CARD GAMES IN TODAY."
	done

Text1261:
	text "WOAH, I MUST BE DREAMING! HEYA!"
	linefw "IT'S ME, AMY FROM THE WATER CLUB!"
	linefw "I'M ON THE SAME MISSION AS YOU."
	linefw "I'M A LONE GIRL BATTLING MY WAY UP!"
	linefw "BUT I WAS THE ONLY PERSON WHO"
	linefw "DECIDED TO COME TO GR ISLAND..."
	linefw "HAHH...IT'S ROUGH..."
	done

Text1262:
	text "HEY, ", "<RAMNAME>", "! THANKS TO YOU,"
	linefw "I CAN FINALLY VISIT YOUR ISLAND."
	linefw "I'VE ALWAYS DREAMT OF GOING THERE"
	linefw "TO CHALLENGE AMY IN YOUR WATER CLUB!"
	done

Text1263:
	text "WHOA!"
	linefw "IF IT ISN'T ", "<RAMNAME>", "!"
	linefw "REMEMBER ME?"
	linefw "I'M YOUR LONG-TIME RIVAL, RONALD!"
	linefw "<RAMNAME>", ", DO YOU HAVE ANY"
	linefw "POKÉMON CARDS ON YOU?"
	linefw "OH!"
	linefw "TEAM GREAT ROCKET STOLE THEM?! "
	linefw "I'D BETTER CHECK THEM OUT TO STAY"
	linefw "ONE STEP AHEAD OF YOU!"
	linefw "BY THE WAY, I THINK DR. MASON WANTS"
	linefw "TO SPEAK WITH YOU."
	linefw "WELL THEN, SEE YA, ", "<RAMNAME>", "!"
	done

Text1264:
	text "YO!"
	linefw "IF IT ISN'T ", "<RAMNAME>", "!"
	done

Text1265:
	text "IT'S MORE SERIOUS THAN I THOUGHT!!"
	linefw "EVERY CLUB HAS BEEN BURGLED!"
	linefw "TEAM GR DOESN'T SEEM TO BE IN THIS"
	linefw "PARTICULAR CLUB AT THE MOMENT."
	linefw "I'VE HEARD THAT THERE'S BEEN A"
	linefw "SIGHTING IN THE ROCK CLUB, THOUGH."
	linefw "ANYWAY, I BARELY HAVE ANY CARDS"
	linefw "TO DUEL WITH AS IT IS!"
	linefw "SAY, WHY DON'T WE CARD POP! TO"
	linefw "GET SOME NEW CARDS?"
	linefw "COME ON, LET'S CARD POP!"
	done

Text1266:
	text "ALRIGHT!"
	linefw "NOW TO SAVE MY DATA!"
	done

Text1267:
	text "IN ANY CASE, TEAM GR ISN'T HERE."
	linefw ""
	linefw "<RAMNAME>", "!"
	linefw "PLEASE GO CHECK OUT THE ROCK CLUB!"
	linefw "I'LL VISIT THE OTHER CLUBS AND"
	linefw "GATHER INFORMATION ABOUT TEAM GR."
	linefw "LATER, ", "<RAMNAME>", "!"
	done

Text1268:
	text "IT'S SERIOUS, ", "<RAMNAME>", "!"
	linefw "THIS CLUB HAS BEEN TAKEN OVER!"
	linefw "THERE'S A PERSON HERE ACCEPTING"
	linefw "CHALLENGES NAMED ", "<RAMTEXT>", "..."
	linefw "ANOTHER, GR No.1, IS APPARENTLY"
	linefw "TRYING TO TAKE OVER THE ROCK CLUB."
	linefw "I BARELY HAVE ANY CARDS TO DUEL"
	linefw "WITH EITHER OF THEM, THOUGH!"
	linefw "SAY, WHY DON'T WE CARD POP! TO"
	linefw "GET SOME NEW CARDS?"
	linefw "COME ON, LET'S CARD POP!"
	done

Text1269:
	text "ANYWAY, I CAN'T SEEM TO BEAT"
	linefw "THE TEAM GR MEMBER HERE JUST YET."
	linefw "<RAMNAME>", "! PLEASE CHECK OUT THE"
	linefw "ROCK CLUB AS SOON AS YOU CAN!"
	linefw "I'LL VISIT THE OTHER CLUBS AND"
	linefw "GATHER INFORMATION ABOUT TEAM GR."
	linefw "LATER, ", "<RAMNAME>", "!"
	done

Text126a:
	text "IT'S SERIOUS, ", "<RAMNAME>", "!"
	linefw "TEAM GR IS HERE!"
	linefw "A WEIRDO CALLING HIMSELF GR No.1"
	linefw "IS ATTACKING THE ROCK CLUB!"
	linefw "THE CLUB MASTER AND MEMBERS ARE"
	linefw "TRYING THEIR HARDEST TO RESIST HIM."
	linefw "I'D LIKE TO FIGHT HIM MYSELF, BUT"
	linefw "I DON'T HAVE ANY CARDS TO DUEL WITH!"
	linefw "SAY, WHY DON'T WE CARD POP! TO"
	linefw "GET SOME NEW CARDS?"
	linefw "COME ON, LET'S CARD POP!"
	done

Text126b:
	text "JUST ONE CARD ISN'T ENOUGH FOR ME"
	linefw "TO TAKE CARE OF THAT GUY..."
	linefw "ALRIGHT, ", "<RAMNAME>", "!"
	linefw "I'M LEAVING IT TO YOU!!"
	linefw "I'LL VISIT THE OTHER CLUBS AND"
	linefw "GATHER INFORMATION ABOUT TEAM GR."
	linefw "LATER, ", "<RAMNAME>", "!"
	done

Text126c:
	text "OH!"
	linefw "HEYA, ", "<RAMNAME>", "!"
	done

Text126d:
	text "WOW! SO YOU BEAT TWO MEMBERS"
	linefw "OF TEAM GR ALREADY?"
	linefw "I WOULDN'T EXPECT OTHERWISE"
	linefw "FROM MY DESTINED RIVAL!"
	linefw "FORTUNATELY, I'VE BEEN AMASSING"
	linefw "LOTS OF CARDS MYSELF."
	linefw "I'VE GOT A FULL DECK NOW!"
	linefw "LET'S HAVE A DUEL!"
	linefw "WE'LL USE 6 PRIZE CARDS! IF YOU WIN,"
	linefw "I'LL GIVE YOU A RARE CARD!"
	done

Text126e:
	text "AS EXPECTED, THE CARDS I HAD"
	linefw "GATHERED WEREN'T QUITE ENOUGH..."
	linefw "WELL, I GUESS IT WAS INEVITABLE."
	linefw "HERE, THIS CARD IS NOW YOURS!"
	done

Text126f:
	text "I NEED TO COLLECT MORE CARDS..."
	linefw ""
	linefw "ANYWAY, IF I DIG UP ANY NEW INTEL"
	linefw "ABOUT TEAM GR, I'LL LET YOU KNOW!"
	done

Text1270:
	text "YOU CAN'T TAKE DOWN TEAM GR WITH"
	linefw "THAT KIND OF WEAK PLAY STYLE!"
	linefw "WAS IT A FLUKE THAT YOU BEAT THOSE"
	linefw "TWO MEMBERS OF TEAM GR...?"
	linefw "ANYWAY, ", "<RAMNAME>", ","
	linefw "I'LL SEE YA AROUND!"
	done

Text1271:
	text "YO, ", "<RAMNAME>", "!"
	linefw "I WAS SENT TO FIND YOU!"
	done

Text1272:
	text "I WAS BUSY WHILE YOU WERE FIGHTING"
	linefw "AGAINST THE MEMBERS OF TEAM GR."
	linefw "I SNUCK ABOARD THEIR AIRSHIP"
	linefw "AND TOOK BACK SOME STOLEN CARDS!"
	linefw "THE CARDS HAVE BEEN RETURNED TO"
	linefw "THEIR OWNERS IN THE ISLAND'S CLUBS!"
	linefw "I ALSO MANAGED TO SNATCH A FEW"
	linefw "BOOSTER PACKS WHILE I WAS THERE!"
	linefw "HERE, THIS LOST ISLE BOOSTER PACK"
	linefw "HAS YOUR NAME ON IT!!"
	done

Text1273:
	text "THE AIRSHIP THAT FLIES TO GR ISLAND"
	linefw "IS FINALLY READY TO BOARD!"
	linefw "YOU'VE GOTTA GO! BUT BE CAREFUL!"
	linefw "IT'S ENEMY TERRITORY OVER THERE!"
	linefw "I'M GOING TO STICK AROUND THIS"
	linefw "ISLAND AND COLLECT SOME MORE CARDS."
	linefw "MY DECK NEEDS A LOT OF WORK"
	linefw "BEFORE I'M READY TO TRAVEL!"
	linefw "I'LL SEE YA LATER,"
	linefw "<RAMNAME>", "."
	done

Text1274:
	text "IF IT ISN'T ", "<RAMNAME>", "!"
	linefw "FANCY MEETING YOU HERE."
	done

Text1275:
	text "THIS GAME CENTER WAS BUILT AND"
	linefw "IS MANAGED BY TEAM GR!"
	linefw "THERE ARE LOTS OF SLOT MACHINES AND"
	linefw "VIDEO GAMES YOU CAN PLAY HERE."
	linefw "YOU CAN EXCHANGE THE CHIPS YOU WIN"
	linefw "FOR A PROMOTIONAL CARD VOUCHER."
	linefw "I JUST GOT A FEW VOUCHERS MYSELF."
	linefw "HERE, TAKE ONE, ", "<RAMNAME>", "!"
	done

Text1276:
	text "OF COURSE, YOU CAN'T PUT THAT"
	linefw "CARD IN ANY OF YOUR DECKS!"
	linefw "INSTEAD, YOU TRADE IT AND ONE OF THE"
	linefw "OTHER LISTED CARDS FOR SWEET PROMOS!"
	linefw "BE CAREFUL, THOUGH, BECAUSE YOU"
	linefw "WON'T GET EITHER CARD BACK."
	linefw "ANYWAY, I'M OFF TO SEARCH FOR"
	linefw "THE PEOPLE THAT TEAM GR KIDNAPPED."
	linefw "I WAS SO HOOKED TO THE GAMES HERE"
	linefw "THAT I ALMOST FORGOT! HEH HEH..."
	linefw "LATER, ", "<RAMNAME>", "!"
	done

Text1277:
	text "WH-WHAT?! YOU!"
	linefw "GET OVER HERE!"
	done

Text1278:
	text "YOU..."
	linefw "YOU'RE NOT A MEMBER OF TEAM GR!"
	linefw "IT ALSO SEEMS THAT YOU'RE IN"
	linefw "POSSESSION OF POKÉMON CARDS, TOO..."
	linefw "THAT'S GOOD!"
	linefw "I'D LOVE TO SEE YOUR PLAY STYLE!"
	linefw "IS IT POSSIBLE THAT YOU COULD"
	linefw "OUST MY DARK POKÉMON?"
	linefw "LET'S DUEL, ", "<RAMNAME>", "!"
	linefw "START THE 6-PRIZE BATTLE!"
	done

Text1279:
	text "KEH! YOU'VE BEATEN ME SO EASILY,"
	linefw "<RAMNAME>", "!!"
	done

Text127a:
	text "IT'S ME, RONALD!"
	linefw "ARE YOU SURPRISED, ", "<RAMNAME>", "?"
	linefw "I'VE BEEN USING THIS DISGUISE TO"
	linefw "SPY ON THE AREA'S ACTIVITY."
	linefw "TAKE THESE BOOSTER PACKS! HOPEFULLY"
	linefw "THEY'LL HELP YOU BEAT TEAM GR!!"
	done

Text127b:
	text "I'VE GATHERED A LOT OF INFORMATION"
	linefw "ABOUT DUELLING TEAM GR FOR YOU!"
	linefw "MEMBERS OF TEAM GR UTILIZE"
	linefw "DARK POKÉMON IN THEIR DECKS."
	linefw "THEY ONLY FIGHT CHALLENGERS IF"
	linefw "THEIR DECKS MEET CERTAIN CONDITIONS."
	linefw "MOREOVER, SOME HAVE ALSO ADDED"
	linefw "SPECIAL DUELLING RULES!"
	linefw "BATTLE WITH THE RULES IN MIND AND"
	linefw "TAKE ADVANTAGE OF THEIR ODD EFFECTS."
	linefw "OTHERWISE,"
	linefw "YOU MAY FIND IT HARD TO WIN."
	linefw "ANYWAY,"
	linefw "I'LL SEE YA AROUND!"
	done

Text127c:
	text "I'LL KEEP UP WITH MY SPYWORK."
	linefw "GOOD LUCK, ", "<RAMNAME>", "."
	done

Text127d:
	text "I GOT YOU GOOD THIS TIME,"
	linefw "<RAMNAME>", "!!"
	done

Text127e:
	text "IT'S ME, RONALD!"
	linefw "ARE YOU SURPRISED, ", "<RAMNAME>", "?"
	linefw "I'VE BEEN USING THIS DISGUISE TO"
	linefw "SPY ON THE AREA'S ACTIVITY."
	linefw "YOU'LL HAVE SOME TOUGH TIMES AGAINST"
	linefw "TEAM GR IF YOU CAN'T EVEN BEAT ME."
	done

Text127f:
	text "HEY ", "<RAMNAME>", "!!"
	linefw "C'MERE!!"
	done

Text1280:
	text "BE THANKFUL I'M NOT REALLY PART OF"
	linefw "TEAM GR! IT'S ME, RONALD!!"
	done

Text1281:
	text "IS THAT COIN YOU HAVE THE"
	linefw "GR ", "<RAMTEXT>", " COIN??"
	linefw "COOL, BUT YOU'LL NEED ANOTHER COIN"
	linefw "TO ENTER THE GR FIGHTING FORTRESS."
	linefw "IF I'M NOT MISTAKEN, THAT COIN"
	linefw "IS THE GR ", "<RAMTEXT>", " COIN!"
	linefw "THE GR FIGHTING FORTRESS SEEMS TO"
	linefw "BE A MUCH LARGER FORT THAN THIS."
	linefw "IT'S BEEN A WHILE SINCE WE MET,"
	linefw "THOUGH, ", "<RAMNAME>", "!"
	linefw "I'M HERE TO SEE IF YOU'VE BEEN"
	linefw "GETTING STRONGER LIKE I'VE BEEN!"
	linefw "LET'S HAVE A 6-PRIZE CARD DUEL!"
	linefw "WIN, AND I'LL GIVE YOU A COOL CARD!"
	done

Text1282:
	text "IT SEEMS LIKE YOU'VE GAINED A LOT OF"
	linefw "EXPERIENCE FIGHTING TEAM GR."
	linefw "ALRIGHT, A PROMISE IS A PROMISE."
	linefw "TAKE THIS SPECIAL CARD!"
	done

Text1283:
	text "HOW YOU USE THAT CARD IS ENTIRELY"
	linefw "UP TO YOU."
	linefw "ANYWAY, I'M GONNA GO GET STRONGER."
	linefw "FIGHT ON, ", "<RAMNAME>", "!"
	done

Text1284:
	text "WHAT?"
	linefw "ARE YOU STILL THAT WEAK?"
	linefw "YOU'RE DESPERATELY IN NEED OF SOME"
	linefw "BETTER CARDS TO BUILD DECKS WITH."
	linefw "DO WHAT I DID AND RETURN TO OUR HOME"
	linefw "ISLAND TO STOCK UP ON CARDS!"
	linefw "ANYWAY, I'M OFF TO GET STRONGER."
	linefw "FIGHT ON, ", "<RAMNAME>", "!"
	done

Text1285:
	text "YOU'VE MADE IT HERE QUICKLY,"
	linefw "<RAMNAME>", "!"
	done

Text1286:
	text "IT'S ME! RONALD!"
	linefw "GOOD TO SEE YOU AGAIN!!"
	done

Text1287:
	text "DID YOU HAVE SOME TROUBLE IN THE"
	linefw "GR FIGHTING FORTRESS'S LABYRINTH?"
	linefw "I GOT SICK OF WAITING FOR YOU!"
	linefw "LISTEN, I HAVE NEW TEAM GR INTEL."
	linefw "THERE'S A MAN CALLED THE GR KING"
	linefw "IN THE GR CASTLE JUST NORTH OF HERE!"
	linefw "THERE'S A CATCH, THOUGH."
	linefw "YOU NEED 2 COINS TO MEET HIM."
	linefw "THOSE WOULD BE THE GR PSYCHIC COIN"
	linefw "AND THE GR COLORLESS COIN!"
	linefw "YOU'D SHOULD GET THEM QUICKLY AND"
	linefw "ATTACK THAT CASTLE!"
	linefw "BUT SEEING HOW SLOW YOU WORK,"
	linefw "I BET I'LL GET THERE FIRST!!"
	linefw "I'M OFF!"
	linefw "LATER, ", "<RAMNAME>", "!!"
	done

Text1288:
	text "DE...DEFEATED..."
	linefw "I WAS SO THOROUGHLY DEFEATED..."
	done

Text1289:
	text "OH, ", "<RAMNAME>", ". GOSH, THE PLAYERS"
	linefw "IN HERE ARE INDESCRIBABLY STRONG!"
	linefw "I COULDN'T DO A THING, EVEN AFTER"
	linefw "ALL OF MY WORK TO GET HERE!"
	linefw "BUT ", "<RAMNAME>", ", YOU..."
	linefw "YOUR DECK MIGHT DO THE TRICK."
	linefw "THIS IS THE END."
	linefw "SHOW EVERYONE YOUR POWER!"
	linefw "IF YOU CAN'T DEFEAT ME, THOUGH, YOU"
	linefw "WON'T STAND A CHANCE IN THERE."
	linefw "C'MON, WE'LL PLAY WITH OUR USUAL"
	linefw "6 PRIZE CARDS RULES."
	linefw "IF YOU WIN, I'LL GIVE YOU A RARE"
	linefw "SUPER ENERGY RETRIEVAL CARD!"
	done

Text128a:
	text "I MUST ADMIT, ", "<RAMNAME>", ":"
	linefw "YOU'RE VERY STRONG."
	linefw "ANYWAY, HERE'S YOUR NEW"
	linefw "SUPER ENERGY RETRIEVAL CARD."
	done

Text128b:
	text "I'M SURE YOU CAN BEAT THESE GUYS!!"
	linefw "YOU JUST GOTTA DO YOUR BEST!"
	linefw "ANYWAY,"
	linefw "FIGHT ON, ", "<RAMNAME>", "!!"
	done

Text128c:
	text "HEY, WHAT WAS THAT, ", "<RAMNAME>", "?!"
	linefw "HOW DID YOU EVEN GET THIS FAR?"
	linefw "YOU CAN'T POSSIBLY DEFEAT THE GUYS"
	linefw "BEYOND HERE IF YOU CAN'T BEAT ME!"
	linefw "BUT DO YOUR BEST, ", "<RAMNAME>", "!"
	linefw "I HAVE FAITH IN YOU!"
	linefw "I'M SURE YOU CAN PULL IT OFF!!"
	linefw "YOU JUST GOTTA TRY HARDER!"
	linefw "ANYWAY,"
	linefw "FIGHT ON, ", "<RAMNAME>", "!!"
	done

Text128d:
	text "YO, ", "<RAMNAME>", "!"
	linefw "SAY, THAT'S A BIG SMILE!"
	done

Text128e:
	text "THAT GR No.3 WAS RUSHING OUT OF"
	linefw "HERE SO FAST, HE DROPPED SOME CARDS!"
	linefw "I'LL TAKE THIS LOST ISLE"
	linefw "BOOSTER PACK."
	linefw "HERE, YOU CAN HAVE THE OTHER,"
	linefw "A LEGENDS BOOSTER PACK!"
	done

Text128f:
	text "KEEP UP YOUR RHYTHM OF DEFEATING"
	linefw "THE TEAM GR MEMBERS!"
	linefw "I'LL HELP OUT BY SHARING ANY"
	linefw "BOOSTER PACKS I FIND!"
	linefw "LATER,"
	linefw "<RAMNAME>", "!"
	done

Text1290:
	text "YOU CAN CREATE POWERFUL COMBOS BY"
	linefw "COMBINING THE ABILITIES OF 2 CARDS."
	linefw "POKÉMON POWERS AND TRAINER CARDS"
	linefw "ARE USEFUL IN CREATING COMBOS!"
	linefw "FIND CARD COMBINATIONS THAT WILL"
	linefw "CREATE YOUR OWN POWERFUL COMBOS."
	done

Text1291:
	text "WHAT IF YOU HAVE AN EXEGGUTOR IN THE"
	linefw "ARENA WITHOUT ANY ENERGY CARDS?"
	linefw "USE VENUSAUR'S ENERGY TRANS TO MOVE"
	linefw "<GRASS>", " ENERGY AND USE BIG EGGSPLOSION!"
	linefw "WITH 8 ENERGY CARDS, YOU CAN GIVE"
	linefw "YOUR OPPONENT UP TO 160 DAMAGE!"
	done

Text1292:
	text "MUK'S TOXIC GAS IS VERY POWERFUL."
	linefw "IT CAN BLOCK ALL POKÉMON POWERS!"
	linefw "BE CAREFUL, THOUGH: IT ALSO"
	linefw "BLOCKS YOUR OWN POKÉMON'S POWERS!"
	done

Text1293:
	text "BLASTOISE'S POKÉ POWER, RAIN DANCE,"
	linefw "IS A GREAT AID TO YOUR ", "<WATER>", " POKÉMON!"
	linefw "USE IT TO ATTACH AS MANY ", "<WATER>", " ENERGY"
	linefw "CARDS AS YOU LIKE TO WATER POKÉMON."
	linefw "YOU CAN POWER UP YOUR POKÉMON"
	linefw "QUICKLY BY IMPLEMENTING IT!"
	linefw "YOU'RE ONLY LIMITED BY THE NUMBER OF"
	linefw "ENERGY CARDS IN YOUR HAND."
	linefw "USE PROF. OAK TO GET EVEN MORE"
	linefw "ENERGY FROM YOUR DECK!"
	done

Text1294:
	text "IT'S A GOOD IDEA TO USE DEFENDER"
	linefw "WHEN ATTACKING WITH SELFDESTRUCT."
	linefw "THAT WAY, YOU'LL BE ABLE TO GIVE"
	linefw "MAJOR DAMAGE TO YOUR OPPONENT'S"
	linefw "ACTIVE AND BENCHED POKÉMON WITHOUT"
	linefw "YOUR POKÉMON GETTING KNOCKED OUT."
	done

Text1295:
	text "ALAKAZAM'S DAMAGE SWAP MOVES DAMAGE"
	linefw "COUNTERS FROM 1 POKÉMON TO ANOTHER."
	linefw "USE IT TO MOVE DAMAGE COUNTERS FROM"
	linefw "POKÉMON THAT ARE ALMOST KNOCKED OUT."
	linefw "YOU CAN EVEN MAKE A COMBO USING IT"
	linefw "WITH CHANSEY AND SCOOP UP."
	linefw "FIRST, MOVE AS MANY DAMAGE COUNTERS"
	linefw "AS YOU CAN TO CHANSEY."
	linefw "NEXT, USE SCOOP UP TO RETURN"
	linefw "CHANSEY TO YOUR HAND."
	linefw "FINALLY, PUT CHANSEY BACK IN PLAY."
	linefw "ALL THOSE DAMAGE COUNTERS ARE GONE!"
	done

Text1296:
	text "TRY USING SUPER ENERGY REMOVAL AND"
	linefw "ENERGY REMOVAL CARDS IN A DUEL."
	linefw "THESE CARDS LET YOU DISCARD ENERGY"
	linefw "ATTACHED TO YOUR OPPONENT'S POKÉMON!"
	linefw "POKÉMON CANNOT ATTACK IF THEY DON'T"
	linefw "HAVE ANY ENERGY CARDS ATTACHED."
	linefw "ADDITIONALLY, IT'S IMPOSSIBLE FOR"
	linefw "THEM TO RETREAT FROM THE ARENA."
	linefw "SOME POKÉMON EVEN HAVE ATTACKS THAT"
	linefw "LET YOU DISCARD ENERGY CARDS!"
	done
