Text152f:
	text "ALTHOUGH IT CAN'T WALK WELL ON LAND,"
	linefw "IT IS A GRACEFUL SWIMMER. IT LOVES"
	linefw "BEING IN FRIGID SEAS THE MOST."
	done

Text1530:
	text "HEADBUTT"
	done

Text1531:
	text "A POKÉMON THAT LIVES ON ICEBERGS."
	linefw "IT SWIMS IN THE SEA USING THE POINT"
	linefw "ON ITS HEAD TO BREAK UP ICE."
	done

Text1532:
	text "DEWGONG "
	done

Text1533:
	text "REST"
	done

Text1534:
	text "REMOVE ALL DAMAGE COUNTERS FROM"
	linefw "DEWGONG. DEWGONG IS NO LONGER"
	linefw "CONFUSED OR POISONED. DEWGONG IS"
	linefw "NOW ASLEEP."
	done

Text1535:
	text "AURORA WAVE"
	done

Text1536:
	text "ITS STREAMLINED BODY HAS LITTLE DRAG"
	linefw "IN WATER. THE COLDER THE"
	linefw "TEMPERATURE, THE FRISKIER IT GETS. "
	done

Text1537:
	text "AURORA BEAM"
	done

Text1538:
	text "IN SNOW, THE PURE WHITE COAT"
	linefw "COVERING ITS BODY OBSCURES IT FROM"
	linefw "PREDATORS."
	done

Text1539:
	text "SHELLDER "
	done

Text153a:
	text "HIDE IN SHELL"
	done

Text153b:
	text "BIVALVE"
	done

Text153c:
	text "IT SWIMS BACKWARD BY OPENING AND"
	linefw "CLOSING ITS TWO SHELLS. ITS LARGE"
	linefw "TONGUE IS ALWAYS KEPT HANGING OUT."
	done

Text153d:
	text "WATER SPOUT"
	done

Text153e:
	text "DOES 10 EXTRA DAMAGE FOR EACH"
	linefw "<WATER>", " ENERGY ATTACHED TO THIS"
	linefw "POKÉMON BUT NOT USED TO PAY FOR THIS"
	linefw "ATTACK'S ENERGY COST. YOU CAN'T ADD"
	linefw "MORE THAN 20 DAMAGE IN THIS WAY."
	done

Text153f:
	text "IT SWIMS FACING BACKWARD BY OPENING"
	linefw "AND CLOSING ITS TWO-PIECE SHELL. IT"
	linefw "IS SURPRISINGLY FAST. "
	done

Text1540:
	text "CLOYSTER "
	done

Text1541:
	text "CLAMP"
	done

Text1542:
	text "FLIP A COIN. IF HEADS, THE"
	linefw "DEFENDING POKÉMON IS NOW PARALYZED."
	linefw "IF TAILS, THIS ATTACK DOES NOTHING"
	linefw "(NOT EVEN DAMAGE)."
	done

Text1543:
	text "SPIKE CANNON"
	done

Text1544:
	text "IT FIGHTS BY KEEPING ITS SHELL"
	linefw "TIGHTLY SHUT FOR PROTECTION AND BY"
	linefw "SHOOTING SPIKES TO REPEL FOES."
	done

Text1545:
	text "KRABBY "
	done

Text1546:
	text "GUILLOTINE"
	done

Text1547:
	text "RIVER CRAB"
	done

Text1548:
	text "IF IT SENSES DANGER APPROACHING, IT"
	linefw "CLOAKS ITSELF WITH BUBBLES FROM ITS"
	linefw "MOUTH SO IT WILL LOOK BIGGER."
	done

Text1549:
	text "SEARCH YOUR DECK FOR A BASIC"
	linefw "POKÉMON NAMED KRABBY AND PUT IT ON"
	linefw "YOUR BENCH. SHUFFLE YOUR DECK"
	linefw "AFTERWARD. (YOU CAN'T USE THIS"
	linefw "ATTACK IF YOUR BENCH IS FULL.)"
	done

Text154a:
	text "IRONGRIP"
	done

Text154b:
	text "IT LIVES IN BURROWS DUG ON SANDY"
	linefw "BEACHES. ITS PINCERS FULLY GROW BACK"
	linefw "IF THEY ARE BROKEN IN BATTLE."
	done

Text154c:
	text "KINGLER "
	done

Text154d:
	text "FLAIL"
	done

Text154e:
	text "DOES 10 DAMAGE TIMES THE NUMBER OF"
	linefw "DAMAGE COUNTERS ON THIS POKÉMON."
	done

Text154f:
	text "CRABHAMMER"
	done

Text1550:
	text "RIVER CRAB"
	done

Text1551:
	text "THE LARGER PINCER HAS 10,000-"
	linefw "HORSEPOWER STRENGTH. HOWEVER, IT IS"
	linefw "SO HEAVY, IT IS DIFFICULT TO AIM."
	done

Text1552:
	text "SALT WATER"
	done

Text1553:
	text "FLIP A COIN. IF HEADS, SEARCH YOUR"
	linefw "DECK FOR UP TO 3 ", "<WATER>", " ENERGY CARDS"
	linefw "AND ATTACH THEM TO KINGLER. SHUFFLE"
	linefw "YOUR DECK AFTERWARDS."
	done

Text1554:
	text "DOUBLE-EDGED CLAW"
	done

Text1555:
	text "DURING YOUR OPPONENT'S NEXT TURN,"
	linefw "ALL DAMAGE DONE TO KINGLER IS"
	linefw "DOUBLED. "
	done

Text1556:
	text "IT CAN HARDLY LIFT ITS MASSIVE,"
	linefw "OVERGROWN PINCER. THE PINCER'S SIZE"
	linefw "MAKES IT DIFFICULT TO AIM PROPERLY. "
	done

Text1557:
	text "HORSEA "
	done

Text1558:
	text "DRAGON"
	done

Text1559:
	text "IT MAKES ITS NEST IN THE SHADE OF"
	linefw "CORALS. IF IT SENSES DANGER, IT"
	linefw "SPITS MURKY INK AND FLEES."
	done

Text155a:
	text "HIDE"
	done

Text155b:
	text "FLIP A COIN. IF HEADS, DURING YOUR"
	linefw "OPPONENT'S NEXT TURN, PREVENT ALL"
	linefw "EFFECTS OF ATTACKS, INCLUDING"
	linefw "DAMAGE, DONE TO HORSEA."
	done

Text155c:
	text "IF ATTACKED BY A LARGER ENEMY, IT"
	linefw "QUICKLY SWIMS TO SAFETY BY ADEPTLY"
	linefw "CONTROLLING ITS DORSAL FIN. "
	done

Text155d:
	text "SEADRA "
	done

Text155e:
	text "ITS SPINES PROVIDE PROTECTION. ITS"
	linefw "FINS AND BONES ARE PRIZED AS"
	linefw "TRADITIONAL MEDICINE INGREDIENTS."
	done

Text155f:
	text "WATER BOMB"
	done

Text1560:
	text "IF SEADRA HAS EXTRA ", "<WATER>", " ENERGY"
	linefw "CARDS ATTACHED THAT ARE NOT USED TO"
	linefw "PAY FOR THIS ATTACK'S ENERGY COST,"
	linefw "YOU MAY DO 10 DAMAGE TO ANY OF YOUR"
	linefw "OPPONENT'S BENCHED POKÉMON PER EXTRA"
	linefw "<WATER>", " ENERGY CARD."
	done

Text1561:
	text "(", "<WATER>", " ENERGY PAST THE SECOND DOESN'T"
	linefw "COUNT.) (DON'T APPLY WEAKNESS AND"
	linefw "RESISTANCE FOR BENCHED POKÉMON.)"
	done

Text1562:
	text "AN EXAMINATION OF ITS CELLS REVEALED"
	linefw "THE PRESENCE OF A GENE NOT FOUND IN"
	linefw "HORSEA. IT BECAME A HOT TOPIC. "
	done

Text1563:
	text "GOLDEEN "
	done

Text1564:
	text "HORN ATTACK"
	done

Text1565:
	text "GOLDFISH"
	done

Text1566:
	text "IT SWIMS AT A STEADY 5 KNOTS. IF IT"
	linefw "SENSES DANGER, IT WILL STRIKE BACK"
	linefw "WITH ITS SHARP HORN."
	done

Text1567:
	text "SEAKING "
	done

Text1568:
	text "WATERFALL"
	done

Text1569:
	text "TO PROTECT ITS FAMILY, IT WILL FIGHT"
	linefw "WITH ITS DRILL-SHARP HORN. IT LIVES"
	linefw "IN HOLLOWED ROCKS IN STREAMS."
	done

Text156a:
	text "STARYU "
	done

Text156b:
	text "SLAP"
	done

Text156c:
	text "STARSHAPE"
	done

Text156d:
	text "IF ITS BODY IS TORN, IT CAN GROW"
	linefw "BACK IF THE RED CORE REMAINS. THE"
	linefw "CORE FLASHES AT MIDNIGHT."
	done

Text156e:
	text "STRANGE BEAM"
	done

Text156f:
	text "DURING YOUR OPPONENT'S NEXT TURN,"
	linefw "IGNORE ALL WEAKNESSES OF ", "<WATER>"
	linefw "POKÉMON."
	done

Text1570:
	text "SPINNING ATTACK"
	done

Text1571:
	text "AT NIGHT, THE CENTER OF ITS BODY"
	linefw "SLOWLY FLICKERS WITH THE SAME RHYTHM"
	linefw "AS A HUMAN HEARTBEAT. "
	done

Text1572:
	text "STARMIE "
	done

Text1573:
	text "RECOVER"
	done

Text1574:
	text "DISCARD 1 ", "<WATER>", " ENERGY CARD IN ORDER"
	linefw "TO USE THIS ATTACK. REMOVE ALL"
	linefw "DAMAGE COUNTERS FROM STARMIE."
	done

Text1575:
	text "STAR FREEZE"
	done

Text1576:
	text "MYSTERIOUS"
	done

Text1577:
	text "AT THE CENTER OF ITS BODY IS A RED"
	linefw "CORE, WHICH SENDS MYSTERIOUS RADIO"
	linefw "SIGNALS INTO THE NIGHT SKY."
	done

Text1578:
	text "DARK STARMIE "
	done

Text1579:
	text "REBIRTH"
	done

Text157a:
	text "ONCE DURING YOUR TURN (BEFORE YOUR"
	linefw "ATTACK) YOU MAY DISCARD ALL CARDS"
	linefw "ATTACHED TO DARK STARMIE AND REMOVE"
	linefw "ALL DAMAGE COUNTERS FROM DARK"
	linefw "STARMIE. THEN, DISCARD THIS"
	linefw "EVOLUTION CARD TO RETURN DARK"
	linefw "STARMIE TO ITS BASIC STAGE."
	done

Text157b:
	text "THIS POWER CAN'T BE USED IF DARK"
	linefw "STARMIE IS ASLEEP, CONFUSED, OR"
	linefw "PARALYZED."
	done

Text157c:
	text "SPINNING SHOWER"
	done

Text157d:
	text "FLIP A COIN. IF HEADS, CHOOSE 1 OR 2"
	linefw "(THE NUMBER IS RANDOM) OF YOUR"
	linefw "OPPONENT'S POKÉMON. THIS ATTACK DOES"
	linefw "20 DAMAGE TO EACH OF THEM. (DON'T"
	linefw "APPLY WEAKNESS AND RESISTANCE.)"
	linefw "DISCARD 1 ENERGY CARD AT RANDOM"
	linefw "ATTACHED TO EACH OF THEM."
	done

Text157e:
	text "THE CENTER SECTION OF ITS BODY IS"
	linefw "CALLED THE CORE. IT GLOWS IN A"
	linefw "DIFFERENT COLOR EACH TIME IT'S SEEN."
	done

Text157f:
	text "MAGIKARP "
	done

Text1580:
	text "FLOP"
	done

Text1581:
	text "RAPID EVOLUTION"
	done

Text1582:
	text "SEARCH YOUR DECK FOR AN EVOLUTION"
	linefw "CARD NAMED GYARADOS OR DARK GYARADOS"
	linefw "AND PUT IT ON MAGIKARP. (THIS COUNTS"
	linefw "AS EVOLVING MAGIKARP.) SHUFFLE YOUR"
	linefw "DECK AFTERWARD."
	done

Text1583:
	text "FISH"
	done

Text1584:
	text "IT IS SAID TO BE THE WORLD'S WEAKEST"
	linefw "POKÉMON. NO ONE KNOWS WHY IT HAS"
	linefw "MANAGED TO SURVIVE. "
	done

Text1585:
	text "IT IS UNABLE TO SWIM AGAINST EVEN"
	linefw "SLOW-MOVING CURRENTS. IT ALWAYS"
	linefw "SPLASHES ABOUT FOR SOME REASON."
	done

Text1586:
	text "DOUBLE FLOP"
	done

Text1587:
	text "FLIP 2 COINS. THIS ATTACK DOES 10"
	linefw "DAMAGE TIMES THE NUMBER OF HEADS."
	done

Text1588:
	text "DRAGON RAGE"
	done

Text1589:
	text "FLIP 2 COINS. IF AT LEAST ONE OF"
	linefw "THEM IS TAILS, THIS ATTACK DOES"
	linefw "NOTHING."
	done

Text158a:
	text "A MAGIKARP LIVING FOR MANY YEARS CAN"
	linefw "LEAP A MOUNTAIN USING SPLASH. THE"
	linefw "MOVE REMAINS USELESS, THOUGH. "
	done

Text158b:
	text "GYARADOS "
	done

Text158c:
	text "BUBBLEBEAM"
	done

Text158d:
	text "ATROCIOUS"
	done

Text158e:
	text "IN ANCIENT LITERATURE, THERE IS A"
	linefw "RECORD OF A GYARADOS THAT RAZED A"
	linefw "VILLAGE WHEN VIOLENCE FLARED."
	done

Text158f:
	text "DARK GYARADOS "
	done

Text1590:
	text "FINAL BEAM"
	done

Text1591:
	text "WHEN DARK GYARADOS IS KNOCKED OUT"
	linefw "BY AN ATTACK, FLIP A COIN. IF HEADS,"
	linefw "THIS POWER DOES 20 DAMAGE FOR EACH"
	linefw "<WATER>", " ENERGY ATTACHED TO DARK GYARADOS"
	linefw "TO THE POKÉMON THAT KNOCKED IT OUT."
	linefw "APPLY WEAKNESS AND RESISTANCE."
	done

Text1592:
	text "THIS POWER DOESN'T WORK IF DARK"
	linefw "GYARADOS IS ASLEEP, CONFUSED, OR"
	linefw "PARALYZED."
	done

Text1593:
	text "ONCE IT APPEARS, ITS RAGE NEVER"
	linefw "SETTLES UNTIL IT HAS RAZED THE"
	linefw "FIELDS AND MOUNTAINS AROUND IT. "
	done

Text1594:
	text "LAPRAS "
	done

Text1595:
	text "SING"
	done

Text1596:
	text "FLIP A COIN. IF HEADS, THE"
	linefw "DEFENDING POKÉMON IS NOW ASLEEP."
	done

Text1597:
	text "TRANSPORT"
	done

Text1598:
	text "THEY HAVE GENTLE HEARTS. BECAUSE"
	linefw "THEY RARELY FIGHT, MANY HAVE BEEN"
	linefw "CAUGHT. THEIR NUMBERS HAVE DWINDLED."
	done

Text1599:
	text "IT LOVES CROSSING THE SEA WITH"
	linefw "PEOPLE AND POKÉMON ON ITS BACK."
	linefw "IT UNDERSTANDS HUMAN SPEECH."
	done

Text159a:
	text "VAPOREON "
	done

Text159b:
	text "DURING YOUR NEXT TURN, VAPOREON'S"
	linefw "BITE ATTACK'S BASE DAMAGE IS"
	linefw "DOUBLED."
	done

Text159c:
	text "BUBBLE JET"
	done

Text159d:
	text "IT HAS EVOLVED TO BE SUITABLE FOR AN"
	linefw "AQUATIC LIFE. IT CAN INVISIBLY MELT"
	linefw "AWAY INTO WATER."
	done

Text159e:
	text "VAPOREON UNDERWENT A SPONTANEOUS"
	linefw "MUTATION AND GREW FINS AND GILLS"
	linefw "THAT ALLOW IT TO LIVE UNDERWATER."
	done

Text159f:
	text "DARK VAPOREON "
	done

Text15a0:
	text "IF THE DEFENDING POKÉMON HAS ANY"
	linefw "ENERGY CARDS ATTACHED TO IT, CHOOSE"
	linefw "1 OF THEM AND DISCARD IT."
	done

Text15a1:
	text "WHEN VAPOREON'S FINS BEGIN TO"
	linefw "VIBRATE, IT IS A SIGN THAT RAIN WILL"
	linefw "COME WITHIN A FEW HOURS. "
	done

Text15a2:
	text "OMANYTE "
	done

Text15a3:
	text "MYSTERIOUS FOSSIL "
	done

Text15a4:
	text "CLAIRVOYANCE"
	done

Text15a5:
	text "YOUR OPPONENT PLAYS WITH HIS OR HER"
	linefw "HAND FACE UP. THIS POWER STOPS"
	linefw "WORKING WHILE OMANYTE IS ASLEEP,"
	linefw "CONFUSED, OR PARALYZED."
	done

Text15a6:
	text "SPIRAL"
	done

Text15a7:
	text "A POKÉMON THAT WAS RESURRECTED FROM"
	linefw "A FOSSIL USING MODERN SCIENCE."
	linefw "IT SWAM IN ANCIENT SEAS."
	done

Text15a8:
	text "PREHISTORIC DREAM"
	done

Text15a9:
	text "ONCE DURING YOUR TURN (BEFORE YOUR"
	linefw "ATTACK) YOU MAY FLIP A COIN. IF"
	linefw "HEADS, ALL DAMAGE DONE BY POKÉMON"
	linefw "THAT HAVE EVOLVED FROM A MYSTERIOUS"
	linefw "FOSSIL WILL DO AN ADDITIONAL 10"
	linefw "DAMAGE WHEN THEY ATTACK. (THIS DOES"
	linefw "NOT APPLY TO BENCHED POKÉMON.)"
	done

Text15aa:
	text "THIS POWER CANNOT BE USED IF"
	linefw "THIS POKÉMON IS ASLEEP, CONFUSED,"
	linefw "OR PARALYZED."
	done

Text15ab:
	text "ROLLING TACKLE"
	done

Text15ac:
	text "REVIVED FROM AN ANCIENT FOSSIL, THIS"
	linefw "POKÉMON USES AIR STORED IN ITS SHELL"
	linefw "TO SINK AND RISE IN WATER. "
	done

Text15ad:
	text "FOSSIL GUIDANCE"
	done

Text15ae:
	text "ONCE DURING YOUR TURN (BEFORE YOUR"
	linefw "ATTACK) YOU MAY FLIP A COIN. IF"
	linefw "HEADS, SELECT 1 TRAINER CARD NAMED"
	linefw "MYSTERIOUS FOSSIL FROM YOUR DISCARD"
	linefw "PILE AND PUT IT INTO YOUR HAND. THIS"
	linefw "POWER CAN'T BE USED IF OMANYTE IS"
	linefw "ASLEEP, CONFUSED, OR PARALYZED."
	done

Text15af:
	text "OMASTAR "
	done

Text15b0:
	text "IT IS THOUGHT THAT THIS POKÉMON"
	linefw "BECAME EXTINCT BECAUSE ITS SPIRAL"
	linefw "SHELL GREW TOO LARGE."
	done

Text15b1:
	text "TENTACLE GRIP"
	done

Text15b2:
	text "FLIP A NUMBER OF COINS EQUAL TO THE"
	linefw "NUMBER OF ", "<WATER>", " ENERGY CARDS"
	linefw "ATTACHED TO OMASTAR. FOR EACH HEADS,"
	linefw "DRAW 2 CARDS."
	done

Text15b3:
	text "CORROSIVE ACID"
	done

Text15b4:
	text "FLIP A COIN. IF HEADS, THE"
	linefw "DEFENDING POKÉMON IS NOW PARALYZED."
	linefw "IF TAILS, YOU CAN'T USE THIS ATTACK"
	linefw "DURING YOUR NEXT TURN."
	done

Text15b5:
	text "APPARENTLY, IT CRACKED SHELLDER'S"
	linefw "SHELL WITH ITS SHARP FANGS AND"
	linefw "SUCKED OUT THE INSIDES. "
	done

Text15b6:
	text "ARTICUNO "
	done

Text15b7:
	text "AURORA VEIL"
	done

Text15b8:
	text "AS LONG AS ARTICUNO IS YOUR ACTIVE"
	linefw "POKÉMON, YOUR BENCHED POKÉMON DO NOT"
	linefw "TAKE DAMAGE FROM AND ARE NOT"
	linefw "AFFECTED BY ATTACKS. THIS POWER"
	linefw "CANNOT BE USED IF ARTICUNO IS"
	linefw "ASLEEP, CONFUSED, OR PARALYZED."
	done

Text15b9:
	text "FREEZE"
	done

Text15ba:
	text "THE MAGNIFICENT SEEMINGLY TRANS-"
	linefw "LUCENT WINGS OF THIS LEGENDARY BIRD"
	linefw "POKÉMON ARE SAID TO BE MADE OF ICE. "
	done

Text15bb:
	text "FREEZE DRY"
	done

Text15bc:
	text "BLIZZARD"
	done

Text15bd:
	text "FLIP A COIN. IF HEADS, THIS ATTACK"
	linefw "DOES 10 DAMAGE TO EACH OF YOUR"
	linefw "OPPONENT'S BENCHED POKÉMON. IF"
	linefw "TAILS, THIS ATTACK DOES 10 DAMAGE TO"
	linefw "EACH OF YOUR OWN BENCHED POKÉMON."
	linefw "(DON'T APPLY WEAKNESS AND RESISTANCE"
	linefw "FOR BENCHED POKÉMON.)"
	done

Text15be:
	text "A LEGENDARY BIRD POKÉMON. IT CAN"
	linefw "CREATE BLIZZARDS BY FREEZING"
	linefw "MOISTURE IN THE AIR."
	done

Text15bf:
	text "QUICK FREEZE"
	done

Text15c0:
	text "WHEN YOU PUT ARTICUNO INTO PLAY"
	linefw "DURING YOUR TURN (NOT DURING SETUP),"
	linefw "FLIP A COIN. IF HEADS, THE DEFENDING"
	linefw "POKÉMON IS NOW PARALYZED."
	done

Text15c1:
	text "ICE BREATH"
	done

Text15c2:
	text "DOES 40 DAMAGE TO 1 OF YOUR"
	linefw "OPPONENT'S POKÉMON CHOSEN AT RANDOM."
	linefw "DON'T APPLY WEAKNESS AND RESISTANCE"
	linefw "FOR THIS ATTACK. (ANY OTHER EFFECTS"
	linefw "OF ATTACKS THAT WOULD HAPPEN AFTER"
	linefw "APPLYING WEAKNESS AND RESISTANCE"
	linefw "STILL HAPPEN.)"
	done

Text15c3:
	text "A LEGENDARY BIRD POKÉMON THAT IS"
	linefw "SAID TO APPEAR TO DOOMED PEOPLE WHO"
	linefw "ARE LOST IN ICY MOUNTAINS. "
	done

Text15c4:
	text "MARILL "
	done

Text15c5:
	text "AQUA MOUSE"
	done

Text15c6:
	text "THE TIP OF ITS TAIL IS FILLED WITH"
	linefw "OIL THAT IS LIGHTER THAN WATER, SO"
	linefw "IT ACTS AS A FLOAT. "
	done

Text15c7:
	text "PIKACHU "
	done

Text15c8:
	text "THUNDERSHOCK"
	done

Text15c9:
	text "MOUSE"
	done

Text15ca:
	text "IT LIVES IN FORESTS WITH OTHERS."
	linefw "IT STORES ELECTRICITY IN THE POUCHES"
	linefw "ON ITS CHEEKS. "
	done

Text15cb:
	text "GNAW"
	done

Text15cc:
	text "THUNDER JOLT"
	done

Text15cd:
	text "FLIP A COIN. IF TAILS, PIKACHU DOES"
	linefw "10 DAMAGE TO ITSELF."
	done

Text15ce:
	text "IF IT LOOSES CRACKLING POWER FROM"
	linefw "THE ELECTRIC POUCHES ON ITS CHEEKS,"
	linefw "IT IS BEING WARY."
	done

Text15cf:
	text "RECHARGE"
	done

Text15d0:
	text "SEARCH YOUR DECK FOR A ", "<LIGHTNING>", " ENERGY"
	linefw "CARD AND ATTACH IT TO PIKACHU."
	linefw "SHUFFLE YOUR DECK AFTERWARD."
	done

Text15d1:
	text "THUNDERBOLT"
	done

Text15d2:
	text "DISCARD ALL ENERGY CARDS ATTACHED"
	linefw "TO PIKACHU."
	done

Text15d3:
	text "IT OCCASIONALLY USES AN ELECTRIC"
	linefw "SHOCK TO RECHARGE A FELLOW PIKACHU"
	linefw "THAT IS IN A WEAKENED STATE. "
	done

Text15d4:
	text "SPARK"
	done

Text15d5:
	text "IF YOUR OPPONENT HAS ANY BENCHED"
	linefw "POKÉMON, CHOOSE 1 OF THEM. THIS"
	linefw "ATTACK DOES 10 DAMAGE TO IT. (DON'T"
	linefw "APPLY WEAKNESS AND RESISTANCE FOR"
	linefw "BENCHED POKÉMON.)"
	done

Text15d6:
	text "THIS INTELLIGENT POKÉMON ROASTS HARD"
	linefw "BERRIES WITH ELECTRICITY TO MAKE"
	linefw "THEM TENDER ENOUGH TO EAT. "
	done

Text15d7:
	text "FLYING PIKACHU "
	done

Text15d8:
	text "FLY"
	done

Text15d9:
	text "FLIP A COIN. IF HEADS, DURING YOUR"
	linefw "OPPONENT'S NEXT TURN, PREVENT ALL"
	linefw "EFFECTS OF ATTACKS, INCLUDING"
	linefw "DAMAGE, DONE TO FLYING PIKACHU."
	linefw "IF TAILS, THIS ATTACK DOES NOTHING"
	linefw "(NOT EVEN DAMAGE)."
	done

Text15da:
	text "BY LEARNING HOW TO FLY, PIKACHU"
	linefw "OVERCAME ITS WEAKNESS TO"
	linefw "GROUND-TYPE POKÉMON."
	done

Text15db:
	text "SURFING PIKACHU "
	done

Text15dc:
	text "ONE SUMMER, A GROUP OF PIKACHU WAS"
	linefw "FOUND RIDING WAVES AT A LOCAL BEACH."
	done

Text15dd:
	text "RAICHU "
	done

Text15de:
	text "SHORT-CIRCUIT"
	done

Text15df:
	text "CHOOSE 1 OF YOUR OPPONENT'S POKÉMON."
	linefw "THIS ATTACK DOES 10 DAMAGE TIMES"
	linefw "THE NUMBER OF ", "<WATER>", " ENERGY CARDS"
	linefw "ATTACHED TO THAT POKÉMON. DON'T"
	linefw "APPLY WEAKNESS OR RESISTANCE."
	done

Text15e0:
	text "SPARKING KICK"
	done

Text15e1:
	text "ITS TAIL DISCHARGES ELECTRICITY INTO"
	linefw "THE GROUND, PROTECTING IT FROM"
	linefw "GETTING SHOCKED. "
	done

Text15e2:
	text "FLIP A COIN. IF HEADS, THIS ATTACK"
	linefw "DOES 20 ADDITIONAL DAMAGE."
	done

Text15e3:
	text "DISCARD ALL ENERGY CARDS ATTACHED"
	linefw "TO RAICHU IN ORDER TO USE THIS"
	linefw "ATTACK."
	done

Text15e4:
	text "IF THE ELECTRIC POUCHES IN ITS"
	linefw "CHEEKS BECOME FULLY CHARGED, BOTH"
	linefw "EARS WILL STAND STRAIGHT UP. "
	done

Text15e5:
	text "THUNDER"
	done

Text15e6:
	text "FLIP A COIN. IF TAILS, THIS POKÉMON"
	linefw "DOES 30 DAMAGE TO ITSELF."
	done

Text15e7:
	text "IT CAN LOOSE 100,000-VOLT BURSTS OF"
	linefw "ELECTRICITY, INSTANTLY DOWNING FOES"
	linefw "SEVERAL TIMES ITS SIZE."
	done

Text15e8:
	text "GIGASHOCK"
	done

Text15e9:
	text "CHOOSE 3 OF YOUR OPPONENT'S BENCHED"
	linefw "POKÉMON. THIS ATTACK DOES 10 DAMAGE"
	linefw "TO EACH OF THEM. (DON'T APPLY"
	linefw "WEAKNESS AND RESISTANCE FOR BENCHED"
	linefw "POKÉMON). IF YOUR OPPONENT HAS FEWER"
	linefw "THAN 3 BENCHED POKÉMON, DO THE"
	linefw "DAMAGE TO EACH OF THEM."
	done

Text15ea:
	text "DARK RAICHU "
	done

Text15eb:
	text "SURPRISE THUNDER"
	done

Text15ec:
	text "THIS ATTACK DOES 0, 10, OR 20 DAMAGE"
	linefw "TO EACH OF YOUR OPPONENT'S BENCHED"
	linefw "POKÉMON (THE AMOUNT OF DAMAGE DONE"
	linefw "IS RANDOM)."
	done

Text15ed:
	text "IT TURNS AGGRESSIVE IF IT HAS TOO"
	linefw "MUCH ELECTRICITY IN ITS BODY. IT"
	linefw "DISCHARGES POWER THROUGH ITS TAIL. "
	done

Text15ee:
	text "MAGNEMITE "
	done

Text15ef:
	text "MAGNETISM"
	done

Text15f0:
	text "DOES 10 DAMAGE PLUS 10 MORE DAMAGE"
	linefw "FOR EACH MAGNEMITE, MAGNETON, AND"
	linefw "DARK MAGNETON ON YOUR BENCH."
	done

Text15f1:
	text "MAGNET"
	done

Text15f2:
	text "THE FASTER THE UNITS AT ITS SIDES"
	linefw "ROTATE, THE GREATER THE MAGNETIC"
	linefw "FORCE THEY GENERATE. "
	done

Text15f3:
	text "THUNDERSHOCK"
	done

Text15f4:
	text "DOES 10 DAMAGE TO EACH POKÉMON ON"
	linefw "EACH PLAYER'S BENCH. (DON'T APPLY"
	linefw "WEAKNESS AND RESISTANCE FOR BENCHED"
	linefw "POKÉMON.) MAGNEMITE DOES 40 DAMAGE"
	linefw "TO ITSELF."
	done

Text15f5:
	text "THE UNITS AT ITS SIDES GENERATE"
	linefw "ELECTROMAGNETIC WAVES THAT KEEP IT"
	linefw "AIRBORNE. IT FEEDS ON ELECTRICITY."
	done

Text15f6:
	text "MAGNETIC STORM"
	done

Text15f7:
	text "REMOVE ALL ENERGY CARDS ATTACHED TO"
	linefw "ALL OF YOUR POKÉMON, THEN RANDOMLY"
	linefw "REATTACH EACH OF THEM."
	done

Text15f8:
	text "THIS POKÉMON BECOMES INCAPABLE OF"
	linefw "FLIGHT IF ITS INTERNAL ELECTRICAL"
	linefw "SUPPLY IS DEPLETED. "
	done

Text15f9:
	text "MAGNET"
	done

Text15fa:
	text "ONCE DURING YOUR TURN, YOU MAY"
	linefw "FLIP A COIN. IF HEADS, SEARCH YOUR"
	linefw "DECK FOR A POKÉMON NAMED MAGNEMITE"
	linefw "AND PUT IT ON YOUR BENCH. SHUFFLE"
	linefw "YOUR DECK. THIS POWER CAN'T BE USED"
	linefw "IF MAGNEMITE IS PARALYZED, CONFUSED,"
	linefw "ASLEEP, OR IF YOUR BENCH IS FULL."
	done

Text15fb:
	text "SUPERCONDUCTIVITY"
	done

Text15fc:
	text "CHOOSE 1 OF YOUR OPPONENT'S POKÉMON"
	linefw "AND DO 10 DAMAGE TO IT. DON'T APPLY"
	linefw "WEAKNESS AND RESISTANCE FOR THIS"
	linefw "ATTACK. (ANY OTHER EFFECTS THAT"
	linefw "WOULD HAPPEN AFTER APPLYING WEAKNESS"
	linefw "AND RESISTANCE STILL HAPPEN.)"
	done

Text15fd:
	text "IT IS ATTRACTED BY ELECTROMAGNETIC"
	linefw "WAVES. IT MAY APPROACH TRAINERS IF"
	linefw "THEY ARE USING THEIR POKÉGEAR. "
	done

Text15fe:
	text "MAGNETON "
	done

Text15ff:
	text "DOES 20 DAMAGE TO EACH POKÉMON ON"
	linefw "EACH PLAYER'S BENCH. (DON'T APPLY"
	linefw "WEAKNESS AND RESISTANCE FOR BENCHED"
	linefw "POKÉMON.) MAGNETON DOES 80 DAMAGE TO"
	linefw "ITSELF."
	done

Text1600:
	text "IT IS ACTUALLY THREE MAGNEMITE"
	linefw "LINKED BY MAGNETISM. A GROUP CAN"
	linefw "SET OFF A MAGNETIC STORM."
	done

Text1601:
	text "MICROWAVE"
	done

Text1602:
	text "CHOOSE 1 OF YOUR OPPONENT'S POKÉMON"
	linefw "IN PLAY AND DO 20 DAMAGE TO IT."
	linefw "(DON'T APPLY WEAKNESS AND"
	linefw "RESISTANCE.) FLIP A COIN. IF"
	linefw "HEADS, CHOOSE 1 ENERGY CARD ATTACHED"
	linefw "TO THAT POKÉMON AND DISCARD IT."
	done

Text1603:
	text "MANY MYSTERIOUSLY APPEAR WHEN MORE"
	linefw "SUNSPOTS DOT THE SUN. THEY STOP TV"
	linefw "SETS FROM DISPLAYING PROPERLY. "
	done

Text1604:
	text "SONICBOOM"
	done

Text1605:
	text "DON'T APPLY WEAKNESS AND RESISTANCE"
	linefw "FOR THIS ATTACK. (ANY OTHER EFFECTS"
	linefw "THAT WOULD HAPPEN AFTER APPLYING"
	linefw "WEAKNESS AND RESISTANCE STILL"
	linefw "HAPPEN.)"
	done

Text1606:
	text "DOES 20 DAMAGE TO EACH POKÉMON ON"
	linefw "EACH PLAYER'S BENCH. (DON'T APPLY"
	linefw "WEAKNESS AND RESISTANCE FOR BENCHED"
	linefw "POKÉMON.) THIS POKÉMON DOES"
	linefw "100 DAMAGE TO ITSELF."
	done

Text1607:
	text "DARK MAGNETON "
	done

Text1608:
	text "DON'T APPLY WEAKNESS AND RESISTANCE"
	linefw "FOR THIS ATTACK. (ANY OTHER EFFECTS"
	linefw "THAT WOULD HAPPEN AFTER APPLYING"
	linefw "WEAKNESS AND RESISTANCE STILL"
	linefw "HAPPEN.)"
	done

Text1609:
	text "MAGNETIC LINES"
	done

Text160a:
	text "IF THE DEFENDING POKÉMON HAS ANY"
	linefw "BASIC ENERGY CARDS ATTACHED TO IT,"
	linefw "CHOOSE 1 OF THEM. IF YOUR OPPONENT"
	linefw "HAS ANY BENCHED POKÉMON, CHOOSE 1 OF"
	linefw "THEM AND MOVE THAT ENERGY CARD TO"
	linefw "IT."
	done

Text160b:
	text "THREE MAGNEMITE ARE LINKED BY A"
	linefw "STRONG MAGNETIC FORCE. EARACHES WILL"
	linefw "OCCUR IF YOU GET TOO CLOSE. "
	done

Text160c:
	text "VOLTORB "
	done

Text160d:
	text "GROUP SPARK"
	done

Text160e:
	text "DOES 20 DAMAGE PLUS 10 TIMES THE"
	linefw "NUMBER OF VOLTORB IN PLAY."
	done

Text160f:
	text "BALL"
	done

Text1610:
	text "IT ROLLS TO MOVE. IF THE GROUND IS"
	linefw "UNEVEN, A SUDDEN JOLT FROM HITTING A"
	linefw "BUMP CAN CAUSE IT TO EXPLODE."
	done

Text1611:
	text "IT LOOKS JUST LIKE A POKÉBALL."
	linefw "IT IS DANGEROUS BECAUSE IT MAY"
	linefw "ELECTROCUTE OR EXPLODE ON TOUCH."
	done

Text1612:
	text "SPEEDBALL"
	done

Text1613:
	text "IT WAS DISCOVERED WHEN POKÉ BALLS"
	linefw "WERE INTRODUCED. IT IS SAID THAT"
	linefw "THERE IS SOME CONNECTION. "
	done

Text1614:
	text "ELECTRODE "
	done

Text1615:
	text "ENERGY SPIKE"
	done

Text1616:
	text "SEARCH YOUR DECK FOR A BASIC ENERGY"
	linefw "CARD AND ATTACH IT TO 1 OF YOUR"
	linefw "POKÉMON. SHUFFLE YOUR DECK"
	linefw "AFTERWARD."
	done

Text1617:
	text "STORES ELECTRICAL ENERGY INSIDE ITS"
	linefw "BODY. EVEN THE SLIGHTEST SHOCK"
	linefw "COULD TRIGGER A HUGE EXPLOSION. "
	done

Text1618:
	text "CHAIN LIGHTNING"
	done

Text1619:
	text "IF THE DEFENDING POKÉMON ISN'T"
	linefw "COLORLESS, THIS ATTACK DOES 10"
	linefw "DAMAGE TO EACH BENCHED POKÉMON OF"
	linefw "THE SAME TYPE AS THE DEFENDING"
	linefw "POKÉMON (INCLUDING YOUR OWN)."
	done

Text161a:
	text "IT STORES ELECTRIC ENERGY UNDER VERY"
	linefw "HIGH PRESSURE. IT OFTEN EXPLODES"
	linefw "WITH LITTLE OR NO PROVOCATION."
	done

Text161b:
	text "DARK ELECTRODE "
	done

Text161c:
	text "ENERGY BOMB"
	done

Text161d:
	text "TAKE ALL ENERGY CARDS ATTACHED TO"
	linefw "DARK ELECTRODE AND ATTACH THEM TO"
	linefw "YOUR BENCHED POKÉMON (IN ANY WAY"
	linefw "YOU CHOOSE). IF YOU HAVE NO BENCHED"
	linefw "POKÉMON, DISCARD ALL ENERGY CARDS"
	linefw "ATTACHED TO DARK ELECTRODE."
	done

Text161e:
	text "IT IS DANGEROUS. IF IT HAS TOO MUCH"
	linefw "ELECTRICITY AND HAS NOTHING TO DO,"
	linefw "IT AMUSES ITSELF BY EXPLODING. "
	done

Text161f:
	text "ELECTABUZZ "
	done

Text1620:
	text "LIGHT SCREEN"
	done

Text1621:
	text "IF ELECTABUZZ RECEIVES DAMAGE"
	linefw "DURING YOUR OPPONENT'S NEXT TURN,"
	linefw "THE ATTACK ONLY DOES HALF THE"
	linefw "DAMAGE (ROUNDED DOWN TO THE NEAREST"
	linefw "10). (ANY OTHER EFFECTS OF ATTACKS"
	linefw "STILL HAPPEN.)"
	done

Text1622:
	text "HALF OF ALL BLACKOUTS OCCUR WHEN"
	linefw "THIS POKÉMON APPEARS AT POWER PLANTS"
	linefw "AND EATS ELECTRICITY."
	done

Text1623:
	text "IT WINDMILLS ITS ARMS TO SLIGHTLY"
	linefw "BOOST ITS PUNCHES. FOES HAVE BEEN"
	linefw "KNOWN TO ESCAPE IN THE MEANTIME. "
	done

Text1624:
	text "THUNDERPUNCH"
	done

Text1625:
	text "FLIP A COIN. IF HEADS, THIS ATTACK"
	linefw "DOES 30 DAMAGE PLUS 10 MORE DAMAGE;"
	linefw "IF TAILS, THIS ATTACK DOES 30 DAMAGE"
	linefw "AND ELECTABUZZ DOES 10 DAMAGE TO"
	linefw "ITSELF."
	done

Text1626:
	text "NORMALLY FOUND NEAR POWER PLANTS,"
	linefw "THEY CAN WANDER AWAY AND CAUSE MAJOR"
	linefw "BLACKOUTS IN CITIES. "
	done

Text1627:
	text "JOLTEON "
	done

Text1628:
	text "FLIP 2 COINS. THIS ATTACK DOES 20"
	linefw "DAMAGE TIMES THE NUMBER OF HEADS."
	done

Text1629:
	text "STUN NEEDLE"
	done

Text162a:
	text "IT CONTROLS 10,000-VOLT POWER AND"
	linefw "CAN RAISE ALL THE FUR ON ITS BODY AS"
	linefw "IF IT WERE SHARP NEEDLES."
	done

Text162b:
	text "FLIP A COIN. IF HEADS, THIS ATTACK"
	linefw "DOES 10 DAMAGE PLUS 20 MORE DAMAGE;"
	linefw "IF TAILS, THIS ATTACK DOES 10"
	linefw "DAMAGE. "
	done

Text162c:
	text "PIN MISSILE"
	done
