Text162d:
	text "FLIP 4 COINS. THIS ATTACK DOES 20"
	linefw "DAMAGE TIMES THE NUMBER OF HEADS."
	done

Text162e:
	text "ITS CELLS GENERATE WEAK POWER THAT"
	linefw "IS AMPLIFIED BY ITS FUR'S STATIC"
	linefw "ELECTRICITY TO DROP THUNDERBOLTS."
	done

Text162f:
	text "DARK JOLTEON "
	done

Text1630:
	text "LIGHTNING FLASH"
	done

Text1631:
	text "IF THE DEFENDING POKÉMON TRIES TO"
	linefw "ATTACK DURING YOUR OPPONENT'S NEXT"
	linefw "TURN, YOUR OPPONENT FLIPS A COIN."
	linefw "IF TAILS, THAT ATTACK DOES NOTHING. "
	done

Text1632:
	text "THUNDER ATTACK"
	done

Text1633:
	text "FLIP A COIN. IF HEADS, THE"
	linefw "DEFENDING POKÉMON IS NOW PARALYZED."
	linefw "IF TAILS, DARK JOLTEON DOES 10"
	linefw "DAMAGE TO ITSELF."
	done

Text1634:
	text "IF AGITATED, IT USES ELECTRICITY TO"
	linefw "STRAIGHTEN OUT ITS FUR AND LAUNCH IT"
	linefw "IN SMALL BUNCHES. "
	done

Text1635:
	text "ZAPDOS "
	done

Text1636:
	text "RAGING THUNDER"
	done

Text1637:
	text "FLIP A COIN. IF TAILS, CHOOSE 1 OF"
	linefw "YOUR POKÉMON. THIS ATTACK DOES 30"
	linefw "DAMAGE TO IT. (DON'T APPLY WEAKNESS"
	linefw "AND RESISTANCE FOR BENCHED POKÉMON.)"
	done

Text1638:
	text "THUNDER CRASH"
	done

Text1639:
	text "FLIP A COIN. IF HEADS, THIS ATTACK"
	linefw "DOES 50 DAMAGE PLUS 20 MORE DAMAGE;"
	linefw "IF TAILS, THIS ATTACK DOES 50 DAMAGE"
	linefw "AND ZAPDOS DOES 20 DAMAGE TO ITSELF."
	done

Text163a:
	text "THIS LEGENDARY BIRD POKÉMON CAUSES"
	linefw "SAVAGE THUNDERSTORMS BY FLAPPING"
	linefw "ITS GLITTERING WINGS. "
	done

Text163b:
	text "THUNDERSTORM"
	done

Text163c:
	text "FOR EACH OF YOUR OPPONENT'S BENCHED"
	linefw "POKÉMON, FLIP A COIN. IF HEADS, THIS"
	linefw "ATTACK DOES 20 DAMAGE TO THAT"
	linefw "POKÉMON. (DON'T APPLY WEAKNESS AND"
	linefw "RESISTANCE FOR BENCHED POKÉMON.)"
	linefw "THEN, ZAPDOS DOES 10 DAMAGE TIMES"
	linefw "THE NUMBER OF TAILS TO ITSELF."
	done

Text163d:
	text "A LEGENDARY POKÉMON THAT IS SAID TO"
	linefw "LIVE IN THUNDERCLOUDS. IT FREELY"
	linefw "CONTROLS LIGHTNING BOLTS."
	done

Text163e:
	text "DISCARD ALL ENERGY CARDS ATTACHED"
	linefw "TO ZAPDOS IN ORDER TO USE THIS"
	linefw "ATTACK."
	done

Text163f:
	text "ONE OF THE LEGENDARY BIRD POKÉMON."
	linefw "WHILE IT IS FLYING, IT MAKES"
	linefw "CRACKLING AND SNAPPING SOUNDS."
	done

Text1640:
	text "PEAL OF THUNDER"
	done

Text1641:
	text "WHEN YOU PUT ZAPDOS INTO PLAY"
	linefw "DURING YOUR TURN (NOT DURING SETUP),"
	linefw "DO 30 DAMAGE TO A POKÉMON OTHER"
	linefw "THAN ZAPDOS CHOSEN AT RANDOM. (DON'T"
	linefw "APPLY WEAKNESS AND RESISTANCE.)"
	done

Text1642:
	text "BIG THUNDER"
	done

Text1643:
	text "CHOOSE A POKÉMON OTHER THAN ZAPDOS"
	linefw "AT RANDOM. THIS ATTACK DOES 70"
	linefw "DAMAGE TO THAT POKÉMON. DON'T APPLY"
	linefw "WEAKNESS AND RESISTANCE FOR THIS"
	linefw "ATTACK. (ANY OTHER EFFECTS THAT"
	linefw "WOULD HAPPEN AFTER APPLYING WEAKNESS"
	linefw "AND RESISTANCE STILL HAPPEN.)"
	done

Text1644:
	text "IT USUALLY LIVES IN THUNDERCLOUDS."
	linefw "IT GAINS POWER IF IT IS STRICKEN BY"
	linefw "LIGHTNING BOLTS. "
	done

Text1645:
	text "SANDSHREW "
	done

Text1646:
	text "SAND-ATTACK"
	done

Text1647:
	text "TO PROTECT ITSELF FROM ATTACKERS, IT"
	linefw "CURLS UP INTO A BALL. IT LIVES IN"
	linefw "ARID REGIONS WITH MINIMAL RAINFALL."
	done

Text1648:
	text "SWIFT"
	done

Text1649:
	text "THIS ATTACK'S DAMAGE ISN'T AFFECTED"
	linefw "BY WEAKNESS, RESISTANCE, POKÉMON"
	linefw "POWERS, OR ANY OTHER EFFECTS ON THE"
	linefw "DEFENDING POKÉMON."
	done

Text164a:
	text "IF IT FELL FROM A GREAT HEIGHT, THIS"
	linefw "POKÉMON COULD SAVE ITSELF BY ROLLING"
	linefw "INTO A BALL AND BOUNCING. "
	done

Text164b:
	text "SANDSLASH "
	done

Text164c:
	text "FLIP 3 COINS. THIS ATTACK DOES 20"
	linefw "DAMAGE TIMES THE NUMBER OF HEADS."
	done

Text164d:
	text "IT CURLS UP, THEN ROLLS INTO FOES"
	linefw "WITH ITS BACK. ITS SHARP SPINES"
	linefw "INFLICT SEVERE DAMAGE."
	done

Text164e:
	text "SAND VEIL"
	done

Text164f:
	text "ROLLING NEEDLE"
	done

Text1650:
	text "FLIP 3 COINS. THIS ATTACK DOES 40"
	linefw "DAMAGE PLUS 10 MORE DAMAGE FOR EACH"
	linefw "HEADS. THEN, SANDSLASH DOES 10"
	linefw "DAMAGE TIMES THE NUMBER OF TAILS TO"
	linefw "ITSELF."
	done

Text1651:
	text "IN AN ATTEMPT TO HIDE ITSELF, IT"
	linefw "WILL RUN AROUND AT TOP SPEED TO KICK"
	linefw "UP A BLINDING DUST STORM. "
	done

Text1652:
	text "DIGLETT "
	done

Text1653:
	text "DIG"
	done

Text1654:
	text "MUD SLAP"
	done

Text1655:
	text "MOLE"
	done

Text1656:
	text "A POKÉMON THAT LIVES UNDERGROUND."
	linefw "BECAUSE OF ITS DARK HABITAT, IT IS"
	linefw "REPELLED BY BRIGHT SUNLIGHT."
	done

Text1657:
	text "DIG UNDER"
	done

Text1658:
	text "CHOOSE 1 OF YOUR OPPONENT'S"
	linefw "POKÉMON. THIS ATTACK DOES 10 DAMAGE"
	linefw "TO THAT POKÉMON. (ANY OTHER EFFECTS"
	linefw "THAT WOULD HAPPEN AFTER APPLYING"
	linefw "WEAKNESS AND RESISTANCE STILL"
	linefw "HAPPEN.)"
	done

Text1659:
	text "ITS SKIN IS VERY THIN. IF IT IS"
	linefw "EXPOSED TO LIGHT, ITS BLOOD HEATS"
	linefw "UP, CAUSING IT TO GROW WEAK. "
	done

Text165a:
	text "ROLLING MOVEMENT"
	done

Text165b:
	text "IF A DIGLETT DIGS THROUGH A FIELD,"
	linefw "IT LEAVES THE SOIL PERFECTLY TILLED"
	linefw "AND IDEAL FOR PLANTING CROPS. "
	done

Text165c:
	text "DUGTRIO "
	done

Text165d:
	text "EARTHQUAKE"
	done

Text165e:
	text "DOES 10 DAMAGE TO EACH OF YOUR OWN"
	linefw "BENCHED POKÉMON. (DON'T APPLY"
	linefw "WEAKNESS AND RESISTANCE TO BENCHED"
	linefw "POKÉMON.)"
	done

Text165f:
	text "ITS THREE HEADS MOVE ALTERNATELY,"
	linefw "DRIVING IT THROUGH TOUGH SOIL TO"
	linefw "DEPTHS OF OVER 60 MILES."
	done

Text1660:
	text "GO UNDERGROUND"
	done

Text1661:
	text "AS LONG AS DUGTRIO IS ON THE BENCH,"
	linefw "PREVENT ALL DAMAGE DONE BY ATTACKS"
	linefw "TO DUGTRIO. "
	done

Text1662:
	text "EARTH WAVE"
	done

Text1663:
	text "CHOOSE UP TO 2 OF YOUR OPPONENT'S"
	linefw "BENCHED POKÉMON. THIS ATTACK DOES"
	linefw "10 DAMAGE TO EACH OF THEM. (DON'T"
	linefw "APPLY WEAKNESS AND RESISTANCE FOR"
	linefw "BENCHED POKÉMON.)"
	done

Text1664:
	text "ITS THREE HEADS BOB SEPARATELY UP"
	linefw "AND DOWN TO LOOSEN THE SOIL NEARBY,"
	linefw "MAKING IT EASIER FOR IT TO BURROW. "
	done

Text1665:
	text "DARK DUGTRIO "
	done

Text1666:
	text "SINKHOLE"
	done

Text1667:
	text "WHENEVER YOUR OPPONENT RETREATS"
	linefw "THEIR ACTIVE POKÉMON, THEY FLIP A"
	linefw "COIN. IF TAILS, DO 20 DAMAGE TO THAT"
	linefw "POKÉMON. (DON'T APPLY WEAKNESS AND"
	linefw "RESISTANCE.) THIS POWER STOPS"
	linefw "WORKING WHILE DARK DUGTRIO IS"
	linefw "ASLEEP, CONFUSED, OR PARALYZED."
	done

Text1668:
	text "KNOCKDOWN"
	done

Text1669:
	text "YOUR OPPONENT FLIPS A COIN. IF"
	linefw "TAILS, THIS ATTACK DOES 20 DAMAGE"
	linefw "PLUS 20 MORE DAMAGE; IF HEADS, THIS"
	linefw "ATTACK DOES 20 DAMAGE."
	done

Text166a:
	text "EXTREMELY POWERFUL, THEY CAN DIG"
	linefw "THROUGH EVEN THE HARDEST GROUND TO"
	linefw "A DEPTH OF OVER 60 MILES. "
	done

Text166b:
	text "MANKEY "
	done

Text166c:
	text "PEEK"
	done

Text166d:
	text "ONCE DURING YOUR TURN, YOU MAY"
	linefw "LOOK AT THE TOP CARD OF EITHER"
	linefw "PLAYER'S DECK, A RANDOM CARD FROM"
	linefw "YOUR OPPONENT'S HAND, OR ONE OF"
	linefw "EITHER PLAYER'S PRIZES. THIS POWER"
	linefw "CAN'T BE USED IF MANKEY IS ASLEEP,"
	linefw "CONFUSED, OR PARALYZED."
	done

Text166e:
	text "PIG MONKEY"
	done

Text166f:
	text "IT LIVES IN TREETOP COLONIES. IF ONE"
	linefw "BECOMES ENRAGED, THE WHOLE COLONY"
	linefw "RAMPAGES FOR NO REASON."
	done

Text1670:
	text "MISCHIEF"
	done

Text1671:
	text "SHUFFLE YOUR OPPONENT'S DECK."
	done

Text1672:
	text "ANGER"
	done

Text1673:
	text "IT IS EXTREMELY ILL-TEMPERED. GROUPS"
	linefw "OF THEM WILL ATTACK ANY HANDY TARGET"
	linefw "FOR NO REASON. "
	done

Text1674:
	text "PRIMEAPE "
	done

Text1675:
	text "TANTRUM"
	done

Text1676:
	text "FLIP A COIN. IF TAILS, PRIMEAPE IS"
	linefw "NOW CONFUSED (AFTER DOING DAMAGE)."
	done

Text1677:
	text "IT GROWS ANGRY IF YOU SEE ITS EYES"
	linefw "AND GETS ANGRIER IF YOU RUN. IF YOU"
	linefw "BEAT IT, IT GETS EVEN MADDER."
	done

Text1678:
	text "DARK PRIMEAPE "
	done

Text1679:
	text "FRENZY"
	done

Text167a:
	text "IF DARK PRIMEAPE DOES ANY DAMAGE"
	linefw "WHILE IT'S CONFUSED (EVEN TO"
	linefw "ITSELF), IT DOES 30 MORE DAMAGE."
	done

Text167b:
	text "FRENZIED ATTACK"
	done

Text167c:
	text "DARK PRIMEAPE IS NOW CONFUSED"
	linefw "(AFTER DOING DAMAGE)."
	done

Text167d:
	text "IT BECOMES WILDLY FURIOUS IF IT EVEN"
	linefw "SENSES SOMEONE LOOKING AT IT. IT"
	linefw "CHASES ANYONE THAT MEETS ITS GLARE. "
	done

Text167e:
	text "MACHOP "
	done

Text167f:
	text "FOCUS ENERGY"
	done

Text1680:
	text "FLIP A COIN. IF HEADS, MACHOP'S"
	linefw "CORKSCREW PUNCH ATTACK'S BASE DAMAGE"
	linefw "IS 60 INSTEAD OF 30 DURING YOUR NEXT"
	linefw "TURN. IF TAILS, YOU CAN'T USE"
	linefw "CORKSCREW PUNCH NEXT TURN."
	done

Text1681:
	text "CORKSCREW PUNCH"
	done

Text1682:
	text "SUPERPOWER"
	done

Text1683:
	text "IT HEFTS A GRAVELER REPEATEDLY TO"
	linefw "STRENGTHEN ITS ENTIRE BODY. IT USES"
	linefw "EVERY TYPE OF MARTIAL ARTS. "
	done

Text1684:
	text "LOW KICK"
	done

Text1685:
	text "ITS MUSCLES NEVER CRAMP HOWEVER MUCH"
	linefw "IT TRAINS. IT LIVES IN THE MOUNTAINS"
	linefw "AWAY FROM HUMANS."
	done

Text1686:
	text "PUNCH"
	done

Text1687:
	text "KICK"
	done

Text1688:
	text "THOUGH SMALL IN STATURE, IT IS"
	linefw "POWERFUL ENOUGH TO EASILY HEFT AND"
	linefw "THROW A NUMBER OF GEODUDE AT ONCE. "
	done

Text1689:
	text "MACHOKE "
	done

Text168a:
	text "AGONIZING THRUST"
	done

Text168b:
	text "FOCUS BLAST"
	done

Text168c:
	text "FLIP A COIN. IF HEADS, CHOOSE 1 OF"
	linefw "YOUR OPPONENT'S POKÉMON. THIS"
	linefw "ATTACK DOES 20 DAMAGE TO IT. APPLY"
	linefw "WEAKNESS AND RESISTANCE AS"
	linefw "NORMAL."
	done

Text168d:
	text "MACHOKE'S BOUNDLESS POWER IS VERY"
	linefw "DANGEROUS, SO IT WEARS A BELT THAT"
	linefw "SUPPRESSES ITS ENERGY. "
	done

Text168e:
	text "MEGA KICK"
	done

Text168f:
	text "ONE-TWO PUNCH"
	done

Text1690:
	text "IT HAPPILY CARRIES HEAVY CARGO TO"
	linefw "TOUGHEN UP. IT WILLINGLY DOES HARD"
	linefw "WORK FOR PEOPLE. "
	done

Text1691:
	text "KARATE CHOP"
	done

Text1692:
	text "DOES 50 DAMAGE MINUS 10 DAMAGE FOR"
	linefw "EACH DAMAGE COUNTER ON THIS POKÉMON."
	done

Text1693:
	text "SUBMISSION"
	done

Text1694:
	text "IT CAN LIFT A DUMP TRUCK WITH ONE"
	linefw "HAND. USING THAT POWER, IT HELPS"
	linefw "PEOPLE WITH HEAVY JOBS."
	done

Text1695:
	text "DARK MACHOKE "
	done

Text1696:
	text "DRAG OFF"
	done

Text1697:
	text "BEFORE DOING DAMAGE, CHOOSE 1 OF"
	linefw "YOUR OPPONENT'S BENCHED POKÉMON AND"
	linefw "SWITCH IT WITH THE DEFENDING"
	linefw "POKÉMON. DO THE DAMAGE TO THE NEW"
	linefw "DEFENDING POKÉMON. THIS ATTACK"
	linefw "CAN'T BE USED IF YOUR OPPONENT HAS"
	linefw "NO BENCHED POKÉMON."
	done

Text1698:
	text "KNOCK BACK"
	done

Text1699:
	text "WHILE NORMALLY PEACEFUL AND"
	linefw "FRIENDLY, THE NUMBER OF INCIDENTS"
	linefw "INVOLVING CRUEL MACHOKES IS RISING. "
	done

Text169a:
	text "MACHAMP "
	done

Text169b:
	text "EXPLOSION OF RAGE"
	done

Text169c:
	text "FLIP A NUMBER OF COINS EQUAL TO"
	linefw "THE AMOUNT OF DAMAGE COUNTERS ON"
	linefw "MACHAMP. THIS ATTACK DOES 20 DAMAGE"
	linefw "PLUS 10 DAMAGE TIMES THE NUMBER OF"
	linefw "HEADS."
	done

Text169d:
	text "FLING AWAY"
	done

Text169e:
	text "USING ITS AMAZING MUSCLES, IT THROWS"
	linefw "POWERFUL PUNCHES THAT CAN KNOCK ITS"
	linefw "VICTIM CLEAR OVER THE HORIZON. "
	done

Text169f:
	text "STRIKES BACK"
	done

Text16a0:
	text "WHENEVER YOUR OPPONENT'S ATTACK"
	linefw "DAMAGES MACHAMP (EVEN IF MACHAMP IS"
	linefw "KNOCKED OUT), THIS POWER DOES 10"
	linefw "DAMAGE TO THE ATTACKING POKÉMON."
	linefw "(DON'T APPLY WEAKNESS AND"
	linefw "RESISTANCE.)"
	done

Text16a1:
	text "THIS POWER CAN'T BE USED IF MACHAMP"
	linefw "IS ASLEEP, CONFUSED, OR PARALYZED"
	linefw "WHEN YOUR OPPONENT ATTACKS."
	done

Text16a2:
	text "SEISMIC TOSS"
	done

Text16a3:
	text "IT CAN KNOCK A TRAIN FLYING WITH A"
	linefw "PUNCH. HOWEVER, IT IS TERRIBLE AT"
	linefw "DELICATE WORK USING ITS FINGERS."
	done

Text16a4:
	text "DARK MACHAMP "
	done

Text16a5:
	text "FLING"
	done

Text16a6:
	text "YOUR OPPONENT SHUFFLES HIS OR HER"
	linefw "ACTIVE POKÉMON AND ALL CARDS"
	linefw "ATTACHED TO IT INTO HIS OR HER"
	linefw "DECK. THIS ATTACK CAN'T BE USED IF"
	linefw "YOUR OPPONENT HAS NO BENCHED"
	linefw "POKÉMON."
	done

Text16a7:
	text "IT PUNCHES WITH ITS FOUR ARMS AT"
	linefw "BLINDING SPEED. IT CAN LAUNCH 1,000"
	linefw "PUNCHES IN TWO SECONDS."
	done

Text16a8:
	text "GEODUDE "
	done

Text16a9:
	text "HARDEN"
	done

Text16aa:
	text "DURING YOUR OPPONENT'S NEXT TURN,"
	linefw "WHENEVER 20 OR LESS DAMAGE IS DONE"
	linefw "TO GEODUDE (AFTER APPLYING WEAKNESS"
	linefw "AND RESISTANCE), PREVENT THAT"
	linefw "DAMAGE. (ANY OTHER EFFECTS OF"
	linefw "ATTACKS STILL HAPPEN.)"
	done

Text16ab:
	text "ROCK"
	done

Text16ac:
	text "MANY LIVE ON MOUNTAIN TRAILS AND"
	linefw "REMAIN HALF BURIED WHILE KEEPING AN"
	linefw "EYE ON CLIMBERS. "
	done

Text16ad:
	text "STONE BARRAGE"
	done

Text16ae:
	text "FLIP A COIN UNTIL YOU GET TAILS."
	linefw "THIS ATTACK DOES 10 DAMAGE TIMES"
	linefw "THE NUMBER OF HEADS."
	done

Text16af:
	text "IT IS IMPOSSIBLE TO DISTINGUISH FROM"
	linefw "ROCKS. IT SLAMS AGAINST OTHERS IN"
	linefw "CONTESTS OF HARDNESS."
	done

Text16b0:
	text "GRAVELER "
	done

Text16b1:
	text "BOULDER SMASH"
	done

Text16b2:
	text "FLIP 2 COINS. FOR EACH HEADS,"
	linefw "CHOOSE 1 OF YOUR OPPONENT'S BENCHED"
	linefw "POKÉMON AND DO 10 DAMAGE TO IT."
	done

Text16b3:
	text "GRAVELER MAKE THEIR HOMES ON SHEER"
	linefw "CLIFF FACES BY GOUGING OUT NUMEROUS"
	linefw "HORIZONTAL HOLES. "
	done

Text16b4:
	text "STONE BARRAGE"
	done

Text16b5:
	text "FLIP A COIN UNTIL YOU GET TAILS."
	linefw "THIS ATTACK DOES 20 DAMAGE TIMES"
	linefw "THE NUMBER OF HEADS."
	done

Text16b6:
	text "DOES 10 DAMAGE TO EACH OF YOUR OWN"
	linefw "BENCHED POKÉMON. (DON'T APPLY"
	linefw "WEAKNESS AND RESISTANCE TO BENCHED"
	linefw "POKÉMON.)"
	done

Text16b7:
	text "WITH A FREE AND UNCARING NATURE, IT"
	linefw "DOESN'T MIND IF PIECES BREAK OFF"
	linefw "WHILE IT ROLLS DOWN MOUNTAINS. "
	done

Text16b8:
	text "DURING YOUR OPPONENT'S NEXT TURN,"
	linefw "WHENEVER 30 OR LESS DAMAGE IS DONE"
	linefw "TO GRAVELER (AFTER APPLYING WEAKNESS"
	linefw "AND RESISTANCE), PREVENT THAT"
	linefw "DAMAGE. (ANY OTHER EFFECTS OF"
	linefw "ATTACKS STILL HAPPEN.)"
	done

Text16b9:
	text "ROCK THROW"
	done

Text16ba:
	text "IT TUMBLES DOWN SLOPES, HEEDLESS OF"
	linefw "ANY BODY PARTS CHIPPING OFF. IT EATS"
	linefw "A TON OF ROCKS DAILY."
	done

Text16bb:
	text "GOLEM "
	done

Text16bc:
	text "AVALANCE"
	done

Text16bd:
	text "MEGATON"
	done

Text16be:
	text "IT TUMBLES DOWN MOUNTAINS, LEAVING"
	linefw "GROOVES FROM PEAK TO BASE. STAY"
	linefw "CLEAR OF THESE GROOVES."
	done

Text16bf:
	text "ROCK BLAST"
	done

Text16c0:
	text "DISCARD UP TO 5 ", "<FIGHTING>", " ENERGY CARDS"
	linefw "ATTACHED TO GOLEM. FOR EACH ", "<FIGHTING>"
	linefw "ENERGY CARD DISCARDED, CHOOSE 1 OF"
	linefw "YOUR OPPONENT'S POKÉMON AND DO 20"
	linefw "DAMAGE TO IT. (YOU MAY CHOOSE ANY"
	linefw "OF YOUR OPPONENT'S POKÉMON MORE"
	linefw "THAN ONCE.)"
	done

Text16c1:
	text "DON'T APPLY WEAKNESS OR RESISTANCE."
	linefw "(ANY OTHER EFFECTS THAT WOULD HAPPEN"
	linefw "AFTER APPLYING WEAKNESS AND"
	linefw "RESISTANCE STILL HAPPEN.)"
	done

Text16c2:
	text "IT SHEDS ITS HIDE ONCE A YEAR. ITS"
	linefw "BOULDERLIKE BODY IS SO TOUGH, EVEN"
	linefw "DYNAMITE CAN'T HARM IT. "
	done

Text16c3:
	text "ONIX "
	done

Text16c4:
	text "DURING YOUR OPPONENT'S NEXT TURN,"
	linefw "WHENEVER 30 OR LESS DAMAGE IS DONE"
	linefw "TO ONIX (AFTER APPLYING WEAKNESS AND"
	linefw "RESISTANCE), PREVENT THAT DAMAGE."
	linefw "(ANY OTHER EFFECTS OF ATTACKS STILL"
	linefw "HAPPEN.)"
	done

Text16c5:
	text "ROCK SNAKE"
	done

Text16c6:
	text "IT SQUIRMS THROUGH THE GROUND USING"
	linefw "ITS LONG AND RUGGED BODY. IT ALWAYS"
	linefw "EATS WHILE BURROWING."
	done

Text16c7:
	text "ROCK TOMB"
	done

Text16c8:
	text "FLIP A COIN. IF HEADS, THE"
	linefw "DEFENDING POKÉMON CAN'T RETREAT"
	linefw "DURING YOUR OPPONENT'S NEXT TURN."
	done

Text16c9:
	text "WHEN IT TRAVELS UNDERGROUND, IT"
	linefw "CAUSES RUMBLING AND TREMORS."
	linefw "IT CAN MOVE AT 50 MPH. "
	done

Text16ca:
	text "CUBONE "
	done

Text16cb:
	text "SNIVEL"
	done

Text16cc:
	text "IF THE DEFENDING POKÉMON ATTACKS"
	linefw "CUBONE DURING YOUR OPPONENT'S NEXT"
	linefw "TURN, ANY DAMAGE DONE BY THE ATTACK"
	linefw "IS REDUCED BY 20 (AFTER APPLYING"
	linefw "WEAKNESS AND RESISTANCE). (BENCHING"
	linefw "EITHER POKÉMON ENDS THIS EFFECT.)"
	done

Text16cd:
	text "LONELY"
	done

Text16ce:
	text "WHEN IT THINKS OF ITS DEAD MOTHER,"
	linefw "IT CRIES. ITS CRYING MAKES THE SKULL"
	linefw "IT WEARS RATTLE HOLLOWLY."
	done

Text16cf:
	text "BONE TOSS"
	done

Text16d0:
	text "FLIP A COIN. IF HEADS, THIS ATTACK"
	linefw "DOES 30 DAMAGE TO THE DEFENDING"
	linefw "POKÉMON. IF TAILS, CHOOSE 1 OF YOUR"
	linefw "OPPONENT'S BENCHED POKÉMON AND DO 10"
	linefw "DAMAGE TO IT. (DON'T APPLY WEAKNESS"
	linefw "AND RESISTANCE FOR BENCHED POKÉMON.)"
	done

Text16d1:
	text "IF IT IS SAD OR LONELY, THE SKULL"
	linefw "IT WEARS SHAKES AND EMITS A"
	linefw "PLAINTIVE AND MOURNFUL SOUND. "
	done

Text16d2:
	text "MAROWAK "
	done

Text16d3:
	text "BONE BOOMERANG"
	done

Text16d4:
	text "CALL FOR FAMILY"
	done

Text16d5:
	text "SEARCH YOUR DECK FOR A ", "<FIGHTING>", " BASIC"
	linefw "POKÉMON CARD AND PUT IT ONTO YOUR"
	linefw "BENCH. SHUFFLE YOUR DECK AFTERWARD."
	linefw "(YOU CAN'T USE THIS ATTACK IF YOUR"
	linefw "BENCH IS FULL.)"
	done

Text16d6:
	text "BONEKEEPER"
	done

Text16d7:
	text "FROM ITS BIRTH, THIS SAVAGE POKÉMON"
	linefw "CONSTANTLY HOLDS BONES. IT IS"
	linefw "SKILLED IN USING THEM AS WEAPONS."
	done

Text16d8:
	text "BONE ATTACK"
	done

Text16d9:
	text "FLIP A COIN. IF HEADS, THE"
	linefw "DEFENDING POKÉMON CAN'T ATTACK"
	linefw "DURING YOUR OPPONENT'S NEXT TURN."
	done

Text16da:
	text "WAIL"
	done

Text16db:
	text "EACH PLAYER FILLS HIS OR HER BENCH"
	linefw "WITH BASIC POKÉMON CHOSEN AT RANDOM"
	linefw "FROM HIS OR HER DECK. IF A PLAYER"
	linefw "HAS FEWER BASIC POKÉMON THAN THAT IN"
	linefw "HIS OR HER DECK, HE OR SHE CHOOSES"
	linefw "ALL OF THEM. EACH PLAYER SHUFFLES"
	linefw "HIS OR HER DECK AFTERWARD."
	done

Text16dc:
	text "IT IS SMALL AND WAS ORIGINALLY VERY"
	linefw "WEAK. ITS TEMPERAMENT TURNED"
	linefw "FEROCIOUS WHEN IT BEGAN USING BONES."
	done

Text16dd:
	text "DARK MAROWAK "
	done

Text16de:
	text "MULTIPLE BONE HIT"
	done

Text16df:
	text "DOES A RANDOMLY SELECTED AMOUNT OF"
	linefw "DAMAGE (0, 10, OR 20) TO 1 OF YOUR"
	linefw "OPPONENT'S BENCHED POKÉMON CHOSEN"
	linefw "AT RANDOM. THEN, SWITCH THAT"
	linefw "POKÉMON WITH THE DEFENDING POKÉMON."
	done

Text16e0:
	text "IT COLLECTS BONES FROM AN UNKNOWN"
	linefw "PLACE. SOME WHISPER THAT A MAROWAK"
	linefw "GRAVEYARD EXISTS SOMEWHERE. "
	done

Text16e1:
	text "HITMONLEE "
	done

Text16e2:
	text "ROLLING KICK"
	done

Text16e3:
	text "THIS AMAZING POKÉMON HAS AN AWESOME"
	linefw "SENSE OF BALANCE. IT CAN KICK IN"
	linefw "SUCCESSION FROM ANY POSITION. "
	done

Text16e4:
	text "STRETCH KICK"
	done

Text16e5:
	text "IF YOUR OPPONENT HAS ANY BENCHED"
	linefw "POKÉMON, CHOOSE 1 OF THEM. THIS"
	linefw "ATTACK DOES 20 DAMAGE TO IT. (DON'T"
	linefw "APPLY WEAKNESS AND RESISTANCE FOR"
	linefw "BENCHED POKÉMON.)"
	done

Text16e6:
	text "HIGH JUMP KICK"
	done

Text16e7:
	text "ITS LEGS CAN STRETCH DOUBLE. FIRST-"
	linefw "TIME FOES ARE STARTLED BY ITS"
	linefw "EXTENSIBLE REACH."
	done

Text16e8:
	text "HITMONCHAN "
	done

Text16e9:
	text "MACH PUNCH"
	done

Text16ea:
	text "IF YOUR OPPONENT HAS ANY BENCHED"
	linefw "POKÉMON, CHOOSE 1 OF THEM. THIS"
	linefw "ATTACK DOES 10 DAMAGE TO IT."
	linefw "(DON'T APPLY WEAKNESS AND RESISTANCE"
	linefw "FOR BENCHED POKÉMON.)"
	done

Text16eb:
	text "ITS PUNCHES SLICE THE AIR. THEY ARE"
	linefw "LAUNCHED AT SUCH HIGH SPEED, EVEN A"
	linefw "SLIGHT GRAZE COULD CAUSE A BURN. "
	done

Text16ec:
	text "JAB"
	done

Text16ed:
	text "SPECIAL PUNCH"
	done

Text16ee:
	text "THE ARM-TWISTING PUNCHES IT THROWS"
	linefw "PULVERIZE EVEN CONCRETE. IT RESTS"
	linefw "AFTER THREE MINUTES OF FIGHTING."
	done

Text16ef:
	text "RHYHORN "
	done

Text16f0:
	text "LEER"
	done

Text16f1:
	text "FLIP A COIN. IF HEADS, THE"
	linefw "DEFENDING POKÉMON CAN'T ATTACK"
	linefw "THIS POKÉMON DURING YOUR OPPONENT'S"
	linefw "NEXT TURN. (BENCHING EITHER POKÉMON"
	linefw "ENDS THIS EFFECT.)"
	done

Text16f2:
	text "SPIKE"
	done

Text16f3:
	text "ITS BODY IS CLAD IN A THICK HIDE,"
	linefw "AND ITS TACKLES TOPPLE BUILDINGS."
	linefw "UNFORTUNATELY, IT IS NOT SMART."
	done

Text16f4:
	text "RHYDON "
	done

Text16f5:
	text "MOUNTAIN BREAK"
	done

Text16f6:
	text "TAKE THE FIRST 5 CARDS OF YOUR"
	linefw "DECK. PUT ALL ", "<FIGHTING>", " ENERGY CARDS IN"
	linefw "YOUR HAND. DISCARD THE REST."
	done

Text16f7:
	text "ONE-TWO STRIKE"
	done

Text16f8:
	text "STANDING ON ITS HIND LEGS FREED ITS"
	linefw "FORELEGS AND MADE IT SMARTER. IT IS"
	linefw "VERY FORGETFUL, HOWEVER. "
	done

Text16f9:
	text "RAM"
	done

Text16fa:
	text "RHYDON DOES 20 DAMAGE TO ITSELF."
	linefw "IF YOUR OPPONENT HAS ANY BENCHED"
	linefw "POKÉMON, HE OR SHE CHOOSES 1 OF THEM"
	linefw "AND SWITCHES IT WITH THE DEFENDING"
	linefw "POKÉMON. (DO THE DAMAGE BEFORE"
	linefw "SWITCHING THE POKÉMON.) (SWITCH EVEN"
	linefw "IF RHYDON IS KNOCKED OUT.)"
	done

Text16fb:
	text "ITS BRAIN DEVELOPED AFTER IT STOOD"
	linefw "UP ON ITS HIND LEGS. ITS DRILL HORN"
	linefw "BORES TUNNELS THROUGH SOLID ROCK."
	done

Text16fc:
	text "KABUTO "
	done

Text16fd:
	text "KABUTO ARMOR"
	done

Text16fe:
	text "ALL ATTACKS TO KABUTO DO HALF DAMAGE"
	linefw "(ROUNDED DOWN TO THE NEAREST 10,"
	linefw "AFTER APPLYING WEAKNESS AND"
	linefw "RESISTANCE). (ANY OTHER EFFECTS OF"
	linefw "ATTACKS STILL HAPPEN). THIS POWER"
	linefw "STOPS WORKING WHILE KABUTO IS"
	linefw "ASLEEP, CONFUSED, OR PARALYZED."
	done

Text16ff:
	text "IT IS THOUGHT TO HAVE INHABITED"
	linefw "BEACHES 300 MILLION YEARS AGO. IT IS"
	linefw "PROTECTED BY A STIFF SHELL."
	done

Text1700:
	text "FOSSILIZATION"
	done

Text1701:
	text "ONCE DURING YOUR TURN, YOU MAY"
	linefw "FLIP A COIN. IF HEADS, TAKE ALL"
	linefw "EVOLUTION CARDS ATTACHED TO 1 OF"
	linefw "YOUR POKÉMON IN PLAY THAT EVOLVES"
	linefw "FROM MYSTERIOUS FOSSIL AND PUT THEM"
	linefw "INTO YOUR HAND. (THIS DOESN'T COUNT"
	linefw "AS DEVOLVING THAT POKÉMON.) "
	done

Text1702:
	text "SHARP CLAWS"
	done

Text1703:
	text "FLIP A COIN. IF HEADS, THIS ATTACK"
	linefw "DOES 10 DAMAGE PLUS 30 MORE DAMAGE;"
	linefw "IF TAILS, THIS ATTACK DOES 10"
	linefw "DAMAGE."
	done

Text1704:
	text "ON RARE OCCASIONS, SOME HAVE BEEN"
	linefw "FOUND AS FOSSILS WHICH THEY BECAME"
	linefw "WHILE HIDING ON THE OCEAN FLOOR. "
	done

Text1705:
	text "KABUTOPS "
	done

Text1706:
	text "SHARP SICKLE"
	done

Text1707:
	text "ABSORB"
	done

Text1708:
	text "IT IS THOUGHT THAT THIS POKÉMON CAME"
	linefw "ONTO LAND BECAUSE ITS PREY ADAPTED"
	linefw "TO LIFE ON LAND."
	done

Text1709:
	text "AERODACTYL "
	done

Text170a:
	text "PREHISTORIC POWER"
	done

Text170b:
	text "NO MORE EVOLUTION CARDS CAN BE"
	linefw "PLAYED. THIS POWER STOPS WORKING"
	linefw "WHILE AERODACTYL IS ASLEEP,"
	linefw "CONFUSED, OR PARALYZED."
	done

Text170c:
	text "FOSSIL"
	done

Text170d:
	text "A POKÉMON THAT ROAMED THE SKIES IN"
	linefw "THE DINOSAUR ERA. ITS TEETH ARE LIKE"
	linefw "SAW BLADES."
	done

Text170e:
	text "SWOOP DIVE"
	done

Text170f:
	text "AERODACTYL DOES 10 DAMAGE TO ITSELF."
	linefw "(DON'T APPLY WEAKNESS OR RESISTANCE"
	linefw "FOR YOUR POKÉMON)."
	done

Text1710:
	text "A VICIOUS POKÉMON FROM THE DISTANT"
	linefw "PAST, IT APPEARS TO HAVE FLOWN BY"
	linefw "SPREADING ITS WINGS AND GLIDING. "
	done

Text1711:
	text "ABRA "
	done

Text1712:
	text "PSYCHIC BEAM"
	done

Text1713:
	text "CHOOSE 1 OF YOUR OPPONENT'S POKÉMON"
	linefw "AND DO 10 DAMAGE TO IT. (DON'T APPLY"
	linefw "WEAKNESS AND RESISTANCE.)"
	done

Text1714:
	text "IT SLEEPS FOR 18 HOURS A DAY. EVEN"
	linefw "WHEN AWAKE, IT TELEPORTS ITSELF"
	linefw "WHILE REMAINING SEATED. "
	done

Text1715:
	text "EVEN WHILE ASLEEP, IT MAINTAINS A"
	linefw "TELEPATHIC RADAR. IT TELEPORTS WHEN"
	linefw "IT IS THREATENED."
	done

Text1716:
	text "VANISH"
	done

Text1717:
	text "SHUFFLE ABRA INTO YOUR DECK."
	linefw "(DISCARD ALL CARDS ATTACHED TO"
	linefw "ABRA.)"
	done

Text1718:
	text "IT SENSES IMPENDING ATTACKS AND"
	linefw "TELEPORTS AWAY TO SAFETY BEFORE THE"
	linefw "ACTUAL ATTACKS CAN STRIKE. "
	done

Text1719:
	text "KADABRA "
	done

Text171a:
	text "DISCARD 1 ", "<PSYCHIC>", " ENERGY CARD ATTACHED"
	linefw "TO KADABRA IN ORDER TO USE THIS"
	linefw "ATTACK. REMOVE ALL DAMAGE COUNTERS"
	linefw "FROM KADABRA."
	done

Text171b:
	text "WHEN IT USES ITS PSYCHIC POWER, IT"
	linefw "EMITS STRONG ALPHA WAVES THAT CAN"
	linefw "RUIN PRECISION DEVICES."
	done

Text171c:
	text "PSY-PANIC"
	done

Text171d:
	text "IF THE DEFENDING POKÉMON IS ", "<PSYCHIC>", "-TYPE,"
	linefw "THIS ATTACK'S BASE DAMAGE IS"
	linefw "DOUBLED."
	done

Text171e:
	text "BLINK"
	done

Text171f:
	text "FLIP A COIN. IF HEADS, DURING YOUR"
	linefw "OPPONENT'S NEXT TURN, PREVENT ALL"
	linefw "EFFECTS OF ATTACKS, INCLUDING"
	linefw "DAMAGE, DONE TO KADABRA."
	done

Text1720:
	text "IF ONE IS NEARBY, AN EERIE SHADOW"
	linefw "APPEARS ON TV SCREENS. SEEING THE"
	linefw "SHADOW IS SAID TO BRING BAD LUCK. "
	done

Text1721:
	text "DARK KADABRA "
	done

Text1722:
	text "MATTER EXCHANGE"
	done

Text1723:
	text "ONCE DURING YOUR TURN (BEFORE YOUR"
	linefw "ATTACK) YOU MAY DISCARD A CARD FROM"
	linefw "YOUR HAND IN ORDER TO DRAW A CARD."
	linefw "THIS POWER CAN'T BE USED IF DARK"
	linefw "KADABRA IS ASLEEP, CONFUSED, OR"
	linefw "PARALYZED."
	done

Text1724:
	text "MIND SHOCK"
	done

Text1725:
	text "DON'T APPLY WEAKNESS AND RESISTANCE"
	linefw "FOR THIS ATTACK."
	done
