Text0fd5:
	text "PLACE ASIDE 6 PRIZE CARDS."
	linefw "LET'S HAVE A GREAT CARD BATTLE!"
	done

Text0fd6:
	text "HO HO... I GUESS I DIDN'T DO SO HOT"
	linefw "AFTER ALL."
	done

Text0fd7:
	text "WE HAVE OUR WINNER!"
	linefw "IT'S GRAND MASTER ", "<RAMTEXT>", "!"
	linefw "WHAT A TURN OF EVENTS!!"
	linefw "<RAMNAME>", " WAS DEFEATED!!"
	done

Text0fd8:
	text "STEVE IS THE CHEERFUL"
	linefw "ELECTRIC GRAND MASTER!"
	done

Text0fd9:
	text "LET'S SHOW THE CROWD A TRULY"
	linefw "ELECTRIFYING BATTLE!"
	done

Text0fda:
	text "JACK IS THE GENTLEMANLY"
	linefw "GRAND MASTER OF ICE!"
	done

Text0fdb:
	text "I WON'T LOSE AGAINST YOU THIS TIME"
	linefw "WITH MY GORGEOUS DECK!"
	done

Text0fdc:
	text "SO YOU HAVE ONCE AGAIN BESTED"
	linefw "MY GORGEOUS DECK...INDEED."
	done

Text0fdd:
	text "ROD IS THE POWERFUL"
	linefw "GRAND MASTER OF DRAGONS!"
	done

Text0fde:
	text "LET'S SEE HOW WELL YOU PLAY AGAINST"
	linefw "THE MIGHT OF MY HARDY DRAGONS!"
	done

Text0fdf:
	text "YOU'VE DONE IT, ", "<RAMNAME>", "!"
	linefw "CONGRATULATIONS!"
	done

Text0fe0:
	text "WE HAVE OUR GRAND MASTER CUP"
	linefw "CHAMPION!"
	done

Text0fe1:
	text "NOW, THEN."
	linefw "IT'S TIME TO CHOOSE YOUR PRIZES!"
	done

Text0fe2:
	text "AS OUR CHAMPION, THEN,"
	linefw "TAKE THESE CARDS AS YOUR PRIZES!"
	done

Text0fe3:
	text "THAT'S NOT ALL YOU'VE WON,"
	linefw "THOUGH, ", "<RAMNAME>", "!"
	linefw "FOR YOUR VICTORY, PLEASE ALSO TAKE"
	linefw "THIS SPECIAL COIN!"
	done

Text0fe4:
	text "ONCE MORE,"
	linefw "CONGRATULATIONS, ", "<RAMNAME>", "!"
	done

Text0fe5:
	text "CONGRATULATIONS, ", "<RAMNAME>", "!"
	done

Text0fe6:
	text "<RAMNAME>", " HAS BEEN DUBBED AS THE"
	linefw "GRAND MASTER CUP CHAMPION."
	linefw "WITH THAT, THE GRAND MASTER CUP"
	linefw "COMES TO A CLOSE. GOODBYE, EVERYONE!"
	done

Text0fe7:
	text "SORRY FOR YOUR LOSS, ", "<RAMNAME>", "."
	linefw "PLEASE EXIT THE BATTLE HALL."
	done

Text0fe8:
	text "OH HO HO..."
	linefw "IF IT ISN'T ", "<RAMNAME>", "."
	linefw "YOU HAVE MY GRATITUDE FOR RESCUING"
	linefw "ME FROM TEAM GR."
	linefw "HO HO HO...BECAUSE OF YOUR EFFORTS,"
	linefw "I COULD RETURN TO THE POKÉMON DOME."
	linefw "SINCE YOU CAME HERE ALL FIRED UP,"
	linefw "ARE YOU GOING TO BATTLE ME?"
	done

Text0fe9:
	text "OH HO HO HO..."
	linefw "IF IT ISN'T ", "<RAMNAME>", "."
	linefw "OH, YOU WANT MY LEGENDARY POKÉMON"
	linefw "CARD? IT'S NOT THAT EASY!"
	linefw "YOU MUST FIRST DEFEAT THE 4"
	linefw "GRAND MASTERS IN THE FINAL CUP..."
	linefw "HOWEVER,"
	linefw "THE CUP ISN'T BEING HELD RIGHT NOW."
	linefw "BUT IF YOU WANT TO BATTLE ME..."
	linefw "HO HO HO, SURE! I'LL TAKE YOU ON!"
	done

Text0fea:
	text "WOULD YOU LIKE TO DUEL COURTNEY?"
	done

Text0feb:
	text "YOU'LL FEEL THE FIERY PLAY STYLE "
	linefw "THAT HAS GAINED ME MY NOTORIETY!"
	linefw "6 PRIZE CARDS SHOULD DO."
	linefw "OH HO HO HO...LET'S GO!"
	done

Text0fec:
	text "OH HO HO..."
	linefw "THAT'S TOO BAD."
	linefw "BUT I UNDERSTAND. BEST OF LUCK"
	linefw "IN YOUR FIGHT AGAINST TEAM GR."
	done

Text0fed:
	text "OH HO HO...ALL THE GRAND MASTERS"
	linefw "HAVE BEEN ASSEMBLED AT LAST."
	linefw "LET'S START THE FINAL CUP!"
	linefw "WIN THE POKÉMON CARDS OF LEGEND!"
	linefw "BUT ", "<RAMNAME>", ","
	linefw "DON'T BE CARELESS."
	done

Text0fee:
	text "THANKS TO YOU, ", "<RAMNAME>", ","
	linefw "TEAM GR IS FINALLY ACTING GOOD."
	linefw "POKÉMON CARDS HAVE SINCE BEEN FREELY"
	linefw "DISTRIBUTED ALL OVER THE PLACE."
	linefw "OH HO HO..."
	linefw "THANKS MUCH, ", "<RAMNAME>", "!"
	done

Text0fef:
	text "EVEN WE, THE GRAND MASTERS, WILL"
	linefw "NOT BE DEFEATED BY TEAM GR NOW."
	linefw "THIS WHOLE SERIES OF EVENTS HAS MADE"
	linefw "US LOVE OUR POKÉMON CARDS EVEN MORE."
	linefw "HO HO HO...WE ACCEPT ALL CHALLENGERS"
	linefw "AS LONG AS THEY SHARE THAT PASSION!"
	done

Text0ff0:
	text "OH HO HO..."
	linefw "IT'S MY LOSS."
	done

Text0ff1:
	text "VERY CLEVER FIGHTING,"
	linefw "<RAMNAME>", "."
	linefw "YOU JUST MAY INHERIT THE LEGENDARY"
	linefw "POKÉMON CARDS SOMEDAY!"
	done

Text0ff2:
	text "OH HO HO..."
	linefw "IT'S MY WIN!"
	linefw "BY ALL MEANS,"
	linefw "RETURN SOMETIME TO BATTLE AGAIN."
	done

Text0ff3:
	text "HEY, ", "<RAMNAME>", "! THANKS AGAIN"
	linefw "FOR SAVING ME ON GR ISLAND!"
	linefw "I STILL CAN'T GET OVER HOW I LOST"
	linefw "TO TEAM GR AND GOT MYSELF CAPTURED."
	linefw "GRAND MASTERS ARE SUPPOSED TO BE"
	linefw "TOUGH, SKILLED ADVERSARIES!"
	linefw "MY PRIDE AS A REVERED GRAND MASTER"
	linefw "IS ON A CRUMBLING FOUNDATION."
	linefw "HEY, ", "<RAMNAME>", "!"
	linefw "C'MON AND BATTLE WITH ME!"
	done

Text0ff4:
	text "HEY ", "<RAMNAME>", "!"
	linefw "ARE YOU WELL?"
	linefw "WITHOUT THE OTHER GRAND MASTERS,"
	linefw "WE'RE UNABLE TO HOLD A FINAL CUP."
	linefw "IF IT'S NOT A FINAL CUP BATTLE,"
	linefw "YOU CAN'T WIN THE CARDS OF LEGEND."
	linefw "BUT I THINK IT'S A-OK TO PLAY WITH"
	linefw "OUR POKÉMON CARDS UNOFFICIALLY."
	linefw "HEY, ", "<RAMNAME>", "!"
	linefw "C'MON AND BATTLE ME!"
	done

Text0ff5:
	text "WOULD YOU LIKE TO DUEL STEVE?"
	done

Text0ff6:
	text "I'M FAIRLY CERTAIN A STANDARD"
	linefw "BATTLE HAS 6 PRIZE CARDS."
	linefw "<RAMNAME>", "!"
	linefw "LET'S YOU AND ME BATTLE!!"
	done

Text0ff7:
	text "OH, NOOOO!"
	linefw "DON'T BE LIKE THAT, ", "<RAMNAME>", "!"
	linefw "IF YOU WON'T BE MY BATTLE PARTNER,"
	linefw "HOW CAN I KEEP MY SKILLS SHARP?"
	done

Text0ff8:
	text "HEY ", "<RAMNAME>", "!"
	linefw "ROD'S FINALLY BACK!"
	linefw "YOU KNOW WHAT THAT MEANS."
	linefw "WE'RE OK TO START THE FINAL CUP!"
	linefw "YOU'RE HERE TO WIN THE POKÉMON"
	linefw "CARDS OF LEGEND FROM US, RIGHT?"
	done

Text0ff9:
	text "YOU CAN FIGHT TEAM GR,"
	linefw "BUT THEY'RE NO GRAND MASTERS."
	linefw "IF YOU WANT TO CHALLENGE US,"
	linefw "I'M A-OK TO FIGHT!"
	done

Text0ffa:
	text "HEY ", "<RAMNAME>", "!"
	linefw "CONGRATULATIONS!"
	linefw "I'M SURE YOU'RE AWARE THAT TEAM GR"
	linefw "IS ALL ABOUT LOVE AND PEACE NOW."
	linefw "THAT BEING THE CASE,"
	linefw "LET'S ALL ENJOY OUR POKÉMON CARDS!"
	done

Text0ffb:
	text "HEY, ", "<RAMNAME>", "!"
	linefw "ARE YOU HAVING FUN WITH YOUR CARDS?"
	linefw "I'M PREPARING MY CARDS FOR THE BIG"
	linefw "GRAND MASTER CUP WE'RE HAVING SOON."
	linefw "MAKE SURE YOU STOP BY AND ENTER"
	linefw "THE CUP, ALRIGHT?"
	done

Text0ffc:
	text "HEY, ", "<RAMNAME>", "!"
	linefw "ARE YOU ENJOYING YOUR POKÉMON CARDS?"
	linefw "SORRY, BUT THE GRAND MASTER CUP IS"
	linefw "CURRENTLY CLOSED."
	linefw "DON'T WORRY, THOUGH! WE'LL BE"
	linefw "HOLDING IT AGAIN IN NO TIME!"
	done

Text0ffd:
	text "YOU'RE THE WINNER!"
	linefw "YOU WERE GREAT!"
	done

Text0ffe:
	text "MMM, I'M THE LOSER."
	linefw "I WAS DEFEATED IN BATTLE."
	linefw "<RAMNAME>", "."
	linefw "YOU'LL RETURN AGAIN, RIGHT?"
	linefw "I'LL MAKE SURE THAT I'M THE WINNER"
	linefw "OF OUR NEXT BATTLE!!"
	done

Text0fff:
	text "YOU LOSE!"
	linefw "YOU'VE STILL GOT SOME GROWING TO DO!"
	linefw "COME CHALLENGE ME AGAIN SOMETIME!"
	linefw "NOBODY LIKES A QUITTER!"
	done

Text1000:
	text "WELL, WELL!"
	linefw "IF IT ISN'T ", "<RAMNAME>", "."
	linefw "YOU HAVE MY HEARTFELT THANKS FOR"
	linefw "RESCUING ME FROM TEAM GR'S CLUTCHES."
	linefw "THERE IS SURELY NO WAY I CAN REPAY"
	linefw "YOU FOR SUCH A KIND-HEARTED FAVOR."
	linefw "TEAM GR HAS NOT BEEN ENTIRELY"
	linefw "THWARTED YET, HOWEVER."
	linefw "OUR LEADER, ROD, IS STILL BEING"
	linefw "HELD BY THE HOOLIGANS."
	linefw "WITHOUT HIM, WE CANNOT BE THE FOUR"
	linefw "GRAND MASTERS OF POKÉMON CARD FAME."
	linefw "I'M AFRAID WITHOUT ALL 4 OF US HERE,"
	linefw "THE FINAL CUP CANNOT BE HELD, TOO."
	linefw "WE ARE STILL ACCEPTING INDIVIDUAL"
	linefw "CHALLENGES IN THE MEAN TIME, THOUGH."
	linefw "HOW ABOUT IT? WOULD YOU LIKE TO"
	linefw "CHALLENGE MY GORGEOUS DECK?"
	done

Text1001:
	text "OH, MY!"
	linefw "IF IT ISN'T ", "<RAMNAME>", "!"
	linefw "HAVE YOU COME TO CHALLENGE ME"
	linefw "TO A DUEL TODAY?"
	linefw "UNTIL ROD RETURNS, WE CANNOT OPEN"
	linefw "THE FINAL CUP, I'M AFRAID TO SAY."
	linefw "IF IT'S ACCEPTABLE BY YOU, HOWEVER,"
	linefw "I'LL DUEL YOU WITH MY GORGEOUS DECK."
	done

Text1002:
	text "WOULD YOU LIKE TO DUEL JACK?"
	done

Text1003:
	text "ARE YOU AMENABLE TO USING"
	linefw "6 PRIZE CARDS? VERY GOOD!"
	done

Text1004:
	text "I SEE. THAT'S TOO BAD."
	linefw "AFTER ALL, YOU DID RESCUE ME."
	linefw "I WANTED TO SEE WHAT KIND OF"
	linefw "GORGEOUS DECK YOU USE..."
	done

Text1005:
	text "THE POKÉMON CARDS OF LEGEND ARE"
	linefw "BESTOWED TO THE FINAL CUP'S VICTOR."
	linefw "IF YOU'RE INTERESTED,"
	linefw "SPEAK WITH OUR LEADER, ROD."
	done

Text1006:
	text "WELL THIS IS A SURPRISE."
	linefw "HELLO, ", "<RAMNAME>", "."
	linefw "THE GR KING HAS BEEN PERSUADED AT"
	linefw "LONG LAST TO RENOUNCE HIS EVIL WAYS."
	linefw "HOWEVER, THIS DOES NOT MEAN WE'LL"
	linefw "NEVER HEAR FROM TEAM GR AGAIN."
	linefw "GORGEOUS BATTLES ARE POSSIBLE WITH"
	linefw "OPPONENTS FROM ALL WALKS OF LIFE."
	linefw "I THINK EVERYONE'S LEARNED THIS"
	linefw "LESSON THANKS TO YOU, ", "<RAMNAME>", "."
	done

Text1007:
	text "SPEAK WITH OUR LEADER, ROD, IF YOU'D"
	linefw "LIKE TO HAVE A GORGEOUS BATTLE."
	linefw "HE'S IN CHARGE OF ANNOUNCING OUR"
	linefw "STUNNING GRAND MASTER CUP."
	linefw "IN ANY CASE, MY FRIEND,"
	linefw "I HOPE YOU HAVE A GOOD DAY."
	done

Text1008:
	text "I ALWAYS SEE SUCH GORGEOUS DECKS AND"
	linefw "PLAYERS IN THE GRAND MASTER CUP."
	linefw "BUT EVEN GRAND MASTERS NEED SOME"
	linefw "TIME TO THEMSELVES SOMETIMES."
	linefw "WHY DON'T YOU STOP BY THE POKÉMON"
	linefw "DOME FOR A DUEL INSTEAD?"
	done

Text1009:
	text "SO YOU HAVE ONCE AGAIN BESTED"
	linefw "MY GORGEOUS DECK...INDEED."
	done

Text100a:
	text "YOUR POWER SEEMS TO BE"
	linefw "GREAT INDEED... "
	done

Text100b:
	text "YOUR GORGEOUS DECK WAS FAIR, BUT IT"
	linefw "CAN'T COMPARE TO MY GORGEOUS DECK!"
	done

Text100c:
	text "<RAMNAME>", "!"
	linefw "I'VE BEEN EXPECTING YOU."
	linefw "YOU SHOULD TRY YOUR BEST TO MEET"
	linefw "WITH KING VILLICCI ON GR ISLAND."
	linefw "THAT'S THE ONLY WAY TO MAKE TEAM GR"
	linefw "CHANGE THEIR TERRIBLE WAYS."
	linefw "YOU'LL NEED THE POKÉMON CARDS OF"
	linefw "LEGEND TO HAVE A DUEL WITH VILLICCI."
	linefw "SO, LET'S START THE FINAL CUP!"
	linefw "WELL, ASSUMING YOU'RE PREPARED."
	done

Text100d:
	text "<RAMNAME>", "..."
	linefw "UNLESS YOU DEFEAT THE FOUR OF US..."
	linefw "IT'S NOT POSSIBLE TO GET THE"
	linefw "POKÉMON CARDS OF LEGEND."
	linefw "THE POKÉMON CARDS OF LEGEND ARE"
	linefw "REQUIRED TO MEET WITH KING VILLICCI."
	linefw "SO LET'S START THE FINAL CUP!"
	linefw "ASSUMING YOU'RE READY, OF COURSE."
	done

Text100e:
	text "<RAMNAME>", ", YOUR MAIN GOAL"
	linefw "IS TO MEET TEAM GR'S KING, VILLICCI."
	linefw "ONLY THEN WILL TEAM GR CHANGE"
	linefw "ITS TERRIBLE WAYS."
	linefw "THE OTHER GRAND MASTERS AND I ARE"
	linefw "LOOKING FORWARD TO THAT CHANGE."
	linefw "YOU NEED TO HAVE THE POKÉMON CARDS"
	linefw "OF LEGEND TO FIGHT TEAM GR."
	linefw "IF YOU LIKE,"
	linefw "WE CAN START THE FINAL CUP AGAIN."
	linefw "<RAMNAME>", "."
	linefw "WHAT WOULD YOU LIKE TO DO?"
	done

Text100f:
	text "START THE FINAL CUP?"
	done

Text1010:
	text "VERY WELL!"
	linefw "LET'S ENTER THE FINALS HALL."
	done

Text1011:
	text "THAT'S FINE. MAKE YOUR PREPARATIONS"
	linefw "AND RETURN WHEN YOU FEEL READY."
	linefw "REMEMBER, YOU'RE THE ONLY ONE"
	linefw "CAPABLE OF TAKING DOWN TEAM GR."
	done

Text1012:
	text "YOU HAVE MY EARNEST THANKS,"
	linefw "<RAMNAME>", "."
	linefw "YOUR BRAVERY AND VILLICCI'S WILL TO"
	linefw "ACCEPT HIS MISTAKES OPENED OUR EYES."
	linefw "EVERYONE WHO LOVES POKÉMON CARDS"
	linefw "IS A FRIEND TO US."
	linefw "THIS IS A SINCERE MORAL WE'VE ALL"
	linefw "LEARNED FROM OUR BOUTS WITH TEAM GR."
	linefw "NO MATTER WHAT, JUST KEEP THAT"
	linefw "LOVE AND TOLERANCE IN YOUR HEART..."
	done

Text1013:
	text "YOU SHOULD BATTLE EVERYONE YOU CAN,"
	linefw "CLUB MEMBERS AND TEAM GR ALIKE."
	linefw "IF YOU WANT A DUEL, A GOOD PLACE TO"
	linefw "START IS THE LOCAL BATTLE CENTER."
	linefw "THAT'S A GOOD STEP TOWARD EARNING"
	linefw "NEW CARDS YOU DON'T OWN YET."
	done

Text1014:
	text "I HOPE YOU'VE ENJOYED PARTICIPATING"
	linefw "IN THE GRAND MASTER CUP."
	linefw "IT WAS A LOT OF FUN ALL AROUND."
	linefw "WE'LL HOLD IT AGAIN SOMETIME SOON."
	linefw "UNTIL THEN, STRENGTHEN YOURSELF BY"
	linefw "FIGHTING AT THE BATTLE CENTER."
	done

Text1015:
	text "THAT'S RIGHT! TEAM GREAT ROCKET"
	linefw "HAS TAKEN OVER THE POKÉMON DOME!"
	linefw "THE GRAND MASTERS HAVE BEEN CAUGHT"
	linefw "AND TAKEN TO GR ISLAND!"
	linefw "ONCE WE'RE DONE WITH OUR TAKEOVER,"
	linefw "WE'LL HAVE EVERY LAST CARD THERE IS!"
	linefw "POKÉMON TRADING CARDS ARE SIMPLY"
	linefw "WASTED ON THE LIKES OF YOU FOOLS."
	linefw "WE'LL PICK ALL THE BEST CARDS FOR"
	linefw "OUR DECKS AND LOCK THE REST AWAY!"
	linefw "TEAM GR WILL HAVE ALL THE CARDS"
	linefw "IN THE WORLD SOON ENOUGH!!!"
	done

Text1016:
	text "TEAM GR HAS BUT ONE PURPOSE!"
	linefw ""
	linefw "WE EXIST TO COLLECT EVERY POKÉMON"
	linefw "TRADING CARD IN THE WORLD!"
	done

Text1017:
	text "WELCOME TO THE GRAND MASTER CUP."
	linefw "WE'RE ACCEPTING PARTICIPANTS HERE!"
	linefw "WINNERS OF THE TOURNAMENT WILL GET"
	linefw "TO DUEL A POKÉMON CARD GRAND MASTER!"
	linefw "FURTHERMORE, A SPECIAL PRIZE IS"
	linefw "GIVEN IF THEY BEAT THE GRAND MASTER!"
	done

Text1018:
	text "<RAMTEXT>"
	linefw "<RAMTEXT>"
	done

Text1019:
	text "THE WINNER GETS TO CHOOSE 2 OF THOSE"
	linefw "4 PROMOTIONAL CARDS AS THEIR PRIZE!"
	linefw "SO, ", "<RAMNAME>", ", WOULD YOU"
	linefw "LIKE TO ENTER THE GRAND MASTER CUP?"
	done

Text101a:
	text "SORRY FOR YOUR BAD LUCK,"
	linefw "<RAMNAME>", "..."
	linefw "PLEASE COME BACK AND TRY AGAIN IN"
	linefw "THE NEXT GRAND MASTER CUP."
	done

Text101b:
	text "WOW, CONGRATS, ", "<RAMNAME>", "!"
	linefw ""
	linefw "PLEASE STOP BY FOR THE NEXT"
	linefw "GRAND MASTER CUP AS WELL."
	done

Text101c:
	text "PARTICIPATE IN THE GRAND MASTER CUP?"
	done

Text101d:
	text "THEN PLEASE ENTER THE"
	linefw "CHALLENGE HALL!"
	done

Text101e:
	text "I SEE. THAT'S TOO BAD."
	linefw "PLEASE COME BACK NEXT TIME."
	done

Text101f:
	text "I CAME OVER FROM GR ISLAND JUST TO"
	linefw "PARTICIPATE IN THE GRAND MASTER CUP."
	linefw "THIS TOURNAMENT WAS MY BIG CHANCE TO"
	linefw "HAVE A DUEL WITH A GRAND MASTER!"
	done

Text1020:
	text "WE'LL SEE WHAT HAPPENS!"
	linefw "I'M SO EXCITED AND NERVOUS..."
	done

Text1021:
	text "IT WAS AN AMAZING BATTLE!!"
	linefw "MY HEART IS STILL POUNDING..."
	done

Text1022:
	text "ROD MAY BE THE FINAL HURDLE OF"
	linefw "THE GRAND MASTER CUP."
	linefw "BUT ONLY THE WINNER OF THE"
	linefw "GRAND MASTER CUP GETS TO FIGHT HIM."
	linefw "I'D DO ANYTHING TO GET THE CHANCE"
	linefw "TO BATTLE A CARD MASTER LIKE HIM."
	done

Text1023:
	text "HEY, HEY! HOW'D YOU END UP DOING"
	linefw "IN THE GRAND MASTER CUP?"
	linefw "DID YOU BECOME THE TOURNAMENT"
	linefw "CHAMPION?"
	linefw "DID YOU FIGHT A GRAND MASTER?"
	done

Text1024:
	text "THE RULES OF THE GRAND MASTER CUP"
	linefw "SAY 8 ENTRANTS DUEL IN A TOURNAMENT."
	linefw "THE WINNER OF THAT TOURNAMENT GETS"
	linefw "TO BATTLE A GRAND MASTER."
	linefw "IF THAT ENTRANT BEATS THE"
	linefw "GRAND MASTER, THEY'RE THE CHAMPION!"
	linefw "HOWEVER, ENTRANTS ONLY GET TO USE"
	linefw "ONE DECK THROUGHOUT THE WHOLE EVENT."
	linefw "THESE ARE THE RULES THAT ROD HIMSELF"
	linefw "HAS CREATED FOR THE CUP."
	done

Text1025:
	text "I'VE HEARD THAT YOU'RE THE CHAMPION"
	linefw "OF THE GRAND MASTER CUP."
	linefw "THAT'S AMAZING, ", "<RAMNAME>", "!"
	linefw "YOU'RE LIKE A GRAND MASTER YOURSELF!"
	done

Text1026:
	text "I HEARD THE WINNER OF THE TOURNAMENT"
	linefw "WAS DEFEATED BY THE GRAND MASTER."
	linefw "IT'S JUST AS I'VE THOUGHT."
	linefw "THE GRAND MASTERS ARE SO STRONG!"
	done

Text1027:
	text "THOSE DOORS ARE OFF-LIMITS!"
	linefw " "
	linefw "ONLY THE GRAND MASTERS CAN OPEN 'EM,"
	linefw "AND THEY'RE NOT HERE, ARE THEY?"
	done

Text1028:
	text "<RAMNAME>", "! THIS IS ROD,"
	linefw "THE LEADER OF THE GRAND MASTERS!"
	done

Text1029:
	text "THE FINAL CUP MAY BE OVER FOR YOU,"
	linefw "BUT IT WILL OPEN ONCE AGAIN LATER."
	linefw "PLEASE REVISIT THE POKÉMON DOME"
	linefw "WHEN YOU FEEL READY FOR A REMATCH."
	linefw "GO OUT AND FOCUS ON MAKING"
	linefw "A NEW DECK."
	done

Text102a:
	text "YOU'VE PROBABLY HEARD ABOUT THE"
	linefw "4 GRAND MASTERS OF THE POKÉMON DOME."
	linefw "ALL FOUR OF THEM HAVE BEEN"
	linefw "KIDNAPPED BY TEAM GR..."
	linefw "WHAT'LL HAPPEN TO THE THE LEGENDARY"
	linefw "POKÉMON CARDS THEY WERE PROTECTING?"
	done

Text102b:
	text "THE GRAND MASTER OF THUNDER, STEVE,"
	linefw "HAS FINALLY RETURNED!"
	linefw "THOUGH THE OTHER 3 GRAND MASTERS ARE"
	linefw "STILL HELD HOSTAGE BY TEAM GR..."
	linefw "WON'T ANYONE RESCUE THEM?"
	done

Text102c:
	text "WOOHOO! THE FIRE QUEEN, COURTNEY,"
	linefw "HAS RETURNED SAFELY!"
	linefw "I WONDER WHO ON EARTH HELPED HER"
	linefw "GET AWAY?"
	linefw "NOW THERE ARE ONLY 2 GRAND MASTERS"
	linefw "MISSING: JACK AND ROD."
	done

Text102d:
	text "WOOHOO! THE ICE KING, JACK,"
	linefw "HAS RETURNED SAFELY!"
	linefw "I WONDER WHO ON EARTH HELPED HIM"
	linefw "GET AWAY?"
	linefw "NOW THERE ARE ONLY 2 GRAND MASTERS"
	linefw "MISSING: COURTNEY AND ROD."
	done

Text102e:
	text "YOU'RE BACK, ", "<RAMNAME>", "! YOU'VE"
	linefw "HELPED FREE SO MANY GRAND MASTERS!"
	linefw "THE ONLY ONE LEFT IS THE LEADER"
	linefw "OF THE GRAND MASTERS: ROD!"
	linefw "WHEN ALL 4 GRAND MASTERS ARE UNITED"
	linefw "HERE, THE FINAL CUP CAN OPEN AGAIN!"
	linefw "AFTER THAT, I CAN TRY TO GET"
	linefw "THE LEGENDARY POKÉMON CARDS!"
	done

Text102f:
	text "ROD HAS FINALLY RETURNED, SO THE"
	linefw "FINAL CUP CAN BEGIN AT LAST!"
	linefw "YES! I'M GONNA WIN THE 4 CARDS"
	linefw "OF LEGEND FROM THE GRAND MASTERS!"
	done

Text1030:
	text "THE GRAND MASTER CUP IS EVERYONE'S"
	linefw "CHANCE TO FIGHT THE GRAND MASTERS!"
	linefw "THE PRIZES FOR WINNING ARE"
	linefw "2 PROMOTIONAL CARDS!"
	linefw "YOU CAN CHOOSE ANY 2 CARDS FROM"
	linefw "THEIR SELECTION OF 4 CARDS!!"
	linefw "THE ONLY CATCH IS THAT NO ONE KNOWS"
	linefw "WHEN IT'LL BE HELD!"
	done

Text1031:
	text "I'M SO PSYCHED! THE GRAND MASTER CUP"
	linefw "IS CURRENTLY OPEN FOR REGISTRATION!"
	linefw "THE GRAND MASTER CUP IS A BIG,"
	linefw "COMPETITIVE TOURNAMENT!"
	linefw "THE BEST PART IS THAT THE CHAMPION"
	linefw "IS AWARDED 2 RARE PROMOTIONAL CARDS!"
	linefw "NOT ONLY THAT, BUT THEY GET TO"
	linefw "CHOOSE FROM A SELECTION OF 4 PROMOS!"
	done

Text1032:
	text "HEY THERE!"
	linefw "IS THE COMPETITION OVER ALREADY?"
	linefw "AWW, BUT THE GRAND MASTER CUP IS"
	linefw "HELD SO SELDOMLY..."
	linefw "I WONDER WHEN THE NEXT ONE WILL BE?"
	done

Text1033:
	text "TO THOSE IN SEARCH OF THE"
	linefw "LEGENDARY POKÉMON CARDS,"
	linefw "YOU MUST FIRST DEFEAT THE FOUR GRAND"
	linefw "MASTERS IN SUCCESSIVE CARD DUELS."
	linefw "COURTNEY, STEVE, JACK, AND ROD:"
	linefw "EACH IS A SKILLED CARD PLAYER."
	linefw "ANYONE WHO EMERGES AS VICTOR WILL"
	linefw "INHERIT THE POKÉMON CARDS OF LEGEND."
	done

Text1034:
	text "OH, WELCOME TO OUR HUMBLE CLUB,"
	linefw "<RAMNAME>", "."
	linefw "THANKS AGAIN FOR RESCUING ME FROM"
	linefw "GR ISLAND. I'M IN YOUR DEBT."
	linefw "HOW ABOUT WE CELEBRATE MY FREEDOM"
	linefw "WITH A ROUSING CARD BATTLE?"
	done

Text1035:
	text "IT'S STILL UNFATHOMABLE TO ME"
	linefw "HOW I LOST SO EASILY TO TEAM GR..."
	linefw "SURELY IT WAS BECAUSE MY STUDIES"
	linefw "WERE LACKING IN KEY AREAS."
	linefw "I STILL LOVE RESEARCHING AND PLAYING"
	linefw "THE POKÉMON CARD GAME, THOUGH."
	linefw "SO, WHAT DO YOU SAY?"
	linefw "WANT TO ENJOY A DUEL WITH ME?"
	done

Text1036:
	text "HELLO, ", "<RAMNAME>", "."
	linefw "ARE YOU WELL?"
	linefw "WHAT WOULD YOU SAY TO A CARD BATTLE?"
	done

Text1037:
	text "WOULD YOU LIKE TO DUEL RICK?"
	done

Text1038:
	text "NOW, ABOUT THE PRIZE CARDS..."
	linefw "HOW DOES 6 SOUND?"
	linefw "THAT WAY WE'LL GET MAXIMUM ENJOYMENT"
	linefw "OUT OF OUR DUEL."
	done

Text1039:
	text "I WAS REALLY LOOKING FORWARD TO"
	linefw "BATTLING WITH YOU ONCE MORE..."
	linefw "WELL, I WILL BE ANXIOUS TO DUEL"
	linefw "IF YOU EVER HAVE THE DESIRE."
	done

Text103a:
	text "MITCH FROM THE FIGHTING CLUB BROUGHT"
	linefw "ME QUITE A LOT OF BOOSTER PACKS."
	linefw "IF YOU CAN DEFEAT ME IN A CARD DUEL,"
	linefw "I'LL AWARD SOME TO YOU AS A PRIZE!"
	done

Text103b:
	text "WOULD YOU LIKE TO HAVE A FUN"
	linefw "CARD BATTLE?"
	linefw "IF YOU WIN, I'LL GIVE SOME OF THESE"
	linefw "BOOSTER PACKS I HAVE TO YOU."
	done

Text103c:
	text "SHALL WE SET ASIDE 6 PRIZE CARDS"
	linefw "AS WE HAVE DONE IN THE PAST?"
	linefw "LET'S MAKE THIS DUEL A FUN ONE!"
	done

Text103d:
	text "IF YOU EVER FEEL LIKE TESTING YOUR"
	linefw "POWER OVER SCIENCE, PLEASE RETURN."
	done

Text103e:
	text "ALRIGHT. I'LL GIVE YOU THESE"
	linefw "BOOSTER PACKS FOR BEATING ME."
	done

Text103f:
	text "EVEN IF I LOST,"
	linefw "I HAD A LOT OF FUN."
	linefw "IT'S IMPORTANT TO ENJOY YOURSELF,"
	linefw "NO MATTER WHAT!"
	done

Text1040:
	text "WIN OR LOSE, THE ONLY IMPORTANT"
	linefw "THING IS ENJOYING POKÉMON CARDS!"
	done

Text1041:
	text "SINCE I'VE LOST, I'M MORE THAN HAPPY"
	linefw "TO GIVE YOU THESE NEW CARDS."
	done

Text1042:
	text "YOU'VE GOT SOME REALLY STRONG CARDS"
	linefw "AND AMAZING STRATEGIES AT WORK."
	linefw "BECAUSE OF THOSE TRAITS, I ALWAYS"
	linefw "HAVE FUN WHEN I BATTLE AGAINST YOU."
	done

Text1043:
	text "I'VE WON, SO I GUESS I GET TO KEEP"
	linefw "THE NEW CARDS!"
	done

Text1044:
	text "WE STUDY POKÉMON CARD TACTICS"
	linefw "USING THIS DECK MACHINE."
	linefw "THIS IS A CUSTOM-BUILT DECK MACHINE,"
	linefw "DIFFERENT THAN DR. MASON'S."
	linefw "BUT HOW WELL IS IT FUNCTIONING?"
	linefw "IT LOOKS LIKE IT WASN'T BROKEN."
	linefw "I WAS WORRIED THAT TEAM GR MAY HAVE"
	linefw "BROKEN IT DURING THEIR ATTACK..."
	linefw "WOULD YOU LIKE TO HAVE A DUEL"
	linefw "WITH ME TO SEE HOW IT WORKS?"
	done

Text1045:
	text "ARE YOU UP FOR A BATTLE?"
	linefw "I'D LOVE TO TEST MY MACHINE."
	done

Text1046:
	text "WOULD YOU LIKE TO DUEL DAVID?"
	done

Text1047:
	text "THEN LET'S EACH USE 4 PRIZE CARDS!"
	done

Text1048:
	text "IF YOU'D LIKE TO DUEL WITH ME,"
	linefw "I'M GOOD TO GO AT ANY TIME."
	done

Text1049:
	text "MAYBE THE MACHINE REALLY WAS"
	linefw "TAMPERED WITH..."
	linefw "WELL, I GUESS I OWE YOU"
	linefw "SOME BOOSTER PACKS."
	done

Text104a:
	text "I SUPPOSE I SHOULD RUN A DIAGNOSTIC"
	linefw "ON MY MACHINE AND FIX IT..."
	done

Text104b:
	text "DON'T YOU THINK OUR DECK MACHINE"
	linefw "IS AMAZING?"
	done

Text104c:
	text "THANKS FOR DRIVING GR No.2"
	linefw "AWAY FOR US, ", "<RAMNAME>", "!"
	linefw "BUT..."
	linefw "RICK HASN'T RETURNED YET..."
	done

Text104d:
	text "WHEN I GET SOME CARDS BACK,"
	linefw "I'LL BUILD A NEW DECK."
	linefw "THOSE ARE THE ORDERS I'VE RECEIVED"
	linefw "FROM CLUB MASTER RICK."
	done

Text104e:
	text "HEY, ", "<RAMNAME>", "."
	linefw "CLUB MASTER RICK IS STILL MISSING."
	linefw "HOWEVER, I'VE COLLECTED ENOUGH"
	linefw "CARDS TO DUEL YOU. WANT TO PLAY?"
	done

Text104f:
	text "<RAMNAME>", ", THESE BOOSTER PACKS"
	linefw "ARE YOURS IF YOU CAN DEFEAT ME!"
	linefw "PLEASE, I'M COUNTING ON YOU"
	linefw "TO BRING RICK BACK TO US!!"
	linefw "HE'S SURELY STILL BEING HELD"
	linefw "PRISONER ON GR ISLAND!"
	linefw "<RAMNAME>", "! I BELIEVE IN YOU!"
	linefw "FIGHT YOUR WAY TO GR ISLAND!"
	done

Text1050:
	text "WOULD YOU LIKE TO DUEL JOSEPH?"
	done

Text1051:
	text "I'M PARTIAL TO DUELS"
	linefw "WITH 4 PRIZE CARDS!"
	done

Text1052:
	text "OH, SO YOU DON'T WANT"
	linefw "PLAY RIGHT NOW..."
	done

Text1053:
	text "RICK HAS COME BACK!"
	linefw "IT WAS YOUR DOING, WASN'T IT?!"
	linefw "THANK YOU SO MUCH!"
	linefw "THANK YOU SO MUCH!"
	linefw "NOW THE SCIENCE CLUB CAN FINALLY"
	linefw "CONTINUE OUR MAIN PROJECT!"
	linefw "I'M SO HAPPY I COULD DUEL YOU!"
	linefw "WOULD YOU LIKE TO BATTLE?"
	done

Text1054:
	text "HEY THERE, ", "<RAMNAME>", "!"
	linefw "I'M HARD AT WORK STUDYING."
	linefw "BUT I THINK I'VE EARNED A REST."
	linefw "CARE FOR A CARD BATTLE?"
	done

Text1055:
	text "YES! JUST AS EXPECTED!"
	linefw "HERE, THESE BOOSTER PACKS ARE YOURS!"
	done

Text1056:
	text "BY EARNING BOOSTER PACKS,"
	linefw "YOU GET STRONGER AND STRONGER."
	linefw "AS LONG AS YOU USE THAT STRENGTH"
	linefw "TO SAVE RICK, I'M HAPPY LOSING!"
	done

Text1057:
	text "YOU SHOULDN'T GET DEFEATED BY ME!"
	linefw "YOU HAVE TO TRY HARDER."
	done

Text1058:
	text "YOU'RE GETTING SO STRONG..."
	linefw "I MAY NOT BE ABLE TO WIN ANY MORE!"
	done

Text1059:
	text "WE'VE GOT OUR EQUIPMENT BACK,"
	linefw "BUT OUR CARDS ARE STILL MISSING."
	linefw "SORRY, BUT I CAN'T DUEL JUST YET."
	done

Text105a:
	text "WE'VE PROCURED SOME CARDS"
	linefw "SINCE YOUR LAST VISIT!"
	linefw "NATURALLY, YOU'RE UP FOR PLAYING"
	linefw "POKÉMON CARDS WITH ME, RIGHT?"
	done

Text105b:
	text "I HAVE SO MUCH FUN PLAYING CARDS"
	linefw "THAT I FORGET TO STUDY."
	linefw "WELL, A DUEL IS CLOSE ENOUGH TO"
	linefw "STUDYING! C'MON, FIGHT ME!"
	done

Text105c:
	text "WOULD YOU LIKE TO DUEL ERIC?"
	done

Text105d:
	text "I PROPOSE WE USE 4 PRIZE CARDS!"
	done
