DEF MAX_PLAYER_NAME_CHARS       EQU 6
DEF MAX_PLAYER_NAME_LENGTH      EQU MAX_PLAYER_NAME_CHARS * 2

RSRESET
DEF NAME_BUFFER_NAME     RB MAX_PLAYER_NAME_LENGTH ; $0
DEF NAME_BUFFER_NAME_END RB ; $c
DEF NAME_BUFFER_GENDER   RB ; $d
DEF NAME_BUFFER_ID       RW ; $e

DEF NAME_BUFFER_LENGTH EQU _RS ; 16

DEF MAX_DECK_NAME_LENGTH        EQU 20 * 1 ; note that its unit is byte!

DEF NAMING_SCREEN_BUFFER_LENGTH EQU 24

	const_def
	const NAME_MODE_HIRAGANA  ; $0
	const NAME_MODE_KATAKANA  ; $1
	const NAME_MODE_UPPER_ABC ; $2
	const NAME_MODE_LOWER_ABC ; $3
DEF NUM_NAME_MODES EQU const_value

	const_def $06
	const KEYBOARD_UNKNOWN          ; $06
	const KEYBOARD_TOGGLE_KATAKANA  ; $07
	const KEYBOARD_TOGGLE_UPPER_ABC ; $08
	const KEYBOARD_TOGGLE_LOWER_ABC ; $09
	const KEYBOARD_DONE             ; $0a
